### ISSUE TITLE
An accordion tab link should move the window to the beginning of its text

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express#1000]
## Context

If an accordion is very long and I move to the next one, I do not see my text with out scrolling back. Note: Bug is intermitted on the same page, I can't get it to happen 100%.

## Process

1. Login to site as a CE
2. Create an accordion tab with a 'large' amount of content (500+ words) and 5+ tabs with a 'small' amount of content (50 or fewer) following it
3. View the page on a narrow screen (mobile dimensions)
4. Expand the 'large' tab and scroll to the end of the tab
5. Click the next 'small' tab

## Expected result

I see the content in the 'small' tab

## Current result

The large tab is closed and the view port is pulled up. Moving the small' tab content out of the viewport

## Screenshots

![tabs](https://cloud.githubusercontent.com/assets/4621248/24729052/b06a3aa2-1a19-11e7-864f-0ae129d6cc54.gif)
----

## Links to Examples

* http://www.colorado.edu/polisci/undergraduate/faq (`What are electives? How many electives do I need?` tab)

**Comment by kevincrafts** [comment]
I think this will be fixed when we transition to expandables (where this is fixed) and not use the FAQ page content type anymore.
