### ISSUE TITLE
Anchor links in Collection do not work

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express#1003]
## Context

Anchor links get created by Collections. They don't work properly

## Process

http://www.colorado.edu/p171eaeb5eaa/academics/degree-programs and
http://www.colorado.edu/p171eaeb5eaa/academics/degree-programs#collection-652-Graduate-Programs return the same thing. I would expect the second link to pre filter the results

**Comment by kreynen** [comment]
Issue moved to [CuBoulder/express_collections_bundle #9](https://github.com/CuBoulder/express_collections_bundle/issues/9) via [**ZenHub**](https://www.zenhub.com/)
