### ISSUE TITLE
Captcha and multiple file upload fields are not compatible

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express#1004]
## Context

Submitting the file upload uses the captcha token for the form.

## Process

1. Create a form with a file upload and a captcha field
2. Log out and try to complete the form

## Expected result

File upload works and then form submits.

## Current result

Errors with message about token reuse.

## Possible Fix

Might be https://www.drupal.org/node/1395184

**Comment by owenmorrill** [comment]
Could not reproduce. See http://www-dev.colorado.edu/p1b0c5fdf3a9/content/hh
