### ISSUE TITLE
As a SM, we want to limit the file types that we allow anonymous users to upload

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express#1011]
## Context

Currently the helplet for a webform file upload reads as follows:
```
Web images: gif, jpg, png
Desktop images: bmp, eps, tif, pict, psd
Documents: txt, rtf, html, pdf, doc, docx, odt, ppt, pptx, odp, xls, xlsx, ods, xml,
Media: avi, mov, mp3, ogg, wav
Archives: bz2, dmg, gz, jar, rar, sit, tar, zip
Additional extensions: Enter a list of additional file extensions for this upload field, separated by commas.
```

Some of these strike me as security risks, or things we just don't want to deal with for size reasons. Some that stand out include: avi, mov, mp3, ogg, wav, dmg, jar, psd, eps

We also probably want to prohibit exe, dmg, rpm etc

**Comment by alexfinnarn** [comment]
Some files would need to be added to the tests/behat/assets directory but there is already one file that has been used to test file uploads.

**Comment by owenmorrill** [comment]
https://github.com/CuBoulder/express/pull/1266

**Comment by cathysnider** [comment]
Test Results: All Media files have been 
![screen shot 2017-08-11 at 3 47 23 pm](https://user-images.githubusercontent.com/638275/29233085-6758efd2-7eac-11e7-842f-60808523d101.png)
removed, as well as ability to add Additional extensions.
