### ISSUE TITLE
Title tag on site front page lists campus name twice

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1014]
## Context

When viewing the front page of a site, the site slogan/campus name is repeated twice. This only happens on the front page. Other pages are correct.

## Process

[ordered list the process to finding and recreating the issue, example below]

1. Visit the front page of a site

## Expected result

<title>Home | {SITE NAME} | University of Colorado Boulder</title>

## Current result

<title>{SITE NAME}  | University of Colorado Boulder | University of Colorado Boulder</title>

**Comment by owenmorrill** [comment]
It's working as <title>Home | {SITE NAME} | University of Colorado Boulder</title> now.

**Comment by owenmorrill** [comment]
http://www.colorado.edu/music/ is a good example of what's happening.

**Comment by cathysnider** [comment]
Also 
https://www.colorado.edu/today, https://www.colorado.edu/visit,  https://www.colorado.edu/alumni and https://www.colorado.edu/cmci, etc etc.

BUT these two have a little space instead of a duplicated 'U of C B'
https://www.colorado.edu/law
https://www.colorado.edu/webcentral

**Comment by cathysnider** [comment]
Testing: https://www-dev-new.colorado.edu/p15eae2b6813/

**Comment by cathysnider** [comment]
Looks good.  Home Page title reads "Home | Site Name | University of Colorado Boulder" 
Other pages continue to be labeled appropriately "MyPage | Site Name | University of Colorado Boulder"
