### ISSUE TITLE
As a SO/CE I would like to be able to display articles in an article list page in reverse chronological order

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#1016]
## Context

Our "Events Archive" page is listed in reverse chronological order, so that
the most recent event is listed first. In order to list our "Upcoming Events"
in the opposite order (chronological order), I must manually change the
publishing date of each event, which is time consuming and cumbersome with
the amount of events we schedule. This is a major issue as I must change
multiple events' publishing dates in order to get them all in the correct
order.
I would very much appreciate these article lists to have the option to list
events in either chronological or reverse chronological order. This would
remove the necessity to manually change all of these publishing dates.
## Process

[ordered list the process to finding and recreating the issue, example below]

https://www.colorado.edu/alc/news-events

**Comment by kevincrafts** [comment]
I'm not sure that trying to make an events calendar out of article nodes is something we want to support.  We've had this request before and denied it.

I would prefer at least to delay any future action with this issue until the new events calendar is available.
