### ISSUE TITLE
As a SO/ CE I would like to have the Newsletter Banner Text to be more distinctive than the content headings

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#1017]
## Context

it would be great if we could customize the header with the unit lockup, rather than the name of the newsletter and CU-B logo. Making the name of the email bigger would even help a little – it looks smaller than the H2, which for me doesn’t make for very good visual hierarchy. 
![newsletter banner text](https://cloud.githubusercontent.com/assets/16137919/25028339/d5c2e9b8-2070-11e7-95f6-448d8678df3a.JPG)

## Screenshots

[if relevant, include screenshots]

**Comment by ekellagher** [comment]
Here is another re4quest from a client to have a more distinctive banner: From: Clint M Talbott 
Sent: Tuesday, May 02, 2017 4:57 PM
To: Emily Kellagher <Emily.Kellagher@Colorado.EDU>
Subject: Thanks and question

Hi, Emily,

Thanks for your help today with the newsletter bundle. This is very cool. I wonder if you could help me with a question I have about the draft I have here:

https://www.colorado.edu/asmagazine/node/2266/email

Generally, we use the A&S magazine’s brand-compliant lockup on the top of the email, and I built this that way. However, I see that the CU Boulder logo is atop the page. My question:

Is there a way to use the A&S magazine logo rather than the CU logo?

Thanks again.

Clint

Clint Talbott, Director of Communications and External Relations
College of Arts and Sciences
University of Colorado
1B-90B Old Main
Campus Box 275
Boulder, CO 80309-0275
303-492-6111 / FAX 303-492-4944
http://www.colorado.edu/asmagazine/

**Comment by kreynen** [comment]
Issue moved to [CuBoulder/cu_newsletter_bundle #39](https://github.com/CuBoulder/cu_newsletter_bundle/issues/39) via [**ZenHub**](https://www.zenhub.com/)
