### ISSUE TITLE
As a SO/CE I want to more easily be able to view how blocks are used throughout the site

### ISSUE THREAD

**Issue by wturnbull** [CuBoulder/express#1018]
## Context

It would be helpful to be able to view blocks, similar to how you can view content. I would like to be able to go to the Blocks list and click on the name of the block to view it, instead of having to first edit the block, then view it. 

In addition, it would be very helpful to be able to see which blocks are being used on the site, and possibly where they are placed. 

## Process

1. Login to site as a [SO, CE, EO, ADMIN or DEV]
2. Click Find Content
3. Click Blocks

## Expected result

I would like to see a link on each Block name on the Blocks listing page. When clicking on the block name, you will go to a page to view the Block.

I would like to see something like 'Active' next to blocks to see which ones are placed. Or whatever makes sense. And some way to see a list of where it's placed. Realize this is a tough one to produce. 

## Current result

I go to blocks listing and have to first edit to view the block. I also may have a lot of unused blocks on the site, but there's no easy way to see which ones are no longer being used.

## Screenshots

----

## Links to Examples

https://www.colorado.edu/p1026604f052/admin/content/blocks

**Comment by kreynen** [comment]
I think the best we can do is tell if a block is used in a layout entity or referenced at all in a context.  That doesn't tell you extactly where the block is used if the context is something like node where type = article and user role = site_owner, but it gives users more info about the block usage than we provide now and would let you know if the block wasn't used in either layout or context.

**Comment by jwfuller** [comment]
Need to be careful with the queries in this, we are going to be loading large result sets, so performance could easily deteriorate on a large instance.
