### ISSUE TITLE
As an ADMIN I want to clear the Varnish cache

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express#1022]
## Context

We would like to increase the TTL for Drupal requests. The current 300 second TTL is to mitigate the impact of our simple cache clearing logic. We do not have good logic to clear URLs that contain content via entityreference.

## Possible Fix

Add Varnish cache clear buttons in 3 places
- On nodes, `ban` the path for the node
- Whole site button, `ban` the whole site (limited use button, similar to Drupal cache clear)
- Form to `ban` a given path (do not support regex or wildcards)

Requires documentation update

**Comment by jwfuller** [comment]
See google doc [Clearing Caches in Web Express](https://docs.google.com/document/d/1Qdnj0_Qy9gjRYlei0JyUYyn0lmmUqq0Zwu0D4rar1hg/edit) for suggested documentation.

**Comment by ekellagher** [comment]
Web Central Documentation:
https://www.colorado.edu/webcentral/tutorial/v2/clearing-caches-web-express

**Comment by kreynen** [comment]
The cache clear option is currently under Administer.  That section was going to be for users w/ Admin role, but we've already deprecated the only other feature in that section.  Is this UI supposed to be available to both Site Owners and Content Editors?  Or should the CE limited to the per node clearing?

**Comment by kreynen** [comment]
Leave as admin role only for 2.4

**Comment by jwfuller** [comment]
Commit reverted
