### ISSUE TITLE
As SM, I want to reduce the maximum image file size allowed

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express#1023]
## Context

We run out of memory several time a week trying process images that are 10 MB+.
 
## Possible Fix

- Add file size and dimension limits to all image fields. Proposed 4MB and 2000x2000 px.

## Process
1. Click Add Content
2. Click Basic Page
3. Upload an image larger than 2000x2000 to the image field
4. If you download the uploaded image, it should be resized to 2000x2000

**Comment by kreynen** [comment]
I'm assuming this would be happening at the client side before the image is uploaded to the server to fix this.

**Comment by cathysnider** [comment]
*Acceptance Criteria:*
- [ ] Too-big Images are sized down to 2000

**Comment by jeor0980** [comment]
I agree with cathy, it could be nice to change the 'Images must be smaller than 2000 x 2000.' text to something like 'Images larger than 2000 x 2000 will be scaled down / compressed when uploaded.' Same thing for images over 4 MB and bigger than 2000 x 2000.

**Comment by kevincrafts** [comment]
The ''Images must be smaller than 2000 x 2000" is coming from Drupal Core - I don't think we should add who knows how many form alters for it to display something different.
