### ISSUE TITLE
As a SO/CE I would like to have the option to resize my embedded map window

### ISSUE THREAD

**Issue by wturnbull** [CuBoulder/express#1024]
## Context

When embedding a map, there is a default size height that narrow. This works okay when there is only one point on the map, but we're looking into using Google maps with multiple points and categories and need to be able to see more information - including the points and the text to the left side. 

## Process

1. Login to site as a SO, CE
2. Click into any WYSIWYG editor
3. Click Map Shortcode Generator icon
4. Paste in map embed code
5. Click save

## Expected result

I expected to have the option to show more of the map - have a taller area display - and be able to see the text to the right.

## Current result

The size is defaulted to a pretty narrow area. 

## Possible Fix

Have default size and option to resize the height the window/area the map is placed in.

## Screenshots

![screen shot 2017-04-20 at 1 44 36 pm](https://cloud.githubusercontent.com/assets/1757082/25249709/0ed63fc0-25d0-11e7-997b-9c9c1d068770.png)
![screen shot 2017-04-20 at 1 45 01 pm](https://cloud.githubusercontent.com/assets/1757082/25249726/254a021e-25d0-11e7-85a7-56cf1f43b167.png)

## Links to Examples

* Test block: https://www.colorado.edu/p1026604f052/research (this is a working site so this may be changed - but is the same as the screenshot above)
* Example of a site that it looks good embedded: https://mediacommons.psu.edu/locations/ 
* Test map: https://www.google.com/maps/d/viewer?mid=1bhxhZLqr6_fBB9yAjPITC7PbhPU&ll=39.13578941760871%2C-106.78071464375296&z=7

**Comment by kevincrafts** [comment]
Related to #883

**Comment by cathysnider** [comment]
Not working at this time. https://www-dev.colorado.edu/feature/883/map-sizes 
All the iframe are being given a class of map-small. 
![mapsmall](https://cloud.githubusercontent.com/assets/638275/26018952/5afb1266-372f-11e7-918e-6b2b500bab85.png)

**Comment by cathysnider** [comment]
https://www-dev.colorado.edu/feature/883-2

**Comment by cathysnider** [comment]
Verified: The map shortcode generator has a drop-down which allows the user to specify map size. 
![screen shot 2017-05-16 at 9 23 46 am](https://cloud.githubusercontent.com/assets/638275/26114081/9f0bdd2c-3a19-11e7-8482-833770187da1.png)

**Comment by ekellagher** [comment]
Tutorial Updated: https://www.colorado.edu/webcentral/tutorial/v2/embed-google-map
