### ISSUE TITLE
Context UI not visible when Publications Bundle enabled

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1026]
## Context

Context does not available in www-test sites

## Process

1. Create a test site. 
2. Login to site as a DEV
3. Click Structure

## Expected result

Context should appear in the list.

Nor is it available at admin/structure/context

## Current result

nada

## Links to Examples

https://www-test.colorado.edu/p1386f7a359a/admin/structure/context

**Comment by jwfuller** [comment]
I believe the permissions for that menu item are defined in Adv Design or Adv Layout. Neither of those is enabled for that instance, at this time.

**Comment by cathysnider** [comment]
The Publications Bundle needs Context in order to place the Issue blocks. So,
1)  it should be enabled with the bundle or 
2) the instructions should say, “Enable Advanced Design or Advanced Layout." http://www.colorado.edu/webcentral/tutorials/publications-bundle

**Comment by alexfinnarn** [comment]
"the instructions should say, “Enable Advanced Design or Advanced Layout." http://www.colorado.edu/webcentral/tutorials/publications-bundle" 

I agree with this option. Using the publications bundle doesn't "require" the Context module, adding Context gives you more options but isn't necessary.

**Comment by alexfinnarn** [comment]
Add to http://www.colorado.edu/webcentral/tutorial/v2/publication-blocks

"Note: To use the issue blocks feature, you will have to have Context enabled which can be turned on via the Advanced Design or Advanced Layout bundles"

**Comment by alexfinnarn** [comment]
From Emily K..."@afinnarn Yes you can close it - I updated the tutorial to note that context is needed and that one of the other bundles would need to be enabled."
