### ISSUE TITLE
As a SO, I want a Simple Site Verification Process

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1028]
## Context

Our site verification process is currently too complicated.  The primary reason for using this over metatag_verify is easy of use, but giving a SO so many options is confusing.  After checking the list of services we recommend integrating with, we've confirmed that they all support metatag based verification.  

## Process

1. Login to site as a SO enable the SEO Bundle
2. Click Express > Settings > Verification > Add Verification
3. Select Google

## Expected result

Users are presented 1 option for metatag base verification with inline help

## Current result

Users are given multiple options for verification

## Possible Fix

Instead of offering both file upload and metatag verification, we should suppress the file upload option by wrapping it in an addtional permission.  Instead leaving the metatag option as an open text field, we should parse the input for the metatag value.

**Comment by kevincrafts** [comment]
Google provides these steps to grant membership to a Analytics ID:

Create an analytics.txt file with the following information:

GooGhywoiu9839t543j0s7543uw1 - pls add {INSERT EMAIL ADDRESS} to GA account {INSERT UA-ID} with ‘Manage Users and Edit’ permissions - date {INSERT DATE}.
Add the analytics.txt file to the top-level domain, e.g., example.com/analytics.txt

If the URL of the site that is sending data to Analytics is a subdomain, then you can upload analytics.txt to either the subdomain or the top-level domain, for example:

sales.example.com/analytics.txt or example.com/analytics.txt

If you cannot prove ownership of all the sites identified by Default URLs in the Analytics account, then we cannot grant access.

After you have uploaded the analytics.txt file, then fill out and submit the following form, and our support team will contact you.
