### ISSUE TITLE
As a SO/CE I would like to be able to display social media links in the footer of a newsletter

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1044]
@ekellagher commented on [Thu May 04 2017](https://github.com/CuBoulder/documentation/issues/5)

There is not a convenient place to add social media icons in the newsletter content type.
If you add an icon to the promos/ adds section the image is too big - this is also the case in the blocks since the smallest image you can add is 300 px (image style small)

## Possible fix
Add a reference field to social media blocks from the newsletter taxonomy term (where other newsletter type, title, footer info is stored).

Though we can't just output the social media block entity as it's designed, since HTML email can't use the font icons.

**Comment by alexfinnarn** [comment]
not sure you can view the newsletter in the Drupal UI, but I feel like I saw that feature. You would need to view the HTML output somewhere to test this.

**Comment by cathysnider** [comment]
Note: Social Media Bundle must be enabled for this to work.

**Comment by cathysnider** [comment]
https://github.com/CuBoulder/express/issues/1821
