### ISSUE TITLE
As a SO/CE, I need to create a timeline or sequence of content.

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1049]
This is an add on bundle: https://github.com/CuBoulder/cu_timeline_bundle

## Context

When creating a sequence of content using available tools in web express, the results are not all that compelling.

Creating a custom block type that will allow people to make date based, or step based sequences of content will allow SO/CE users to easily create  media rich, interactive content.

## Possible Fix

Timeline content should have multiple display options, some which are good for date based content, others that are better for a sequence of content.

![screen shot 2017-05-02 at 9 07 40 am](https://cloud.githubusercontent.com/assets/349713/25956373/ca67b814-3628-11e7-8cd6-b0dee1db7b23.jpg)
![screen shot 2017-05-02 at 9 06 44 am](https://cloud.githubusercontent.com/assets/349713/25956375/caa13b98-3628-11e7-9a52-20588578ef2e.jpg)
![screen shot 2017-05-02 at 9 06 12 am](https://cloud.githubusercontent.com/assets/349713/25956374/ca8dc9dc-3628-11e7-8221-cb4c4f7c32e6.jpg)

**Comment by cathysnider** [comment]
http://www-dev.colorado.edu/feature/1049-sequence/

**Comment by cathysnider** [comment]
Problem: Block Titles don't stick. 
To Reproduce: Create a simple timeline, filling out the Title field. Save. Place block on a page. 
Result: The title is not displayed. Edit the block and you'll see that the Block Title field has been purged. Fill out title field again. Save. Same result.

**Comment by cathysnider** [comment]
Another note: in the Advanced Sequence Body field, the shortcodes don't work but the other stuff does (bolding, links, etc). See screenshot. This may be something that is solved with proper documentation. https://www-dev.colorado.edu/feature/1049-sequence/node/22
![advancedsettingsbody](https://cloud.githubusercontent.com/assets/638275/26506288/385e137c-4209-11e7-92ab-b5c61a335f54.jpg)

**Comment by cathysnider** [comment]
Problem: When a Content Sequence block is given a theme, the text colors become unreadable. See screenshot. Example: https://www-dev.colorado.edu/feature/1049-sequence/simple-horizontal
![whitetext](https://cloud.githubusercontent.com/assets/638275/26593199/829f9f9a-4520-11e7-9b1e-df25c841e5e5.jpg)

**Comment by cathysnider** [comment]
Problem: When an Advanced Timeline has empty content (i.e. no body content, no graphic or no video) the timeline throws an error that is difficult to understand. The Simple Timelines do not do this.  Example:  https://www-dev.colorado.edu/feature/1049-sequence/advanced/advanced-one-empty
![timelineerror](https://cloud.githubusercontent.com/assets/638275/26593739/74acb7a4-4522-11e7-8697-5dfbec57e59e.jpg)
