### ISSUE TITLE
Rework cu_profile_module_manager to be more efficient.

### ISSUE THREAD

**Issue by owenmorrill** [CuBoulder/express#1071]
## Context

Right now we're using three complete builds for each page (addon, request, beta) and there's definitely an opportunity to bring it down to a single function that builds out each page based on tags.

We also want to add a way to bring in github descriptions and demo sites so they display in the bundle card.

Also, right now we're passing the machine name to the "are you sure you want to..." page. We need to change that to the label so it's easier to read/is consistent.

**Comment by alexfinnarn** [comment]
marking as In Progress due to blocker.

**Comment by owenmorrill** [comment]
Woohoo, blocker has been removed.

**Comment by cathysnider** [comment]
Note to self: when testing, also check that CuBoulder/express/issues/1409 functionality works -- i.e. that Bundles Screens should only show the current version of the bundle

**Comment by alexfinnarn** [comment]
I'm basing my branch off of #2434 and the UI changes it makes. One of the first issues to deal with is normalizing how the info for bundles is pulled from actual files on the server as well as GitHub repos.

Secondly, you need to store the information somewhere, and it is better to do that in a cache bin or a db table than the Drupal variable set/get functions.
