### ISSUE TITLE
As A Site Owner, I Need To Grant Users Certain Permissions Without Adding Roles

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#1084]
## Context

We are starting to see the need for permissions that don't fit into the roles we have defined in Express. We just added a Campaign Manager role that is only included in a custom add-on bundle. 

The more roles we add like this, the more chance for side effects and extra debugging because of this potential difference between sites. 

You could add canary users by this method as well. The beta bundles would only be seen by users we deem canaries.

## Expected result

Within the configuration for the bundle, I can grant specific users any permissions needed for that bundle. 

## Current result

New user roles need to be created to grant specific permissions. 

## Possible Fix

Hack core. Yeah, let's do it! If you extend user_role_permissions() here https://api.drupal.org/api/drupal/modules%21user%21user.module/function/user_access/7.x, then you can do the same things that function does but add a check for individual permissions tied to an account. 

In cu_user_role_permissions($account), you would call user_role_permissions() and then check an added db table that indexes uids to permission strings. 

There are many modules that deal with node_access(). However, if you are working outside of nodes, granting permissions using those hooks wouldn't cover this use case. Adding the same check in hook_node_access() should take care of node access permissions.  

## Process

1. A SO would save the config form with a string of usernames that are granted a set of permissions. The set of permissions is defined in code so SO's don't have the option of choosing those permissions.  
2. The username gets converted to uid and stored with one entry per permission. 
3. When user_access() is checked, the permissions for the uid are obtained from that db table and included in the access check.

**Comment by kreynen** [comment]
We are adding some of this with Digital Campaign Managers and https://github.com/CuBoulder/express/issues/1869, but it still makes sense to keep the a set of core roles with common permission configurations.  Creating a role for the permission of every feature would just to too confusing for SO.
