### ISSUE TITLE
As SM, I want custom bundles highlighted for SO 

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1085]
## Context

We made a number of changes to the Bundles UI in #898.  We've deployed those in 2.4.0 and documented the changes for [users](http://www.colorado.edu/webcentral/web-express-features/bundles-features) and [developers](https://github.com/CuBoulder/express_documentation/blob/master/docs/express_bundles.md), but we weren't able to improve the UI

**Comment by alexfinnarn** [comment]
What is SM? You mean SO, as in Site Owner?

**Comment by kreynen** [comment]
Service Manager

**Comment by kreynen** [comment]
- [ ] https://github.com/CuBoulder/cu_livechat_bundle
- [ ] https://github.com/CuBoulder/cu_alumni_bundle
- [ ] https://github.com/CuBoulder/cu_campus_news_bundle
- [ ] https://github.com/CuBoulder/cu_classes_bundle
- [ ] https://github.com/CuBoulder/cu_countdown_bundle
- [ ] https://github.com/CuBoulder/cu_custom_logo_bundle
- [ ] https://github.com/CuBoulder/cu_demo_bundle
- [ ] https://github.com/CuBoulder/cu_editor_note_bundle
- [ ] https://github.com/CuBoulder/cu_livestream_bundle
- [ ] https://github.com/CuBoulder/cu_publications_bundle
- [ ] https://github.com/CuBoulder/cu_soundcloud_bundle
- [ ] https://github.com/CuBoulder/cu_storify_bundle
- [ ] https://github.com/CuBoulder/express_output_region_bundle
