### ISSUE TITLE
Getting 500 errors when enabling bundles and modules

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1086]
![screen shot 2017-05-30 at 1 41 35 pm](https://cloud.githubusercontent.com/assets/385234/26601643/dade759c-453d-11e7-83c6-60e9798e3c6c.png)

**Comment by kreynen** [comment]
8 sites are reporting that they have newsletter nodes https://osr-atlas03.int.colorado.edu/statistics?where={%22nodes_other%22:{%22$regex%22:%22newsletter%22,%22$options%22:%22i%22}}&projection={%22site%22:1}

**Comment by kreynen** [comment]
Launched:
chbe
postdoctoralaffairs
asmagazine
today
education
isss

Unlaunched:
p1f4bca2b935
p15a75c78bd6

**Comment by kreynen** [comment]
This error is very intermittent.  My current guess about what is happening is that the AJAX fails to get even a 200 response from the HTTP request because another process has cleared the APC cache for the entire service and the request times out.  The good news is that once the PHP service starts processing the queue of requests again, the bundle is actually enabled properly.  The bad news is that with the changes we've made to the Bundles UI in #898, there is going to be a lot more cache clearing.

**Comment by kreynen** [comment]
I've also gotten 500 errors when adding modules through admin/modules, but that may have been due to adding modules that only existed in APC's cache

**Comment by alexfinnarn** [comment]
After updating only the commit hash on https://osr-atlas01.int.colorado.edu/code/5938525235f7c348428c24c4 I then saw the following for all paths on http://www-dev.colorado.edu/webcentral.

```
PHP Fatal error:  Class 'context_condition' not found in /data/code/profiles/express/express-2.4.0/modules/custom/context_sitewide_public/context_sitewide_public.context.inc on line 3
```

**Comment by kreynen** [comment]
@jwfuller
