### ISSUE TITLE
Publications Bundle Needs A Cache Clear

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#1088]
## Context
Upon enabling the Publications bundle, I couldn't create an issue until I cleared the cache. 

## Process

1. Login to site as a SO
2. Request Publications bundle through UI. 
3. Enable Publications bundle through UI. 
4. Go to create an issue via add content UI.

## Expected result

All the fields needed to create an issue are there. 

## Current result

Sometimes only the title field is present. 

## Possible Fix

Add a cache clear key to the bundle info file. https://github.com/CuBoulder/express/blob/dev/modules/custom/cu_advanced_design_bundle/cu_advanced_design_bundle.info#L13

## Screenshots

![screen shot 2017-05-30 at 2 14 01 pm](https://cloud.githubusercontent.com/assets/3640707/26603693/07d0d912-4545-11e7-9e0b-e28eb3c3af0a.png)

**Comment by kreynen** [comment]
Fixed with https://github.com/CuBoulder/cu_publications_bundle/commit/f025620b29ea2f386bf407f217a5782ca4f95cf6
