### ISSUE TITLE
Varnish Cache Clear On Content Creation Screen

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#1090]
## Context

The Varnish cache clearing button doesn't care whether or not the form is creating or editing content. You can't clear a Varnish entry for content that doesn't exist. 

## Process

1. Login to site as a SO.
2. Go to "node/add/page".

## Expected result

I don't have the option to clear the Varnish cache. 

## Current result

I am confused. 

## Possible Fix

Only add cache clear button if on a node edit form. 

## Screenshots

![screen shot 2017-05-30 at 2 38 24 pm](https://cloud.githubusercontent.com/assets/3640707/26604221/e485d960-4546-11e7-979c-240fcb23da5c.png)

## To Test

**Varnish Path Cache**

This is the only part of this feature available to CE.

It is possible to view this using the Network tab of the deveoper tools, but much easier if you install a Chrome plugin like https://chrome.google.com/webstore/detail/varnish-indicator-forked/cecjclajledipahfcbkcajegnbmpnbco?hl=en

![varnish](https://user-images.githubusercontent.com/385234/27648413-b31b8f94-5beb-11e7-8fe3-269912d0aa11.png)

Going to a url like the homepage would be difficult to get a miss, but most requests to dev and tests will be a miss after 5 minutes since there are so few users going to those sites.

When a path is cleared, the first request for that page using http should be a miss.  This means the request wasn't cached by vanish and had to be generated by Drupal.

**Varnish Full Cache**

Access to this is limitted to user with the SO, Admin, and Dev roles.  

The process to test should be the same as the path test, but all urls for that specific site should be a miss.

**Drupal Full Cache**

Access to this is limitted to user with the SO, Admin, and Dev roles.  

No easy way to test that the cache was actually cleared from the UI.  On a local install w/ memcache disabled, we can look at the cache tables.  They should be empty after the user executes this.  Since we are leveraging the core cache clearing functionality, this should work the same way as admin/config/development/performance or drush cc all.

**Comment by kreynen** [comment]
The path to the admin form is limited, but the form alter is not https://github.com/CuBoulder/express/blob/dev/modules/custom/express_settings/express_settings.module#L493

**Comment by kevincrafts** [comment]
I suggest that we add the link to the primary tabs. Since this is a page level function, not a node level function, I think it works better there.

**Comment by alexfinnarn** [comment]
![screen shot 2017-06-06 at 9 55 15 am](https://user-images.githubusercontent.com/3640707/26838752-478cb20c-4a9e-11e7-9e22-f15ee6a8c21b.png)

Shouldn't the Varnish notes part be in a fieldset to keep consistency with the Drupa cache section? Also, aren't all caps a bad practice?

**Comment by cathysnider** [comment]
Acceptance Criteria: 
- [ ] Button 'Clear Varnish Cache' appears in Primary Tabs
- [ ] After page is created, not before
- [ ] for Site Owners and Content Creators.

**Comment by cathysnider** [comment]
Fail: Neither Site Owners nor Content Creators can see the button in the Primary Tabs. 
![clearvarnishcachedev](https://user-images.githubusercontent.com/638275/27195314-7d507dd4-51c3-11e7-9a99-3cffa760af6b.jpg)
![clearvarnishcacheso](https://user-images.githubusercontent.com/638275/27195313-7d4f1818-51c3-11e7-8850-8c4a715b909f.jpg)

https://www-dev.colorado.edu/p12c41187287

**Comment by kreynen** [comment]
This actually doesn't clear the varnish cache regardless of whether you are clicking it on the homepage or a node.  Why are we passing this node vs. just clearing the path the user is on regardless of what it handling the path?

**Comment by alexfinnarn** [comment]
The button on the node, where you don't specify the path, was using a form element that didn't exist after moving it. The form now takes the second argument of the path "node/%/" to get the alias. 

I see the green status message when I click any of the buttons, but I have no working sites locally to test the actual Varnish cache clear. 

The permission on "node/%/clear-varnish" is set to "administer cache settings" so that permission or a new permission needs to be made for content editors to use it...or that permission can be added to site owners and content editors.

**Comment by kreynen** [comment]
I've updated this and made a number of changes.  CE can now clear varnish by path.  SO can clear the full Drupal and varnish caches.

Moved the menu item in admin/settings from administration to cache.

There are limits on the path cach clearing, but I'll open new issues for those.

**Comment by jwfuller** [comment]
Yes, we want to clear the path, not 'node/123'. If 'node/123' existed in varnish it would be a redirect to the path so we still just want to clear the path, the redirect is still good.

**Comment by kreynen** [comment]
Running the path cache clear locally on the front node as a SO I see this in the logs...

```
 1.34 CLI            Rd ban req.http.host ~ express.local && req.url ~ /test/
     0.74 CLI            Rd ban req.http.host ~ express.local && req.url ~ ^/test//test/profiles/express/themes/expressbase/apple-icon-57x57.png$|^/test//test/profiles/express/themes/ex
     0.74 CLI            Rd ban req.http.host ~ express.local && req.url ~ ^/test/node/1/attachment$|^/test/node/1/backstretch$|^/test/node/1/large$|^/test/node/1/medium$|^/test/node/1/
```
As a CE I see this error and nothing in the logs...

<img width="812" alt="varnish_error_message" src="https://user-images.githubusercontent.com/385234/27802530-7be4a2c8-5fe1-11e7-9610-8e02e6d7cf07.png">

When clearing the Full Page Cache using varnish_purge_all I see just...

``` 
1.24 CLI            Rd ban req.http.host ~ express.local && req.url ~ /test/
```

So I think that it isn't necessary to clear the filepaths and other assets, but we are are clearing the right paths.

**Comment by cathysnider** [comment]
I suggest a change to the text of tabs to 

- "Clear One Page Path"
- "Clear All Page Paths"
- "Clear Database Cache"
