### ISSUE TITLE
Add Bundle Tag To Custom Bundles

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#1094]
## Context

A lot of bundles now show up in the core tab of the Bundles UI. 

## Process

1. Log in to a site as a Developer.
2. Add as many packages via Atlas that have "_bundle" in the name as makes sense. 
3. See a lot of add-on bundles listed in the core tab. 

## Possible Fix

Add bundle tag key to info files of add-on bundles. 

- [ ] https://github.com/CuBoulder/cu_livechat_bundle
- [ ] https://github.com/CuBoulder/cu_alumni_bundle
- [ ] https://github.com/CuBoulder/cu_campus_news_bundle
- [ ] https://github.com/CuBoulder/cu_classes_bundle
- [ ] https://github.com/CuBoulder/cu_countdown_bundle
- [ ] https://github.com/CuBoulder/cu_custom_logo_bundle
- [ ] https://github.com/CuBoulder/cu_demo_bundle
- [ ] https://github.com/CuBoulder/cu_editor_note_bundle
- [ ] https://github.com/CuBoulder/cu_livestream_bundle
- [ ] https://github.com/CuBoulder/cu_publications_bundle
- [ ] https://github.com/CuBoulder/cu_soundcloud_bundle
- [ ] https://github.com/CuBoulder/cu_storify_bundle
- [ ] https://github.com/CuBoulder/express_output_region_bundle

**Comment by kreynen** [comment]
Issue defined in https://github.com/CuBoulder/express/issues/1085
