### ISSUE TITLE
Article External URL Notice Not Displaying

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1095]
## Context

When a SO/CE/ADMIN views an article that uses the external url field, a message should display letting them know that the article will be redirected for anonymous users and display the link.

It seems that only developers can see this message, as the message type is set to 'notice'.  If the type is removed or type is set to 'status' the message will display.

## Process

[ordered list the process to finding and recreating the issue, example below]

1. Login to site as a [SO, CE, EO, ADMIN]
2. Click Add Content
3. Click Article
4. Enter a url in the External URL field
5. Click save
6. View Article

## Expected result

A message should display:
A user without editing permissions would have been redirected to {{URL}}

## Current result

No message is displayed.

## Possible Fix

Set the message type to 'status'.
https://github.com/CuBoulder/express/blob/dev/modules/features/cu_article/cu_article.module#L1338

**Comment by cathysnider** [comment]
Acceptance Criteria:
- [x] For SO or CE, on Articles that link to External URLs, the External URL message displays. 

Note: there doesn't seem to be anything else to test here, as all we're doing basically is displaying a different variable than previously. 

https://www-dev.colorado.edu/p18a3c859925/2017/06/26/important-article

Test Result: Pass
