### ISSUE TITLE
Improve Embed UI

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1102]
- [x] Add icon to Embed tab
- [x] Format filter options to minimize form 
- [x] Add inline documentation links

**Comment by alexfinnarn** [comment]
PR in https://github.com/CuBoulder/cu_digital_campaign_bundle/pull/16

**Comment by alexfinnarn** [comment]
I removed the older code asset on https://www-dev.colorado.edu/p14d966617ad, and now it appears ready for testing.
