### ISSUE TITLE
Deprecate Active Data Events Bundle

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1103]
- [x] Confirm we have stats to find the sites using this bundle
- [x] Create bundle repo
- [ ] Deploy to prod with beta_bundles tag
- [ ] Enable on all sites using Calendar now
- [ ] Update bundle to addon_bundle tag
- [ ] Remove code from Express repo

**Comment by kreynen** [comment]
https://osr-atlas03.int.colorado.edu/statistics?where={%22bundles.cu_events_bundle.schema_version%22:{%22$ne%22:null}} reports 423 sites have the  cu_events_bundle enabled, but only 143 have blocks according to https://osr-atlas03.int.colorado.edu/statistics?where={%22beans_by_type.cu_events_calendar_block%22:{%22$ne%22:null}}

**Comment by kreynen** [comment]
now 451 https://osr-atlas03.int.colorado.edu/statistics?where={%22bundles.cu_events_bundle.schema_version%22:{%22$ne%22:null}} and 156 https://osr-atlas03.int.colorado.edu/statistics?where={%22beans_by_type.cu_events_calendar_block%22:{%22$ne%22:null}}

**Comment by owenmorrill** [comment]
https://github.com/CuBoulder/cu_events_bundle

**Comment by kreynen** [comment]
Because we ended up removing the Active Data event modules as we deployed the Localist bundle, the only step left is to delete the cu_events_calendar_block module
