### ISSUE TITLE
Content Sequence Bundle: descriptive text needed

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1104]
## Context

The Content Sequence bundle has no descriptive text

## Process

1. Login to site as Site Owner or Dev (anyone who's got bundle-enable permissions)
2. Go to Settings >> Enable Bundles >> Add On (admin/settings/bundles/list/addon)
3. Enable the Content Sequence Bundle
4. Wait till it has been downloaded. 
5. Click save

## Expected result

I expect the Content Sequence Bundle description on the Core tab to have a description.

## Current result

Description is blank

## Screenshots

[if relevant, include screenshots]

----

## Links to Examples

* https://www.colorado.edu/isss/admin/settings/bundles/list

![screen shot 2017-06-01 at 10 49 21 am](https://cloud.githubusercontent.com/assets/638275/26691501/9d2bf714-46ba-11e7-9b43-be4508e38d36.png)

**Comment by kreynen** [comment]
Once the bundle is added to the site's codebase, the description comes from https://github.com/CuBoulder/cu_content_sequence_bundle/blob/master/cu_content_sequence_bundle.info

**Comment by kreynen** [comment]
Right now the SO should only see the bundle in this state once... between the time they request it and when they enable it, but with https://github.com/CuBoulder/express/issues/1114 this becomes a bigger issue.
