### ISSUE TITLE
As a SO/CE I would like to create a hero unit with a video background

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1105]
## Context

Many of the sites that are making good marketing pages have requested the ability to have a hero unit that has a video background instead of a still photo background.

https://github.com/CuBoulder/cu_video_hero_unit_bundle

**Comment by cathysnider** [comment]
Doesn't seem to be working so well: https://www-dev.colorado.edu/p102abf4220a/

**Comment by kevincrafts** [comment]
This required an update to the FitVids.js library which was merged last week. https://github.com/CuBoulder/express/issues/1185
