### ISSUE TITLE
As a SO I would like to create a page on my site that is a destination from an advertisement

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1106]
## Context

Sites that are running ad campaigns have wanted to create pages that have little, if no navigation to focus the user on completing a certain action, like filling out a form.

Currently, units are creating new Web Express instances just to create a single page for each campaign. 

## Possible Fix

Create a configuration to select pages, paths, etc that can be used as a campaign page.
Campaign pages will hide main, secondary, footer, mobile menus, breadcrumbs, and search.

https://github.com/CuBoulder/cu_funnel_page_bundle

**Comment by alexfinnarn** [comment]
Need to follow https://github.com/CuBoulder/express_documentation/blob/master/docs/creating_custom_bundles.md#info-file

**Comment by alexfinnarn** [comment]
No way to automatically test this code on PRs. Need to come up with a system for that.

**Comment by cathysnider** [comment]
https://github.com/CuBoulder/express/issues/1363
