### ISSUE TITLE
Move Feeds from Express Profile to Add-on Bundle

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1107]
- [x] Confirm we have stats to find the sites using this bundle
- [x] Create bundle repo
- [ ] Deploy to prod with beta_bundles tag
- [ ] Enable on all sites using Calendar now
- [ ] Update bundle to addon_bundle tag
- [ ] Remove code from Express repo

**Comment by kreynen** [comment]
[92 sites report running this bundle](https://osr-atlas03.int.colorado.edu/statistics?where={%22bundles.cu_feeds_bundle.schema_version%22:{%22$ne%22:null}})

**Comment by owenmorrill** [comment]
https://github.com/CuBoulder/cu_feeds_bundle
