### ISSUE TITLE
As a SO I need to have a link to web support on the add-on bundle tab

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#1109]
## Context

The current text on the page reads:
"Don't see your bundle available in Core yet? It takes a few minutes to download. If it takes longer than 15 minutes, contact your site owner for help."

Should say something like:
Don't see your bundle available in Core yet? It takes a few minutes to download. If it takes longer than 15 minutes, contact Web Support for help.

**Comment by ekellagher** [comment]
<img width="747" alt="add-on text" src="https://cloud.githubusercontent.com/assets/16137919/26693753/7dba21c8-46c2-11e7-9a9f-058355204f5a.PNG">

**Comment by cathysnider** [comment]
It would be better if the link went to contact information or included an email

**Comment by cathysnider** [comment]
We meant, link the words 'contact Web Support' to WebCentral. However, there is a link to WebCentral in the upper right. 

![screen-shot-2017-09-19-at-11 50 31-am](https://user-images.githubusercontent.com/638275/30607303-bb978448-9d31-11e7-8f95-c466ccedf2fa.jpg)
