### ISSUE TITLE
As SO, I want to see more information about Add-on Bundles before adding/requesting them

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1114]
## Context

Currently, we are showing the same text for each Add-on bundle vs. the description from module's .info file.  We do this because 

## Process

When a user goes to admin/settings/bundles/list/addon the site either uses a cached version of the descriptions or goes to GitHub using the way we used to do with cu_inventory.

## Expected result

See the values from bundle .info files the same way that local bundles are displayed.

## Current result

We are currently displaying "For information on this and other bundles that require a request, visit Webcentral's page about bundle requests." for all Add-on and Request bundles.

## Possible Fix

If the machine name of the bundle matches the repo and the .info file is at the root level of the repo/project (the normal Drupal.org structure), we could parse that data from GitHub similar to how we were getting the git submodule names in [cu_inventory ](https://github.com/CuBoulder/express/blob/283d995a194ba6c0c6254cd476fae08b1c7e6772/modules/custom/cu_inventory/cu_inventory.module#L93).

Because there will end up being > 10 add-on/request bundles, these outgoing requests will add up.  To make this perform well, we could save these are variables and only get them if they are missing.  

This would allow us to set the default values in Express updates, but deploy new bundles between updates.

The links to http://www.colorado.edu/webcentral/tutorial/v2/adding-bundles and http://www.colorado.edu/webcentral/content/request-add-bundle should be moved to inline

![configure_bundles___university_of_colorado_boulder_and_configure_bundles___university_of_colorado_boulder_and_cu_digital_campaign_bundle_module](https://cloud.githubusercontent.com/assets/385234/26695844/a067fd1a-46c9-11e7-88cf-7959f2eca6b7.png)

https://docs.google.com/spreadsheets/d/182Zxoi38D3FWv4tkfIWz0ZAErWje5j-e9t6LRnvsSaY/edit#gid=0

**Comment by anniebyellow13** [comment]
Just a heads up that the correct nomenclature is Add-on.

**Comment by owenmorrill** [comment]
This is going to require updating the bundles where the bundle .info isn't in the root of the repo.  Create new issues for all of the bundles that need updates

**Comment by owenmorrill** [comment]
Need to update: https://github.com/CuBoulder/express_documentation/blob/master/docs/creating_custom_bundles.md#info-file

**Comment by kreynen** [comment]
We only need to update bundles that will be seen by users in Profile Module Manager.  Bundles like cu_custom_logo_bundle need a Label in Atlas and grouping in the .info so they appear correctly once they've been added, but they will be added using the Atals or Shugger UI for the foreseeable future.

**Comment by owenmorrill** [comment]
Add-on
- [ ]  Publications
- [ ]  Content Sequence
- [ ]  Collections

Request
- [ ]  Chemistry Title
- [ ]  Livechat
- [ ]  Livestream
- [ ] Newsletter
- [ ] Responsive Visibility
- [ ] Video Hero Unit

Beta
- [ ] Digital Campaign

**Comment by cathysnider** [comment]
Test Results:
Not all bundles are pulling their info from the .info file at root.
Publications, Chemistry Titles, Live Chat, Live Stream, and Newsletter all still say "For information on this and other bundles that require a request, visit Webcentral's page about bundle requests."
