### ISSUE TITLE
As a SO, I want to be able to link webforms to ServiceNow

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1115]

**Comment by jwfuller** [comment]
Need to make sure we can handle situations where they cannot accept data

**Comment by owenmorrill** [comment]
- [ ] process a webform email so that the sent email has the uploaded file as an email attachment?

**Comment by kreynen** [comment]
Issue moved to [CuBoulder/cu_forms_bundle #43](https://github.com/CuBoulder/cu_forms_bundle/issues/43) via [**ZenHub**](https://www.zenhub.com/)
