### ISSUE TITLE
BUGS: Content Sequence

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1117]
Simple Horizontal:

UL or OL in content does not display.

Simple Vertical:

Colors not visible if block theme is dark.

Advanced: 

Link colors not accessible if block theme is dark.

**Comment by kreynen** [comment]
Fixed in https://github.com/CuBoulder/cu_content_sequence_bundle/pull/3

**Comment by cathysnider** [comment]
Review: https://www-dev.colorado.edu/p1fe1fef161e/one
All three sequence types look good: Lists in content display; when block theme is dark both text and link colors are visible.
