### ISSUE TITLE
Alphabetically List Blocks On Quicktabs Edit

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#1120]
## Context

The other day, I was trying to place a block via Quicktabs on a site that had a lot of blocks. I literally couldn't find my block until I got pissed off enough to write the code to sort them alphabetically by label. 

I have made a patch to Quicktabs that should go into Express to help site editors more easily add blocks to Quicktabs. 

https://www.drupal.org/node/2883516

**Comment by cathysnider** [comment]
- [ ] Create new screenshots

**Comment by cathysnider** [comment]
*Acceptance Criteria*:  The blocks displayed in the QuickTabs block selector drop down are in alphabetical order.

**Comment by cathysnider** [comment]
Test results: 
1) blocks are alphabetized
2) all blocks are in list.

**Comment by kreynen** [comment]
I tested this is Chrome and Safari and could open and close tabs without any issues.  The code change doesn't alter the javascript or the display so I don't see why resorting the list in the admin UI could cause this.

**Comment by cathysnider** [comment]
I believe the configuration checkbox "jQuery UI Options - Collapsible" used to be checked by default. The tester was expecting that behavior and failed to notice that the box was unchecked.  When the 'collapsible' checkbox is checked, the accordions do open and shut.  

Test Pass. 

(Note: Auto height seems pointless on accordions but whatever)
