### ISSUE TITLE
cu_block_to_bean module has no method of being enabled

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1125]
## Context

We made the cu_block_to_bean module to be able to wrap non-bean blocks so they can be added to layouts or other blocks that use entity references.

But unless I'm mistaken, we haven't added a way to enable it.

**Comment by kreynen** [comment]
This either needs to be a dependency of express, cu_core or a bundle.  Any module that's enabled that isn't a dependency or optional dependency will result in a PMM error.
