### ISSUE TITLE
Add LinkedIn Tracking Pixel To Embed Templates

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#1127]
## Context

The Digitial Engagement Team is asking for the addition of a LinkedIn tracking pixel to the digital campaign bundle. This tracking pixel is general enough that it can probably go in the drupal.org module. 

## Process

Hi Melissa,
Here's the code for the Insight Tag you requested for University of Colorado Boulder so you can install it on your website.

The LinkedIn Insight Tag is a lightweight Javascript snippet that drops a cookie on visitors' web browsers whenever they visit the site. This will allow you to track whenever a member converts on your website.

Installation is easy and should only take a few minutes. Here's how:

1. First, copy the code:
```
<script type="text/javascript"> _linkedin_data_partner_id = "55748"; </script><script type="text/javascript"> (function(){var s = document.getElementsByTagName("script")[0]; var b = document.createElement("script"); b.type = "text/javascript";b.async = true; b.src = "https://snap.licdn.com/li.lms-analytics/insight.min.js"; s.parentNode.insertBefore(b, s);})(); </script> <noscript> <img height="1" width="1" style="display:none;" alt="" src="https://dc.ads.linkedin.com/collect/?pid=55748&fmt=gif" /> </noscript>
```
2. Next, paste the code into the global footer of your domain either before or after the <body> tag.

3. Finally, log in to the LinkedIn Campaign Manager and navigate to the Tools tab on the upper right side of the page to check the installation status. That's it!

For more information about the LinkedIn Insight Tag, just visit our [Help Center](https://www.linkedin.com/help/linkedin/answer/65521?lang=en&trk=eml-email_conversion_tracking_insight_tag_single_01-hero-2-help-center&midToken=AQEK_FTvsRSQ9g&fromEmail=fromEmail&ut=0TlUZIA1vME7M1).

**Comment by alexfinnarn** [comment]
Hooray!
 
I don’t have any ads running now and neither does Erin D. as far as I know. Can we say early July and to www.colorado.edu and www.colorado.edu/today?
 
Thanks!
Melissa

**Comment by alexfinnarn** [comment]
This has been added to the Digital Campaign Bundle and will be deployed on prod soon.

**Comment by cathysnider** [comment]
This adds module "Embed Templates - LinkedIn" to the Digital Campaign Bundle. It does NOT turn the module on. A developer still needs to turn on the module itself. Once the module is turned on, the capability of adding LinkedIn Tracking code is added to the Embed tab. 

![screen shot 2017-09-19 at 11 43 40 am](https://user-images.githubusercontent.com/638275/30606730-ec096288-9d2f-11e7-810a-abf86d6e6c07.png)

**Comment by cathysnider** [comment]
So we still need more information on the requirements of this module. Does it need to be turned on or not?
