### ISSUE TITLE
As a SO/CE, I would like to know what version of Express I'm using

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1129]
## Context

As we are referencing the semantic version number of Express more often when communicating with users (that's coming in 2.5.0), it would be helpful for them to be able to see what version of Express they are currently using.

This would also be helpful when looking at sites on www-dev and www-test now that we can have several of versions of the profile running at the same time.

I started https://www.drupal.org/project/profile_version when we started working on the FIT -> Express transition, but when we dropped Environmental Indicator that was scaled back to just https://github.com/CuBoulder/express/blob/dev/modules/custom/express_version/.  

Not sure of if we need/want Environmental Indicator again or to do something similar with a simple CSS change based on which server environment the site is currently running on, but we should find a way to get the version number displayed somewhere in the UI.  On admin/dashboard if not the toolbar.

**Comment by alexfinnarn** [comment]
This should be reviewed since there has been more work done with environment indicators. I would think sticking a version number in there would be easy to do.

**Comment by kreynen** [comment]
This is now available for both admins and dev in admin/reports/status

**Comment by cathysnider** [comment]
Just a note for clarification: SOs and CEs are not given access to the Status Report page.
