### ISSUE TITLE
As a SO, I want to be able to limit CE from adding items to the main menu

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1136]
## Context

This was brought up by Erik about /business, but we've seen this issue ourselves when we create test nodes for a basic page on site and forget to uncheck the option to create a menu item.

On sites with a large number of CEs, giving them all permission to add/update/alter the main menu is a maintenance nightmare.

**Comment by kevincrafts** [comment]
Another thought with this is maybe not to restrict the use of adding items to the main menu, but alerting the user whenever they are going to add a top level menu item.
