### ISSUE TITLE
Improvement: All Entity Reference fields should use the Inline Entity Form widget

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1139]
## Context

[provide introduction to the issue , why it is relevant, and who it impacts]

We have various places where entity reference fields are used, such as Block Sections and Block Rows.  When creating one of these, you need to have created some other bean entity first.  By switching the field widgets from auto complete to inline entity form, we could create a better user workflow.

**Comment by jwfuller** [comment]
This could have a serious performance impact. Instead of loading a single form, we end up loading several at one time. There will be a point at which this approach could require too much memory.

**Comment by kevincrafts** [comment]
![screen shot 2017-08-24 at 1 39 54 pm](https://user-images.githubusercontent.com/349713/29685145-c6f8069c-88d1-11e7-91ad-9ca9af701ccc.jpg)

**Comment by alexfinnarn** [comment]
Seems like there are still 40 references to `'module' => 'entityreference',` in field bases. I'm not sure if this ticket is just to test block rows, but it doesn't accomplish making this change throughout the Express codebase. 

Also, do we need to search custom bundles for switching entity reference to IEF? 

I added back the documentation label since I'd imagine the docs need to be changed to say you can create blocks inside block rows.

**Comment by alexfinnarn** [comment]
So, the title of changing all entityreference fields to inline entity form is misleading. The issue means "add ief to all fields with entityreference" and not a complete replacement. 

cu_content_list isn't included here, but I'm not sure if you want that module to be able to create other content. 

Also, this feature makes it way easier to nest things like block rows where you might not want those nested.

**Comment by kevincrafts** [comment]
I don't think the Content List entity reference widget should be replaced by IEF since node forms are much more complex.

**Comment by cathysnider** [comment]
Acceptance Criteria: 
All blocks that have an entity reference field, will also now have an inline entity form. This way, if they have forgotten to build the blocks that are being pulled in to another block (say a text block into a block section) they can do so while editing the block section. 
 - [ ] Block Section
 - [ ] Block Row
