### ISSUE TITLE
As a SO/CE I want to build a page of blocks

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1140]
## Context

Following the model of the Paragraphs module, pages can contain block content. This would create a easier workflow when creating pages that contain block content in the main body area.

Layouts could still be used to add content to the various other regions.

## Possible Fix

Add an Inline Entity Form field to Basic Pages.

**Comment by jwfuller** [comment]
This could have a serious performance impact. Instead of loading a single form, we end up loading several at one time. There will be a point at which this approach could require too much memory.
