### ISSUE TITLE
As a SO/CE I would like to display articles in a pinterest matrix

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#1143]
## Context
The client would like to have an articles block that offers a masonry or pinterest view of articles to place on their site.

Original Request was via email:
Hi Emily,

Can you advise on how we can get our blocks to be closer together so it’s more compact? 

https://www.colorado.edu/alumni/block/main-block-row

We want it to look like this:

http://arizonaalumni.com/

Janeyl Tellez
Digital Marketing Coordinator
University of Colorado Boulder Alumni Association
Koenig Alumni Center
1202 University Avenue - 459 UCB Boulder, CO  80309-0459
janeyl.tellez@colorado.edu
colorado.edu/alumni

**Comment by jwfuller** [comment]
I don't have backend performance concerns, but leaving label on for @kevincrafts to review Frontend performance implications.
