### ISSUE TITLE
The newsletter block is no longer displaying newsletters

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#1149]
This page has two newsletter blocks and neither are working

When I go to edit the block (working in Chrome)
The items to display drop down is not working ie I cannot make a selection

Site with issue:
http://www-test.colorado.edu/express/training/bls/newsletters

**Comment by kevincrafts** [comment]
Something is weird with this site in that the developers are all set to be site owners. I can't troubleshoot this any further but I think the problem is that the newsletter bundle is no longer attached to the site.

**Comment by ekellagher** [comment]
I added the bundle back to the site - and the blocks are working - 
the new code update must have caused the problem to the site
