### ISSUE TITLE
All hero unit blocks have overlay

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#1150]
Client Reported Issue:
The Hero image on the home page now has a tinted overlay under the text.
It makes the photo too difficult to see and I want to turn it off. The “Add
overlay to improve readability” checkbox is unchecked in the “Design”
tab of the Hero block. The tinting was turned off, but now it’s not
working. See:
https://www.colorado.edu/p10d996698e3/block/herogeography-title/edit?destination=node/2

Tier 1 Tech Support:
I went to the site and created a new hero unit block and did not check the tinted overlay box and the block displayed the overlay on the image

**Comment by cathysnider** [comment]
https://www-dev.colorado.edu/p17e46ef8f5b/
