### ISSUE TITLE
Atlas times out on larger reports

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1152]
https://github.com/CuBoulder/express/blob/dev/modules/custom/atlas/atlas.module#L348

https://osr-atlas03.int.colorado.edu/statistics?where={%22express_code_version%22:{%22$exists%22:false}} works, but https://www.colorado.edu/webcentral/admin/tools/reports/basic_report/20/view says no matching

**Comment by alexfinnarn** [comment]
While looking at the query results from the stats endpoint, one site ID reporting back has been deleted, and so the site record can't be pulled up. 

https://osr-atlas03.int.colorado.edu/sites/5893a72e926f5b130c908c06

I suspect that this is the case with all site IDS in this query report.

**Comment by kreynen** [comment]
Issue moved to [CuBoulder/atlas #268](https://github.com/CuBoulder/atlas/issues/268) via [**ZenHub**](https://www.zenhub.com/)
