### ISSUE TITLE
As a SO/ CE I would like to add interactive buttons that have a roll over action to my site

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#1153]
## Context

Hi Emily
On Housing and Dinning Services website [1]https://living.colorado.edu/get-involved under How you can get involved, there are 6 blocks that when you scroll over them they change color or do a roll over.  You know it’s coming – Can we do this?
Please let me know.
Thanks much!
Jan
![housing and dining interactive buttons](https://user-images.githubusercontent.com/16137919/27101587-99b30bac-503f-11e7-8b48-df675fc2ac34.PNG)

**Comment by kreynen** [comment]
HDS has 6 people spending the majority of their time on design and development of their hybrid sites.  These are just customized quicktabs, but without someone to write the CSS and Javascript as well as someone to design the images, this would be really difficult to do.

**Comment by alexfinnarn** [comment]
an example of Behat mouseover test https://stackoverflow.com/questions/18499851/how-do-i-tell-behat-mink-to-hover-over-an-element-on-a-webpage
