### ISSUE TITLE
BUG: Menu icons with a value set to none add extra space in menu

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1159]
## Context

When a user has set a menu item to have an icon and then later sets it to none, the menu icon markup is still printed and adds extra spaces between menu items.

http://www.colorado.edu/p1135ade2fb8/

## Process

1. Login to site as a [SO, CE, EO, ADMIN or DEV]
2. Go to admin/structure/menu/manage/main-menu
3. Click Configure Item for a menu item
5. Click save

## Expected result

There should be no extra space added.

## Current result

There is extra space before the our people menu item.

![screen shot 2017-06-15 at 4 29 49 pm](https://user-images.githubusercontent.com/349713/27204359-ea1c1a1c-51e7-11e7-991c-7c60796c1052.jpg)

http://www.colorado.edu/p1135ade2fb8/

**Comment by cathysnider** [comment]
Acceptance Criteria: 
-[ ] A user is able to add and remove menu icons
-[ ] When a menu icon is added, it shows up in the menu bar
-[ ] When a menu icon is removed, it no longer shows up in menu bar AND there is no space where it used to be.

**Comment by cathysnider** [comment]
Test results: I am unable to add or remove menu icons because the Icon field is missing. 
https://www-dev.colorado.edu/p1ffb962bea9/

![menuiconsmissing](https://user-images.githubusercontent.com/638275/27357918-7512b9cc-55d1-11e7-9b38-bacc1d1aff5a.png)
