### ISSUE TITLE
Disable login on instances that are in a 'locked' state. 

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express#1173]
## Context

Relates to https://github.com/CuBoulder/atlas/issues/272.

```
With CuBoulder/express#1090 and reports like https://www.colorado.edu/webcentral/admin/tools/reports/basic_report/22/view, we now have the tools to identify sites that are no longer being maintained and reduce the impact those sites have on te service by extending the cache lifetime, reducing (or even eliminating) cron and blocking logins.

I'm not sure if we want to use https://github.com/CuBoulder/express/tree/dev/modules/custom/cu_logout_users or add a variable to disable logins in https://github.com/CuBoulder/express/blob/dev/modules/features/cu_ldap/cu_ldap.module and show a message on that form that the site is in archive mode and to contact OSR to switch it back to launched, but I think it improves security to disable logins on a site without an active SO.
```

**Comment by owenmorrill** [comment]
SMs locking out other users: https://github.com/CuBoulder/express/pull/1050

**Comment by owenmorrill** [comment]
Atlas lock: Get ready for eventual take down. Change Elysia cron rate. Lock everyone but devs.
Security lock: Drush command. Log everyone out. Lock everyone out but devs.
SM lock: #1050 SMs can lock out other content editors from making changes to the site.

**Comment by owenmorrill** [comment]
drush vset lock_user_dev TRUE

**Comment by owenmorrill** [comment]
- express_dashboard_lock allows SMs to lock users out
- lock_user_dev is the variable that locks everyone out who is not in the "developer" part in cu_users.module.
- The drush command to lock the site is `drush lud`

Need a lot testing. Probably need some documentation--might add a README.

**Comment by owenmorrill** [comment]
Need to change cron, still.

**Comment by cathysnider** [comment]
Acceptance Criteria:
- [ ] you can lock people out

Failing at this time: https://www-dev.colorado.edu/feature/1173/

**Comment by cathysnider** [comment]
Acceptance Criteria:
- [ ] Module 'express_user_lock' is enabled
- [ ] a developer can lock the whole site
- [ ] a site owner can lock pages


https://www-dev.colorado.edu/p1c304eff27f/

**Comment by kreynen** [comment]
We've removed the perm for site owners.  The core functionality for this is working, but we will make additional changes to it in 2.7.0.

**Comment by cathysnider** [comment]
Acceptance Criteria:
- [ ] Module 'express_user_lock' is enabled
- [ ] The 'Lock' tab shows on User pages for developers
- [ ] The 'Lock' tab does NOT show on User pages for SO or CE
- [ ] The site lock message shows on the .... page (what page?)
