### ISSUE TITLE
Files paths aren't cleared from varnish when file nodes are cleared

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1178]
I added an additional check to actually clear / instead of node/1 or home in https://github.com/CuBoulder/express/issues/1090, but for files, I think we need to clear node/x/backstretch, node/x/large, node/x/medium and node/x/small in addtion to just the default alias of node/x

![screen shot 2017-06-27 at 4 53 35 pm](https://user-images.githubusercontent.com/385234/27613639-ea2f0b42-5b59-11e7-9daf-0d451bcca12d.png)

**Comment by jwfuller** [comment]
Need to clear:

-  node/x/backstretch
-  node/x/large
-  node/x/medium
-  node/x/small
-  node/x
-  sites/default/files/[dir]/[filename]
