### ISSUE TITLE
As a SO/CE I would like to embed a Twitter list on my website

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#1182]
## Context
Twitter users can create curated lists of several twitter accounts
https://support.twitter.com/articles/76460

We have had one client ask to feature @cuboulder and @cuboulderfacman within the same feed.
[JIRA] (EXP-6712) Twitter block
https://cuboulder.atlassian.net/browse/EXP-6712

## Links to Examples
https://dev.twitter.com/web/wordpress/embedded-timelines/list

Embedded Timelines
https://dev.twitter.com/web/embedded-timelines

**Comment by jwfuller** [comment]
Need to make sure we handle Twitter outages gracefully
