### ISSUE TITLE
Improve cache clearing by including image paths w/ current itok token

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1187]
## Context

As of  #1090, express_settings now clears the cached redirects for all of the file attachment paths, but we are only clearing the node paths.  These are essentially the redirect to a URL that looks something like sites/default/files/styles/backstretch/public/large/FILENAME.jpeg?itok=XXX.  While the redirect will get cleared, the image it is pointed at will not.  

Initially I didn't think that the actual image could be cleared since the itok value in some ways is designed to invalidate the cache similar to the JSONP microtimestamps.

There is a function to get the current itok token for a specific file/image style.

https://api.drupal.org/api/drupal/modules%21image%21image.module/function/image_style_path_token/7.x

So it is possible, but I'm not sure if there is actually a need to follow the rabit this far into its hole.

**Comment by jwfuller** [comment]
@kreynen Closing this, we shouldn't/don't/won't cache images in varnish via itok token. https://github.com/CuBoulder/varnish/blob/master/default.vcl#L264
