### ISSUE TITLE
Bundle Enable Bug

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#1188]
## Context

As an example, on https://www-dev.colorado.edu/p14d966617ad/admin/settings/bundles/list/addon the Digital Campaign bundle code is on the site; however, it doesn't get enabled when the user clicks the button. 

I'm not sure exactly what is happening, but it might have to do with having duplicate bundles on the same Atlas instance when Express tries to get the code assets. There might be a mismatch in the version of the code the user selects and what the first bundle in the list on https://osr-atlas01.int.colorado.edu/code is. 

## Process

1. Create two versions of https://github.com/CuBoulder/cu_digital_campaign_bundle
2. Login to site as a SO.
2. Go to admin/settings/bundles/list/addon
3. Try adding the digital campaign bundle. 
4. See that bundle doesn't get enabled. 

## Expected Result

A user can have multiple versions of a bundle on an Atlas instance without only being able to enable one of them.

**Comment by owenmorrill** [comment]
I believe this is covered with #1071.
