### ISSUE TITLE
Change express_status to cu_status and make it only a dependency of cu_core

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1196]
## Context

The integration with http://status.colorado.edu/ is specific to Boulder and shouldn't be a dependency at the express.info level.  The tests should be able to run without this.

https://github.com/CuBoulder/express/blob/dev/tests/behat/features/Express/express_dashboards/express_dashboards.feature

**Comment by owenmorrill** [comment]
#1272

**Comment by kreynen** [comment]
Because the code changes on the site before the update hooks are run, this change will remove the status message during an update.

I'm not sure if we want to push this change out by itself or wait for changes related to https://github.com/CuBoulder/express/issues/1708
