### ISSUE TITLE
As a SO/CE I would like to place interactive blocks on my website

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#1210]
## Context

Good afternoon,

Do we have the feature in Drupal that allows us to hover a box and for text to appear like so:

http://alumni.umich.edu/

Thank you,

Janeyl
![interactive blocks](https://user-images.githubusercontent.com/16137919/28079330-2165aca8-6625-11e7-8770-455dc6821c6e.png)

**Comment by alexfinnarn** [comment]
Behat mouseover for testing: https://stackoverflow.com/questions/18499851/how-do-i-tell-behat-mink-to-hover-over-an-element-on-a-webpage
