### ISSUE TITLE
AS a SO/CE I would like to display an events page with a filter

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#1211]
## Context
Here is the link to the Department Ceremonies page on the University of Oregon Commencement website that we would like to model our department listing to if feasible.

https://commencement.uoregon.edu/ceremonies

Here is our current listing page for Spring 2017 ceremonies for reference (73 schools, colleges, departments or programs listed):
http://www.colorado.edu/commencement/spring-ceremony/spring-collegedepartment-recognition-ceremonies

![events page](https://user-images.githubusercontent.com/16137919/28080833-8bb0d5ce-662a-11e7-99cf-e7a933d25ef4.PNG)

![events item expanded](https://user-images.githubusercontent.com/16137919/28080854-9afcb408-662a-11e7-8810-7f89edf61f2e.PNG)

**Comment by kevincrafts** [comment]
This is not possible with the current events calendar integration, and may not be possible with the new Events integration.
