### ISSUE TITLE
Create list of sites to be Locked

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1213]
## Context

As we develop functionality to reduce the impact of sites that aren't updated for https://github.com/CuBoulder/express/issues/817, we need to use the reports available at https://www.colorado.edu/webcentral/admin/tools/reports/basic_report to come up with the list of sites to lock.

**Comment by cathysnider** [comment]
Sites with Less than Two Nodes
https://docs.google.com/a/colorado.edu/spreadsheets/d/1Y3XPaNuGzJ_Ji8aLVwlCtzJtSS47VgUnQAnzIlGeNSI
