### ISSUE TITLE
Undefined index in cu_advanced_article.module

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1214]
## Context

This is now the bug most frequently logged.

`Notice: Undefined index: field_adv_article_image in cu_advanced_article_preprocess_node() (line 125 of /data/code/modules/cu_advanced_article_bundle/cu_advanced_article_bundle-7.x-1.0/modules/custom/cu_advanced_article/cu_advanced_article.module).`

**Comment by alexfinnarn** [comment]
Also...

```
Notice: Undefined index: und in cu_article_list_filter_form() (line 1647 of /data/code/profiles/express/express-2.5.4/modules/features/cu_article/cu_article.module).
```

**Comment by owenmorrill** [comment]
https://github.com/CuBoulder/cu_advanced_article_bundle/pull/6

**Comment by kreynen** [comment]
<img width="1418" alt="screen shot 2017-08-23 at 7 59 14 am" src="https://user-images.githubusercontent.com/385234/29634134-06968278-8806-11e7-9bae-9acf68b23a1f.png">
