### ISSUE TITLE
Resolve missing dependencies in launched sites

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1220]
## Context

We've been working towards keeping a clean report of any issues that report as errors to admin/reports/status.  We're still working through a few other issues, but these sites need attention... most likely requires updating dependencies in a bundle.

- [x] https://www.colorado.edu/studentgroups/boardgameunderground/admin/reports/status - cu_related_articles, cu_article
- [x] https://www.colorado.edu/alumni/admin/reports/status - cu_storify_embed
- [ ] https://www.colorado.edu/libraries/admin/reports/status -culibraries, cu_libraries_search, metatag, xmlsitemap, xmlsitemap_engines
- [ ] https://www.colorado.edu/summer/admin/reports/status - match_redirect
- [x] https://www.colorado.edu/career/admin/reports/status - ds_ui, job_scheduler
- [x] https://www.colorado.edu/studentemployment/admin/reports/status - cu_related_articles, cu_article
- [ ] https://www.colorado.edu/chancellor/admin/reports/status - ds_ui, themekey, views_ui
- [x] https://www.colorado.edu/crowdfunding/admin/reports/status - community_funded, context_query_param, crowdfunding, ds_ui
- [x] https://www.colorado.edu/law/admin/reports/status - third_party_wrappers, views_ui
- [x] https://www.colorado.edu/lab/weimer - cu_related_articles, cu_article
- [x] https://www.colorado.edu/researchinnovation - vcr_article, vcr_context, views_ui 
- [ ] https://www.colorado.edu/webcentral - charts, charts_google, comment, context_query_param, cu_test_content_context, cu_update_ping, flag, google_analytics_reports_api, highlight_js, highlight_js_filter, google_analytics_reports
- [x] https://www.colorado.edu/business - et_beans, et_blocks, et_slate_form_bean, et_slate_form_block
- [x] https://www.colorado.edu/mechanical - et_beans, et_slate_form_bean
- [x] https://www.colorado.edu/p1f0a6fb0a43 - context_ui, cu_block_section, cu_column_override 
- [x] https://www.colorado.edu/theatredance - cu_tracking_pixel, cu_tracking_pixel_overview
- [x] https://www.colorado.edu/p1f0a6fb0a43 (National Behavioral Health Innovation Center) -  context_ui, cu_block_section, cu_column_override
- [ ] https://www.colorado.edu/p15a75c78bd6/ (Atlas) - cu_test_content_articles, views_ui
- [x] https://www.colorado.edu/project/maxwellcubesat - cu_content_list, cu_feature_callout, cu_quicktab_styles, cu_video_reveal, quicktabs, quicktab_beans
- [x] https://www.colorado.edu/innovate - path_redirect_import

**Comment by kevincrafts** [comment]
I enabled the News bundle for boardgameunderground and studentemployment

**Comment by owenmorrill** [comment]
I made a PR to fix the VCR errors for innovate. Not sure why views_ui is flagged on that site. https://github.com/CuBoulder/cu_vcr_bundle/pull/5

**Comment by owenmorrill** [comment]
https://www.colorado.edu/lab/weimer/admin/reports/status is reporting cu_article and cu_related_articles because cu_news_bundle isn't enabled. If you enable cu_news_bundle, the flags go away. (locally anyway)

**Comment by owenmorrill** [comment]
https://github.com/CuBoulder/cu_storify_bundle/pull/2 and using the bundle instead of just the embed module will fix the alumni site error.

**Comment by owenmorrill** [comment]
https://github.com/CuBoulder/custom_crowdfunding_bundle/pull/3 crowdfunding to an actual bundle.

**Comment by owenmorrill** [comment]
Chancellor has new items in status report from PMM: Check cu_dashboard_seo, cu_linkchecker, cu_sitemap, ds_ui, linkchecker, linkchecker_bean, site_verify, themekey, views_ui, xmlsitemap_menu, xmlsitemap, xmlsitemap_engines

**Comment by kreynen** [comment]
Still a handful of issues, but we'll be dealing with those in other issues.
