### ISSUE TITLE
Update drupal_system_status value to return false instead of NULL as default

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1221]
## Context

drush core-requirements allows --severity=2.  True/False/NULL as values for drupal_system_status is just confusing and isn't being passed consistently when stats are updated from within Drupal (on admin/config/development/atlas/statistics or cron) vs. drush atst.  

I think we should change the statistic element to `core_requirements` and make it an int storing the highest level seen on admin/reports/status.

**Comment by kreynen** [comment]
After looking at https://api.drupal.org/api/drupal/modules%21system%21system.admin.inc/function/system_status/7.x this is actually is the correct way to use drupal_system_status.  I still think we could benefit from the level of status issue like `drush core-requirements`, but I'll open a different issue for that change.

**Comment by alexfinnarn** [comment]
Closed PR since it had no code changes somehow.
