### ISSUE TITLE
The Content Sequence Bundle is not available to add to a site on test sites

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#1233]
## Context

In training today, the Content Sequence Bundle does not show up on the test training sites to enable
https://www-test.colorado.edu/p17802e0a547/admin/settings/bundles/list/addon
![bundle missing](https://user-images.githubusercontent.com/16137919/28226923-1b2620da-6895-11e7-9482-70e180fe9b50.PNG)

The bundle is visible on production sites tho

Some clients like to request a test site to try out a Bundle before they enable on their site. This is a bundle that is really helpful to try to use first before it is enabled on department site - it would be nice if it was available to enable on test sites.

**Comment by kevincrafts** [comment]
Added to test.
