### ISSUE TITLE
BUG: Content Grids set to feature style may cut of content on mobile devices

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1234]
## Context

If a content grid is set to the feature style, depending on the length of the title and content, some may be cut off when viewed on a mobile device.

## Process

[ordered list the process to finding and recreating the issue, example below]

1. Login to site as a [SO, CE, EO, ADMIN or DEV]
2. Click Blocks
3. Click Add Block
4. Click Content Grid
4. Create a 3 cell content grid set to "feature" style
5. Click save

## Expected result
Content should not be cut off.

## Current result

If title and content is long enough, content on the first cell will be cut off.

## Possible Fix

For this view, we should only show the title, not the content.

## Screenshots

![screen shot 2017-07-15 at 8 57 00 am](https://user-images.githubusercontent.com/349713/28240278-2b183b98-693c-11e7-963c-800d2ff0239e.jpg)

![screen shot 2017-07-15 at 8 56 31 am](https://user-images.githubusercontent.com/349713/28240280-31f90a14-693c-11e7-88bc-c2f2df41a658.jpg)

**Comment by cathysnider** [comment]
Acceptance Criteria:
- [ ] The mobile issue is solved for Feature layout
- [ ] The other layouts look good on mobile view
- [ ] The layouts continue to look good on desktop view

Test Site: https://www-dev.colorado.edu/p13320265b25/feature

Screenshot of Mobile: 
![img_9148](https://user-images.githubusercontent.com/638275/28389409-3d6f5326-6c93-11e7-8606-5a1f13e4a4f8.PNG)

Test results: Pass
