### ISSUE TITLE
As SM, we need to make changes to cron so that all cron functions are completed in a reasonable amount of time

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express#1243]
## Context

Currently cron is monolithic. We can optimize by switching to something that allows us to run each hook on a specific interval.

This will allow us to run cron more frequently with an optimized workload and a shorter average duration.

## To test

* All bundles

## Possible Fix

* [Elysia Cron](https://www.drupal.org/project/elysia_cron)
* [Ultimate Cron ](https://www.drupal.org/project/ultimate_cron)

**Comment by jwfuller** [comment]
Ultimate Cron
* Pros
  * Recent activity
  * D8 port
  * More configurable
* Cons
  * Requires additional PHP modules `mbstring`

Elsyia Cron
* Pros
  * Simple

**Comment by jwfuller** [comment]
## Elysia Cron jobs

* atlas_statistics_cron
* ctools_cron
* cu_redirect_cron
* cu_users_cron
* field_cron
* googleanalytics_cron
* honeypot_cron
* ldap_servers_cron
* ldap_user_cron
* node_cron
* redirect_cron
* system_cron
* user_external_invite_cron
* views_bulk_operations_cron
* queue_file_entity_type_determine
* queue_views_bulk_operations

**Comment by alexfinnarn** [comment]
Can run drush commands for Behat tests 

https://github.com/jhedstrom/drupalextension/blob/203929d9d71bc0f30ff2c73a8053727b014451e1/features/drush.feature#L8

**Comment by jwfuller** [comment]
Not an end user facing change

**Comment by jwfuller** [comment]
Look at shifting CPU load into off hours. Ex: Linkchecker

Also need to go through core bundles to set this stuff

**Comment by kreynen** [comment]
Added https://github.com/CuBoulder/express/commit/ce4bdd169e5ac245efffd5b4afc47cefb2bf7db1and merged
