### ISSUE TITLE
Issue with admin bundles in latest Profile Module Manager

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1248]
## Context

Aerospace (and potentially other sites) report error in `drush core-requirements --severity=2`, but not admin/reports/status

` Title                   Severity  Description                                                                                       
 Profile Module Manager  Error     Some required modules either not enabled or extra modules are enabled. Check cu_seo_admin_bundle, 
                                   cu_tracking_pixel, cu_tracking_pixel_overview  `

Looking at https://www.colorado.edu/aerospace/admin/reports/status says there are no issues.

I tried running `drush core-requirements --severity=2` on multiple wweb servers.  Same issue. 

I don't understand why this would be an issue after looking at...

https://github.com/CuBoulder/express/blob/dev/modules/custom/profile_module_manager/profile_module_manager.module#L179

https://github.com/CuBoulder/express/blob/dev/modules/custom/cu_seo_admin_bundle/cu_seo_admin_bundle.info

**Comment by owenmorrill** [comment]
https://github.com/CuBoulder/express/pull/1250
