### ISSUE TITLE
Sites returning drupal_system_status = True when using drush cron

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1253]
## Context

It has taken weeks to track this down to this level because of the number of other issues with sites, but several sites continue to reappear in reports because the stats object has  drupal_system_status = True only when it is populated via drush cron.

For these sites, going to admin/reports/status shows no errors.
Running `drush core-requirements --severity=2` as osr_web_deploy returns nothing.
Running `drush eval "module_load_include('inc', 'atlas_statistics', 'atlas_statistics'); print atlas_statistics_pretty_print(drupal_json_encode(atlas_statistics_get_statistics()));"` as osr_web_deploy returns same JSON that drush atst should send to Atlas.  That includes "drupal_system_status": false.

I've tried running these commands on all 3 wweb servers.

HOWEVER...

If you run `drush vset cron_last 0` and then `drush cron`, you will see the stats object now has drupal_system_status as True.

- [ ] http://www.colorado.edu/hr-makeadifference

**Comment by kreynen** [comment]
Another oddity about ics and orientation is that after the first drush cc all, they added needing a db update to the status report.  drush updb says no updates are needed.

**Comment by jwfuller** [comment]
https://github.com/CuBoulder/atlas/issues/356
