### ISSUE TITLE
Block wrapper is part of the Advanced content bundle but shows up in the "other" section on the Add block admin page

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#1254]
## Context

Please add the block wrapper link to the Advanced content Bundle section on the Add Block admin
![block wrapper](https://user-images.githubusercontent.com/16137919/28433850-72205f36-6d4a-11e7-85e7-85c21cabd4c0.PNG)
 page

**Comment by cathysnider** [comment]
Acceptance Criteria:
- [ ] Advanced Layout has Block Row, Block Section and Block Wrapper
- [ ] Appearance of other bundled blocks are not affected (i.e. blocks in the Express Core and Advanced Content appear as they should)
- [ ] The Advanced Layout blocks continue to work as designed (Menus and Webforms are wrapped and placeable)

Test site: https://www-dev.colorado.edu/p1d168a8bf51/
