### ISSUE TITLE
Add test to check admin/config for hook_requirement fails

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1258]
## Context

Running `drush core-requirements --severity=2` will return the same results as you see when visiting admin/reports/status.  

These errors include:
- Profile Module Manager's check that modules are declared as dependencies or optional dependencies of the profile, a core or a bundle.
- Permission to directories are correct when commands are run as drush (ctools and xmlsitemap are commonly misconfigured) 
- That the site is running on the expected version of Drupal core

@alexfinnarn found this [example of how to write a test that evaluates the drush response](https://github.com/jhedstrom/drupalextension/blob/203929d9d71bc0f30ff2c73a8053727b014451e1/features/drush.feature#L8).

drush core-requirements --severity=2 should return nothing during testing.

**Comment by alexfinnarn** [comment]
Behat should only be used for user interaction not Drush output. I don't know why I thought this was a good idea before, but I aim to not add a drush driver to the test suite. 

An added test could check for the "There seems to be an issue with your Drupal installation" message or some sort of message on "/admin/reports/status".

The better way to do this is to run the Drush command before and after the test suite to check for errors and exit with a 1 if there are some.

**Comment by alexfinnarn** [comment]
Add a test at the beginning of a test run right after install that goes to "admin/reports/status" and looks for errors.

**Comment by alexfinnarn** [comment]
This test was added but is currently commented out. It would be a great test to get "right" but with certain environments having different PHP modules and so forth, there are "issues" on Travis that wouldn't relate to anything an Express site on prod would encounter.

Commented out tests will be looked at in another ticket.
