### ISSUE TITLE
Callout Shortcode Tip doesn't include options

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1271]
## Context

When viewing the filter tips page, the callout shortcode tip doesn't show the options available.

https://github.com/CuBoulder/express/blob/dev/modules/custom/cu_shortcodes/cu_shortcodes.module#L482

**Comment by cathysnider** [comment]
**Acceptance Criteria**
- [ ] The Compose Tips page includes all 23 shortcodes
- [ ] The shortcodes are correctly represented on the Compose Tips page

**Fail:** 
* Missing Shortcodes:  imagecaption and share_on_twitter (https://www-dev.colorado.edu/p18c13894764/filter/tips)
* Incorrect Shortcodes: calendar should be googlecalendar (https://www-dev.colorado.edu/p18c13894764/calendar)

Examples:
* [Compose Tips Test Site](https://www-dev.colorado.edu/p18c13894764/filter/tips)
* [Full List of Shortcodes](https://www.colorado.edu/p1f4bca2b935/node/326)
