### ISSUE TITLE
Can't Connect To LDAP Server 

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#1296]
## Context

There seems to be an intermittent issue with connecting to the LDAP server on authentication and when requirements are checked on the Status Report page. 

## Process

Error on /user login:
1. Login to site as a [SO, CE, EO, ADMIN or DEV]
2. Log out if successful and log back in. 
3. At some point, you will see the failure and not be logged in. 

Error on Status reports page:
1. Logon to a site as a DEV.
2. Go to "admin/reports/status" 
3. Refresh the page until you see the LDAP error. 

## Related Issues

I think this issue might relate to the unavailable sockets error that happens for the random alerts red bar showing up sporadically. You would have to follow the connection method to see more about what it going on.

## Screenshots

![screen shot 2017-07-27 at 3 21 59 pm](https://user-images.githubusercontent.com/3640707/28692864-acea68ec-72df-11e7-99bf-4b92b403a25d.png)

![screen shot 2017-07-27 at 3 12 42 pm](https://user-images.githubusercontent.com/3640707/28692870-b400d9fe-72df-11e7-8c2e-e1a674a2cf1b.png)

**Comment by alexfinnarn** [comment]
More error message in logs...

```
Warning: ldap_start_tls(): Unable to start TLS: Connect error in LdapServer->connect() (line 298 of /data/code/profiles/express/express-2.5.4/modules/contrib/ldap/ldap_servers/LdapServer.class.php).
```

```
Could not start TLS. (Error -11: Connect error).
```

**Comment by alexfinnarn** [comment]
Seems like a cert error...on "admin/config/people/ldap/servers/edit/oud"

![screen shot 2017-07-27 at 4 04 14 pm](https://user-images.githubusercontent.com/3640707/28694146-50260df4-72e5-11e7-9a68-3bca7fbf22cd.png)

So for some reason, the cert isn't trusted or maybe it is not updated on one of the three web heads?

**Comment by alexfinnarn** [comment]
Might be able to add debugging to catch more logs via http://php.net/manual/en/function.ldap-start-tls.php#115150

**Comment by jwfuller** [comment]
IAM issue with misconfigured TLS on a node
