### ISSUE TITLE
As a SO/CE I would like to configure a thumbnail to be used in twitter when I tweet a link to my newsletter

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#1297]
## Context

I would like to configure a thumbnail to be used in Twitter when I tweet a link to our newsletter. OR I would like the site name banner to be used as the social media thumbnail on newsletters but in the size format of the twitter image

It would be great to have this look great in Facebook as well but facebook does not put in an image placeholder when there is no image

Just a thought

**Comment by alexfinnarn** [comment]
would need some sort of external API request mocking if tests are to be added.
