### ISSUE TITLE
As a SO/CE I want to understand how the View mode works in the Block Wrapper block

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#1311]
I have been testing the block wrapper block to be able to understand its features and to write up a complete tutorial and I do not understand what the View mode does. The information says: The view mode determines how much of the webform to show within the block. You may customize different view modes (other than the "Form only" mode) or even create new custom view modes if either the Entity view modes or Display Suite modules are installed.
I tried several options, feature teaser, full content, form only but these other views have not been configure for the block?

!s this just a feature that is part of basic Drupal but it does not do anything? Our clients will be curious to see if it does anything like I was - so I need to give them a heads up to not waste time on it - if it does not work.

Dev Site: https://www-dev.colorado.edu/feature/843/
Prod Site: https://www.colorado.edu/p1b19709e33f/about/block-wrapper-block

**Comment by kevincrafts** [comment]
The view mode field is hidden from SO/CE
