### ISSUE TITLE
As a SM I would like to see the number of users with the Edit My Content role

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1312]
## Context

Users with the edit_my_content role are not added to the sites statistics.

**Comment by jeor0980** [comment]
Atlas side changes needed

**Comment by cathysnider** [comment]
So this is out in PROD and is reporting the 'edit my content' count correctly. 
https://osr-atlas03.int.colorado.edu/atlas/statistics/589a3467926f5b488b755ea8
