### ISSUE TITLE
As a SM I would like to see counts of the various roles in a site

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1313]
## Context

Site status provide usernames and emails of users in their roles, but we should provide a simple count of users in those roles too.

**Comment by jeor0980** [comment]
Atlas side changes needed

**Comment by alexfinnarn** [comment]
Closing since I see it in prod stats records like https://osr-atlas03.int.colorado.edu/atlas/statistics/589a3467926f5b488b755ea8
