### ISSUE TITLE
Block Wrapper Titles should behave as other block titles

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1314]
... or else they shouldn't exist at all

## Context

Block Wrapper Titles are difficult to access and edit.

Background: 
There are two ways to create a block wrapper: 
 1. on the Block creation page /block/add/block-wrapper , where you cannot add a block title
 1. or within Page Layout /node/#/layout , where you can add a block title

If you use Page Layout to create your block wrapper block, the block title cannot be removed or changed except from within Page Layout. You have go to page upon which the Block Wrapper is placed, enter Page Layout and edit the block from there. 

## Process

One: 
1. Login to site
2. Enable Advanced Layout if not already
3. Create a page, then Edit Layout
3. Add a Block Wrapper block, choosing any random system block available. Give it a title. 
5. Save the page
6. Click widget 'edit block' 

## Expected result

You should be able to change the block title

## Current result

Block title field is not available

## Possible Fix

Either: 
1: Block Wrappers should not have titles at all.  Stop this field from showing up on the Page Layout page.
2: If Block Wrappers should have titles, then add this field to the Block Edit page. block/wrapper-two/edit

## Screenshots

![blockwrapperinpagelayout](https://user-images.githubusercontent.com/638275/28984507-7fcd6584-791b-11e7-82d0-05b5811afc26.png)

![noblockwrappertitlefield](https://user-images.githubusercontent.com/638275/28984548-c3fcb9ee-791b-11e7-8091-49aac9da76a0.png)

----

## Links to Examples

[Test site](https://www-dev.colorado.edu/p19449716bca/)

**Comment by kevincrafts** [comment]
Because the block that is being selected is providing the title, the title field was hidden because multiple title fields seemed more confusing.  The only title being displayed should come from the block that is being wrapped.

**Comment by cathysnider** [comment]
This has been fixed; The Title Field is no longer being exposed in the Page Layout form.

![blockwrappercreation](https://user-images.githubusercontent.com/638275/45315998-07759880-b4f3-11e8-92bc-25b6e49b0f38.jpg)
