### ISSUE TITLE
Determine/Communicate about quicktabs changes

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1325]
#1151 removes the ability to add new quicktabs and preserves the ability to edit existing quicktabs.

We need to decide how long the transition phase will be for users to migrate their quicktab content to the new expandable blocks, and what that communication will be.

**Comment by cathysnider** [comment]
Tutorials have been updated. The 2.6 communication went out Aug 15.

**Comment by jbertrand** [comment]
We have communication in the 2.6.0 release email that we are replacing Quick Tabs with Expandable. There are links to information on what is in Expandable. There is a note that sites currently using Quick Tabs will be able to edit existing quick tabs but will not be able to add new Quick Tabs but will need to start using Expandable. We will be sending a targeted email to site owners with Quick Tabs to work with setting a timeline for them to move all of their tabs to Expandable. Our goal is within 6 months we will be able to turn off Quick Tab complete.
