### ISSUE TITLE
Collection categories with long labels can cause horizontal scrolling

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1327]
## Context

The Express Admin theme displays longer lists (10+) of checkboxes in multiple columns instead of a single column. Each column is the same width, which is determined by the largest column.

This works fine except for when a checkbox label is also very long.  Drupal Core is styling these labels to not wrap even if there are spaces in the label, which can cause the columns to be very wide.

## Process

1. Login to site as a [SO, CE, EO, ADMIN or DEV]
2. Click Structure
3. Click Taxonomy
4. Enter 15 Collection Categories with multiple words in each term
5. Click Blocks
6. Click Add Block
7. Click Collection Grid

## Expected result

![screen shot 2017-08-09 at 12 11 37 pm](https://user-images.githubusercontent.com/349713/29136930-f3ab5266-7cfb-11e7-99f8-ece0012479df.jpg)

## Current result

![screen shot 2017-08-09 at 12 04 31 pm](https://user-images.githubusercontent.com/349713/29136936-fbe69e22-7cfb-11e7-8d22-708c46ceb80b.jpg)

## Possible Fix

add 
.express-field-columns tr.odd .form-item, .express-field-columns tr.even .form-item { white-space: inherit; }

## Links to Examples

* https://www.colorado.edu/alumni/block/collection-grid-career-services-/edit

**Comment by owenmorrill** [comment]
![1327](https://user-images.githubusercontent.com/5008565/30395740-7a7751e8-9884-11e7-81dc-651c978448b0.png)

**Comment by cathysnider** [comment]
Works
