### ISSUE TITLE
As a SO/ CE I would like to freeze the first row or first column of a large table.

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#1329]
## Context

I would like to set the table headers as frozen on large tables that have a scroll bar

## Links to Examples
See: Responsive table with the flip mode:
The table is flipped to the side and can be scrolled horizontally.
https://tablepress.org/extensions/responsive-tables/

**Comment by jwfuller** [comment]
Adding JS could negatively impact performance.

Would need to carefully evaluate libraries for accessibility, particularly keyboard.

**Comment by jwfuller** [comment]
@ekellagher Do you have any examples of large tables in WE that would benefit from this?
