### ISSUE TITLE
As a SO/CE, bean forms should be the same regardless if the form is stand alone or an inline entity form

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1332]
## Context

Some bean forms contain form alters.  These form alters are not called/processed if the bean form is loaded into an inline entity form.

Examples of this would be the Events Calendar Block, where the dynamic link to the calendar is not included if the bean form is loaded as an inline entity form.

## Impacted Modules

* cu_block_row
* cu_rss_block
* cu_block_to_bean
* cu_feature_callout

## Process

1. Login to site as a [SO, CE, EO, ADMIN or DEV]
2. Click Home
3. Click Edit Layout
4. Add New Block Row Block
5. I should see a blue button that says "Add another column"

## Expected result
![screen shot 2017-09-12 at 10 46 10 am](https://user-images.githubusercontent.com/349713/30338873-4f35b9d2-97aa-11e7-9dde-0a2b4de055ad.jpg)

## Current result
![screen shot 2017-09-12 at 10 46 53 am](https://user-images.githubusercontent.com/349713/30338883-5887c0c0-97aa-11e7-8f47-85f0ad64c6c6.jpg)

## Possible Fix

Copy the alters to hook_inline_entity_form_entity_form_alter()
The existing alter function can't be used because the structure of the array has changed.

For example:

https://github.com/CuBoulder/express/blob/0eef19e82ad3d497b9c2420e1cb8bded41297440/modules/custom/cu_expandable/cu_expandable.module#L228

vs.

https://github.com/CuBoulder/express/blob/0eef19e82ad3d497b9c2420e1cb8bded41297440/modules/custom/cu_expandable/cu_expandable.module#L245

**Comment by cathysnider** [comment]
Acceptance Criteria:
The various block forms appear the same whether called separately or from within an inline entity form.
 - [ ] Block Row
 - [ ] 
 - [ ] 
 - [ ] 

https://www-dev.colorado.edu/p127a5d5cabf/
