### ISSUE TITLE
Bug: List of Funnel Pages is always blank

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1362]
## Context

When you enter a node # and save, the field goes blank. 
This site has two funnel pages set; neither is listed in the path field. 

(also, remove wildcard as a choice. If someone chooses this just to see what happens, they will have seriously messed up their site)

https://www-test.colorado.edu/p1557d5f9fed/

![funnelpage](https://user-images.githubusercontent.com/638275/29288133-ede702d8-80f4-11e7-8add-c7bae28c0e96.jpg)

**Comment by kevincrafts** [comment]
This has been fixed, but still needs to be merged and deployed. 

https://github.com/CuBoulder/cu_digital_campaign_bundle/pull/23
