### ISSUE TITLE
Bug: Compose Tips page is missing some shortcodes

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1364]
## Context

The page at /filter/tips is missing some of the shortcode options

## Process

Login to any site. Edit a page. Directly below the WYSIWIG editor, find the link 'More information about text formats' and click it. 

## Expected result

All the shortcodes and their options should be on this page

## Current result

Missing Shortcodes: imagecaption and share_on_twitter 

Incorrect Shortcodes: calendar should be googlecalendar

**Comment by jeor0980** [comment]
@cathysnider imagecaption usage is actually missing from code, share_on_twitter doesn't show under **Shortcodes usage** unless the cu_share module is enabled.

**Comment by cathysnider** [comment]
Acceptance Criteria:
- [ ] Tips are complete; contain all current shortcodes and their attributes
