### ISSUE TITLE
Bug: Site Search returns results that it shouldn't

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1381]
## Context

In testing the new Search box in various production sites, the following issues were found

## Process

Go to a Production site. Search for something you know is there. 

Examples:
Search [Jewish Studies](http://www.colorado.edu/jewishstudies) for 'Funding'
Search [Human Resources](http://www.colorado.edu/hr/) for Faculty & Staff Assistance

## Expected result

I expect to see links to pages that live within the site I am searching

## Current result

None of the results for Jewish Studies were on the Jewish Studies site. 
![searchresults3](https://user-images.githubusercontent.com/638275/29331102-985c9976-81b8-11e7-9df7-e1b0e88b5aba.jpg)

The Featured Search Results on HR includes a link to Inside CU, which was decommissioned years ago and throws a 404 error. 
![searchresults](https://user-images.githubusercontent.com/638275/29330949-1701c1a8-81b8-11e7-8dc1-3307ae38f5d5.jpg)

**Comment by kevincrafts** [comment]
I don't think this is related to the new search box, as testing a site that had NOT been updated yet didn't show results from that site, which I think could be that the site does not have a unique collection in the GSA.
