### ISSUE TITLE
BUG: Extra padding in ivory theme footer

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1384]
The Ivory theme has some extra padding in the footer even if no content is placed there.

## To test

Take a new install and switch theme to Ivory.

## Expected result

![screen shot 2017-08-15 at 1 46 03 pm](https://user-images.githubusercontent.com/349713/29333226-3983836c-81c0-11e7-9de9-2404b3e8db99.jpg)

## Current result

![screen shot 2017-08-15 at 1 45 33 pm](https://user-images.githubusercontent.com/349713/29333234-41f2fa46-81c0-11e7-8516-23cf1cdcb3a5.jpg)

**Comment by cathysnider** [comment]
Fixed: The extra padding does not show in Ivory footer.
