### ISSUE TITLE
Bug: Add 'active' behavior to navigation bar icons

### ISSUE THREAD

**Issue by jeor0980** [CuBoulder/express#1399]
## Context

In the Express navigation bar (the one toggled by the hamburger menu), certain items will not change to show that they've been selected, the name will be bolded but the icon will stay gray.

The following menu options are affected:

- Users
- Design
- Settings
- User

## Process

1. Login to site as a [SO, CE, EO, ADMIN or DEV]
2. Click Express
3. Click Users, or Design, or Settings, observe bold text and icon
4. Click Dashboard, or Content, or Structure, observe bold text and gray icon

## Expected result

When selecting Users, or Design, or Settings the accompanying menu icon should turn darker to indicate it was clicked and remain darker/bold when page is loaded.

![screen shot 2017-08-16 at 3 23 17 pm](https://user-images.githubusercontent.com/8441552/29385952-fd5a75a8-8296-11e7-987a-e9111ec4ec23.png)

## Current result

![screen shot 2017-08-16 at 3 23 36 pm](https://user-images.githubusercontent.com/8441552/29385965-0570a85c-8297-11e7-9147-c93a0ff8ee50.png)

## Possible Fix

Update express-settings.css in the express_settings module

**Comment by alexfinnarn** [comment]
looks like it works to me. Putting in 2.6.x

**Comment by cathysnider** [comment]
Acceptance Criteria: The little icon for all the menu items have an 'on' state of black. 
 - [ ] Users
 - [ ] Design
 - [ ] Settings
