### ISSUE TITLE
Block title is not centered when block designer title alignment is set to center

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1400]
## Context

If the block designer settings have the block title set to be centered AND the icon position to be inline, the title is still aligned left.

## Process

1. Login to site as a [SO, CE, EO, ADMIN or DEV]
2. Click Block
3. Click Add Block
4. Click Text Block
5. Create a text block with content and a title
6. Click Save
7. Place the block on a page
8. Go to the Block Designer settings for the block
9. Set the Block TItle Alignment to Center
10. Click Save

## Expected result

The title should be centered.

## Current result

The title is not centered.

**Comment by cathysnider** [comment]
Acceptance Criteria:
- [ ] centered on all block types
- [ ] other alignments work as designed
