### ISSUE TITLE
Some Content Grid styles require images to display properly

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1402]
## Context

Some grid styles won't display properly if an image is not set. Let's add some validation to check.

## Process

[ordered list the process to finding and recreating the issue, example below]

1. Login to site as a [SO, CE, EO, ADMIN or DEV]
2. Click Blocks
3. Click Add Block
4. Click Content Grid
5. Create a content grid without images with the style set to 'overlay'
6. Click save

## Expected result

There should be a form error saying that the style requires images to be set.

## Current result

Content grid saves and does not display properly.

![screen shot 2017-08-17 at 2 01 53 pm](https://user-images.githubusercontent.com/349713/29431387-0339a75a-8355-11e7-8a07-24f9f3def4cb.jpg)

**Comment by cathysnider** [comment]
Acceptance Criteria:
- [ ] Error message for grid types: Overlay, Feature and Tiles_alt
- [ ] No error message for the rest

https://www-dev.colorado.edu/p1e82536e603/
