### ISSUE TITLE
BUG: Content grid large teaser row alignment

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1405]
## Context

Content Grids set to teaser alternate style may not align properly depending on the amount of content in each row.

Because the rows display as flex, their width needs to be set to 100%.

![screen shot 2017-08-18 at 3 41 34 pm](https://user-images.githubusercontent.com/349713/29478764-d1130fd2-842b-11e7-8bf0-b76abf760cf8.jpg)

**Comment by cathysnider** [comment]
Acceptance Criteria:
- [x] Each section of Content Grid 'Large Teaser Alternate' is appropriately staggered and equally sized.
- [x] The other Content Grid layouts continue to work as designed.

https://www-dev.colorado.edu/p11c83a51302/cgs
