### ISSUE TITLE
Bundles Screens should only show the current version of the bundle

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1409]
## Context

If there are multiple versions of a bundle added, the bundle screen shows them. Only the one tagged "current" should display.

## Process

1. Login to site as a [SO, CE, EO, ADMIN or DEV]
2. Click Settings
3. Click Enable Bundles
4. Click Request Bundles
5. I should see two newsletter bundles

## Expected result

I should only see the current version

## Current result

I see all versions

![screen shot 2017-08-23 at 10 31 08 am](https://user-images.githubusercontent.com/349713/29627237-aaecb6f2-87ee-11e7-95dc-2e1dd8f83db8.jpg)

**Comment by owenmorrill** [comment]
Closing as these changes have been manually merged into #1071

**Comment by cathysnider** [comment]
FYI about this: This does not happen when there are more than two bundles up there, but only when the the most recent bundle is not the current bundle.  

Newsletter Bundles:
cu_newsletter_bundle 7.x-1.0 - Current
cu_newsletter_bundle 7.x-1.1.1

Resulting Display:
![screen shot 2017-09-22 at 12 03 51 pm](https://user-images.githubusercontent.com/638275/30758072-2feb3976-9f8e-11e7-88cf-d9c45f06000b.png)

Digital Campaign Bundles:
cu_digital_campaign_bundle 7.x-1.0-beta1
cu_digital_campaign_bundle 7.x-1.0-beta2
cu_digital_campaign_bundle 7.x-1.2
cu_digital_campaign_bundle 7.x-1.3 - Current
cu_digital_campaign_bundle 7.x-1.4

Resulting Display:
![screen shot 2017-09-22 at 12 03 44 pm](https://user-images.githubusercontent.com/638275/30758085-38c87afe-9f8e-11e7-8f4a-db79aa67a5dd.png)

**Comment by cathysnider** [comment]
Following up on above comment ... apparently this is how it is supposed to work; i.e. sometimes we want to be able to beta test a release in a production environment.
