### ISSUE TITLE
As a SO, I want more Google Analytics integration with Express

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1410]
## Context

We have several issues in Jira related to this...

https://cuboulder.atlassian.net/browse/FIT-1098
https://cuboulder.atlassian.net/browse/FIT-1562
https://cuboulder.atlassian.net/browse/FIT-1693
https://cuboulder.atlassian.net/browse/FIT-1072
https://cuboulder.atlassian.net/browse/FIT-1766
https://cuboulder.atlassian.net/browse/FIT-1787

We integrated this on Web Central, but thought the process of enabling the API was going to be too complicate for most site owners.

Now that we are planning on giving websupport@colorado.edu access to all custom analytic accounts, we can actually show some select analytics data within Express.  Even if we only offered this to sites getting custom CSEs, it might shed some light on why users are coming to their site.

![google_analytics_summary___web_central](https://user-images.githubusercontent.com/385234/29630838-bffa1d9e-87fa-11e7-9e7f-1d3fc51e4604.png)

Even with the custom analytics within the site, I think we need to fix https://www.drupal.org/node/2903906 or users will be very confused.

**Comment by jwfuller** [comment]
Security Notes:
We would be starting to bypass the access control built into GA, we run the risk of exposing analytic data to users that are not privileged. 

Performance Notes:
Normal concerns about isolating 3rd party integrations with kill switches and timeouts.

**Comment by alexfinnarn** [comment]
For automated testing, some sort of fake GA account would be needed to populate the fields.
