### ISSUE TITLE
As a Newsletter publisher, I'd like the brand lockup to include the name of my site

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1425]
## Context

The current email version of newsletter includes University of Colorado Boulder lockup only.  There's no indication that a newsletter is coming from the Department of Human Resources, or the School of Engineering, or wherever. The newsletter designer is limited in the naming and design of their newsletter. They have to include their department in the newsletter name. 

## What We'd Like

To be able to give a newsletter a name that is catchy and unique, with the the department logo appearing separately in the upper right. 

### Hoped For Results
![newsletterlogo](https://user-images.githubusercontent.com/638275/29686070-d5d1fe04-88d4-11e7-99ba-5e34d1739d90.jpg)

### Current Results
![newsletterlogo1](https://user-images.githubusercontent.com/638275/29685532-0d71f4a6-88d3-11e7-9c5c-e1329ed7bd78.jpg)
![newsletterlogo2](https://user-images.githubusercontent.com/638275/29685674-5f70ff54-88d3-11e7-9e7e-0b0c8178b10c.jpg)
![newsletterlogo3](https://user-images.githubusercontent.com/638275/29685675-5f7428fa-88d3-11e7-910f-03995a6a40bf.jpg)

**Comment by kevincrafts** [comment]
While I agree that this would be really cool, the only way to accomplish this is with images, not fonts and css like we do on the sites.

Because it requires uploading a logo, this is NOT something we want to expose to users because we will lose control of what is appearing there - too many people uploading either totally wrong images/custom logos, or images that attempt and fail to be the proper branding image.

**Comment by cathysnider** [comment]
Then how about this? The site lockup, followed by a graphic that contains the newsletter name. 
![screen shot 2017-08-24 at 2 30 14 pm](https://user-images.githubusercontent.com/638275/29687259-eccd616c-88d8-11e7-94b3-5171a6cf3ac7.png)

**Comment by kevincrafts** [comment]
Each lockup of the CU Logo + Text requires an image be created an uploaded.

The design of the newsletter was made so unique images for each newsletter were not required.
