### ISSUE TITLE
Profile Module Manager not allowing Bundles to be added on new installed

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1429]
## Context

Because the value of the page callback in https://github.com/CuBoulder/express/blob/075b1812ee87070af07b5e49517f62dd10be3a46/modules/custom/cu_atlas/cu_atlas.module#L311 is cached, it doesn't allow bundles to be added even after the value of atlas_status is updated until the menu is rebuilt with something like 'drush eval "menu_rebuild();"

![screen shot 2017-08-25 at 10 13 45 am](https://user-images.githubusercontent.com/385234/29722592-b3e99de2-897e-11e7-873d-fc1c23df8d15.png)

**Comment by cathysnider** [comment]
Acceptance Criteria:
[ ] A site that cannot enable bundles, when updated to this profile, is able to.

Test site: https://www-dev.colorado.edu/p1e8d5f71a8f/
