### ISSUE TITLE
Remove Block Title Icons from Advanced Design Bundle Description

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1430]
## Context

This module has been disabled and functionality has been moved to core Express.

## Currently

"Advanced Design
Add visual elements to your site such as background images, title images, menu icons, block title icons and sticky menus."

**Comment by cathysnider** [comment]
To check:
- [ ] Text is removed from Adv Des Bundle
- [ ] Blocks with title icons added the old way still have their icons and are editable
- [ ] The Block Designer functionality works on current sites
