### ISSUE TITLE
Update the shortcode to work with https://map.colorado.edu

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1436]
## Context

Because the CampusBird service requires https and that currently bypasses varnish, we want to move this to Pantheon where https traffic is being cached by their new global CDN configuration.

https://github.com/CuBoulder/express/blob/bb3a87e25fd5e8baaa7b55d5f8848471f697d74a/modules/custom/cu_shortcodes/cu_shortcodes.module#L760

**Comment by kevincrafts** [comment]
Closing due to a duplicate issue being made that already has a commit and pull request #1437
