### ISSUE TITLE
Blocks placed sitewide should not appear on user pages

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1446]
## Context

When a block is placed, via Context, in the Sitewide or Sitewide-except-homepage contexts, it appears on the User pages.  It is disconcerting to have a block appear on the user login page. 

## Problem Cause

In the contexts sitewide and sitewide-except-homepage, the Condition 'Path' indicating 'not the user pages' is incorrect.

It currently stands at 
~/user
~/user/*

## Possible Fix

Remove the first forward slash in the path designation
i.e. change ~/user to ~user; change ~/user/* to ~user/*

## Screenshots

![userpages](https://user-images.githubusercontent.com/638275/29834973-b0cb3a4e-8cad-11e7-8791-6b7f48e8abb7.jpg)
![userpath](https://user-images.githubusercontent.com/638275/29834974-b0cf7d20-8cad-11e7-99ae-6da74bbababf.png)

----

**Comment by kevincrafts** [comment]
While I agree that this should be fixed, it needs to be done in a way that does not revert the feature.
