### ISSUE TITLE
Add tooltips for 'Move toolbar' link in admin bar

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express#1465]
## Context

Icons do not always make it clear what is going to happen.

The icon that moves the admin bar from the top to the left side does not have a tooltip and the icon could be confused with a 'logout' icon

**Comment by jeor0980** [comment]
Dashboard, Content, Design, and Settings are also missing tooltips

**Comment by jeor0980** [comment]
Fix: https://www.drupal.org/node/2842205#comment-11859762

**Comment by cathysnider** [comment]
QA - Icons are now labeled with 'horizontal orientation' and 'vertical orientation'
