### ISSUE TITLE
As SO, I want to be able to see unused beans

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1475]
## Context

This is related to https://github.com/CuBoulder/express/issues/1018, but approaching it from unused vs. used.  

We want this deployed to help with https://github.com/CuBoulder/express/issues/1103

@kevincrafts wrote cu_unused_beans_bundle, but we need to add this into Express profile.
I'm not exactly sure where this should go, but we don't need it in an add-on bundle https://github.com/CuBoulder/cu_unused_beans_bundle

**Comment by cathysnider** [comment]
Acceptance Criteria:
 - [ ] Unused blocks are correctly listed
- [ ] No blocks that are used are listed. hmm. Testing for a negative ....
