### ISSUE TITLE
BUG: Related articles doesn't sort properly if compared article only has a single term

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1506]
## Context

https://www.colorado.edu/today/2017/09/05/make-donation-sept-6-aid-hurricane-harvey-victims has only one category attached to it ("General"). 

Because there is only this single term to compare it to, the related results list does NOT need to be sorted by occurrences. Doing this sorting for a single term undoes the original sorting by publish date in the query.

When an article has multiple terms, articles that have more in common will have more occurrences - but if all the occurrences are 1, then sorting them messes up the order.

Still, even if more terms are used and content is scored as more related and there are more occurrences, still sorting will mess up the order, however it may be less noticeable because there is more data to work with.

This fix is only for when an article has a single category or tag.

**Comment by alexfinnarn** [comment]
I'm not sure how to test this...

1. Create three articles with "General" as the only category. 
2. ...?

**Comment by kevincrafts** [comment]
For testing I would create 10 articles with a wide range of publish dates all with a single category. After this fix is applied, there should be 3 related articles ordered by descending publish date.
