### ISSUE TITLE
As a SO/CE, I want the site-lock message to accurately reflect site-lock status

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1507]
## Context

1. The manually-entered site lock message will display even if site is not actually locked. 
2. If no message is entered, no message will display even if site is locked

## Process

Login to site; go to admin/people and lock people out. Don't enter a message. 

or

Login to site; go to admin/people and enter a site-lock message but don't lock anybody out. 

## Expected result

1. The manually-entered site lock message should not display if site is not locked. 
2. A default lock message should display if site is locked. 

## Current result

The site lock message displays or not; doesn't matter actually lock status of site.

## Screenshots

![siteisnotlocked](https://user-images.githubusercontent.com/638275/30133033-98c96462-930f-11e7-9403-6c00734c032c.jpg)

![sitelockeditor](https://user-images.githubusercontent.com/638275/30132889-2bf57970-930f-11e7-9fb7-d13a4761cdf2.jpg)

----

## Links to Examples

https://www-dev.colorado.edu/test-file-perms

**Comment by kreynen** [comment]
This isn't a bug.  If a user wants the message to say who is locked out and why, then put that in the message.  We can't read a site owner's mind.
