### ISSUE TITLE
As a SM I would like to update context that places required blocks

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1516]
## Context

Each express site has a context (pc2tr40fz12bx) that places the required blocks on the site, such as the search box, and the campus alerts block.

Because this context is part of the cu_sitewide module, we can never update this because there is likely the cu_sitewide feature has been overridden and we cannot revert it without deleting changes that have been made to a site by the SO/CE.

Moving this context to its own module would allow us to update and revert as necessary without risk of losing user changes.

With the upcoming search changes, this should be done asap.

## Testing

1. On Dev branch, make changes to the sitewide context (place a block, etc)
2. Switch to feature/1516, drush updb
3. Search box, alerts block, site info block should still be placed

**Comment by cathysnider** [comment]
This code is out in production, and has been for some time, possibly from the 2.6 release or even earlier. 

**Acceptance criteria**:
- [x] Modules cu_sitewide and cu_sitewide_required are there
- [x] Search and help modules exist on site; function properly
- [x] a site owner can place a block sitewide with sitewide context
- [x] a site owner cannot access the locked blocks
- [x] current production sites using sitewide context are not messed up

Examples:
https://www.colorado.edu/p1bd7f24600a/ 
https://www.colorado.edu/graduateschool/ 
https://www.colorado.edu/business/
