### ISSUE TITLE
Add Express profile to cu_update_ping

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1529]
## Context

With https://github.com/CuBoulder/express/issues/1462 cu_update_ping currently only checks the status for modules.  We want to include the express profile in that list

**Comment by alexfinnarn** [comment]
Since Express is listed as a "module" the query works now to check for Express' version.

**Comment by alexfinnarn** [comment]
https://github.com/CuBoulder/express/pull/1533/files#diff-b1d21b45dfea4c8883d84ddf8e128556R27

**Comment by alexfinnarn** [comment]
Changed module to use Update but only check for modules we care about. 

![screen shot 2017-09-12 at 10 16 04 am](https://user-images.githubusercontent.com/3640707/30336793-7c972822-97a3-11e7-876c-0f7b70b1b64c.png)
