### ISSUE TITLE
BUG: Columns of icons in Block Designer are too wide and causes horizontal scrolling - Safari Only

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1555]
## Context

When using Block Designer in the Safari browser, when selecting an icon, the columns of icons are too wide and it causes horizontal scrolling which is not very noticeable and could create confusion for users trying to find icons.

The issue is caused by some conflicting css that is from the cu_menu_icons module.

## Process

1. Login to site as a [SO, CE, EO, ADMIN or DEV]
2. Go to block/site_info/design
3. Expand the icon fieldset

## Expected result

Icons should be displayed in columns which fit inside the browser window.

![screen shot 2017-09-15 at 11 51 38 am](https://user-images.githubusercontent.com/349713/30496357-5c946ede-9a0c-11e7-96ae-adc84137c19f.jpg)

## Current result

The columns are very wide and cause the page to have horizontal scrolling to display all the icons.

![screen shot 2017-09-15 at 11 52 06 am](https://user-images.githubusercontent.com/349713/30496369-63953ef2-9a0c-11e7-8f23-921b10c3a463.jpg)

## Possible Fix

Fix the css in the menu icons module to display the icons in the same way they are displayed with Block Designer.

**Comment by cathysnider** [comment]
Test Results: 
- [ ] Several columns of icons fit inside the browser window in the major browsers: Safari, Firefix, Chrome. 
https://www-dev.colorado.edu/p11c83a51302
