### ISSUE TITLE
Google no longer using border-image the same admin/settings/bundles/list

### ISSUE THREAD

**Issue by owenmorrill** [CuBoulder/express#1563]
## Context

Something updated on Chrome and now the border-image usage has changed. We need to update the border on admin/settings/bundles/list.

## Expected result

Border on left-hand side of bundle enable cards.

## Current result

No border in Chrome.

## Possible Fix

border-width: 0 0 0 0.5px;
border-style: solid;
border-color: #cfb87c;

**Comment by cathysnider** [comment]
Test Results: border is no longer gradient. It is now now a solid gray in major browsers.
