### ISSUE TITLE
Bug: Test Content Collection Module has incorrect dependency

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1570]
## Problem

Test Content Module for Collections has dependency of 'cu-collections' which no longer exists.

## Process

login to site as DEV; go to Modules and try to run the CU Test Content Collections module. 

## Current result

Can't run because it has a dependency of  Cu_collections which is missing

## Possible Fix

Update cu_test_content_collections.info of cu_test_content_collections module so that 

Change 
dependencies[] = cu_collections
to 
dependencies[] = express_collections_bundle

## Screenshots

![screen shot 2017-09-20 at 3 11 57 pm](https://user-images.githubusercontent.com/638275/30668362-b8d404de-9e17-11e7-827b-19f6bc2df08e.png)

----

## Links to Examples

https://www-dev.colorado.edu/p11c83a51302/

**Comment by kevincrafts** [comment]
The test content install also needs to be updated to work with the current code, which it does not right now.

**Comment by jeor0980** [comment]
https://github.com/CuBoulder/express_collections_bundle/pull/6

**Comment by ekellagher** [comment]
During Advanced Content and Forms Training: When we enabled Collections Bundle - the collection taxonomy was missing:
sites used for training
https://www-test.colorado.edu/p18beff68b66/
https://www-test.colorado.edu/p148f9d0734d/
https://www-test.colorado.edu/p1da191eb09b/
https://www-test.colorado.edu/p13120c2768a/

**Comment by kevincrafts** [comment]
@ekellagher your issue is related to #1585
