### ISSUE TITLE
BUG: Bundle modules may not update permissions correctly.

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1585]
## Context

For bundles that have dependencies on other modules, our practice has been to put the permissions for the other modules into the _bundle module.

However, if the bundle is a self-contained module with its own permissions and does not include any other custom dependencies, the permissions may not update correctly, leaving the user with insufficient access to use the bundle they just enabled.

## Process

1. Add the Collections bundle to a site
2. Login to site as a [SO, CE]
3. Go to admin/structure/taxonomy/collection_categories
4. I should see an Access Denied message

## Expected result

I should see the terms (if any) for the collection categories vocabulary

## Current result

I receive an Access Denied message.

## Possible Fix

Add a secure permissions rebuild in https://github.com/CuBoulder/express/blob/dev/modules/custom/profile_module_manager/profile_module_manager.module#L317

**Comment by alexfinnarn** [comment]
https://github.com/CuBoulder/express/blob/dev/modules/contrib/secure_permissions/secure_permissions.module#L129

Secure permissions are rebuilt after each module is enabled. I'm not sure how the permissions are checked per user with a db query vs. using something in the sessions table. 

I would try logging out and then back in to see if that helps here.
