### ISSUE TITLE
Remaining Bugs On CSE Search

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#1588]
## Process

1. Go to http://www-test.colorado.edu/webcentral/search
2. Click the text "Colorado.edu" ; the words in the search field do not toggle. 
4. See the placeholder text change but not the checkbox. 
5. Search "foo bar".
6. See it searches "colorado.edu" and not that site. 

![screen shot 2017-10-05 at 10 31 51 am](https://user-images.githubusercontent.com/3640707/31238863-6d0a4ed0-a9b8-11e7-963d-728195e86a26.png)

**Comment by alexfinnarn** [comment]
Adding to this ticket...

On "admin/settings/search/search-settings"

1. Need to check if there is at least one search option checked. Otherwise, a SO can break search on their site. 
2. Need to sanitize user input for label and make sure it's not empty.

**Comment by owenmorrill** [comment]
I spoke to Jo, we want them to have at least the one option always checked for the search box.
