### ISSUE TITLE
Block Wrapper Block Title bug

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#1600]
When you create a block wrapper and you add a title to the block. You cannot later delete the block title from the edit block option
![block wrapper title](https://user-images.githubusercontent.com/16137919/31454126-a36a1f24-ae71-11e7-835d-1f9df67a53aa.JPG)

You need to go into Edit Layouts to be able to edit the block title
![block wrapper title - edit layouts](https://user-images.githubusercontent.com/16137919/31454150-b1433f86-ae71-11e7-9fa0-55d42fb6bd9d.JPG)

Since this is not typical block editing behavior we should add the block title option in the edit block page

**Comment by kevincrafts** [comment]
This has to do with how form alters are handled differently when the form is rendered through Inline Entity Form.  This issue is being fixed in #1332.

The Block Wrapper titles should NOT be used, as the blocks within them have their own titles.
