### ISSUE TITLE
Edits to Localist Events Block

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#1605]
Could you change the term Category to Interest this is consistent with the terminology in Localist
Filter by Category to Filter by Interest and
Exclude by Category to Exclude by Interest
![localist block 1](https://user-images.githubusercontent.com/16137919/31471621-e5580524-aea6-11e7-99d0-260a29d6eca8.JPG)
![localist block 2](https://user-images.githubusercontent.com/16137919/31471624-e7da3998-aea6-11e7-8172-99cd86e9690b.JPG)

**Comment by kevincrafts** [comment]
The filter field names come from localist, so they would need to be updated there.

**Comment by cathysnider** [comment]
![interestorcategory](https://user-images.githubusercontent.com/638275/31778577-40c15b38-b4ae-11e7-9659-81eb8ca96a37.jpg)
