### ISSUE TITLE
Bug: File content type lists urls as http

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1609]
## Context

At one point we wanted to make sure people were linking to http files, so we altered the urls to be http only.  Now that we are on https we can removed these.

## Possible Fix

Remove:

- https://github.com/CuBoulder/express/blob/dev/modules/features/files/files.module#L135

- https://github.com/CuBoulder/express/blob/dev/modules/features/files/node--file.tpl.php#L5

## Testing

1. Create a file node
2. Upon saving and viewing the file node, the urls listed should be https.

**Comment by cathysnider** [comment]
https://www-dev.colorado.edu/p18ac0b15293/

**Comment by cathysnider** [comment]
Well this is working now, in the site above and in a new site spun up today. 
https://www-dev.colorado.edu/p1a2943abde6/content/minutes 

![https](https://user-images.githubusercontent.com/638275/34009609-cc5409cc-e0c6-11e7-9846-4c840ef30df1.jpg)
