### ISSUE TITLE
Duplicate bundles in Add-on Bundles and Request Bundles

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#1610]
There are two collections bundles display in the Add-on Bundles tab and two Newsletter bundles in the Request Add-on Bundles tab
![add bundles - collections 2x](https://user-images.githubusercontent.com/16137919/31554228-26e1f97e-affa-11e7-9cf1-e2b617d0d08a.JPG)
![add bundles - newsletter 2x](https://user-images.githubusercontent.com/16137919/31554229-297f9240-affa-11e7-911b-b8c80df6dfa5.JPG)

**Comment by kevincrafts** [comment]
Closing as a duplicate for #1527
