### ISSUE TITLE
Enable Diff For All Express Sites

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#1617]
## Context

Due to an update in the Diff module, we need to turn it on for all sites since in 5 sites had an error with the Diff module being NULL in the system table. 

Enabling the Diff module for all sites will also make node revisions and overridden features reviews more useful. 

1. Enable the Diff module in cu_core update hook. 
2. Add Diff as a requirement for all Express sites in express.info.
3. Remove Diff module from cu_debug_admin_bundle. 
4. Check permissions so that the correct roles can use it. 
5. Check with Emily about documentation and assist with any verbiage.

**Comment by kreynen** [comment]
https://github.com/CuBoulder/express/pull/1619 is a mess.  Creating a new branch from dev with a clean PR now.
