### ISSUE TITLE
Bug: Searching content by author uses user name, not real name

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1620]
## Context

When using the filter/search options on /admin/content, the Author field uses the user name, not the Real Name which is displayed everywhere else. Searching by the Real Name could return no results.

Now that we don't display the user name, it makes this field unusable unless you know what the user names are.  If you are looking for your own content, then you probably know your user name. If you are looking for someone else, probably not.

## Screenshots

Content screen with no filtering

![screen shot 2017-10-17 at 2 07 32 pm](https://user-images.githubusercontent.com/349713/31686857-bea67170-b344-11e7-8653-44ae07886210.jpg)

Content screen when filtering by author

![screen shot 2017-10-17 at 2 07 45 pm](https://user-images.githubusercontent.com/349713/31686876-d940ec4a-b344-11e7-8349-ea9beece2616.jpg)

**Comment by kreynen** [comment]
This is a dulicate to https://github.com/CuBoulder/express/issues/1830
