### ISSUE TITLE
Reduce font size of url in search results

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1621]
Set .gs-visibleUrl to 75% 

## Before
![screen shot 2017-10-18 at 10 11 58 am](https://user-images.githubusercontent.com/349713/31729710-0a9aecca-b3ed-11e7-8149-d63397462f6e.jpg)

## After
![screen shot 2017-10-18 at 10 11 45 am](https://user-images.githubusercontent.com/349713/31729714-0ea20bf0-b3ed-11e7-8e49-fe62a03f481d.jpg)

**Comment by cathysnider** [comment]
Already in production; looks good.
