### ISSUE TITLE
As an Event Admin, I want Localist Block Filters to appear in alphabetical order

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1626]
## Context

Department and Group choices are in reverse alphabetical order, which is in contrast to the sort order of Type and Audience.  Let's be consistent.

## Screenshots

![screen shot 2017-10-19 at 9 02 51 am](https://user-images.githubusercontent.com/638275/31778129-16f8d994-b4ad-11e7-8917-a522f0da0175.png)

----

## Links to Examples

https://www-dev.colorado.edu/p1dd7fef4326/

**Comment by kevincrafts** [comment]
https://github.com/CuBoulder/express_localist_bundle/commit/55c586ce358e774cf91a694e4c895d7397914b1a#diff-f97b9cc0ab7c0aa4c59c20af75e49ad5L206
