### ISSUE TITLE
As an Event Admin, I need to be able to chose any of the places in the Localist Calendar

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1627]
## Context

The Web Express Localist Block has a limited list of places. 

The Localist Calendar has a much more extensive list. 

I need to be able to select from all the places on campus.

## Screenshots

Here: the choices in the Web Express Localist Block:
![webexpressplaces](https://user-images.githubusercontent.com/638275/31779242-ebaf9fb8-b4af-11e7-8c48-e2951df916d3.jpg)

Here: in the Localist Calendar has an auto-populating field for Location:
![localistplaces](https://user-images.githubusercontent.com/638275/31779252-f32c637a-b4af-11e7-84cd-ca4183859242.jpg)

----

## Links to Examples

https://www-dev.colorado.edu/p1dd7fef4326

**Comment by kevincrafts** [comment]
https://github.com/CuBoulder/express_localist_bundle/issues/2
