### ISSUE TITLE
More contrib modules to update for 2.8.0

### ISSUE THREAD

**Issue by owenmorrill** [CuBoulder/express#1635]
## Context

Since August, there have been a number of additional contrib module updates.

File Entity Recommended version: | 7.x-2.11 (2017-Oct-18)
Focal Point Recommended version: | 7.x-1.1 (2017-Sep-11)
Google Analytics  Recommended version: | 7.x-2.4 (2017-Sep-25)
Google Custom Search Engine Recommended version: 7.x-3.0-alpha1 (2017-Apr-26)
Insert Recommended version: 7.x-1.4 (2017-Sep-17)
Memcache (will not be updated!) Recommended version: 7.x-1.6 (2017-Feb-24)
Shortcode Recommended version: 7.x-2.23 (2017-Oct-20)
Varnish Recommended version: 7.x-1.5 (2017-Sep-28)
WYSIWYG Filter Recommended version: 7.x-1.6-rc8 (2017-Oct-12)

**Comment by owenmorrill** [comment]
#1440

**Comment by owenmorrill** [comment]
Notice: Undefined variable: output in cu_article_preprocess_entity() (line 743 of /data/code/profiles/express/express-2.8.0/modules/features/cu_article/cu_article.module).
Warning: array_merge() [function.array-merge]: Argument #2 is not an array in cu_article_preprocess_entity() (line 743 of /data/code/profiles/express/express-2.8.0/modules/features/cu_article/cu_article.module).

On article page built by test content bundle. Noting here.

**Comment by owenmorrill** [comment]
Source image at public:// not found while trying to generate derivative image at public://styles/slider/public/.
https://express.local/p11e03edd6f9/sites/default/files/styles/slider/public?itok=DlMHrEdF

I'm not sure if this is a local problem, or if we've broken test content with the updates.

**Comment by alexfinnarn** [comment]
Add Pathologic update if needed.

**Comment by alexfinnarn** [comment]
#1658
