### ISSUE TITLE
Long lists of radio buttons should display in multiple columns

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1647]
## Context

Express currently has functionality to display long lists (> 10) of checkboxes in multiple columns rather than a single long list.  This should apply to radio buttons as well.

Most of our lists of options are checkboxes, but you can test this using the localist bundle where some of the localist block filter options are radios.

**Comment by cathysnider** [comment]
The only Localist Filter that has radio buttons is 'Group.' The rest are checkboxes. And yes, the radio buttons are displayed in columns. 
https://www-test.colorado.edu/p12cdb606c69/block/add/localist-events
