### ISSUE TITLE
As a SO, I would like to maintain a list a acronyms

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1652]
## Context

When I went to the Hacky Hours, the grad student tried to look up the acronym for the org unit I worked for using https://www.colorado.edu/bfa/resources/acronyms.  None of the potential acronyms for the unit I work for existed in that list.  Not only is that far from accurate, it is being maintained as a basic page.  A search for acronyms shows that this is a fairly common content type on Express sites.

https://www.colorado.edu/geography/gcraft/notes/gps/acronym.html
https://www.colorado.edu/ecenter/recycling/resources/curricular-resources/recycling-glossary-and-acronyms
https://www.colorado.edu/researchinnovation/sites/default/files/attached-files/abbreviations_and_acronyms.pdf
https://www.colorado.edu/engineering/civil/CVEN4474/resources/RemedAcron.pdf
https://www.colorado.edu/ecenter/sites/default/files/attached-files/recycling_acronyms.pdf

I think we should create an Acronym Bundle as well as maintaining an official acronym list as part of https://www.colorado.edu/strategicrelations/services/print/writingediting/style-guide/abbreviations

## Process

[ordered list the process to finding and recreating the issue, example below]

1. Login to site as a [SO, CE, EO, ADMIN or DEV]
2. Click Administer
3. Click Webform
4. Enter "Kevin, don't do that" in the body field
5. Click save

## Expected result

[describe what you would expect to have resulted from this process]

## Current result

[describe what you currently experience from this process, and thereby explain the bug]

## Possible Fix

[not obligatory, but suggest fixes or reasons for the bug]

* Fix form validation properly.
* Delete the functionality.

## Screenshots

[if relevant, include screenshots]

----

## Links to Examples

* [Webform Page](https://www.colorado.edu/p1/721)
* [Drupal issue](https://drupal.org/node/721)

**Comment by kevincrafts** [comment]
++

**Comment by kreynen** [comment]
Issue moved to [CuBoulder/directory #19](https://github.com/CuBoulder/directory/issues/19) via [**ZenHub**](https://www.zenhub.com/)
