### ISSUE TITLE
Add sitemap.xml of sitemap.xmls

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1653]
## Context

Something like what http://www.cnn.com/sitemaps/sitemap-index.xml is doing.

**Comment by kevincrafts** [comment]
Do you mean that we would aggregate all of the sitemaps of each express site into a sitemap index? What if individual sites also have sitemap indexes?

**Comment by kreynen** [comment]
Issue moved to [CuBoulder/custom_homepage_bundle #160](https://github.com/CuBoulder/custom_homepage_bundle/issues/160) via [**ZenHub**](https://www.zenhub.com/)
