### ISSUE TITLE
New installs Admin menu in wrong order

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1657]
## Context

New sites have the main admin menu in the wrong order - Help is appearing before the User's name.

![screen shot 2017-11-02 at 10 09 38 am](https://user-images.githubusercontent.com/349713/32336891-270c1774-bfb6-11e7-82a4-536ed138f1cc.jpg)

**Comment by cathysnider** [comment]
Acceptance Criteria: The order of links in Blue Admin Bar is:
 - [ ] Express
 - [ ] Shortcuts
 - [ ] User Name
 - [ ] Help
 - [ ] Logout

**Comment by cathysnider** [comment]
Test site:
https://www-dev.colorado.edu/p1d88971dc04/
I'm sorry but the links in the Blue Admin bar are:
Express, Shortcuts, Help, Username and Logout. This is not the correct order. Help should appear AFTER Username.

**Comment by cathysnider** [comment]
Another Test, using commit fb24ae0ff

Site Whitescreening: https://www-dev.colorado.edu/p1019208e19a/

Still Failing.

**Comment by kevincrafts** [comment]
Checked out the above branch locally and am not having any white screen issues
