### ISSUE TITLE
BUG: Site Owner can access Secure Pages and Localist Configuration Page

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1658]
## Context

Admin Page /admin/config/system/securepages is accessible to users with site owner role, and from there can access /admin/config/system/express-localist where they can change calendar URL.

## Process

Login to https://www-dev.colorado.edu/p16e024d585b/user as OSR Test Site Owner

Click link to https://www-dev.colorado.edu/p16e024d585b/admin/config/system/securepages which is placed on home page, or enter URL in address bar

## Expected result

Site Owner should get 'Access Denied' message

## Current result

Site Owner can access all Secure Pages from here -- currently Localist. They can change URL of calendar.

## Screenshots

[if relevant, include screenshots]

----

## Links to Examples

* [Webform Page](https://www.colorado.edu/p1/721)
* [Drupal issue](https://drupal.org/node/721)

**Comment by kreynen** [comment]
The securepages issue is because the permission was removed without disabling the module, but I'm not seeing that on existing sites on www-test or new www-test sites.

I think the Localist issue is just a side effect of installing that bundle after the change to securepages.

**Comment by kreynen** [comment]
Even though users can't see a link to https://www-test.colorado.edu/cmci/admin/config/system/express-localist they can access it if they know the URL.

**Comment by kevincrafts** [comment]
https://github.com/CuBoulder/express_localist_bundle/commit/81c475b9cde95b6d3c09f583475e8dc6806e901a
