### ISSUE TITLE
Bug: Main Menu Links missing some items

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1665]
## Context

Main Menu links should have more items in there:
/admin/structure/menu/item/xxx/edit

## Process

Go To Main Menu
/admin/structure/menu/manage/main-menu

Choose Dropdown 'Configure Item' for one of the links

## Expected result

You should see 
Icon
XML Siteman
Advanced Menu Settings
Buttons: Save and Delete

## Current result

You see
Buttons: Save and Delete
Advanced Menu Settings

## Screenshots

[if relevant, include screenshots]![menuitemscorrect](https://user-images.githubusercontent.com/638275/32391832-210961ea-c099-11e7-8e6b-8dc829bd0a50.jpg)
![menuitemwrong](https://user-images.githubusercontent.com/638275/32391833-211c5278-c099-11e7-917e-383fcd20c50a.jpg)
----

## Links to Examples

https://www-dev.colorado.edu/p16e024d585b

**Comment by kevincrafts** [comment]
Menu icons are only available if the Advanced Design Bundle is enabled
