### ISSUE TITLE
Bug: admin/content is empty even though there are many nodes

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1667]
## Context

Many nodes have been created but nothing is showing up in admin/content

## Screenshots

Screenshot of random page showing nav bar:
![screen shot 2017-11-03 at 3 41 52 pm](https://user-images.githubusercontent.com/638275/32397072-9a4944e4-c0ad-11e7-9413-d8e244389b7c.png)

Screenshot of admin/content:
<img width="1092" alt="screen shot 2017-11-03 at 3 37 54 pm" src="https://user-images.githubusercontent.com/638275/32397025-6577c146-c0ad-11e7-8b8d-639093c3b265.png">

----

## Links to Examples

https://www-dev.colorado.edu/p16e024d585b/

**Comment by kevincrafts** [comment]
Cleared cache and they came back

**Comment by cathysnider** [comment]
Not an issue anymore
