### ISSUE TITLE
Bug: Bundles appearing twice on www-test

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1673]
## Context

2.8.0 Upgrade: All sites on test have Video Hero Unit bundle twice

## Process

Login to a test site, go to Bundles

## Screenshots

![videoherounit](https://user-images.githubusercontent.com/638275/32454704-3d5da4dc-c2dd-11e7-94a4-b9dcc69a5e43.jpg)

----

## Links to Examples

https://www-test.colorado.edu/business/
https://www-test.colorado.edu/cmci/
https://www-test.colorado.edu/law/

**Comment by kreynen** [comment]
<img width="1394" alt="screen shot 2017-11-06 at 11 55 44 am" src="https://user-images.githubusercontent.com/385234/32460108-e73cb1d0-c2ee-11e7-8199-8de33e470f51.png">

Same issue as Collections.  Multiple entries in Atlas = Multiple Entries in the UI.  

<img width="1394" alt="screen shot 2017-11-06 at 12 35 46 pm" src="https://user-images.githubusercontent.com/385234/32460160-17fb2716-c2ef-11e7-9d0a-bb7ccca5141d.png">

With video hero, I think these both are in the same dir on the servers so deleting one is going to actually delete all the code. 

Who is going to clear up the bundles on www-test?
