### ISSUE TITLE
Horizontal Content Sequence has display issues (2.8.0)

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1683]
## Context

The Horizontal Content Sequence in 2.8.0 is having some display issues.
- The Steps are numbered with zero-based array index
- With dark block background, text is not visible when viewed as a list

## Screenshots

![screen shot 2017-11-07 at 11 55 46 am](https://user-images.githubusercontent.com/638275/32511994-b814581c-c3b2-11e7-83f9-5b02345d3dc4.png)
![screen shot 2017-11-07 at 11 55 58 am](https://user-images.githubusercontent.com/638275/32511995-b830c254-c3b2-11e7-9977-59a68b1a696d.png)

----

## Links to Examples

version 2.8.0: https://www-test.colorado.edu/sandbox/cathy/node/558

Compare this to version 2.7.0:  https://www.colorado.edu/p1f4bca2b935/node/456

**Comment by kevincrafts** [comment]
Working for me. https://www-test.colorado.edu/p16d24ec0c28/
