### ISSUE TITLE
Add HelpScout beacon for authenticated editors

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1684]
## Context

When a editor is logged in, we can use a HelpScout beacon to direct them to our help documentation.

The following code will bring up the beacon modal when the help link is pressed

`<script>!function(e,o,n){window.HSCW=o,window.HS=n,n.beacon=n.beacon||{};var t=n.beacon;t.userConfig={},t.readyQueue=[],t.config=function(e){this.userConfig=e},t.ready=function(e){this.readyQueue.push(e)},o.config={docs:{enabled:!0,baseUrl:"//university-of-colorado-boulder-docs.helpscoutdocs.com/"},contact:{enabled:!0,formId:"3ac3ec6d-c002-11e7-b466-0ec85169275a"}};var r=e.getElementsByTagName("script")[0],c=e.createElement("script");c.type="text/javascript",c.async=!0,c.src="https://djtflbt20bdde.cloudfront.net/",r.parentNode.insertBefore(c,r)}(document,window.HSCW||{},window.HS||{});</script>

<script>
  HS.beacon.config({
    modal:1,
  });
jQuery('#navbar-bar a.navbar-icon-help').click(function(event) {
  event.preventDefault();
  HS.beacon.open();
});
</script>`

<img width="1098" alt="screen shot 2017-11-07 at 12 29 40 pm" src="https://user-images.githubusercontent.com/385234/32515142-605343e0-c3bc-11e7-95b7-b9cf4799dc40.png">

**Comment by cathysnider** [comment]
Well this is awesome. https://www-test.colorado.edu/p1bde2411132/
