### ISSUE TITLE
Unused Blocks problem: Herbst lists block as used when maybe it isn't

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1695]
## Context

While checking sites for unused Events Calendar blocks, I found this: 

Herbst Program of Humanities in Engineering
https://www.colorado.edu/herbst/

Unused Blocks page shows only Herbst Events (Events Calendar Block) as the only unused events calendar blocks. 

They have one other events calendar block - Herbst & Cultural Events - which I cannot find as placed anywhere on the site.

## Screenshots

![unusedblock1](https://user-images.githubusercontent.com/638275/32631222-c2d32eb2-c55c-11e7-882b-9dc1ab86a573.jpg)
![unusedblocks2](https://user-images.githubusercontent.com/638275/32631223-c2f485c6-c55c-11e7-8137-42a07d8a1c1b.jpg)

----

## Links to Examples

https://www.colorado.edu/herbst/

**Comment by kevincrafts** [comment]
This block is not appearing in the list anymore - closing issue.
