### ISSUE TITLE
Notice: Only variables should be passed by reference in _cu_atoz_render_children() (line 143 of cu_atoz.module).

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1696]
## Context
Logged ~9,000 times in 5 hours since the PHP7 update.  This is now the top error.

Notice: Only variables should be passed by reference in _cu_atoz_render_children() (line 143 of /data/code/modules/express_homepage/express_homepage-7.x-1.2/modules/custom/cu_atoz/cu_atoz.module).

**Comment by alexfinnarn** [comment]
duplicate of #1698.
