### ISSUE TITLE
Bug: SO can enable RSS bundle without also enabling News and Articles

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1700]
## Context

RSS bundle is supposed to require News and Articles bundle, but has come unhitched from it somehow.

## Process

Login as SO; enable RSS feed bundle. 

## Expected result

It's supposed to ask you to enable N&A

## Current result

RSS bundle enables w/o also enabling N&A. The N&A blocks (Article List, Article Feature, Article Grid, Article Slider), are turned on, but Articles are not turned on, and Taxonomy is not either.

## Screenshots

![rssfeedbundle](https://user-images.githubusercontent.com/638275/32805119-b93ec310-c945-11e7-95cc-c99fef9b81da.jpg)
![rssfeedbuilder](https://user-images.githubusercontent.com/638275/32805126-bf858204-c945-11e7-858c-a3a0278990f0.jpg)

----

## Links to Examples

https://www.colorado.edu/p1b1692fe80e

**Comment by kreynen** [comment]
Only core, bundle and hosting dependencies are processed by PMM when enabling the bundle and checking dependencies.

This would be fixed by https://github.com/CuBoulder/express/issues/2510
