### ISSUE TITLE
As a SO I would like to embed Sched in my site

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#1703]
Full Name: Marla Schulz
Department: Dance
Email: marla.schulz@colorado.edu
Website URL: https://www.colorado.edu/conference/acda2018/
Website Name: American College of Dance Association (ACDA) Northwest
Conference
Specific URL of problem page(s):
https://www.colorado.edu/conference/acda2018/sched-embed
Detail of problem or question:
We are implementing the use of the event app sched into our conference for
scheduling and waitlisting management. Sched has code that can be embedded
into the website so that the schedule and tools on the app are also available
through any webpage we want. I'm having some difficulties successfully
embedding the code right now. Everytime I try all I get is a link to access
the sched online app, but no embedded schedule. Here is the code I am trying
to embed: View the FUSE ACDA 2018 mobile app [1]
I am currently inserting it into the WYSIWYG box with rich-text enabled.
Thank you!

**Comment by kreynen** [comment]
Exchanged a few emails with Ryan from Sched <ryan@sched.com>.  They currently don't have any public facing status monitoring or change log/roadmap, but they seem open to this...

> Hey Kevin, 
Thank you for such a thoughtful and detailed reply. I really appreciate it. It makes sense why you need to identify an issue quickly.
While I can say fairly certainly that this won't be fully implemented in the next few weeks, I am sharing this with my product team to discuss implementation. 
I'll share any developments in this thread and if the organizer of the event has any questions, feel free to send them my way.

**Comment by kreynen** [comment]
https://www.opencon2018.org/opencon_boulder is an example of Sched being integrated with Nation Builder.

<img width="1198" alt="screen shot 2018-09-07 at 10 28 03 am" src="https://user-images.githubusercontent.com/385234/45231287-ca0dd280-b288-11e8-9871-b4fc5d25bc63.png">
