### ISSUE TITLE
BUG: Permission form changes don't save

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1705]
On a production site, changing the permissions form does not save after submit.

Even though the form is enabled through secure permissions, it appears to be somewhat disabled, as the checked boxes are grey vs blue (see screenshots below).

This only happens on production so far - not on test or local.

Prod site:
![screen shot 2017-11-16 at 2 07 56 pm](https://user-images.githubusercontent.com/349713/32915867-93496870-cad7-11e7-8520-c8ec3eb5a8c1.jpg)

Local Site
![screen shot 2017-11-16 at 2 07 58 pm](https://user-images.githubusercontent.com/349713/32915880-9bb9df76-cad7-11e7-8eeb-b3f506abca55.jpg)

**Comment by jwfuller** [comment]
This is result of server config http://php.net/manual/en/info.configuration.php#ini.max-input-vars
The perms form has too many inputs to submit with the default php configs. Bumping from `1000` to `2000` allows webcentral perms to save. 

To work around, edit perms by single role.

**Comment by jwfuller** [comment]
Check box color issue was a result of changed zoom level
