### ISSUE TITLE
Updating sites to 2.8.1 results in duplicate function error

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express#1726]
@kreynen commented on [Wed Dec 06 2017](https://github.com/CuBoulder/atlas/issues/429)

I tried this on the webcentral site on www-dev and www-test.  www-dev spit this error back to...

`Fatal error: Cannot redeclare ldap_pear_asc2hex32() (previously declared in /data/code/profiles/express/express-2.8.0/modules/contrib/ldap/ldap_servers/ldap_servers.functions.inc:431) in /data/code/profiles/express/express-2.8.1/modules/contrib/ldap/ldap_servers/ldap_servers.functions.inc on line 431`

www-test just returned a 500.

I've checked the server and the 2.8.1 version of the profile is the only version of express symlinked into /profiles

`kere7580@wwebdev2:~$ cd /data/web/express/webcentral/
kere7580@wwebdev2:/data/web/express/webcentral$ cd profiles/
kere7580@wwebdev2:/data/web/express/webcentral/profiles$ ls -all
total 24
drwxr-xr-x 2 osr_web_deploy apache         4096 Dec  6 12:29 .
drwxr-xr-x 4 osr_web_deploy apache         4096 Aug  3 12:53 ..
lrwxrwxrwx 1 osr_web_deploy osr_web_deploy   41 Dec  6 12:29 express -> /data/code/profiles/express/express-2.8.1
lrwxrwxrwx 1 osr_web_deploy osr_web_deploy   60 Aug  3 12:53 minimal -> ./../../../../code/cores/drupal/drupal-7.56/profiles/minimal
lrwxrwxrwx 1 osr_web_deploy osr_web_deploy   63 Aug  3 12:53 README.txt -> ./../../../../code/cores/drupal/drupal-7.56/profiles/README.txt
lrwxrwxrwx 1 osr_web_deploy osr_web_deploy   61 Aug  3 12:53 standard -> ./../../../../code/cores/drupal/drupal-7.56/profiles/standard
lrwxrwxrwx 1 osr_web_deploy osr_web_deploy   60 Aug  3 12:53 testing -> ./../../../../code/cores/drupal/drupal-7.56/profiles/testing`

Running the clear_php_cache resolves the issue.

I'm not sure if this is an issue with the atlas update or an issue with the PHP7/infrastructure changes, but we can't deploy profiles updates to production until we resolve this.

**Comment by kreynen** [comment]
duplicate function error is a larger issue related to how opcode handles symlinks
