### ISSUE TITLE
Confirm impact of sharin colorado.edu cookie namespace on Varnish caching

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1744]
It looks like the existence of a cookie from any Express site may bypass varnish for all sites.  Not sure if varnish is using something specific in the cookie related to Drupal/Express or any colorado.edu cookie will result in a bypass.  That would be really troubling since fedauth uses a colorado.edu cookie.  That would mean that a student logging into Canvas would be bypassing varnish until the fedauth cookie expired.

Before the PHP7/https changes, only authenticated users bypassed varnish.  Now https is used by all users (anonymous and authenticated) and cached, but logging into any site bypasses the user the cached version of ALL pages until the user either logs out or the cookie expires.

https://chrome.google.com/webstore/detail/varnish-indicator-forked/cecjclajledipahfcbkcajegnbmpnbco?hl=en

**Comment by kreynen** [comment]
When troubleshooting https://github.com/CuBoulder/express/issues/1867 I've confirmed that not only will logging into any site on www cause a user to bypass varnish for all other sites on www, it also bypasses varnish on www-dev and www-test

**Comment by jwfuller** [comment]
Looking at this change https://github.com/CuBoulder/express/blob/7f625fbcb8e68eb0ed5f631b75d9fa582e8b5598/modules/contrib/varnish/varnish.cache.inc#L38
