### ISSUE TITLE
Bug: Social Icons in Person Content Type have reverted to external-link-square

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1755]
## Context

Issue https://github.com/CuBoulder/express/issues/996 (As a SO/CE when I add links to the person content type that the link icons represent what I am linking to) was fulfilled and merged with DEV on Sept 12 2017 via Pull Request https://github.com/CuBoulder/express/pull/1414 for the 2.8.0 release.

The functionality should be in production but is not showing up. 
Example: https://www.colorado.edu/p1f4bca2b935/content-types/person-page

The feature needs to be put back into DEV and added to the next release.

## Links to Examples

https://www-dev.colorado.edu/p15b36d24d88/sue-watson

https://www-dev.colorado.edu/p18891755605/ernest-fleming

## Pics
 
Should be this:
![personpage](https://user-images.githubusercontent.com/638275/34421341-f764b872-ebcb-11e7-8b93-8f701b54b2dc.jpg)

But actually is this:
![linkicons](https://user-images.githubusercontent.com/638275/34421134-b21522f8-ebca-11e7-9d6c-e9f140feb2f8.jpg)

**Comment by jeor0980** [comment]
![screen shot 2018-05-22 at 3 57 30 pm](https://user-images.githubusercontent.com/8441552/40392432-dfaf4e70-5dd8-11e8-8996-43aac0bcfdf9.png)
