### ISSUE TITLE
Collection Bundle is missing from the Add-on Bundle List

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#1760]
Site Owners are unable to add the collection Bundle to sites. It is missing from the Add-On Bundle options
![add-on bundles](https://user-images.githubusercontent.com/16137919/34177543-3558d986-e4c1-11e7-9f67-c2444987d2a2.JPG)

**Comment by kreynen** [comment]
This was a combination of the Atlas tags and mulitple versions of the bundle
