### ISSUE TITLE
Move People Search into new tab

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1761]
Move the People search into a tab that will transfer the search query from any other search and does not have any integration with A-Z.

- [ ] https://github.com/CuBoulder/express/issues/1728

<img width="709" alt="screen shot 2017-12-20 at 11 40 14 am" src="https://user-images.githubusercontent.com/385234/34222951-ac381102-e57a-11e7-91cf-a46e61610dd9.png">

<img width="454" alt="screen shot 2017-12-20 at 10 38 26 am" src="https://user-images.githubusercontent.com/385234/34222902-7f9ace96-e57a-11e7-81a7-efbf17fdb924.png">

<img width="708" alt="screen shot 2017-12-20 at 11 40 38 am" src="https://user-images.githubusercontent.com/385234/34222960-b592f06e-e57a-11e7-8ad3-2760825281cc.png">

**Comment by kevincrafts** [comment]
Should this go in https://github.com/CuBoulder/express_homepage ?

**Comment by kreynen** [comment]
I can see the case for either including it in what should be custom_homepage or defining just the main search in that bundle and maintaining each search (people/directory/classes/jobs/etc) in their own bundle so they are easier to update when the backends updates.  There are pros and cons to either direction.

**Comment by kreynen** [comment]
Issue moved to [CuBoulder/custom_homepage_bundle #172](https://github.com/CuBoulder/custom_homepage_bundle/issues/172) via [**ZenHub**](https://www.zenhub.com/)

**Comment by kreynen** [comment]
Issue moved to [CuBoulder/custom_homepage_bundle #173](https://github.com/CuBoulder/custom_homepage_bundle/issues/173) via [**ZenHub**](https://www.zenhub.com/)
