### ISSUE TITLE
Issue with SSL certificate used to load resources from https://bam.nr-data.net

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1766]
## Context

The SSL certificate used to load resources from https://bam.nr-data.net will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.

Not sure where this code is even coming from.

`<script type="text/javascript">window.NREUM||(NREUM={});NREUM.info={"beacon":"bam.nr-data.net","licenseKey":"77bdf6c909","applicationID":"34128397","transactionName":"ZARbNksCWkRYUE1eW11OeAFNCltZFl1WU1FsEVgFXDxCXlxE","queueTime":0,"applicationTime":501,"atts":"SENYQAMYSUo=","errorBeacon":"bam.nr-data.net","agent":""}</script>`

**Comment by owenmorrill** [comment]
https://bam.nr-data.net/1/77bdf6c909?a=34125406&v=1071.385e752&to=ZARbNksCWkRYUE1eW11OeAFNCltZFl1WU1FsEVgFXDxCXlxE&rst=2033&ref=https://www-test.colorado.edu/&ap=566&be=794&fe=2021&dc=1186&perf=%7B%22timing%22:%7B%22of%22:1514394502415,%22n%22:0,%22u%22:595,%22ue%22:596,%22f%22:8,%22dn%22:8,%22dne%22:8,%22c%22:8,%22ce%22:8,%22rq%22:10,%22rp%22:589,%22rpe%22:594,%22dl%22:609,%22di%22:1185,%22ds%22:1185,%22de%22:1476,%22dc%22:2017,%22l%22:2017,%22le%22:2021%7D,%22navigation%22:%7B%22ty%22:1%7D%7D&at=SENYQAMYSUo%3D&jsonp=NREUM.setToken#

**Comment by owenmorrill** [comment]
https://discuss.newrelic.com/t/new-relic-browser-heading-is-causing-a-js-error-which-is-causing-issues-in-app/26893

**Comment by owenmorrill** [comment]
https://discuss.newrelic.com/t/chrome-certificate-update/53563

https://discuss.newrelic.com/t/bam-nr-data-net-using-symantec-certificate-that-will-be-distrusted-in-chrome-70/52370/7

**Comment by owenmorrill** [comment]
NREUM.setToken({
Error: Parse error on line 1:
{'stn':0,'err':0,'ins
-^
Expecting 'STRING', '}'
'stn':0,'err':0,'ins':0,'cap':0,'spa':0})

^^ Error being returned by the New Relic JS.

**Comment by owenmorrill** [comment]
https://docs.newrelic.com/docs/browser/new-relic-browser/troubleshooting/troubleshooting-browser-monitoring-installation

This is where the JS is coming from.

**Comment by yzguy** [comment]
The certificate has since been updated, the errors should no longer show up.
