### ISSUE TITLE
Custom analytics still not tracking 404.html in additional customTrackers

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1771]
## Context

Related to https://github.com/CuBoulder/express/issues/1631 and https://github.com/CuBoulder/express/issues/1770

While we fixed the issue of the 404 in https://github.com/CuBoulder/express/issues/1630, we didn't update our custom alter to send the 404 to both gs and customTracker0 and customTracker1.

`<![CDATA[//><!]]>`

On a normal page, both ga and the customTrackers send pageview.

`<![CDATA[//><!]]>
`

But on a 404 page, ga sets the page with ga("set", "page", "/music/404.html?page=" +
document.location.pathname + document.location.search + "&from=" +
document.referrer);

The update to the Google Analytics module improved the reporting for the universal analytic code, but this didn't fix the Web Express or site specific reports.

![screen shot 2017-12-28 at 12 12 20 pm](https://user-images.githubusercontent.com/385234/34420741-684416c2-ebc8-11e7-8c8a-0e4ec1cf8402.png)

**Comment by kreynen** [comment]
Also add ga("set", "anonymizeIp", true) for each GA we are sending data to

**Comment by alexfinnarn** [comment]
I'm not sure I fully understand this issue, but I've found a few things while trying to figure it out.

Firstly, a user can save a blank value on the GA form under the Settings menu.
<img width="580" alt="screen shot 2018-07-05 at 3 35 32 pm" src="https://user-images.githubusercontent.com/3640707/42344045-13e37f9c-8069-11e8-8457-ec8a65584f7a.png">

There is already a validation function, and I think rejecting a blank value makes sense: https://github.com/CuBoulder/express/blob/dev/modules/custom/express_settings/express_settings.module#L439

**Comment by alexfinnarn** [comment]
Secondly, even if I have a value entered and saved in that form, I see the following on "admin/config/system/googleanalytics":

<img width="773" alt="screen shot 2018-07-05 at 3 38 09 pm" src="https://user-images.githubusercontent.com/3640707/42344212-98937d28-8069-11e8-9425-3590019e3626.png">

The snippet code is inserted correctly...

<img width="1391" alt="screen shot 2018-07-05 at 3 39 49 pm" src="https://user-images.githubusercontent.com/3640707/42344255-bdf7a1a2-8069-11e8-8408-caf94c20f067.png">

**Comment by alexfinnarn** [comment]
Local site on a real page...

```html

<!--//--><![CDATA[//><!--
(function(i,s,o,g,r,a,m){i["GoogleAnalyticsObject"]=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,"script","https://www.google-analytics.com/analytics.js","ga");ga("create", "UA-123456-1", {"cookieDomain":"auto"});ga("set", "anonymizeIp", true);ga("set", "dimension1", "1");ga("set", "dimension2", "Home");ga("set", "dimension3", "Basic page");ga("set", "dimension4", "Thu, 07\/05\/2018 - 13:06");ga("send", "pageview");ga('create', 'UA-123456-1', 'auto', {'name':'customTracker0'});  ga('customTracker0.send', 'pageview');ga('create', 'UA-105731679-1', 'auto', {'name':'customTracker1'});  ga('customTracker1.send', 'pageview');
//--><!]]>
```

and on a missing page...

```html
<!--//--><![CDATA[//><!--
(function(i,s,o,g,r,a,m){i["GoogleAnalyticsObject"]=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,"script","https://www.google-analytics.com/analytics.js","ga");ga("create", "UA-123456-1", {"cookieDomain":"auto"});ga("set", "anonymizeIp", true);ga("set", "page", "/404.html?page=" + document.location.pathname + document.location.search + "&from=" + document.referrer);ga("send", "pageview");ga('create', 'UA-123456-1', 'auto', {'name':'customTracker0'});  ga('customTracker0.send', 'pageview');ga('create', 'UA-105731679-1', 'auto', {'name':'customTracker1'});  ga('customTracker1.send', 'pageview');
//--><!]]>
```

Diff to make it easier to see...
<img width="1241" alt="screen shot 2018-07-05 at 3 46 42 pm" src="https://user-images.githubusercontent.com/3640707/42344553-b1a73f7e-806a-11e8-8f4c-56d90ee3696b.png">

I think I might get it now with the last screenshot.

**Comment by alexfinnarn** [comment]
So the contrib module has hardcoded the "page" value:
https://github.com/CuBoulder/express/blob/dev/modules/contrib/google_analytics/googleanalytics.module#L208

If I comment out those lines, then the JS code generated is:

```html

<!--//--><![CDATA[//><!--
(function(i,s,o,g,r,a,m){i["GoogleAnalyticsObject"]=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,"script","https://www.google-analytics.com/analytics.js","ga");ga("create", "UA-123456-1", {"cookieDomain":"auto"});ga("set", "anonymizeIp", true);ga("send", "pageview");ga('create', 'UA-123456-1', 'auto', {'name':'customTracker0'});  ga('customTracker0.send', 'pageview');ga('create', 'UA-105731679-1', 'auto', {'name':'customTracker1'});  ga('customTracker1.send', 'pageview');
//--><!]]>
```

or the diff...
<img width="1274" alt="screen shot 2018-07-05 at 4 05 26 pm" src="https://user-images.githubusercontent.com/3640707/42345418-4abdc8fc-806d-11e8-9cd0-2e7b6ad5f0f3.png">

It now sends the pageView event but without the metrics.

**Comment by alexfinnarn** [comment]
I think the values for dimensions are blank because https://github.com/CuBoulder/express/blob/dev/modules/contrib/google_analytics/googleanalytics.module#L234 returns `NULL` for the 404 pages.

**Comment by alexfinnarn** [comment]
To test this:

- Enable tracking of authenticated users under "admin/config/system/googleanalytics". I wanted to do this logged in...
- Turn off "Universal web tracking opt-out" under Privacy. With that on, I couldn't get to the part where tracking code is added.
- Go to a regular page and search for "ga(" in the browser tool inspection. 
- Go to a 404 page and search for the same.

You should see snippets like above. You can comment out the $url_custom lines to see the difference.

**Comment by kreynen** [comment]
I think the problem is in the https://github.com/CuBoulder/express/blob/dev/modules/custom/express_settings/express_settings.module#L453

When we do ga('create' a 2nd and 3rd time, we're re-instantiating that object so only the default pageview values are sent to the custom trackers

We need to update https://github.com/CuBoulder/express/blob/dev/modules/custom/express_settings/express_settings.module#L464 to use this approach...

`<![CDATA[//><!]]>`

So the creates happen in the googleanalytics_codesnippet_before and only the sends happen in the googleanalytics_codesnippet_after

**Comment by alexfinnarn** [comment]
The `ga("set",` calls get set before the "before" snippet so I altered the JS code before it is rendered to extract the create calls and place them before `ga("set", "anonymizeIp", true);`. This is very brittle, because it assumes `ga("set", "anonymizeIp", true);` is always what is needed. Some more code could search for `ga("set", ` to improve that.

But I don't see the parameters being sent from the debugging console output.

Normal page:
```js
<!--//--><![CDATA[//><!--
(function(i,s,o,g,r,a,m){i["GoogleAnalyticsObject"]=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,"script","https://www.google-analytics.com/analytics_debug.js","ga");

ga("create", "UA-123456-1", {"cookieDomain":"auto"});
ga("create", "UA-123457-1", "auto", {"name":"customTracker0"});
ga("create", "UA-105731679-1", "auto", {"name":"customTracker1"});

ga("set", "anonymizeIp", true);
ga("set", "dimension1", "1");
ga("set", "dimension2", "Home");
ga("set", "dimension3", "Basic page");
ga("set", "dimension4", "Fri, 07\/06\/2018 - 06:55");

ga("send", "pageview");
ga("customTracker0.send", "pageview");
ga("customTracker1.send", "pageview");
//--><!]]>
```

404 page:
```js
<!--//--><![CDATA[//><!--
(function(i,s,o,g,r,a,m){i["GoogleAnalyticsObject"]=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,"script","https://www.google-analytics.com/analytics_debug.js","ga");

ga("create", "UA-123456-1", {"cookieDomain":"auto"});
ga("create", "UA-123457-1", "auto", {"name":"customTracker0"});
ga("create", "UA-105731679-1", "auto", {"name":"customTracker1"});

ga("set", "anonymizeIp", true);
ga("set", "page", "/404.html?page=" + document.location.pathname + document.location.search + "&from=" + document.referrer);

ga("send", "pageview");
ga("customTracker0.send", "pageview");
ga("customTracker1.send", "pageview");
//--><!]]>
```

Each dimension has to be repeated for each tracker: https://developers.google.com/analytics/devguides/collection/analyticsjs/command-queue-reference#set

**Comment by alexfinnarn** [comment]
Normal page:
```js
<!--//--><![CDATA[//><!--
(function(i,s,o,g,r,a,m){i["GoogleAnalyticsObject"]=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,"script","https://www.google-analytics.com/analytics_debug.js","ga");
ga("create", "UA-123456-1", {"cookieDomain":"auto"});
ga("create", "UA-123457-1", "auto", {"name":"customTracker0"});
ga("create", "UA-105731679-1", "auto", {"name":"customTracker1"});

ga("set", "anonymizeIp", true);
ga("set", "dimension1", "1");
ga("set", "dimension2", "Home");
ga("set", "dimension3", "Basic page");
ga("set", "dimension4", "Fri, 07\/06\/2018 - 06:55");

ga("customTracker0.set", "anonymizeIp", true);
ga("customTracker1.set", "anonymizeIp", true);
ga("customTracker0.set", "dimension1", "1");
ga("customTracker1.set", "dimension1", "1");
ga("customTracker0.set", "dimension2", "Home");
ga("customTracker1.set", "dimension2", "Home");
ga("customTracker0.set", "dimension3", "Basic page");
ga("customTracker1.set", "dimension3", "Basic page");
ga("customTracker0.set", "dimension4", "Fri, 07\/06\/2018 - 06:55");
ga("customTracker1.set", "dimension4", "Fri, 07\/06\/2018 - 06:55");

ga("send", "pageview");
ga("customTracker0.send", "pageview");
ga("customTracker1.send", "pageview");
//--><!]]>
```

404 page with no dimensions:
```js
<!--//--><![CDATA[//><!--
(function(i,s,o,g,r,a,m){i["GoogleAnalyticsObject"]=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,"script","https://www.google-analytics.com/analytics_debug.js","ga");

ga("create", "UA-123456-1", {"cookieDomain":"auto"});
ga("create", "UA-123457-1", "auto", {"name":"customTracker0"});
ga("create", "UA-105731679-1", "auto", {"name":"customTracker1"});

ga("set", "anonymizeIp", true);
ga("set", "page", "/404.html?page=" + document.location.pathname + document.location.search + "&from=" + document.referrer);

ga("customTracker0.set", "anonymizeIp", true);
ga("customTracker1.set", "anonymizeIp", true);
ga("customTracker0.set", "page", "/404.html?page=" + document.location.pathname + document.location.search + "&from=" + document.referrer);
ga("customTracker1.set", "page", "/404.html?page=" + document.location.pathname + document.location.search + "&from=" + document.referrer);

ga("send", "pageview");
ga("customTracker0.send", "pageview");
ga("customTracker1.send", "pageview");
//--><!]]>
```

**Comment by alexfinnarn** [comment]
I still see no GA code when I install a site locally. I have to save the form with a value.

<img width="535" alt="screen shot 2018-07-06 at 11 47 27 am" src="https://user-images.githubusercontent.com/3640707/42388099-6ae88c0c-8112-11e8-9f01-73ff9c92a151.png">
