### ISSUE TITLE
Add matchredirect to all Express sites and integrate with existing URL Redirect UI.  Read for SO.  Write for Admins/Devs

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1772]
## Context

I installed match_redirect on a few sites when I was trying to reduce the number of requests for pages that didn't exist from the service in the fall.  

physics/2000 is a top 404 that could easily be redirected with match_redirect

https://www.colorado.edu/today/2000/05/29/cu-boulders-physics-2000-web-site-wins-international-internet-award

![screen shot 2017-12-28 at 12 19 12 pm](https://user-images.githubusercontent.com/385234/34420992-e5f8643c-ebc9-11e7-999f-343affa2a364.png)

Without match_redirect, a Site Owner would have to hundreds of redirects for every URL.

While the data in the tables of admin/config/search/match_redirect doesn't match up exactly to admin/config/search/redirect adding a Wildcards tab would be one way to consolidate where these live.

![url_redirects___summer_session](https://user-images.githubusercontent.com/385234/34421401-4eadf120-ebcc-11e7-95c0-1aab8cdf05af.png)

Related to https://github.com/CuBoulder/express/issues/1631

At some point in the future, redirects may be handled before Drupal which be even more of a performance improvement.  Adding match_redirect is an easy win for performance and user experience.  

Initially only admins/devs should be able to create these, but we want all users to be able to see these.

**Comment by alexfinnarn** [comment]
<img width="797" alt="screen shot 2018-07-03 at 2 40 17 pm" src="https://user-images.githubusercontent.com/3640707/42238506-0d5c610c-7ecf-11e8-90b9-090349740863.png">

I think the redirect patterns should be split into lines, but that requires patching the module.

**Comment by alexfinnarn** [comment]
<img width="754" alt="screen shot 2018-07-03 at 2 50 58 pm" src="https://user-images.githubusercontent.com/3640707/42238970-8722c5e8-7ed0-11e8-91db-ee0813f8683c.png">

This may have always been this way, but once you save a redirect, it is hard to know what you're actually redirecting from and to.

**Comment by alexfinnarn** [comment]
Now it doesn't work for me for some reason...

**Comment by alexfinnarn** [comment]
<img width="640" alt="screen shot 2018-07-03 at 4 10 41 pm" src="https://user-images.githubusercontent.com/3640707/42242381-aa87912a-7edb-11e8-83d6-c1e45aa8cae3.png">

That is important and easy to miss. Adding to a test...

**Comment by alexfinnarn** [comment]
For admins, it would be better if they could access the config menu. Right now, they need to go to the actual menu path to add them. 

Adding a local task/link "Add match redirect" on "admin/config/search/redirect/wildcards" would help.
