### ISSUE TITLE
As a Site Owner, I'd like to limit the number of taxonomy tag misspellings and duplicate tags

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1773]
## Context

Sites that publish a lot of articles have the problem of duplicate category & tag taxonomies, including:
News / News 
Announcement / Announcements 
Research / Reserach
Internship / Internships / Intership / Interships
Business / Business
List of 10 / List of !0
Feature / Features 
CWA / Conference on World Affairs
Arts / Art
Sept17 / Sept 2017 / September 2017
Ethic Studies / Ethnic Studies
International Affairs / International Affairs / International Affairs (yes, three)
Aprd / APRD
Advertising / Advertising / Advertising 
Event / Events
Journalism news / Journalism News
Press Release / Press Releases
Spotlight / Spotlights
Molecular Cellular And Developmental Biology / Molecular, Cellular And Developmental Biology
Natural Science / Natural Sciences 
2017 Newsletter / Newsletter 2017
In The Spotlight / In the Spotlight
CU Boulder / CU-Boulder
People Soft / PeopleSoft

## Current result

It's way too easy to accidentally create new tags and categories. This makes it difficult to strategically manage articles. 

## Possible Fix

Add Taxonomy Autocomplete Permission to Express sites. Currently only /today has this module.

**Comment by kevincrafts** [comment]
That module was added as a way to keep the Today team from adding too many terms, not to control misspelled terms.  The term reference fields do have an autocomplete that will allow users to select a term if it already exists.
