### ISSUE TITLE
FIX DEPENDENCIES

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1776]
## Context

https://github.com/CuBoulder/express/commit/7905f6b45e7e3f330c7553206caa94d707b3122c

![screen shot 2017-12-28 at 3 49 32 pm](https://user-images.githubusercontent.com/385234/34425167-cde7afac-ebe6-11e7-8169-abc4ae4838bd.png)

**Comment by owenmorrill** [comment]
https://github.com/CuBoulder/express/pull/954 #916 changes reverted.

**Comment by kreynen** [comment]
Fixed by https://github.com/CuBoulder/express/issues/1781
