### ISSUE TITLE
Add SAML configuration for D7 in pantheon_hosting

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1784]
## Context

Related to https://github.com/cuboulder/express/issues/1781

On Pantheon we have SAML configured in D8 for http://bulletin.colorado.edu/, but we didn't configure that for http://alerts.colorado.edu/.  We want to include as much of the configuration as we can and a Readme.txt that spells out the additional steps that need to happen with IAM.

**Comment by alexfinnarn** [comment]
Placeholder doc: https://docs.google.com/document/d/1n9wf9gbVJXDQJgKVfS0P7vGWNf5Th3fVZCnxPOgYUlA/edit

**Comment by owenmorrill** [comment]
https://www-dev.colorado.edu/p104092b69d6/

**Comment by owenmorrill** [comment]
https://www-dev.colorado.edu/p123a723cdd2/saml_login

**Comment by owenmorrill** [comment]
https://www-test.colorado.edu/p135271e0667/saml_auth

**Comment by owenmorrill** [comment]
www-test.colorado.edu/p123a723cdd2/saml_login

**Comment by owenmorrill** [comment]
https://www-test.colorado.edu/p1d0d212264e/profiles/express/simplesaml/module.php/saml/sp/metadata.php/cu_boulder?output=xhtml

**Comment by owenmorrill** [comment]
https://www-test.colorado.edu/p1d0d212264e/profiles/express/simplesaml/module.php/core/authenticate.php

**Comment by owenmorrill** [comment]
php
Wednesday, February 28, 2018 - 11:17
Owen Paul Morrill
https://www-test.colorado.edu/p1d0d212264e/admin/config/people/simplesamlphp_auth
https://www-test.colorado.edu/p1d0d212264e/admin/config/people/simplesamlphp_auth
PDOException: SQLSTATE[HY000] [2002] No such file or directory in SimpleSAML\Store\SQL->__construct() (line 61 of /data/code/profiles/express/express-2.8.3-1866/libraries/simplesamlphp/lib/SimpleSAML/Store/SQL.php).
error
172.20.62.43


Can't test this on dev and test without a proper database connection.

**Comment by owenmorrill** [comment]
https://www-test.colorado.edu/p157e19ad6b3/user
