### ISSUE TITLE
As a SO, I would like to allow users to edit content without being able to add, delete, change menus, etc

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1799]
## Context

As we continue to add features to Express and grant permissions to those features to both SO and CE, we are working against our own goals in 2 ways:

1. Added complexity.  I would argue that Express 2.8.x is as complex on the initial install as the last Express 1.x release.  We have dozens of issues of users not wanting to make changes because they are unsure of what will happen.
2. CE's have too much power.  We know of hundreds of unintentional menu items added and nodes/blocks deleted by CEs.

One solution to this would be to redefine CEs as only content editors who can't make any changes that a SO can't revert with revisions.  CE's would no longer be able to...

- create new nodes/blocks
- delete nodes/blocks
- add/edit menu items
- edit layouts
- add/edit redirects
- access dashboards/reports

These additional permissions would be added to a new role of Site Editor.  

While the technical/code changes are fairly simple, this would require enough major changes to documentation and training that I think we should brand it as Express 3.0 and make the change at the end of the fall term giving users the summer to adjust who has which role on their site.

**Comment by ekellagher** [comment]
Documentation done
