### ISSUE TITLE
Cannot invite users to new instances

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express#1801]
## Context

@ekellagher reported that she could not invite users to new instances.

I confirmed this on https://www.colorado.edu/p1b4882d3fa1/admin/people/invite, and found that the role were not selected on `/admin/config/people/invite`

This commit removed the necessary code https://github.com/CuBoulder/express/commit/c945e148de1def0a5cf4159f5659e28c032d309c

To workaround the problem, a developer can change the instance to `installing` and when that process is finished, configure user_external_invite

**Comment by kreynen** [comment]
Cherry picking this into 2.8.2 https://github.com/CuBoulder/express/commit/d8d3cccad28be4c7831d9ef39ee71aec13e1a94c

**Comment by kreynen** [comment]
Hash update deployed to prod.  Available instances can now invite users again.
