### ISSUE TITLE
BUG: Main Menu is incomplete; missing Target and Operations Drop Down

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1804]
## Context

Latest Code, commit d8d3cccad28be4c7831d9ef39ee71aec13e1a94c of Jan 5, has a bug in the display of Main Menu at admin/structure/menu/manage/main-menu

## Current Result v Expected Result

Target is missing
Operations Drop Down is missing
New Menu Item field with Add-Item-Target-Content dropdown is missing

(Current result is viewable on dev site https://www-dev.colorado.edu/p1e0a0574079/)

(Expected result is viewable on any prod site https://www.colorado.edu/amath/)

## Screenshots

![mainmenucurrentresult](https://user-images.githubusercontent.com/638275/34690255-a5d34cdc-f475-11e7-94d0-f5d877b11746.jpg)

![mainmenuexpectedresult](https://user-images.githubusercontent.com/638275/34690291-c58cf802-f475-11e7-80dd-55af58de88d7.jpg)

----

## Links to Examples

Current: https://www-dev.colorado.edu/p1e0a0574079/
Expected: https://www.colorado.edu/amath/

**Comment by kevincrafts** [comment]
https://github.com/CuBoulder/express/commit/b935c80a713896354eb844882c29c0a1338a72f0 seems to e the offending commit.  

It looks like we just need to reapply the patch for using content menu and big menu together.

**Comment by cathysnider** [comment]
Per commit hash 6af90511c0e8e90405ecbf5c4e4056fd3d8b3bc1 of Jan 12, this is working 
https://www-dev.colorado.edu/p1b989549b57/
