### ISSUE TITLE
SO should be able to invite users to be CM and assign role to existing users after installing the CM bundle

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1806]
## Context

The Campaign Manager role is created when the bundle is created in https://github.com/CuBoulder/cu_digital_campaign_bundle/blob/master/cu_digital_campaign_bundle.module#L19, but the permission for SO to add that role isn't.  

The role also isn't added to the User Invite options.

**Comment by kevincrafts** [comment]
https://github.com/CuBoulder/cu_digital_campaign_bundle/pull/39

**Comment by alexfinnarn** [comment]
This has been added to the codebase but needs to be deployed to production. There is one other bug listed in that repo, too.

**Comment by alexfinnarn** [comment]
moved to https://github.com/CuBoulder/cu_digital_campaign_bundle/issues/51
