### ISSUE TITLE
Move more link in article feature block to bottom to match display of more link in the article grid block

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1807]
## Context

The design and display of the more link in the article feature block should match the design and display of the more link in the article grid block.

![screen shot 2018-01-10 at 2 04 20 pm](https://user-images.githubusercontent.com/349713/34795391-68ca6ee2-f60f-11e7-939a-93ece20294e3.jpg)

**Comment by alexfinnarn** [comment]
Before 

![screen shot 2018-02-22 at 2 15 47 pm](https://user-images.githubusercontent.com/3640707/36564548-edc7495c-17da-11e8-96d5-cbc458715779.png)

After

![screen shot 2018-02-22 at 2 17 25 pm](https://user-images.githubusercontent.com/3640707/36564622-24b878b4-17db-11e8-8d25-d693ac030f9c.png)

Looks good to me.

**Comment by alexfinnarn** [comment]
merged
