### ISSUE TITLE
BUG: New site Install is unable to invite users. 

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1813]
## Testing 2.8.3 in DEV, commit hash 6af90511c0e8e90405ecbf5c4e4056fd3d8b3bc1 dated Jan 12

https://www-dev.colorado.edu/p1b989549b57/

## Process

Login to site as Site Owner
Go to Users >> Invite User

## Result

See message: "Your site is not yet configured to invite users. Contact the site administrator to configure the invite feature."

![screen shot 2018-01-12 at 2 57 51 pm](https://user-images.githubusercontent.com/638275/34896983-18dd8d6a-f7a9-11e7-9eaa-5e114178d687.png)

**Comment by kreynen** [comment]
These variables are set on site install.  This issue has been discussed repeatedly discussed in https://github.com/CuBoulder/express/issues/1801 and https://github.com/CuBoulder/express/issues/1796.  I just spent another 15 minutes confirm this is not an issue.
