### ISSUE TITLE
Bug: File content type lists Image URLS as http:

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1814]
## Testing 2.8.3 in DEV, commit hash 6af90511c0e8e90405ecbf5c4e4056fd3d8b3bc1 dated Jan 12

https://www-dev.colorado.edu/p1b989549b57/

## Context

An image uploaded with File Content Type, to be used with Backstretch, has URL of http://

This creates an 'Insecure Content' warning with the various browsers. 

## Screenshots

![screen shot 2018-01-12 at 3 17 07 pm](https://user-images.githubusercontent.com/638275/34897712-be40e006-f7ac-11e7-9cd7-fc88e7085c74.png)

![screen shot 2018-01-12 at 3 22 15 pm](https://user-images.githubusercontent.com/638275/34897718-c6e38006-f7ac-11e7-8bf4-c17aa581ac53.png)

**Comment by kreynen** [comment]
https://github.com/CuBoulder/express/blob/dev/modules/features/files/files.module#L134 this is an issue in prod.  The problem is that Apache doesn't know it is returning everything as https to the user.  Varnish is handling that.  

This issue probably exists in other places.

**Comment by cathysnider** [comment]
This is no longer an issue;
![screen shot 2018-09-10 at 10 00 45 am](https://user-images.githubusercontent.com/638275/45310086-929a6280-b4e2-11e8-91bc-1913de250c0a.png)
