### ISSUE TITLE
Bug: link to 'Blocks administration page' has been exposed again

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1815]
## Context

The text and link appearing on the List Menus tab has reverted to "Each menu has a corresponding block that is managed on the Blocks administration page." with a link to /admin/structure/block, which throws an 'Access denied' error.

## Process

1. Login to site as a SO or a DEV
2. Click Structure
3. Click Menus

## Expected result

On the first tab "List Menus", the first line of text should be 'Each menu has a corresponding block which can be placed in a content region.' with no link 

## Current result

"Each menu has a corresponding block that is managed on the Blocks administration page." with a link to /admin/structure/block, which throws an 'Access denied' error.  

## Fix

Replace "Each menu has a corresponding block that is managed on the Blocks administration page."
with "Each menu has a corresponding block which can be placed in a content region."

## Screenshots

![blocksadminlinkexposed](https://user-images.githubusercontent.com/638275/34898166-d9144006-f7ae-11e7-8329-4b7015d0a1e5.jpg)

**Comment by kreynen** [comment]
I see where we used to alter this using string_overrides in https://github.com/CuBoulder/express/blob/dev/express.install#L133 and where the original text is configured in https://github.com/CuBoulder/drupal-7.x/blob/7.x/modules/menu/menu.module#L40.

The contrib String Overrides is still a dependency of Express in https://github.com/CuBoulder/express/blob/dev/express.info#L200

What's even stranger is that the current text is different yet...

<img width="1374" alt="screen shot 2018-01-16 at 1 18 46 pm" src="https://user-images.githubusercontent.com/385234/35010440-1bd1a1cc-fac0-11e7-8e34-a9da6063604d.png">

**Comment by kreynen** [comment]
After checking some of the sites created after the PHP7 update on 11/9/2017, I can confirm this is not an issue with the Drupal code changes but with sites created on any environment after the PHP7 upgrade.

![screen shot 2018-01-16 at 4 44 35 pm](https://user-images.githubusercontent.com/385234/35017987-c45a7a8c-fadc-11e7-8c35-07a815edc0c5.png)

**Comment by cathysnider** [comment]
## Links to Examples

This has been verified on
* https://www.colorado.edu/dontignoreit
* https://www.colorado.edu/p1cfc299fd35
* https://www.colorado.edu/faculty/summers
* https://www.colorado.edu/aquetza

**Comment by cathysnider** [comment]
Branch, including Behat test that needs to pass is:
https://github.com/CuBoulder/express/tree/bug/1815
