### ISSUE TITLE
BUG: Form Action Items Are Not at Bottom of Menu Item Edit Form

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1816]
This issue is related to issue #1665 and pull request #1756;

The original feature branch was merged and then reverted at a later date.

The commits for this new issue are:

- https://github.com/CuBoulder/express/pull/1756/commits/a51adbf4fb93cbdc6755d53535aa32f023aa1a7b

## Eample

https://www-dev.colorado.edu/p1b989549b57/

## Process

Login to site as a SO or a DEV
Go to admin/structure/menu/manage/main-menu 
In Operations Drop Down, choose  'Configure Item'

## Expected result

The form buttons should be at bottom of form; no choices should appear below the action items. 

## Current result

![menuitemeditform](https://user-images.githubusercontent.com/638275/34898781-1eeb655c-f7b2-11e7-99cc-517084665dcb.jpg)

**Comment by kreynen** [comment]
Cherry picked this into dev https://github.com/CuBoulder/express/commit/9414aad5abe2b96220dab834d1fbc3eb4703dfa4
