### ISSUE TITLE
Add login hook to prevent users without a role from really logging in

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1823]
@kreynen commented on [Tue Aug 08 2017](https://github.com/CuBoulder/meta/issues/7)

Back in Aug of 2017 we started seeing an increase in users without a role logging into the homepage.  We were I was seeing this error in the logs...

`PHP Fatal error: require_once(): Failed opening required '/profiles/express/modules/contrib/realname/realname.tokens.inc'`

There are > 1000 users on that site, but more troubling is there have been 8 students who have logged in since 2.5.6 was rolled out.  @kevincrafts checked the webforms, but none of them require authentication.  My guess is they ended up on https://www.colorado.edu/user by mistake, but we never figured out why and it just keeps happening.

This is also an issue for https://github.com/CuBoulder/express/issues/2888

With SAML, the plan is to use https://www.drupal.org/project/r4032login to redirect users to login whenever they hit a page that would have a been a 403.  With SAML, they will just be logged in if they already have an active IdP session.

That will make this problem worse since every site could get hundreds of new Drupal users if they accidentally link to an unpublished node. Currently those users would login, but not even know they don't have a role on this site since they don't get an admin toolbar or an option to logout.

Instead of actually logging users without a role into a site, we want to add a hook_login that checks for roles.  If the only role the user has is rid 2/authenticated user, we want to log them out and send them to a page that tells them they don't have a role and give them options to search or contact websupport at a path like login/norole (or something like that).  Something like that...

`You attempted to log into [Site Name linked to basepath].  Because you are not an owner or editor of this site, there is no reason for you to log in.  If you believe you should have access to this site, please contact websupport@colorado.edu. `

By adding unpublished_404 (or a module like that) for https://github.com/CuBoulder/express/issues/2893 to change the behavior of unpublished nodes from 403 to a 404, users would only see this message if they are trying to login through /user or go directly to /admin

**Comment by cathysnider** [comment]
My opinion: put the 'Are you looking for MyCU Info? Go here' block back on the user login page.

**Comment by kreynen** [comment]
After discussing with @jbertrand and @kevincrafts, we decided to move the /user login of the homepage to a new path and redirect anyone attempting to access /user to https://www.colorado.edu/students

**Comment by kreynen** [comment]
We still want to redirect users attempting to access /user or /user/login, but instead of moving the login path within the homepage itself, we want to test using SAML on https://www.colorado.edu/webcentral/ and the homepage.  That requires #1972

**Comment by owenmorrill** [comment]
https://github.com/CuBoulder/express_homepage/pull/153
