### ISSUE TITLE
Stop creating redirects to user's Real Name

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1824]
## Context

Since implementing the Real Name module, redirects from user/xxx to the clean URL are created each time a user logs in.

Since we don't user those paths anywhere to create something like a user profile page, these are unnecessary.

**Comment by owenmorrill** [comment]
*Goes off to learn about the realname module.*

**Comment by owenmorrill** [comment]
https://github.com/CuBoulder/express/blob/dev/modules/custom/cu_redirect/cu_redirect.module#L235

**Comment by owenmorrill** [comment]
When you login, you should no longer see the message "'Redirect from users/owmo7772 to user/7 was created." You will still see "Your e-mail has been updated to match your current account (Owen.Morrill@Colorado.EDU)."

**Comment by owenmorrill** [comment]
![realname-redirect](https://user-images.githubusercontent.com/5008565/37619212-69a27356-2b7e-11e8-93b9-1aa80f72fd9e.png)

?

**Comment by owenmorrill** [comment]
So far, the PR can take care of removing users/identikey on update, but so far no luck on keeping the realname module from creating them on install without patching/hacking realname.

**Comment by owenmorrill** [comment]
Alias to users/identikey continues to be created when users login. We're going to have to override users/*.

**Comment by owenmorrill** [comment]
The offending alias creator (not redirect): https://github.com/CuBoulder/express/blob/dev/modules/contrib/pathauto/pathauto.module#L1091

**Comment by alexfinnarn** [comment]
https://github.com/CuBoulder/express/blob/dev/modules/contrib/pathauto/pathauto.module#L1072

Can the user account be stripped of that before passing through insert or update?

**Comment by alexfinnarn** [comment]
I added a PR to remove the "users/[user:name]" pattern when Pathauto tries to create any alias.
