### ISSUE TITLE
Update exposed username filters to use Realname filter in all views that use that field

### ISSUE THREAD

**Issue by wturnbull** [CuBoulder/express#1830]
## Context

As an admin, when I went in to filter/search content by author, it displays zero results because the name listed with the content doesn't match what is recognized in the search by author field. 

## Process

1. Login to site as a SO, CE, EO, ADMIN
2. Click Content
3. Type "Wendy Turnbull" or "wendy" into the Author field
4. Content listed area says no content available. 
5. Type "wetu1300" into the Author field
6. Displays all content authored by "Wendy Turnbull"

## Expected result

Expected to see all content authored by "Wendy Turnbull" to display when entering "Wendy Turnbull" or "wendy" into the Author field. 

## Current result

Nothing displays when I enter the name that matches the authored by column - I have to use my identikey to display what is authored. 

## Possible Fix

Fix so it works for both identikey or name that displays under the author column (or at the least to display whatever matches).

## Screenshots

![screen shot 2018-01-24 at 1 15 12 pm](https://user-images.githubusercontent.com/1757082/35354900-ce23260e-0108-11e8-8502-eb54f3c74b6d.png)
![screen shot 2018-01-24 at 1 15 25 pm](https://user-images.githubusercontent.com/1757082/35354901-ce327514-0108-11e8-8602-9e78527de85d.png)
![screen shot 2018-01-24 at 1 15 35 pm](https://user-images.githubusercontent.com/1757082/35354902-ce40d906-0108-11e8-83c5-4cb68bccf69a.png)

----

**Comment by kreynen** [comment]
I configured this on https://www-test.colorado.edu/webcentral/admin/content to use just the RealName filter.  @kevincrafts thinks that's enough since that's all we display now.  https://www-test.colorado.edu/webcentral/admin/people already works with either real name or identikey.  The autolookup on the author field of nodes works too.  I'm not sure if this is an issue anywhere else.

**Comment by cathysnider** [comment]
### The User List at admin/people:
Technically (and in production), the user list at admin/people is not searchable for Real Name. It is searchable for Campus Published Email Address and IdentiKey user name.

**Example One** for user Alexander Henry Finnarn; Alexander.Finnarn@Colorado.EDU; alfi2595. 
'Henry' does not return our user, but 'alfi' does and 'finnarn' does.

**Example Two** for user Joanna Lea Bertrand; joanna.bertrand@Colorado.EDU; linebarg
Both 'line' and 'bert' properly return Jo. 'Lea' does not return anything. 

'kevin' returns both Kevins. 

'ow' returns Owen Paul Morrill
 
---
### The Content List at admin/content
The new functionality as implemented on www-dev works slightly differently. The functionality searches on name AS IT IS DISPLAYED

**Example One** for user Alexander Henry Finnarn; Alexander.Finnarn@Colorado.EDU; alfi2595. 
'Henry' DOES  return our user, but 'alfi' does not. 

**Example Two** for user Joanna Lea Bertrand; joanna.bertrand@Colorado.EDU; linebarg. 
'line' does not, 'bert' and 'lea' do. 

'kevin' returns only the Kevin that has logged in at the time of this test, i.e. Reynen but not crafts.

FAIL: Content whose users have no display name (i.e. owmo7772) have a blank Author field. Either Real Name or IdentiKey should display.

FAIL: The content list at admin/content should continue to be sortable by Title, Type, Author and Updated Date
 
https://www-dev.colorado.edu/p1d170898f1f/

![realnames](https://user-images.githubusercontent.com/638275/36320542-cbcd4a8a-1303-11e8-8509-b23b1abc3406.jpg)
