### ISSUE TITLE
Expandable Block: Blocks embedded within are stripped of titles

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1834]
## Context

Blocks that are embedded into an expandable block are stripped of their titles. 

## Process

Create two text blocks, both with titles. 
Add an icon to both with Block Designer
Create an Expandable Block and pull in both new blocks. 
Save the block. 

## Expected result

I expect the blocks to show their titles and icons. 

## Current result

Title and Icons are stripped out.

## Screenshots

![screen shot 2018-01-25 at 9 49 57 am](https://user-images.githubusercontent.com/638275/35401192-10303822-01b6-11e8-80b9-fa0cfa30247a.png)

----

## Links to Examples

https://www-test.colorado.edu/p1bde2411132/academics#tab_two-14

**Comment by kevincrafts** [comment]
Works as designed. There is a "hide block title" option that was selected in your example.

![screen shot 2018-01-25 at 10 00 48 am](https://user-images.githubusercontent.com/349713/35401504-efe62c92-01b6-11e8-803f-f0dbe56fad6f.jpg)
