### ISSUE TITLE
Newsletter bundle appearing twice in request section

### ISSUE THREAD

**Issue by wturnbull** [CuBoulder/express#1836]
## Context

The newsletter bundle appears twice under the Request Bundles section. 

## Process

1. Login to site as a SO, CE, EO, ADMIN or DEV
2. Click Add Content
3. Click Enable bundles for additional content types
4. Click Request tab

## Expected result

I would expect to see just one Newsletter bundle

## Current result

I'm seeing two newsletter bundles

## Screenshots

![screen shot 2018-01-25 at 10 15 32 am](https://user-images.githubusercontent.com/1757082/35402233-2be39624-01b9-11e8-9f43-88bffaf8f909.png)

**Comment by kreynen** [comment]
This not an issue with the code, but the way Newsletter is tagged for current and add-on, request-add-on, admin-add-on, etc
