### ISSUE TITLE
Add Stat for count of Full HTML blocks

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1840]
## Context

Full HTML blocks have been used for any unknown number of CSS tweaks tracking pixels.  We really have no idea how many of these are currently on sites.

SO's can't edit the body of a block using Full HTML like https://www.colorado.edu/summer/block/css-override/edit

![screen shot 2018-01-25 at 12 12 52 pm](https://user-images.githubusercontent.com/385234/35407470-4ac8ea3e-01c9-11e8-83d4-9c9e80ed4a26.png)

**Comment by alexfinnarn** [comment]
CuBoulder/lil_shrugger#123
