### ISSUE TITLE
Fatal Error when attempting to view Newsletter Revisions

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1842]
## Context

@ekellagher reported this.  I've confirmed the issue exists in prod.

Error: [] operator not supported for strings in cu_newsletter_preprocess_page() (line 94 of /data/code/modules/cu_newsletter_bundle/cu_newsletter_bundle-7.x-1.1.1/modules/custom/cu_newsletter/cu_newsletter.module).

Related: https://github.com/CuBoulder/express/issues/1792

**Comment by kevincrafts** [comment]
Can't reproduce locally.

**Comment by kevincrafts** [comment]
Fixed here https://github.com/CuBoulder/cu_newsletter_bundle/commit/df85f490eeff26320d24452a7a0743962f033cea#diff-6bc0a216f98b839ec59463e10eb42a78R94
