### ISSUE TITLE
Bug: Newsletter - enabling bundle places bundle display in two places

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1844]
## Context

Newsletter bundle appears on Request tab. 

When downloaded, the 'enable' button then appears in the Core tab and the Request tab. 

## Process

Spin up new test site.
https://www-test.colorado.edu/webcentral/admin/tools/sites/available

Login to site as a Dev
Go to Atlas and enable the Newsletter bundle. 
Go to Settings >> Bundles 
Check that Newsletter bundle appears on both Core and Request tabs. 

## Expected result

I expect the enabled bundle info to appear only on the Request Tab

## Current result

Newsletter Bundle info is now on both Core and Request tabs. Enabling one makes both 'ready to use'

**Comment by kreynen** [comment]
This is currently the expected behavior.  We need to change the Core display so it isn't Core + Enabled

Maybe change Core -> Available?  Sort Available to show Enabled
