### ISSUE TITLE
Define Scope of Work

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#1847]
I'm not sure of the scope of work here. I've looked at the current CU Boulder Help Scout modules in the Express repo and get the sense that the PHP integration would look for and store data about topic lists et al. that would appear as suggestions when you click the help icon.

As far as getting the data for when a user clicks on that link, I'm not sure if using PHP is needed if all it is doing is making a request to Help Scout and caching that data. Data could get stale, the cache doesn't clear, have to clear whole site cache when it breaks...stuff like that.

Resources:
CU Boulder Help Scout - http://websupport.colorado.edu/
Developer Docs - https://developer.helpscout.com/
Integrate or extend Drupal module - https://www.drupal.org/project/help_scout_beacon 
PHP SDK - https://github.com/helpscout/helpscout-api-php

**Comment by alexfinnarn** [comment]
Apparently, this has nothing to do with the beacon functionality. I'm still not sure which part of the API is supposed to be used in https://developer.helpscout.com/: help desk or docs?

**Comment by kreynen** [comment]
What I looked at when we were first evaluating Help Scout was https://developer.helpscout.com/help-desk-api/  and https://github.com/helpscout/helpscout-api-php.  I was hoping we could use https://developer.helpscout.com/help-desk-api/webhooks/ to populate the orgs knowing only the Website URL.  I thought that would normally be populated by the Beacon, but now that we have the Beacon working I see that it doesn't populate the Website URL field.    

I made you an admin in the Help Scout instance and opened https://github.com/CuBoulder/express/issues/1914, https://github.com/CuBoulder/express/issues/1915 and https://github.com/CuBoulder/express/issues/1916
