### ISSUE TITLE
Define Scope Of Work

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#1849]
The full feed in JSON or XML is all that the vendor can provide without additional development. To provide a filterable feed, we’d be inserting something in the middle again.  That service would suck in the full feed and then provides an endpoint that is filterable and the endpoints for the values of the filters.  We have no idea how often that would need to happen since we don’t know how often they are publishing jobs in the new system.
 
The HR contact (Jonathan Tarr) isn’t very technical.  The contact from Avature who was on the call took 2 weeks to provide the URL of the XML feed.
 
This can be written in either stand-alone PHP, a D7 module, a Drupal 7 bundle, a D8 module or Python. 
We can also host this wherever it makes sense.  On prem, Pantheon, Platform or AWS.

**Comment by alexfinnarn** [comment]
A feed link is stored in a private doc, but the main challenge here is to deal with a changing data set. 

Thoughts on sub-issues:
* Take the data feed locally and pull it in to see what the performance numbers look like. The sandbox site has too few entries.
* How to test this? I've setup testing using a fake API server in JS and I've also setup API Platform in PHP. Static files are also an option.
* See if CORS plays a role here. If the server doesn't allow cross-origin requests, then this has to be done on a server.
* Define environment to run on. With talk of switching hosting providers, it makes sense to try to stand this up on an option, preferably AWS or Platform.sh, and see how that goes with dev tooling and so forth. 
* Think about maintenance. Easiest to maintain would be an all JS solution.
* Try out only parsing so many nodes of the response via a stream. This can be done in node.js https://nodejs.org/api/stream.html.

**Comment by jbertrand** [comment]
[Department Career Site.xlsx](https://github.com/CuBoulder/express/files/1972771/Department.Career.Site.xlsx)

**Comment by jbertrand** [comment]
Production URL for avature site:
https://colorado.avature.net/PublicReports/1TmAFxZVlBWVfEHaI6eYvH1miWEwMQbz/raw/xml

**Comment by kevincrafts** [comment]
Demo of jobs feed bundle

https://www.colorado.edu/p1a4b5efcabc/

https://github.com/CuBoulder/cu_jobs_bundle

**Comment by kevincrafts** [comment]
The feed still contains sandbox urls, and some of the content is not necessarily fit for displaying.  For instance, departments include a unique ID number and abbreviations that are not accessible.
