### ISSUE TITLE
Update link to http://status.colorado.edu/ in status dashboard

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1861]
## Context

Currently links to https://universityofcoloradoboulder.statuspage.io/.  That was the URL before we registered the subdomain.  The longer url works, but it is long and cryptic compared to http://status.colorado.edu/ 

https://github.com/CuBoulder/express/blob/dev/modules/custom/express_status/express_status.module#L27

**Comment by kreynen** [comment]
Related to https://github.com/CuBoulder/express/issues/1708

**Comment by cathysnider** [comment]
Yep, this works. 
<div class="status-info">
<a href="http://status.colorado.edu" target="_blank">View status information</a>
 </div>
