### ISSUE TITLE
As a SM I would like to have fewer Site Owners and fewer inactive user accounts on Express sites

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1865]
## Context

We currently have two issues with Express sites:
1. Because of the permissions/roles structure, sites have too many Site Owners. This role was originally envisioned as a primary contact/decision maker for a site.
2. Too many people are granted access to a site and then stop logging in, leaving users that still have access.

## Proposed Solution

1. Determine a list of primary contacts for each site.
2. Roles should be Inactive, Edit Only, Site Editor, Temp Site Owner, Site Owner.
     * Inactive is an empty role with no permissions
     * Edit Only can only edit content/blocks and view reports. Cannot create or delete content/blocks/layouts.
     * Site Editor can create/edit/delete all content/blocks/layouts, add bundles, view reports..
     * Site Owner is configuration only permissions, such as active theme, site name/description, site homepage node, user invite, critical communications (from Web Express team), and site launch process (when available). 
3. Allow current Site Owners to self add Temp Site Owner role. Suggest max of 3, set max of 5.
4. Migrate all site owners to Site Editors.  Add new Site Owner role for Temp Site Owners.
5. Migrate all Content Editors to Edit Only.  Requires Site Owners to promote users to higher roles if needed.
6. Determine a period that a user has become inactive (for example, 3 months) - any user (except site owners) not logging in for the duration of this period will receive the Inactive role and other roles removed. This will trigger a new invite to be delivered that will allow them to re-establish their access to the site.  If user does not use invite during the allowed window, a site configuration user would need to send a new invite.
7. After a defined period (after each fall/summer term?) Inactive users will be removed from the site and any content would be re-assigned.
8. Provide instant validation/alert when assigning a user a role with elevated permissions.

**Comment by kreynen** [comment]
Related https://github.com/CuBoulder/express/issues/1799

**Comment by kevincrafts** [comment]
![image_uploaded_from_ios](https://user-images.githubusercontent.com/349713/36609830-7300cdc2-188b-11e8-93a1-63e2dee1e985.jpg)

**Comment by cathysnider** [comment]
https://docs.google.com/spreadsheets/d/1fJk-k9BUySz3a7tMpMvEKKRfcToGeER1MBLajKxFi6s/edit#gid=0

**Comment by kreynen** [comment]
The validation in the invite and forms makes it hard to test when there are > 5 site owners.  Using drush user-add-role "site_owner" [uid] allows you to add more than 5 people the SO role.  Then rolling back the schema of express in the system table can re-run the update hook to test moving users from site_owner -> site_editor when there are > 5 SOs.
