### ISSUE TITLE
As a SO/CE I want my block section background images to appear crisp when viewed on large displays

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1877]
## Context

Block sections currently have 3 breakpoints for loading background images: mobile, tablet, desktop.  The problem is that even loading the desktop breakpoint image sometimes is not large enough when viewing the site on a large monitor.

The largest size loaded will be 1500 pixels wide, but when viewed on a large monitor with a large browser window the scaling can result in a very pixelated image.

## Possible Fix

Create a extra wide breakpoint, which would load a larger (2000px) version of the image if the browser window is that large.

## Current Result
![screen shot 2018-02-06 at 11 11 14 am](https://user-images.githubusercontent.com/349713/35876132-94977838-0b2e-11e8-90a7-440ceb0a87a8.jpg)

## Expected Result

Exported as jpg:
![screen shot 2018-02-06 at 11 11 17 am](https://user-images.githubusercontent.com/349713/35876165-a4404a8a-0b2e-11e8-9f60-cdbf1f0dd95b.jpg)

Exported as 8bit png:
![screen shot 2018-02-06 at 11 11 22 am](https://user-images.githubusercontent.com/349713/35876180-ac1afc1e-0b2e-11e8-8e03-726a5123cfca.jpg)

**Comment by kevincrafts** [comment]
![lines](https://user-images.githubusercontent.com/349713/35984255-48d3f0dc-0cb1-11e8-993c-e25c062ddd49.jpg)

**Comment by cathysnider** [comment]
Saving here for testing:
https://www-dev.colorado.edu/p1e5160a0633/
