### ISSUE TITLE
Uninstall/Remove Quicktabs, Delete existing quicktab instances.

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1884]
## Context

We developed and launched a quicktab replacement. It's time to uninstall and remove existing quicktabs.

**Comment by cathysnider** [comment]
This Google Docs Spreadsheet lists the sites that have issues with Quicktabs.
https://docs.google.com/spreadsheets/d/12L_Qd4VNYBv2qE-1n1Z-2ZqlhznxMeA7x24OMshak6o/edit#gid=1771357329

Color Coding:
Green == fixed, i.e. their quicktabs were recreated as expandable
Yellow == nodes; i.e. their quicktabs are made of nodes, not blocks. They may need to get with a UX/AI person to help them re-think the best way to display the information.
White == either a LOT of quicktabs, or a site that should be communicated with first
