### ISSUE TITLE
As a FO, I would like to know what's happening next when I create a form

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1894]
## Context

From [FIT-826]

While the Webform module is easy enough to use once you've created a few, the initial form is confusing since it only shows the user the title and body with no explanation of what the next steps are.

**Comment by owenmorrill** [comment]
https://github.com/CuBoulder/cu_forms_bundle/pull/3

**Comment by kreynen** [comment]
Issue moved to [CuBoulder/cu_forms_bundle #38](https://github.com/CuBoulder/cu_forms_bundle/issues/38) via [**ZenHub**](https://www.zenhub.com/)
