### ISSUE TITLE
Colorbox does not work on mobile devices

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1896]
## Context

The mobile detection settings for colorbox keep it from working on mobile devices. Instead of having the colorbox image popup, the user is sent to view just the image file. Users are required to use their back button to continue browsing, and image captions are never displayed.

The colorbox settings are set to do this behavior on devices that report less than 480 pixels.  We should change this to be 320.

This cannot be tested within a desktop browser.

To test:

1. Create a photo gallery
2. View Gallery on mobile device
3. Click/press photo

## Expected Result
Photo should open in colorbox viewer

## Current Result
Clicking photo loads image file

**Comment by cathysnider** [comment]
Acceptance Criteria:
 - [ ] On smartphone, Colorbox opens for images inserted into Basic Pages
 - [ ] On smartphone, Colorbox opens for Photo Gallery images
 - [ ] On tablet, Colorbox opens for images inserted into Basic Pages (current behavior)
 - [ ] On tablet, Colorbox opens for Photo Gallery images (current behavior)
 - [ ] and on desktop

![colorboxgallery](https://user-images.githubusercontent.com/638275/36391368-6badfd40-1563-11e8-8fc4-94ac0a4b2175.PNG)

![colorboxpage](https://user-images.githubusercontent.com/638275/36391369-6bbd054c-1563-11e8-8be2-c619cbc9fa2c.PNG)
