### ISSUE TITLE
Move or Map Beacon site_url to Website URL

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1914]
## Context

We were under the impression that the Beacon data would populate the Conversation fields, but this is not currently happening.

![beacon website not populating field](https://user-images.githubusercontent.com/385234/36120581-e7c4ed84-1000-11e8-88db-e2e26bb5e315.png)

**Comment by alexfinnarn** [comment]
If the subject field is not that important for conversations like https://secure.helpscout.net/conversation/523994405/364?folderId=1414561 then it can be used to store data from the site and then update the tickets on a cron run using https://developer.helpscout.com/help-desk-api/conversations/update/#updating-custom-field-responses.

I think the concept of webhooks is weird and the note of "Webhooks are automatically deactivated if three or more events get discarded." sounds discouraging. 

The process would be to look through conversations with something in the subject field that notes the custom fields haven't been applied to that conversation: https://developer.helpscout.com/help-desk-api/search/conversations/#search-reference.

The returned conversations will be looped through adding the custom fields and removing the marker from the subject field.

The next time cron runs, the process is repeated. If needed, the cron job schedule can be adjusted to do this every few minutes.

**Comment by alexfinnarn** [comment]
The Beacon sends a "note" to the conversation object that looks like this JSON in the conversation response from the API.

```json
"threads": [
  {
    "id": 1424794534,
    "type": "note",
    "assignedTo": null,
    "status": "active",
    "createdAt": "2018-02-14T16:32:54Z",
    "openedAt": null,
    "createdBy": {
      "id": 198116,
      "firstName": "Joanna",
      "lastName": "Bertrand",
      "email": "joanna.bertrand@colorado.edu",
      "phone": null,
      "type": "user",
      "photoUrl": "https://d2ojpxxtu63wzl.cloudfront.net/static/e41d63b39be6566c5a34a153ff4ac4cc_471a9a6f71c0a5473c4ca62d784a291e09b8b52a68916a7d14c541ce32f4c590"
    },
    "source": {
      "type": "embed-form",
      "via": "user"
    },
    "actionType": null,
    "actionSourceId": null,
    "fromMailbox": null,
    "state": "published",
    "customer": null,
    "body": "<strong style=\"padding:0 0 5px 5px;\">Customer Information</strong><table cellpadding=\"5\" cellspacing=\"2\"><tbody><tr><td valign=\"top\" width=\"140\">user_email</td><td valign=\"top\">Annie.Brokaw@Colorado.EDU</td></tr><tr><td valign=\"top\" width=\"140\">roles</td><td valign=\"top\">authenticated user, administrator</td></tr><tr><td valign=\"top\" width=\"140\">site_name</td><td valign=\"top\">test site</td></tr><tr><td valign=\"top\" width=\"140\">site_url</td><td valign=\"top\">https://express1.lndo.site:444</td></tr></tbody></table><br><strong style=\"padding:0 0 5px 5px;\">Technical Information</strong><table cellpadding=\"5\" cellspacing=\"2\"><tbody><tr><td valign=\"top\" width=\"140\">IP Address</td><td valign=\"top\">128.138.65.189</td></tr><tr><td valign=\"top\" width=\"140\">Location</td><td valign=\"top\">Boulder, CO</td></tr><tr><td valign=\"top\" width=\"140\">Operating System</td><td valign=\"top\">Mac OS X 10</td></tr><tr><td valign=\"top\" width=\"140\">Browser/Version</td><td valign=\"top\">Chrome 63.0</td></tr><tr><td valign=\"top\" width=\"140\">Device</td><td valign=\"top\">Desktop</td></tr></tbody></table><br><strong style=\"padding:0 0 5px 5px;\">Site Information</strong><table cellpadding=\"5\" cellspacing=\"2\"><tbody><tr><td valign=\"top\" width=\"140\">Current Page</td><td valign=\"top\">https://express1.lndo.site:444/user/9/edit?pass-reset-token=MFrTeRrSEJtypLxA3UDvaxvtxEDEKqyTJiPEdQ0r5Cw</td></tr><tr><td valign=\"top\" width=\"140\">Searches</td><td valign=\"top\">def</td></tr></tbody></table>",
    "to": null,
    "cc": [],
    "bcc": [],
    "attachments": null,
    "savedReplyId": 0,
    "createdByCustomer": false
  }
```

In the `body` field, the structure is an HTML table that starts with

```html
<strong style=\"padding:0 0 5px 5px;\">Customer Information</strong>
```
Parsing the table could provide whatever information needed to update conversation fields like org levels.

Since those fields are located in a thread item, the first item in the thread with `source` of

```json
"source": {
  "type": "embed-form",
  "via": "user"
},
```

would be used to parse the table and extract the data.

**Comment by alexfinnarn** [comment]
For emails the source is different...

```json
"source": {
  "type": "emailfwd",
  "via": "user"
},
```

**Comment by alexfinnarn** [comment]
Somewhat of a success...

![screen shot 2018-02-15 at 4 30 56 pm](https://user-images.githubusercontent.com/3640707/36286583-a420a3d8-126d-11e8-808b-c56b5b203545.png)

**Comment by alexfinnarn** [comment]
This is done in https://github.com/CuBoulder/cu_helpscout_api already.
