### ISSUE TITLE
Help Scout beacon configuration breaks if site name contains some special characters

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1924]
## Context

A site name such as "Women's Rugby" will cause javascript errors with the beacon configuration

## Process

1. Login to site as a [ADMIN or DEV]
2. Set site name to Women's Rugby
3. Click Help

## Expected result

The beacon modal should open

## Current result

The beacon trigger should be visible at the bottom right corner of the window, and clicking the help link does not open the beacon modal

## Possible Fix

Strip special characters from site name.

**Comment by cathysnider** [comment]
Current Result: If site has apostrophe in its name, then 
1) there's a Help Scout Beacon in the lower right corner and 
2) the Help Link in Blue Toolbar opens a https://www.colorado.edu/webcentral/ in a new window
