### ISSUE TITLE
Tenon: Duplicate Search

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1927]
Because we include the search form twice (in one are for desktop users, and another for mobile users), the same form is rendered twice which is triggering Tenon errors:

Error /  priority 66%
This `id` is being used more than once.

Web Content Accessibility Guidelines (WCAG) 2.0, Level A: 4.1.1 Parsing

This `id` attribute value is being used more than once. If this `id` is being used to reference a UI control, that can cause issues for users with assistive technologies.

--

Error /  priority 100%
This field label is not unique.

Web Content Accessibility Guidelines (WCAG) 2.0, Level AA: 2.4.6 Headings and Labels

These field labels have identical text. Make sure that fields have unique labels. If you have a legitimate reason to reuse the label text, make sure that the different fields are grouped appropriately using a `&lt;fieldset&gt;`.

**Comment by kevincrafts** [comment]
Because the searches are hidden, I'm not sure this would actually be an issue, but it still gets reported by Tenon.

**Comment by alexfinnarn** [comment]
I approve but am not merging due to the release of 2.8.5
