### ISSUE TITLE
Tenon: Logo link contains same text for title and image alt text

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1929]
Error /  priority 100%
This link has a `title` attribute that's the same as the text inside the link.

(line: 569, 13)

This link has a `title` attribute that's the same as the text that's inside the link. This may lead to unnecessary verbosity for assistive technologies, and offers no benefits to users.

**Comment by kevincrafts** [comment]
This will be addressed with the new branding designs, but we can still fix this in our current designs.

**Comment by cathysnider** [comment]
@kevincrafts please merge dev into feature branch 1929 for testing.

**Comment by cathysnider** [comment]
Acceptance Criteria:
 - [ ] Title text removed from link on the Interlocking CU Logo
 - [ ] Title text removed from link on the Site Name
 - [ ] Interlocking CU graphic still has alt text of 'Home'

https://www-dev.colorado.edu/p15d2b750d09/
