### ISSUE TITLE
Add tabs to user page that shows a user's content and revisions

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1935]
## Context

This will be used by SOs when deciding when to block vs. delete users.  

The two tabs should appear in two places:
1)  on the dashboard ( /admin/dashboard ) showing the content that that particular user has authored and edited
2) on each user page ( user/% ) , so the Site Owner can easily assess who's been creating what content

**Comment by owenmorrill** [comment]
Getting realname involves loading the entire user object (user_load()) and isn't very performant. Might leave it as identikey if there's not an easy way to get the realname.

**Comment by owenmorrill** [comment]
Getting realname by using a simple db_query. https://github.com/CuBoulder/express/pull/2010/files#diff-10a036c9c6aaa56c2f31e853c8100fdaR82

**Comment by cathysnider** [comment]
https://www-dev.colorado.edu/p110695e960e

**Comment by owenmorrill** [comment]
Trying to use the same views with context filters for both dashboard and user/%user/%.

But I'm having trouble getting it all together. The 'users/identikey" stuff is causing issues with the menu routing with the context % in the view itself. Might have to write a new view instead of using the one for both.

**Comment by owenmorrill** [comment]
Blocks worked much better because of the uid in the view/url problem.

**Comment by cathysnider** [comment]
Acceptance Criteria:
 - [ ] All users see two Content Tabs on their Dashboard, Authored and Edited
 - [ ] Only Site Owners, Access Managers and Developers can access the /user/*/authored and /user/*/edited
