### ISSUE TITLE
As a SO/CE I want to create simple links/buttons that are more descriptive for screen readers

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1942]
## Context

Having "learn more/read more" links/buttons on a page are seen as accessible issues. While users can make the text in the links/buttons more descriptive, this can cause issues with the design/look of the page.

## Possible Fix

Add a shortcode that would allow users to create content that could be hidden in an accessible matter.  For instance a button that could display "Learn More" to regular users, but a screen reader could read "Learn more about Web Express bundles".

### Button Shortcode Example

`[button url="http://www.colorado.edu" color="blue"]Learn More [invisible]about pancakes and waffles[/invisible][/button]`

**Comment by cathysnider** [comment]
https://www-dev.colorado.edu/p19bdc03af8f/accessible-learn-more-buttons

**Comment by cathysnider** [comment]
Also https://www-dev-new.colorado.edu/p1e9b951042c/invisible-text
