### ISSUE TITLE
Tenon: Make 'Read More' links more descriptive

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#1943]
## Context

Article list pages and article list blocks contain read more links in the teaser views. Tenon flags these as errors (This link text is uninformative).

## Possible Fix

Repeat the title after the read more, but hide it in an accessible manner. Example:

`Read more <span class="element-invisible">about Household cleaners are almost as dirty as cars</span>`

**Comment by owenmorrill** [comment]
![two-read-more-links](https://user-images.githubusercontent.com/5008565/39449895-987d0064-4c86-11e8-8ede-2a8198d5f512.png)
![two-read-more-links-inspect](https://user-images.githubusercontent.com/5008565/39449898-99bccfae-4c86-11e8-86d6-f584e066c5de.png)

**Comment by jeor0980** [comment]
No errors related to the "Read More" link on Tenon
