### ISSUE TITLE
Add list of sites a user has a role on to user dashboard

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1972]
## Context

Initially, this can be added to https://github.com/CuBoulder/custom_webcentral_bundle.  Not sure if we want all sites to be able to tell a user what other sites they have access to or not.  That's really a question for @kevincrafts 

We want to test this for #1823 ASAP.  Homepage SOs and CE will start logging into Web Central using FedAuth and then navigating to the homepage.  They should only have to enter their username and password once.  If this works well, we'll consider having all users log into Web Central.

**Comment by owenmorrill** [comment]
https://www-dev-new.colorado.edu/p126dbda793b/admin/dashboard/

https://github.com/CuBoulder/custom_webcentral_bundle/pull/97

This has been rolled into the feature/95a in the webcentral bundle repo and is ready for review.
