### ISSUE TITLE
Add status report to PMM to report error if 0 or > 1 hosting modules are enabled.  Should only be 1

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#1979]
## Context

@jwfuller asked about this yesterday and then I ran into it when spinning up https://github.com/CuBoulder/express/blob/2523afdf1b257bd679d0253502c1f2529d60e422/tests/behat/README.md

Having both ng_hosting and travis_hosting enabled is problematic for a number of reasons.

**Comment by alexfinnarn** [comment]
With no hosting modules enabled...
![screen shot 2018-07-09 at 3 09 49 pm](https://user-images.githubusercontent.com/3640707/42476156-30665eea-838a-11e8-9bd7-b44b3e6b90a1.png)

One hosting module enabled...
![screen shot 2018-07-09 at 3 21 28 pm](https://user-images.githubusercontent.com/3640707/42476696-fc937e8e-838b-11e8-86bf-dd0a30647004.png)

Two hosting modules enabled...
![screen shot 2018-07-09 at 3 22 45 pm](https://user-images.githubusercontent.com/3640707/42476703-05804a36-838c-11e8-91f4-ab3e19bed04c.png)

**Comment by owenmorrill** [comment]
Reverted this commit. There's a problem with fresh install.

`WD php: Warning: array_merge(): Argument #2 is not an array in drupal_check_profile() (line 1189 of   [warning]
/sites/express/includes/install.inc).
WD php: Warning: array_merge(): Argument #1 is not an array in drupal_check_profile() (line 1189 of   [warning]
/sites/express/includes/install.inc).`
