### ISSUE TITLE
Worthless link on Bundle Request page

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#1994]
## Problem

on 'Enable Bundles - Request' page here at /admin/settings/bundles/list/request 
every bundle has a For-More-Information link that reads "Visit Webcentrals' page about bundle requests" . 
The link goes to the home page of Web Central. There is no link on the homepage to the "More Info About Requesting Bundles" page, leading to frustrated users and a bad user experience. 

## Options for Fixing

1. Change the link for all bundle descriptions to  'https://www.colorado.edu/webcentral/web-express-features/bundles-features/request-add-bundles

2. Change the link separately for each bundle description. (examples:)
  - Chemistry Title Bundle https://www.colorado.edu/webcentral/tutorial/v2/chemistry-title-bundle
  - LiveChat Bundle https://www.colorado.edu/webcentral/tutorial/v2/livechat-settings
  - Newsletter Bundle https://www.colorado.edu/webcentral/tutorials/newsletter-bundle

## Links to Examples

Any Web Express site is an example. Here are two:
https://www-test.colorado.edu/visit/admin/settings/bundles/list/request
https://www-dev.colorado.edu/p1673f10c844/admin/settings/bundles/list/request

**Comment by ekellagher** [comment]
Here is a spreadsheet for the bundles admin pages with current links and I am currently creating the content for linking to Help Scout Documentation
https://docs.google.com/spreadsheets/d/1Epgq-Z4Hr6rdrbDv1RU77vFI8t0R3mg5Imlm67H54WQ/edit?usp=sharing

**Comment by ekellagher** [comment]
If we correct these links to point to Web Central content pls use the links to the Bundles overview info in the Web Express Features section of the site and not the tutorial links

**Comment by jeor0980** [comment]
Related https://github.com/CuBoulder/express/issues/1114

**Comment by jeor0980** [comment]
Changed the link for all bundle descriptions to 'https://www.colorado.edu/webcentral/web-express-features/bundles-features/request-add-bundles'

**Comment by kreynen** [comment]
![screen shot 2018-06-05 at 11 26 34 am](https://user-images.githubusercontent.com/385234/40992828-144458ec-68b5-11e8-8d8d-28a1e4b7490a.png)

**Comment by alexfinnarn** [comment]
once again, I think #2434 should be done first.
