### ISSUE TITLE
Block Row Match Heights: is not working

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#1998]
Match Heights is intended to force all blocks to be the same height. The scenario it was designed to resolves is when blocks have background colors applied and there is only one block per column.

I created a block row with three text blocks. the middle text block has a background color (block theme) applied. When I check the match heights option in the block row block. the block titles of the three blocks are still not aligned.

![block row match heights](https://user-images.githubusercontent.com/16137919/37072517-3f1b9c56-217f-11e8-8abe-755c5f8f35dc.JPG)

Test Site:
https://www-test.colorado.edu/p1b5410d9c27/

**Comment by kevincrafts** [comment]
This is because the other two blocks do not have background colors. Adding a background color to a block adds padding.
