### ISSUE TITLE
As a SO I would like to add Math ML authoring text blocks to a page on my site.

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#2001]
In order to create semantically accurate math equations that are accessible to people of diverse abilities, it is imperative to leverage the power of MathML. MathML is a markup language that provides semantic understanding and proper syntax to assistive technologies like screen readers. 

The University Applied Math department would like to build a site that highlights articles that include math equations and it would be more accessible to be able to add Math ML blocks to their page that upload images of equations.

Links to info on Math ML
Princeton Drupal integration:
https://accessibility.princeton.edu/blogs/mathml-accessible-math-markup

Math ML Dev page
https://developer.mozilla.org/en-US/docs/Web/MathML/Authoring

Penn State info
http://accessibility.psu.edu/math/equations/

More Info on What Math ML is on Do It
https://www.washington.edu/doit/what-mathml

**Comment by kreynen** [comment]
This is a duplicate of https://github.com/CuBoulder/express/issues/1817
