### ISSUE TITLE
Valet can't use ajax that requires index.php?q= pattern

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#2006]
![screen shot 2018-03-08 at 1 00 06 pm](https://user-images.githubusercontent.com/3640707/37173407-c1c0abae-22d0-11e8-8f8a-5e10ec5fb090.png)

On the dev branch with hash of 3cc8f7b799cf3839f73158ee713b21eadf275b9b, I can't get the autocomplete to work. 

I'm pretty sure "admin/structure/views/view/express_layout_beans/edit" is the particular view that provides autocomplete functionality.

This might be my local Valet setup, but I'm not sure what's going on.

**Comment by kreynen** [comment]
http://express.test/index.php?q=admin doesn't work either, so I think the issue is that the Valet can't resolve anything using the index.php?q= pattern

**Comment by alexfinnarn** [comment]
On a default install, the `[BasicValetDriver]` serves the requests. You can use whatever driver you want, but for some reason, the Drupal fingerprint of looking for `file_exists($sitePath.'/misc/drupal.js')` doesn't load the `[DrupalValetDriver]`. I looked at Lando's configuration, thinking that would help but not when I tried.

**Comment by alexfinnarn** [comment]
CuBoulder/express-starter/issues/27
