### ISSUE TITLE
Add text and help to invite UI about new roles

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2018]
## Context

![invite_new_user___university_of_colorado_boulder](https://user-images.githubusercontent.com/385234/37532209-fce04f9e-2903-11e8-9fdc-af8582a9a870.png)

**Comment by alexfinnarn** [comment]
Help text taken from column 5 in https://docs.google.com/spreadsheets/d/1fJk-k9BUySz3a7tMpMvEKKRfcToGeER1MBLajKxFi6s/edit#gid=0

**Comment by cathysnider** [comment]
QA Review:
 - [ ] In-page text reads "Site Editor: This role is for site communicators who need to add new content pages, blocks and edits layouts."
 - [ ] Help link goes to https://www.colorado.edu/webcentral/tutorial/v2/inviting-site-editors

Looks good
