### ISSUE TITLE
Behat Test: Admin/Content and Toolbars

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2032]
This issue moves and renames two features

- cu_extended_content_search/cu_extended_content_search-admin_menu.feature to toolbars/toolbars.feature
- cu_extended_content_search/cu_extended_content_search-views.feature to content/content.feature

and ups the tests:

Toolbars
When I log into the website I should be able to see the correct toolbar menus and shortcuts.
Tests: check the toolbars for appropriate links for Devs, Admins, Site Owners, Content Editors and Edit My Contents.

**Content**
When I go to the Admin/Content page I should be able to view, sort and add content
Test: Devs, Admins and SOs get four tabs and 'Add content' link
Test: Content Editors get two tabs and and 'Add content' link
Test: Edit_My_Content editors get no tabs; no 'Add content' link
Test: an anonymous user should not be able to access the form for adding page content
Test: All authenticated users should see the additional fields for finding and sorting content

**Comment by alexfinnarn** [comment]
merged.
