### ISSUE TITLE
RSS Feed Permission issue: CEs and EMCs should not be able to add RSS feeds

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2058]
## Context

The RSS Feed Builder is limited to Devs, Admins, and Site Owners.

Neither "Content Editors" nor "Edit My Content" roles should be able to access the RSS Overview page or the RSS Feed Builder.

But they can.

## Process

Sample Site: https://www-dev.colorado.edu/p18aed8b8b30/

1. Login to site as a Content Editor and Edit My Content
2. Go to Settings page and verify that RSS Feeds is not a choice for you (https://www-dev.colorado.edu/p18aed8b8b30/admin/settings)
3. Now check RSS Overview: https://www-dev.colorado.edu/p18aed8b8b30/admin/settings/feeds/rss/overview
4. And go to RSS Feed Builder: Go to https://www-dev.colorado.edu/p18aed8b8b30/admin/settings/feeds/rss/add

## Expected result

You should see Access Denied. 

You should not be able to add another RSS feed

**Comment by kevincrafts** [comment]
Confused by this ticket. Was there a concern that Content Editors should not be able to create an RSS feed? It is defined in the module that they should be able to and I have never heard someone suggest that they should not be able to do this.

Also, I cannot access any of those pages with the Edit my Content role.

![screen shot 2018-03-26 at 9 29 55 am](https://user-images.githubusercontent.com/349713/37916270-a60f10f6-30d8-11e8-9a68-4657876c030c.jpg)

**Comment by cathysnider** [comment]
My mistake; I've updated the tests to to include the fact that the content_editor role can indeed create an RSS feed.
