### ISSUE TITLE
Update roles and permissions for cu_digital_campaign_bundle

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#2082]
https://github.com/CuBoulder/cu_digital_campaign_bundle

Steps:
- [x] Create a readme file if it doesn't exist. Also add a bit about what the bundle actually does.
- [x] Include a link to https://github.com/CuBoulder/express_documentation/blob/master/docs/creating_custom_bundles.md#releasing-custom-bundle-code in the bundle readme file. 
- [x] Browse through the steps mentioned in What Are Bundles, Creating Bundle Tests, and Releasing Custom Bundle Code.
- [x] Check for any roles on the bundle and update permissions.
- [x] Add at least one Behat test.
- [ ] Make sure Travis tests succeed at least once.
- [x] Update file structure to have bundle module at the root and other modules in their subdirectories.
- [ ] Make a release following release instructions.
- [ ] Make sure bundle has help links to any tutorials and that your changes don't affect those screenshots or instructions

**Comment by alexfinnarn** [comment]
Make sure to update tutorials since user information is being added to the embeds and screenshots won't be the same.

**Comment by alexfinnarn** [comment]
Add the LinkedIn embed by default on module install and update hook.
