### ISSUE TITLE
Update roles and permissions for cu_alumni_class_notes_bundle

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#2087]
https://github.com/CuBoulder/cu_alumni_class_notes_bundle

Steps:
- [x] Create a readme file if it doesn't exist. Also add a bit about what the bundle actually does.
- [x] Include a link to https://github.com/CuBoulder/express_documentation/blob/master/docs/creating_custom_bundles.md#releasing-custom-bundle-code in the bundle readme file. 
- [x] Browse through the steps mentioned in What Are Bundles, Creating Bundle Tests, and Releasing Custom Bundle Code.
- [x] Check for any roles on the bundle and update permissions.
- [x] Add at least one Behat test.
- [x] Make sure Travis tests succeed at least once.
- [x] Update file structure to have bundle module at the root and other modules in their subdirectories.
- [x]  [Make a release following release instructions.](https://github.com/CuBoulder/express_documentation/blob/master/docs/creating_custom_bundles.md#releasing-custom-bundle-code)
- [x] Deploy

**Comment by jeor0980** [comment]
Pull Request: https://github.com/CuBoulder/cu_alumni_class_notes_bundle/pull/1
