### ISSUE TITLE
Create a way to toggle the cloning of site owner/site editor

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#2089]

**Comment by kreynen** [comment]
The permissions for site_editor aren't completely configured, but I did remove some of the perms like inviting users.  You can see that site_editors lose this perm when the synch option isn't selected.

<img width="1349" alt="secure_permissions___university_of_colorado_boulder" src="https://user-images.githubusercontent.com/385234/38271765-93d27942-3744-11e8-8c62-033404a0a1da.png">

<img width="1345" alt="invite_perm_not_set" src="https://user-images.githubusercontent.com/385234/38271777-98659386-3744-11e8-86b1-03eb35dece34.png">

**Comment by kreynen** [comment]
<img width="1406" alt="screen shot 2018-04-03 at 1 54 04 pm" src="https://user-images.githubusercontent.com/385234/38272545-c41f9b64-3746-11e8-81d4-f9f0a15d3b49.png">

<img width="1315" alt="screen shot 2018-04-03 at 1 49 18 pm" src="https://user-images.githubusercontent.com/385234/38272553-c96d7b5e-3746-11e8-8768-6b494c7c1706.png">
