### ISSUE TITLE
Backstretch shouldn't allow full URLs

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2106]
## Context

We've seen this on a few sites where they've included a P1 value or non-https url in the Backstretch Context.  This is going to be a bigger problem when we can clone site instances.

<img width="911" alt="edit_context_sitewide___wardenburg_health_services" src="https://user-images.githubusercontent.com/385234/38003662-cc987078-31f5-11e8-8e20-72a32bdc3029.png">

<img width="1092" alt="whs_background_photo___wardenburg_health_services___university_of_colorado_boulder" src="https://user-images.githubusercontent.com/385234/38003780-6a5997ec-31f6-11e8-8a42-3163848358a0.png">

**Comment by cathysnider** [comment]
One say to solve this would be by hiding the domain and site name on the File Content Type page, since site builders just copy and paste the URL that they are shown. 
So, display "/node/530/backstretch"  and "/node/530/large" etc.
