### ISSUE TITLE
Start Centralize Dashboard on Web Central

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2119]
## Context

This is part of the transition to SAML.  We won't role this out until 3.0, but we want to start working with this now internally

![img_20180329_142748](https://user-images.githubusercontent.com/385234/38203616-0abe7882-365d-11e8-8676-ab0895cc6a59.jpg)

Features we can build now:

- My Sites (look up by role w/ link to edit Users and Content based on role
- Links to other, integrated services
- Forward to requested URL
- Web Central News (from a View)
- Integration with Status Page

The current flow for users that try to go directly to a page /admin/content would be to redirect the user through fedauth so they land on the unified dashboard on Web Central with a link back to /admin/content similar to how we explain the file node redirects.

![screen shot 2018-04-02 at 10 10 17 am](https://user-images.githubusercontent.com/385234/38203931-25a6e372-365e-11e8-9b51-b396a0dc9c16.png)

**Comment by owenmorrill** [comment]
![webcentraldash](https://user-images.githubusercontent.com/5008565/38330471-f651c6da-380d-11e8-9dfb-925156174368.png)

**Comment by kreynen** [comment]
Good start.  My feedback/suggestions...

- we don't want Login | Visit.  I know Crafts had that on his mockup, but there won't be a login on the individual sites.  If you send them to /user, they'd be going from this dashboard to the site's dashboard since they are already logged into the IdP... which I don't think makes sense to maintain 2 versions of basically the same thing.  That's why I was suggesting sending them to Content | Users | Configuration based on their roles, but that was just a suggestion.

- We can add Grouper groups for the different levels of Localist permissions we assign, but that would be an additional step that wouldn't work for Group Officers.  For now,  I think we should add buttons for the integrated services so that we can internally test the workflow of logging in through Webcentral.

- To test, we also want to get the File node type style messaging done early on.  So if I try to go to http://www.colorado.edu/admin/reports I end up here, but with a link go back to where I was originally going.  Eventually, this will need to be integrated with SAML and r403 redirection, but initially let's just use something like ?dashboard-destination= so the UI element is triggered.

- We should be showing the Site Name not the P1.  This is where I think we are going to need a detail or notes field in the Site Object in Atlas explaining why the site exists.  So site owners would see  something like the "Leeds School of Business - LIVE" and "Leeds School of Business - TEST OF NEW BUNDLE" in their list.

- We need to consolidate the amount of space the site list take up and focus on the search and pagination/sorting.  Even it the search isn't functioning yet, add the form element so everyone can get a better idea of the amount of space we are working with.  I think we are probably going to need to have full page for My Sites and a way for users to favorite/star the sites they want on their dashboard.  This may lead to importing sites as entities vs. working with the Atlas data directly especially since @jbertrand wants to show www-test sites as well.

- @ekellagher wants to show a list of Canvas classes, but I still don't have a URL for any class or any idea how many classes there would be.

**Comment by owenmorrill** [comment]
Since we are moving beyond the limits of express_dashboard, I've moved this into webcentral's custom bundle. 

https://github.com/CuBoulder/custom_webcentral_bundle/pull/75

Now we can easily build forms, pages, blocks, and place them via the template anywhere on the new dashboard.

<img width="1250" alt="webcentraldashv2" src="https://user-images.githubusercontent.com/5008565/38387736-0a968bb2-38d6-11e8-9b5f-c66aa876ee97.png">

**Comment by owenmorrill** [comment]
Depending on your role, you see different buttons:

<img width="896" alt="webcentral-editmyown" src="https://user-images.githubusercontent.com/5008565/38391464-87791c16-38e1-11e8-9790-8ece210823cc.png">
<img width="1033" alt="webcentral-sitecontact" src="https://user-images.githubusercontent.com/5008565/38391470-8a1bbf64-38e1-11e8-9e74-fad4fd9e8817.png">

**Comment by owenmorrill** [comment]
<img width="1236" alt="webcentralplaceholders" src="https://user-images.githubusercontent.com/5008565/38393606-8c31a050-38e8-11e8-8514-cbfca3f17e35.png">

**Comment by owenmorrill** [comment]
![screencapture-localhost-ld7-admin-webcentral-dashboard-2018-04-09-14_51_11](https://user-images.githubusercontent.com/5008565/38522329-7923a538-3c05-11e8-8018-6063462171cb.png)

**Comment by owenmorrill** [comment]
The sites entity has been created. I'm tweaking pieces to make sure we get all the right info for each site and then I'll be creating the cron task to run however many sites through at a time. Once that's up and running the dashboard is essentially at the MVP spot I want it to be.

**Comment by owenmorrill** [comment]
![webcentral-dashboard-update](https://user-images.githubusercontent.com/5008565/39266205-96d1e440-4886-11e8-9af6-b3a1470aa759.png)

**Comment by owenmorrill** [comment]
https://github.com/CuBoulder/express/issues/1823

**Comment by owenmorrill** [comment]
<img width="1288" alt="lookup" src="https://user-images.githubusercontent.com/5008565/39768739-6c2a61b0-52a7-11e8-92c6-9f7f82365941.png">

New site owner lookup at /lookup. Permission is "use user dashboard".

**Comment by owenmorrill** [comment]
https://github.com/CuBoulder/custom_webcentral_bundle/pull/79

Lookup and dashboard are now merged and in the webcentral bundle.

**Comment by owenmorrill** [comment]
https://github.com/CuBoulder/custom_webcentral_bundle/pull/79 has been merged.
