### ISSUE TITLE
Include Add-on Roles in initial invites

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2120]
## Context

![img_20180329_115657](https://user-images.githubusercontent.com/385234/38205575-5ce6787e-3664-11e8-9e1a-6b7c1f7f8197.jpg)

This will require updating the changes made for https://github.com/CuBoulder/express/issues/1469 too

**Comment by alexfinnarn** [comment]
![screen shot 2018-05-11 at 9 08 18 am](https://user-images.githubusercontent.com/3640707/39934068-ee0bb862-5501-11e8-8d60-a2a8db45c49f.png)

Site Editor has been added but not any add-on roles. Some of the add-on roles are in external bundles...

**Comment by alexfinnarn** [comment]
Including #2328 and #2329 in this issue.

**Comment by owenmorrill** [comment]
https://github.com/CuBoulder/cu_forms_bundle/pull/2 Has the form_manager addition.

**Comment by jeor0980** [comment]
No errors related to the "Read More" link on Tenon

**Comment by alexfinnarn** [comment]
Test site in LDAP mixed mode: https://www-test-new.colorado.edu/p1312d7fc8f8/

![screen shot 2018-05-21 at 4 42 46 pm](https://user-images.githubusercontent.com/3640707/40333509-06961ef6-5d16-11e8-8999-3f1ed9481a97.png)

**Comment by kreynen** [comment]
The AM and CM Add-on roles should only be able to be added to the invite when inviting SE.  You can't be a CE or EMC and have those admin level addon roles.   

I enabled the Forms and Digital Campaign Bundles on the test site, but those addon roles don't get added to the list of options.  Form Manager and Campaign Manger addon roles should be able to be added to any core role.

**Comment by alexfinnarn** [comment]
Even if you don't have a user, the invite email seems to grant the role when going to the invitation link.

**Comment by alexfinnarn** [comment]
The linked tutorial https://www.colorado.edu/webcentral/tutorial/v2/inviting-site-editors needs to be updated to reflect the add-on roles. 

I think a link to https://www.colorado.edu/webcentral/role-changes would make sense or a permanent version of the info on that page.

Also, something about how/when the user is created and guidelines for sending the email would be good to add.
