### ISSUE TITLE
Sites with cu_social_media_bundle show WYSIWYG feature as overridden

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2133]
## Context

![screen shot 2018-04-04 at 10 07 56 am](https://user-images.githubusercontent.com/385234/38321333-8fb0dd08-37f4-11e8-8b77-f3a01cb54670.png)

Related to https://github.com/CuBoulder/express/issues/2132

This made it difficult to catch https://github.com/CuBoulder/express/issues/2123 until it was causing issues in production.

I don't care if we alter the feature export to ingnore/exclude that value or configure all sites to have that value set to null it if cu_social_media_bundle isn't configured, but we cannot have critical features wrapped up in an overridden feature.  We just end up ignoring that because it is always overridden.

If we can't get the WYSIWYG feature to remain in its default state, we need to figure out another way to set those values and throwing an error if they are not in the expected state.

**Comment by kevincrafts** [comment]
There are a few other modules that also do this - the only way that I know of to stop this from happening is that all shortcodes are added to the core shortcode module and everyone gets all of them.  The other shortcodes that I know will cause this issue include Livestream and Countdown.

**Comment by alexfinnarn** [comment]
I used a Shortcode module function gather enabled shortcodes and merge into the shortcode settings list when Features is building.
