### ISSUE TITLE
As a authenticated user I want to see a better identifiable list of sites I have access to

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#2150]
## Alternate Title

Stop naming sites "University of Colorado Boulder"

## Alternate Title 2

When there are multiple instances of a site, instances need to have unique, recognizable names/identifiers rather than just a list of the site name.  

## Context

1. Every site when installed has the site name of "University of Colorado Boulder" - in some cases this name is changed but in others it is not (particularly for testing/training/sandbox sites.
2. When a site has multiple instances, the site name should not be changed to better identify the instance.   

What I want to prevent in someone logging into Web Central and seeing multiple sites with the same exact name in their list of sites.

**Comment by kreynen** [comment]
<img width="1099" alt="site_owner_lookup___web_central___university_of_colorado_boulder" src="https://user-images.githubusercontent.com/385234/41127379-f72e6bb2-6a67-11e8-8420-ccb43597e7b3.png">

Logging into https://www.colorado.edu/webcentral/lookup as osr-test-owner is an extreme example of this, but it is a problem now.

**Comment by kreynen** [comment]
We also have to be careful with sites that want "University of Colorado Boulder" as part of their sitename like https://www.colorado.edu/faculty/nakassis/ or the whole name like https://www.colorado.edu/beboulder/ and https://www.colorado.edu/

**Comment by owenmorrill** [comment]
How about: 

![sitename-path](https://user-images.githubusercontent.com/5008565/41374911-bad5a2ee-6f11-11e8-8c54-d8f14169482c.png)
