### ISSUE TITLE
Content Grids need URL cleanup

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2172]
## Context

![edit_content_grid__specialization_areas___masters_of_the_environment](https://user-images.githubusercontent.com/385234/38888978-76a0943e-423a-11e8-8134-5a3ca16c47d5.png)

These are strange in that you have to remove the /menv as well for the links to resolve to the correct path.

**Comment by cathysnider** [comment]
I think the little "Search" link should be moved over by the URL field. That way it will be more obvious to site builders. It's pretty easy to overlook it right now.
