### ISSUE TITLE
Provision new test users with roles on login

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2196]
## Context

Functional testing requires being able to login with as an authenticated user with the various roles.  New test users have been created. Now provision them with the proper roles in Web Express, so that when we sign on, they are ready to be used.

**Current OSR Test Users:**
USERNAME 		- ROLE
osr-test-owner	- site_owner
osr-test-content	- content_editor
osr-test-edit-own	- edit_my_content

**The new users are:**
USERNAME 		      -   ROLE
osr-test-site-editor  	- site_editor
osr-test-edit-only    	- edit_only
osr-test-access-mgr	- access_manager
osr-test-config-mgr	- configuration_manager

osr-test-form-mgr          - form_manager

They need to be added as test users on Web Express.

**Comment by kreynen** [comment]
We talked about this.  This is something anyone can do by following the process w/ OIT to get secondary identikeys.

**Comment by cathysnider** [comment]
Whereas I think the same person should be the primary owner of all our osr test accounts.

**Comment by cathysnider** [comment]
Users have been created as Secondary Accounts of sniderc. 
osr-test-config-mgr
osr-test-site-editor
osr-test-edit-only
osr-test-access-mgr
osr-test-form-mgr

**Comment by alexfinnarn** [comment]
conflicts with #814. It would be nice to get a "test_users" array in `cu_users_get_users` though.
