### ISSUE TITLE
Certain Users Can't Add CodeClimate or Travis CI Integrations To Projects

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#2200]
"You’re in an organization but not in its Owners group. In this case, you unfortunately won’t have administrative-rights to view this token."

Taken from https://github.com/CuBoulder/cu_advanced_site_building_bundle/settings/hooks/new?service=codeclimate

So, everyone has to be in the Owners group or something. People should try adding CodeClimate via the GitHub form to see which users can do so now.

**Comment by kreynen** [comment]
OSR now admins all of the bundles at the top of https://docs.google.com/spreadsheets/d/1vLn-TBSmwkMo3yJVHsPi1EKq81vmYywleLjlXELZwrk/edit#gid=0.  Still working on fixing Alumni/Alumni Notes and Geofield.
