### ISSUE TITLE
Get Valet To Work With Sauce Labs

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#2204]
Currently, the JS tests end up with a 502 bad gateway error when trying to access local sites via the Sauce Connect Proxy.

**Comment by alexfinnarn** [comment]
I was getting somewhere with ngrok, but then...

![screen shot 2018-04-25 at 12 39 26 pm](https://user-images.githubusercontent.com/3640707/39265907-c08ef09e-4885-11e8-94f1-aade9efa2dc8.png)

**Comment by alexfinnarn** [comment]
I got as far as `~/.valet/dnsmasq.conf` looping to localhost, 127.0.0.1. `man dnsmasq` is huge and I have no knowledge of any of this stuff.

**Comment by danmichaelo** [comment]
Hi, ended up here while googling "valet sauce labs". The fix for me was to add the option `--dns 127.0.0.1` to `sc` (sauce labs proxy).
