### ISSUE TITLE
Turn Highlight JS module into bundle

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#2209]
https://github.com/CuBoulder/highlightjs

The formatting only works when the text filter is in "Full HTML" mode so more work would have to be done to make this module useful in a repeatable context.

**Comment by alexfinnarn** [comment]
Steps:
- [ ] Create a readme file if it doesn't exist. Also add a bit about what the bundle actually does.
- [ ] Include a link to https://github.com/CuBoulder/express_documentation/blob/master/docs/creating_custom_bundles.md#releasing-custom-bundle-code in the bundle readme file. 
- [ ] Browse through the steps mentioned in What Are Bundles, Creating Bundle Tests, and Releasing Custom Bundle Code.
- [ ] Check for any roles on the bundle. This added a WYSIWYG shortcode, and those permissions are managed elsewhere.
- [ ] Update file structure to have bundle module at the root and other modules in their subdirectories.
- [ ] Make sure Travis tests succeed at least once.
- [ ] Make sure bundle has help links to any tutorials and that your changes don't affect those screenshots or instructions
- [ ] Make a release following release instructions.

**Comment by alexfinnarn** [comment]
helpful links...

CSS class names for languages: http://highlightjs.readthedocs.io/en/latest/css-classes-reference.html

Site where custom version of HighlightJS was downloaded from: https://highlightjs.org/download/

**Comment by alexfinnarn** [comment]
Now this needs a name to put up on GitHub.

Examples:
- code_syntax_highlighting_bundle => Code Syntax Highlighting Bundle
- csh_bundle =>  Code Syntax Highlighting Bundle
- developer_blog_bundle => Developer Blog Bundle
- code_syntax_wysiwyg => Code Syntax WYSIWYG Plugin
- other...

**Comment by alexfinnarn** [comment]
Also, here are the available styles: https://highlightjs.org/static/demo/

Currently, "Sunburst" is my top choice, and I tend to like the dark themes.

Others:
- Tomorrow Night Bright
- Androidstudio
- ...

**Comment by jeor0980** [comment]
Monokai, Hybrid, Tomorrow Night
