### ISSUE TITLE
A Look Into Digital Asset Management Solutions

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#2215]
After looking at https://docs.google.com/spreadsheets/d/1il0iiZVd8xThVF3xdhobGJxkOUMy2SpMtYpCvrw-RwI/edit?ts=5ae23a57#gid=0 and links from http://bits.ashleyblewer.com/blog/2017/08/09/collection-management-system-collection/ I've narrowed down the listed open source solutions that use either Python, PHP, or JavaScript as the backend language.

Top Tier:
- https://github.com/alchemy-fr/Phraseanet (still using Symfony 2 though)

Others:
- https://github.com/remyla/damas-core
- https://github.com/omeka/omeka-s
- https://github.com/MukurtuCMS/mukurtucms#system-requirements
- https://github.com/inveniosoftware/invenio
- https://github.com/collectiveaccess/providence
- https://github.com/artefactual/archivematica
- https://github.com/artefactual/atom

Still can look through if needed:
- FLOSS inventory http://pro.europeana.eu/page/floss-inventory
- COPTR http://www.digipres.org/tools/
- foss4lib https://foss4lib.org/packages
- Results of SAA Lone Arrangers Survey on software https://docs.google.com/spreadsheets/d/1LqsMtCj3A4vFAS_PmezLIqr9QRp3EGIRGjfA-GqogJs/edit#gid=1493595932

**Comment by kreynen** [comment]
Issue moved to [CuBoulder/dam #1](https://github.com/CuBoulder/dam/issues/1) via [**ZenHub**](https://www.zenhub.com/)
