### ISSUE TITLE
Embed path autocomplete is difficult to read

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2218]
## Context

This isn't critical because the user can look up the node ## and just type node/123 instead of using the autocomplete, but it would be nice if the width of the list was larger and/or the titles were truncated or reordered so that the node # always displays

![screen shot 2018-04-27 at 9 35 15 am](https://user-images.githubusercontent.com/385234/39371260-608394f0-49fe-11e8-80e2-8290d4da8d6e.png)

**Comment by alexfinnarn** [comment]
moved to https://github.com/CuBoulder/cu_digital_campaign_bundle/issues/47
