### ISSUE TITLE
Get embeds to match the who/when fields used in content/blocks

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2219]
## Context

![screen shot 2018-04-27 at 10 00 10 am](https://user-images.githubusercontent.com/385234/39372543-ef979292-4a01-11e8-83d0-ea1129c92cda.png)
![screen shot 2018-04-27 at 9 59 50 am](https://user-images.githubusercontent.com/385234/39372544-efaa790c-4a01-11e8-89c6-9f198eb594f1.png)
![screen shot 2018-04-27 at 9 59 39 am](https://user-images.githubusercontent.com/385234/39372545-efbc3f2a-4a01-11e8-9c5e-344bf6579c98.png)

**Comment by alexfinnarn** [comment]
moved https://github.com/CuBoulder/cu_digital_campaign_bundle/issues/50
