### ISSUE TITLE
Page title not aligned properly when breadcrumbs are hidden - Highlight Theme

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#2250]
## Context

When the Highlight theme is used and breadcrumbs are set not to display, the page title is not aligned properly to the left.

## Screenshots

![screen shot 2018-05-03 at 1 36 02 pm](https://user-images.githubusercontent.com/349713/39598874-42498fc0-4ed7-11e8-9b4a-d76b14fbeffc.png)

## Links to Examples

* https://www.colorado.edu/p1743f0dfecb/basic-page

**Comment by jeor0980** [comment]
Before:
![screen shot 2018-05-21 at 3 36 07 pm](https://user-images.githubusercontent.com/8441552/40331277-0cc85f2c-5d0d-11e8-9614-c13c55b083c4.png)

After:
![screen shot 2018-05-21 at 3 38 09 pm](https://user-images.githubusercontent.com/8441552/40331283-0fe8dbbe-5d0d-11e8-983a-8813c23eda0f.png)
