### ISSUE TITLE
STAT - Need new elements in Atlas for new roles

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2291]
## Context

SE being the top priority, but we need to be able to email users in the AM, CM, and FM roles too.

**Comment by alexfinnarn** [comment]
https://github.com/CuBoulder/express/blob/dev/modules/custom/atlas/atlas_statistics/atlas_statistics.inc#L65 really needs to change to reflect the actual role name. With the way MongoDB works, I think you'd have orphaned data in the users/emails arrays.

However, I and others have been confused as to what "site_contact" means but the code clearly maps it to site_owner.

**Comment by alexfinnarn** [comment]
https://github.com/CuBoulder/lil_shrugger/issues/350 for when these are added.

**Comment by alexfinnarn** [comment]
test site https://www-dev.colorado.edu/p1e38f6a685d/admin/config/development/atlas/statistics

**Comment by alexfinnarn** [comment]
merged into dev
