### ISSUE TITLE
When processing invites, remove users from less permissioned roles

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2307]
## Context

When a user is promoted from site_editor -> site_owner, they shouldn't retain site_editor.  Users should only have 1 the core roles; site_owner, site_editor, content_editor, edit_my_own.  Any time one of these roles are added, the other roles should be removed.

BUT ONLY THESE ROLES.  We do not want to remove roles when add-on roles are added.

I think this would be done in hook_user_update, but there may be other ways to accomplish this.

**Comment by alexfinnarn** [comment]
This only takes into account the user/edit role change screens. I'm not sure how the users are being promoted in other ways.
