### ISSUE TITLE
I should be able to invite content editors

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2328]
the invite page is missing Content Editor as a choice

Example: https://www-test-new.colorado.edu/music/admin/people/invite

![screen shot 2018-05-11 at 1 28 54 pm](https://user-images.githubusercontent.com/638275/39943263-8b139aae-551f-11e8-898a-db45daaaf36f.png)

**Comment by jeor0980** [comment]
Content editor, now known as `edit_only`, is hidden for the 2.90 release, so this is correct I believe.

**Comment by alexfinnarn** [comment]
also involves #2120

**Comment by alexfinnarn** [comment]
included in another PR.
