### ISSUE TITLE
I should be able to assign the Site Editor role

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2329]
As a site owner and access manager, the Site Editor role should appear in the list of assignable roles. 

https://www-test-new.colorado.edu/music/user/82/edit?destination=admin/people

![screen shot 2018-05-11 at 1 32 43 pm](https://user-images.githubusercontent.com/638275/39943442-1055ac34-5520-11e8-9f9c-c31a688a1dd3.png)

**Comment by alexfinnarn** [comment]
involves #2120

**Comment by kreynen** [comment]
Unlike the synch role option, there is no option to hide/show roles so until the role hiding code is removed, you can't test that in 2.9.0.  Removing the code to show all the roles will be one of the first changes committed to 2.9.1.
