### ISSUE TITLE
Undefined index: roles in cu_users_user_presave()

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#2331]
I've only seen this on https://www-test-new.colorado.edu/webcentral/admin/dashboard/user, but when I log in I see undefined indexes. It may just be my user, but that line doesn't check for if `$edit['roles']` exists so that should be a ternary statement with a blank array.

![screen shot 2018-05-14 at 9 13 06 am](https://user-images.githubusercontent.com/3640707/40006881-b1b5d790-5758-11e8-8409-555c8c69b0ab.png)

**Comment by owenmorrill** [comment]
Merged in with https://github.com/CuBoulder/express/pull/2327 and https://github.com/CuBoulder/express/pull/2332
