### ISSUE TITLE
Update cu_wysiwyg Shortcode Feature

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#2365]
A recent update to the feature leaves new sites with few shortcodes enabled. The previous code change took into account shortcodes that were already enabled when the feature was checked whereas a new site needs the hardcoded shortcode settings to actually enable the shortcodes on site install.

**Comment by cathysnider** [comment]
All shortcodes are enabled and work:
https://www-dev-new.colorado.edu/p1397812cec8/shortcodes-0
