### ISSUE TITLE
Article Grids don't wrap correctly

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2398]
An Article Grid of nine isn't laying out properly -- the last one is out of place.

Dev:
https://www-dev-new.colorado.edu/p1b8bf68cf47/article-grid
Test:
https://www-test-new.colorado.edu/p16c032fd019/article-grid
Prod:
https://www.colorado.edu/p1f4bca2b935/news/news-and-article-blocks/article-grids

![screen shot 2018-05-17 at 3 31 28 pm](https://user-images.githubusercontent.com/638275/40205019-bf40d612-59e7-11e8-894f-fb8193938c9d.png)

**Comment by kevincrafts** [comment]
The issue is not the number of articles, but that the article elements don't wrap correctly.
