### ISSUE TITLE
Remove Webforms from Find Content page and add VBO to Webform list

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#2424]
## Context

Since Webform has its own page, we can remove them from the Find Content page. 

But...

The Webform page has no VBO filter, so we should add one that would allow people to find/search webforms and perform some basic operations like change publish and form status settings.

**Comment by kreynen** [comment]
![content___web_central](https://user-images.githubusercontent.com/385234/41436517-27f15d00-6fdf-11e8-8965-ae0457a8d59b.png)

EO role with Web Form submissions access can not see the Webform tab.  Currently the node filter is their only way to access.

**Comment by cathysnider** [comment]
Same with Site Editors with Form Manager perms: they do not get the Webform Tab. They have to use node filter.
