### ISSUE TITLE
Simplify the Enable Process for Add-on Bundles

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2426]
## Context

When we initially wrote the multistep process for adding the bundle code to a site and then enabling it, there was a concern that the code might not get added for several minutes if Atlas was working on other tasks.  Now the email that the bundle has been added often arrives in my inbox before Drupal page is reloaded.

The multistep process for some bundles and not others is confusing since the average user doesn't really understand the difference.  This isn't helped by our current UI.

Instead of doing this in steps, we can add a ajax check to see when the code exits in the filesystem for the specific site and then move forward with the enable.

If the code doesn't get added in something like 60 seconds of pinging the server every 5, then show the same type of message we show now.

**Comment by alexfinnarn** [comment]
I would think #2434 would need to be done first to add the AJAX code to.
