### ISSUE TITLE
Simplify Profile Module Manager Tabs to Installed and Available

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#2434]
## Context

The current structure, display, and process is confusing.

Reduce to Installed and Add tabs.  Add tabs include all non-installed bundles.
<img width="716" alt="screen shot 2018-05-22 at 4 43 35 pm" src="https://user-images.githubusercontent.com/349713/40394101-4a88d53a-5ddf-11e8-8eaa-ed47e4ffa53b.png">

<img width="716" alt="screen shot 2018-05-22 at 4 42 58 pm" src="https://user-images.githubusercontent.com/349713/40394092-3d2a2d3a-5ddf-11e8-8e50-87e21b573b88.png">

**Comment by alexfinnarn** [comment]
I still see the "Admin" tab which looks different than the other two tabs.

<img width="820" alt="screen shot 2018-06-25 at 11 38 18 am" src="https://user-images.githubusercontent.com/3640707/41860308-5dc0575c-786c-11e8-9e21-8cb5274f68ed.png">
