### ISSUE TITLE
Some launched sites are white screening on the module page

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2437]
Status Reports shows error:
"Profile Module Manager: Some required modules either not enabled or extra modules are enabled. Check webform"

![screen shot 2018-05-23 at 9 03 49 am](https://user-images.githubusercontent.com/638275/40433109-73740ee0-5e68-11e8-9d09-90cef1d509a9.png)

We're instructed to disable to webform module for these sites. However, going to admin/modules throws a white screen. 

Sites include launched and installed:
https://www.colorado.edu/studentgroup/ostem
https://www.colorado.edu/jtc
https://www.colorado.edu/p15f35566de9
https://www.colorado.edu/p1dfd2f3682f
https://www.colorado.edu/p19d40aabbf0
https://www.colorado.edu/p1fdf27700b0
https://www.colorado.edu/p1faa50f4a68
https://www.colorado.edu/p1f49fdbf202
https://www.colorado.edu/p19af0cc00a2
https://www.colorado.edu/p147f2b8483e

![screen shot 2018-05-23 at 9 02 47 am](https://user-images.githubusercontent.com/638275/40433128-810545e2-5e68-11e8-9a8e-c9538d7bbcf2.png)

**Comment by jwfuller** [comment]
```
Error: Uncaught exception 'Error' with message 'Call to undefined function webform_admin_type_list()' in /data/code/profiles/express/express-2.9.0/modules/contrib/webform/webform.module:46

Stack trace
in webform_help called at /data/code/cores/drupal/drupal-7.57/includes/module.inc (926)
in module_invoke called at /data/code/cores/drupal/drupal-7.57/modules/system/system.admin.inc (866)
in system_modules called at /data/code/cores/drupal/drupal-7.57/includes/form.inc (844)
in drupal_retrieve_form called at /data/code/cores/drupal/drupal-7.57/includes/form.inc (351)
in drupal_build_form called at /data/code/cores/drupal/drupal-7.57/includes/form.inc (131)
in drupal_get_form called at /data/code/cores/drupal/drupal-7.57/includes/menu.inc (527)
…execute_active_handler called at /data/code/cores/drupal/drupal-7.57/
index.php (21)
```

**Comment by owenmorrill** [comment]
This was fixed by updating the express repo's version of the webform module. Some files went missing during the 2.9.0 update and we added them back in temporarily to correct this.

**Comment by cathysnider** [comment]
Fixed
