### ISSUE TITLE
Stop converting https links to http in newsletters

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#2480]
## Context

Before we switched to https everywhere, all https links in newsletters were converted back to http.  We no longer need this conversion.

**Comment by kreynen** [comment]
Issue moved to [CuBoulder/cu_newsletter_bundle #30](https://github.com/CuBoulder/cu_newsletter_bundle/issues/30) via [**ZenHub**](https://www.zenhub.com/)
