### ISSUE TITLE
Form creators don't have access to expose a form as a block

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#2482]
## Context

The expose form as block field is tied to the administer blocks, administer site configuration, and some panels permission.

I can't think of any reason why we would limit this field, so I suggest altering the access to the field to also include the permission of editing webform components.

**Comment by cathysnider** [comment]
Example: https://www-test-new.colorado.edu/p1c2c568a867/content/daisys-webform

Under Edit Webform >> Form Settings >> Advanced Settings, there should be a checkbox "Available as block"

![saveasblock](https://user-images.githubusercontent.com/638275/40945746-7bb55c7c-6817-11e8-9395-ce054a1fdfa4.jpg)

**Comment by kevincrafts** [comment]
https://github.com/CuBoulder/cu_forms_bundle/pull/7
