### ISSUE TITLE
Landing pages for site types like /labs, /centers

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2484]
## Context

http://colorado.edu/studentgroups exists, but redirects to http://sofo.colorado.edu/SOFOsdg.php 

https://www.colorado.edu/labs
https://www.colorado.edu/centers

And potentially https://www.colorado.edu/libguides

https://www.colorado.edu/webcentral/support/website-request/url-standards

**Comment by jbertrand** [comment]
Would like to have landing pages for all our URL patterns that have the ability to search and show a list of sites under that URL pattern

**Comment by kreynen** [comment]
Issue moved to [CuBoulder/custom_homepage_bundle #176](https://github.com/CuBoulder/custom_homepage_bundle/issues/176) via [**ZenHub**](https://www.zenhub.com/)
