### ISSUE TITLE
Bug: User List paginates in weird way for non Web Express team

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2485]
The addition of more OSR-Test-Users has increased the size of the user list, such that it paginates in a very weird way for non Web Express Team people. 

Note that this is difficult to duplicate if you are on the Web Express team as you see the entire list in a normal way.  However, the WebExp team members are hidden for non-team members, so they get a blank first page and a populated second page.

## Current result

**First page:**

![screen shot 2018-06-04 at 10 54 33 am](https://user-images.githubusercontent.com/638275/40930900-493386b0-67e6-11e8-931d-356bd5336c08.png)

**Second Page:**

![screen shot 2018-06-04 at 10 54 47 am](https://user-images.githubusercontent.com/638275/40930925-5b1386b4-67e6-11e8-8aed-c46310867ca0.png)

## Links to Examples

https://www-dev-new.colorado.edu/p1f6e3513b38/user?destination=admin/people

**Comment by kevincrafts** [comment]
Closing as we will not be hiding users for much longer per Kevin R.
