### ISSUE TITLE
Bug: Form Manager not showing in list of available roles

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2486]
The forms bundle has been enabled, but the Forms Manager role is not showing up in the list of roles that can be added. 

![needformmgr](https://user-images.githubusercontent.com/638275/40934785-2913c194-67f3-11e8-86f5-69e5f7271add.jpg)

Login as osr-test-owner

https://www-dev-new.colorado.edu/p1f6e3513b38/user?destination=admin/people

**Comment by cathysnider** [comment]
Never mind; Edit Only is a temp role.

**Comment by kreynen** [comment]
This is fixed in https://github.com/CuBoulder/express/issues/2489
