### ISSUE TITLE
Inviting Users: The EditMyContent role should be able to have Campaign Mgr and Form Mgr

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2489]
Same as Site Editor can have Access Mgr, etc, the EMC role can have add ons of Campagn Mgr and Form Mgr. 

This screenshot shows the add on roles for Site Editor. Edit My Content needs Campaign Manager and Form Manager to display when radio button is clicked. 

![editmycontentinvites](https://user-images.githubusercontent.com/638275/40945201-eedee0ea-6814-11e8-8edf-5177e10a7f90.jpg)

**Comment by kevincrafts** [comment]
![screen shot 2018-06-07 at 4 13 51 pm](https://user-images.githubusercontent.com/349713/41129370-f5745f8c-6a6e-11e8-836c-fd472a0a2ce8.png)

**Comment by cathysnider** [comment]
We're doing the role addition in a different way than above, so this isn't as relevant. In our current iteration of role assignment, EMCs can be given all the add-on roles. So, it works.
