### ISSUE TITLE
Bug: Form Managers cannot see who they've assigned to their site

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2493]
A form manager can allow form viewers and can add form owners using the user entity reference: type a name in the field and the matching ones come up. 

However, when they return to their form to add another, or to see who they've given access to, they do not see the person's name or identikey, instead they see 'Restricted Access' and the user ID. 

Form Managers should be able to see the name(s) of the persons who have access to their form.

https://www-test-new.colorado.edu/p1c2c568a867/

![restrictedaccess](https://user-images.githubusercontent.com/638275/40996106-3c417a2e-68be-11e8-9c70-37e0d01bea49.jpg)

**Comment by owenmorrill** [comment]
With the last ticket merged in, this is only happening for edit my own roles.
