### ISSUE TITLE
Varnish Cache Timeout not being set correctly

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2498]
## Context

https://github.com/CuBoulder/atlas/blob/release/2.1.5/atlas/templates/settings.php#L159
https://github.com/CuBoulder/atlas/blob/release/2.2.0/atlas/templates/settings.php#L149

https://github.com/CuBoulder/express/commits/dev/modules/contrib/varnish

![doug_abraham_appointed_as_new_interim_cupd_chief___cu_boulder_today___university_of_colorado_boulder](https://user-images.githubusercontent.com/385234/41047606-2c7b3966-696a-11e8-94ed-9f6c815debdd.png)

**Comment by kreynen** [comment]
There is no longer a 3 hour expiration being set in varnish on old prod. I can't tell if this is working on new prod because I can't see the necessary headers.

Layout and block edits trigger the full site purge, but Context saves do not fire a full site purge in varnish.  

The result is context changes will never show up on a site until one of the other conditions that purges varnish for that site happens.

The easiest way to experience this is to place a block via context and then toggle the content between disabled/enabled.  I added a block to the bottom of https://www.colorado.edu/webcentral/web-express-support, then disabled the context.  

Authenticated users no longer see the block, but anonymous users will see it until a node, block or layout save happens... or someone updates a node/block/layout on the homepage.

I think content editing on the homepage is really the only thing making it appear as if varnish is configured correctly.

So we are currently;
- over clearing with every node/block/layout save on every site
- over clearing by x1000 on every node/block/layout save on the homepage
- under clearing based on a standard timeout (at least on old prod)

**Comment by jwfuller** [comment]
Object expiration in varnish seems to be working correctly.

Relevant headers are `Cache-Control` and `Age`

```
$ curl -IL https://www-dev.colorado.edu/webcentral/test-5
HTTP/1.1 200 OK
Server: Apache
X-Hostname: wwebdev2.int.colorado.edu
X-Content-Type-Options: nosniff
X-Drupal-Cache: MISS
Expires: Sun, 19 Nov 1978 05:00:00 GMT
Cache-Control: public, max-age=600
X-Content-Type-Options: nosniff
Content-Language: en
X-Frame-Options: SAMEORIGIN
X-Generator: Drupal 7 (http://drupal.org)
Link: <https://www-dev.colorado.edu/webcentral/test-5>; rel="canonical",<https://www-dev.colorado.edu/webcentral/node/8>; rel="shortlink"
Etag: "1528489409-0"
Last-Modified: Fri, 08 Jun 2018 20:23:29 GMT
Vary: Cookie,Accept-Encoding
Content-Type: text/html; charset=utf-8
X-Backend: wwebdev2_express
Date: Fri, 08 Jun 2018 20:30:19 GMT
X-Varnish: 1963534739 1963534504
Age: 410
Via: 1.1 varnish
Connection: keep-alive
X-Cache: HIT
X-Varnish-Server: 2
Set-Cookie: f5_persistence=2719000768.20480.0000; path=/; Httponly; Secure


jafu6031@OSR-WEB-L-001 ~/repos/atlas (release/2.2.0)
$ curl -IL https://www-dev.colorado.edu/webcentral/test-5
HTTP/1.1 200 OK
Server: Apache
X-Hostname: wwebdev2.int.colorado.edu
X-Content-Type-Options: nosniff
X-Drupal-Cache: MISS
Expires: Sun, 19 Nov 1978 05:00:00 GMT
Cache-Control: public, max-age=600
X-Content-Type-Options: nosniff
Content-Language: en
X-Frame-Options: SAMEORIGIN
X-Generator: Drupal 7 (http://drupal.org)
Link: <https://www-dev.colorado.edu/webcentral/test-5>; rel="canonical",<https://www-dev.colorado.edu/webcentral/node/8>; rel="shortlink"
Etag: "1528490022-0"
Last-Modified: Fri, 08 Jun 2018 20:33:42 GMT
Vary: Cookie,Accept-Encoding
Content-Type: text/html; charset=utf-8
X-Backend: wwebdev2_express
Date: Fri, 08 Jun 2018 20:33:42 GMT
X-Varnish: 1963534822
Age: 0
Via: 1.1 varnish
Connection: keep-alive
X-Cache: MISS
X-Varnish-Server: 2
Set-Cookie: f5_persistence=2719000768.20480.0000; path=/; Httponly; Secure
```
