### ISSUE TITLE
Bug: Administrator role cannot edit users who have Form Manager role

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2530]
Our Admins can edit users who have any role -- Except when that user has the add-on role of Form Manager. Then the Admin cannot. 

https://www-test-new.colorado.edu/p1d915dcaeab/user

![admineditfm](https://user-images.githubusercontent.com/638275/41255829-149222aa-6d85-11e8-91bc-7bf9229a7ff8.jpg)

**Comment by jeor0980** [comment]
Same goes for developers and site_owners. Is there any other role that needs this permission as well?

**Comment by cathysnider** [comment]
Access Manager role is the other add on role that needs to be checked.
