### ISSUE TITLE
Bug: Form Managers should be able to clear form submissions

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2532]
Form Managers should have full form permissions, matching that of Site Owner, and that includes clearing form submissions.

This permission needs to be added to the to Form Manager role. 

**Site Owner: Can clear form submissions**
![clearsiteowner](https://user-images.githubusercontent.com/638275/41257179-2a08f254-6d89-11e8-8cd7-b3dc6536edad.jpg)

**Form Manager: Cannot clear form submissions**
![clearformmgr](https://user-images.githubusercontent.com/638275/41257223-4a6e62ae-6d89-11e8-8f65-46918d7c7535.jpg)

**Comment by jeor0980** [comment]
The permission to expose this is `delete all webform submissions`

**Comment by cathysnider** [comment]
Verifying on a beta test site: Form Managers have the ability to clear submissions on the forms they own.
