### ISSUE TITLE
Phone icon shows up on person page even if phone number is empty

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#2548]
## Context

The formatting of a phone number was happening even if the field was blank, resulting in a phone icon with no additional content.

![image001](https://user-images.githubusercontent.com/385234/41365903-e4071df6-6ef7-11e8-86a3-dfdc584702b7.jpg)

## Process

Create a person without a phone number.

## Expected Result

The phone icon should not appear

## Current Result

A phone icon appears

**Comment by cathysnider** [comment]
Totally fixed:
https://www.colorado.edu/admissions/connect/counselors

![phoneicon](https://user-images.githubusercontent.com/638275/41626218-c8e14264-73d8-11e8-8db2-18f4268a36f3.jpg)
