### ISSUE TITLE
Role Text Tweak: Add '(Add-on Role)' to Campaign Mgr and Form Mgr

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2566]
On the Edit User page user/xxx/edit
The way Access Mgr and Config Mgr have. 

Example:
https://www-prod-new.colorado.edu/summer/
![screen shot 2018-06-14 at 2 20 39 pm](https://user-images.githubusercontent.com/638275/41436306-7e0a62c8-6fde-11e8-8f77-bed811d1dfc7.png)

**Comment by kevincrafts** [comment]
Only developers and administrators see this

**Comment by cathysnider** [comment]
It was an Administrator that brought it to my attention as something that should be.

**Comment by jeor0980** [comment]
https://github.com/CuBoulder/express/commit/eb3fc4eb8fd37c04c5d65ef3c9ae67f20cb57ea0

**Comment by cathysnider** [comment]
Fixed

![screen shot 2018-06-18 at 12 28 12 pm](https://user-images.githubusercontent.com/638275/41554802-231d2cf2-72f3-11e8-852f-aa59fc979fc5.png)
