### ISSUE TITLE
Role combo problem: Campaign Mgr + other role = can't edit the user

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2567]
When a Site Owner or Administrator adds the Campaign Manager on to another role (SE, CE, EMC) then the SO/Admin loses the ability to further edit that person's roles. 

Note that the Edit link has disappeared: 

![campaignmgr](https://user-images.githubusercontent.com/638275/41475205-58e8b448-707b-11e8-936c-6fced79019b7.jpg)

See any of the New Prod beta sites, such as https://www-prod-new.colorado.edu/cmci/

**Comment by kevincrafts** [comment]
This is most likely due to no roles having permissions to edit campaign managers.

**Comment by jeor0980** [comment]
Fixed with this PR https://github.com/CuBoulder/cu_digital_campaign_bundle/pull/58
