### ISSUE TITLE
Linkcheck Scanning isn't being enabled on content types when SEO Bundle is enabled

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2575]
## Context

I'm not sure what happened here, but there only reference to a variable like linkchecker_scan_node_page is https://github.com/CuBoulder/express/blob/d1d58b1cb26d402a9e7f4fa1a8913a148add553e/modules/contrib/linkchecker/linkchecker.test#L38

**Comment by alexfinnarn** [comment]
<img width="750" alt="screen shot 2018-07-03 at 5 01 57 pm" src="https://user-images.githubusercontent.com/3640707/42244395-db8f3794-7ee2-11e8-83f3-37e42ec590e3.png">

They moved it to the damn content type settings.

**Comment by alexfinnarn** [comment]
and they definitely want `linkchecker_scan_nodetypes` deleted: https://github.com/CuBoulder/express/blob/dev/modules/contrib/linkchecker/linkchecker.install#L489

**Comment by alexfinnarn** [comment]
Should re-export https://github.com/CuBoulder/express/blob/dev/modules/features/cu_linkchecker/cu_linkchecker.strongarm.inc#L214 since that variable was deleted.
