### ISSUE TITLE
As an SO, I want to see who holds what Add-on role on my site

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2576]
I'd like to be able to sort by all the Add-on roles, not just Form Manager. 
Add Access Manager and Configuration Manager.
Add Campaign Manager when the Digital Campaign bundle is enabled. 

![screen shot 2018-06-15 at 1 02 56 pm](https://user-images.githubusercontent.com/638275/41485238-fcfca2c6-709c-11e8-9c27-d1db79d4ad3b.png)

**Comment by kreynen** [comment]
Easy fix.  Those roles need to removed from https://github.com/CuBoulder/express/blob/dev/modules/custom/express_permissions/express_permissions.module#L951
