### ISSUE TITLE
Run atlas statistics every 4 hours

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express#2577]
## Context

We want better resolution from this data and are no longer concerned about being able to deal with the volume.

https://github.com/CuBoulder/express/blob/dev/modules/custom/atlas/atlas_statistics/atlas_statistics.module#L26

**Comment by alexfinnarn** [comment]
<img width="1064" alt="screen shot 2018-07-05 at 1 28 24 pm" src="https://user-images.githubusercontent.com/3640707/42338304-5c369c28-8057-11e8-8ed9-476d144f1604.png">

Cron seems to run fine and I see the change reflected in the Elysia Cron settings on "admin/config/system/cron".
