### ISSUE TITLE
Remove SRC test and staff accounts on logout/cron

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2586]
## Context

Once https://github.com/CuBoulder/express/issues/814 is in place, we want to remove our accounts from sites unless we are playing a role in the site's development.  If a dev logs in as the SO test account and creates a test page to confirm something is or is not working, they should delete the node before logging out.

If the "user has no content" report comes back clean on logout, the user account should be deleted. 

Unfortunately, we can't rely on users to log out, so we also need to run a cleanup on cron.

**Comment by alexfinnarn** [comment]
I think it is important to not delete a user if they are logged in even if they don't have any edits on the site.

**Comment by kreynen** [comment]
Yike.  Right now the way https://github.com/CuBoulder/express/blob/ead4aa60c5541655dc068ac4e569870c57862bc1/modules/custom/cu_inactive_users/cu_inactive_users.module#L476 is written, I think this would log developers out every 5 minutes unless they create a node. 

Related https://github.com/CuBoulder/express/issues/2713

We should probably tie this into the function that truncates the sessions at 2AM... though I'm not finding that code right now.
