### ISSUE TITLE
"Enable' bundle button should be different color than 'Add bundle' button

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2596]
Background: 
Bundles are added by clicking the 'Add bundle' button. Once the bundle downloads, the text of the button changes from 'Add bundle' to 'Enable.' The color of the button does not change. 

This means that visually, it is difficult to immediately spot that anything happened. 

I suggest that the color of the button should also change, to make it more obvious that the bundle is ready to be enabled.  Let's use Green for Go. 

![enablebutton](https://user-images.githubusercontent.com/638275/41670817-7df1c900-7472-11e8-93fe-2504b1ddf6a5.jpg)

**Comment by kreynen** [comment]
This is being completely reworked in https://github.com/CuBoulder/express/issues/2427
