### ISSUE TITLE
Deleting QuickTabs: some issues when doing so

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2600]
Some problems arise when uninstalling the QuickTime module on a site. These may or may not be issues that we want to fix.

# Action

https://www.colorado.edu/demos/cathys-sandbox/
On my sandbox site, I turned off all QuickTabs modules
![screen shot 2018-06-20 at 12 44 21 pm](https://user-images.githubusercontent.com/638275/41678266-db2165a8-7487-11e8-9e2d-529a7ffc5edd.png)

# Results

On this page, the block titles still appear:
https://www.colorado.edu/demos/cathys-sandbox/blocks/quick-tabs
Hovering over the block produced that little widget with editing controls: 
![quicktabscleanup1](https://user-images.githubusercontent.com/638275/41678165-97805e80-7487-11e8-972f-86f65e5b01e2.jpg)

On Blocks Admin, the bean wrappers show up. The system no longer knows what type of block these are. It used to say Quicktab.
![quicktabscleanup2](https://user-images.githubusercontent.com/638275/41678709-089145a2-7489-11e8-857a-3251f05a7372.jpg)

The placement method -- Page Layout or Context -- still shows the block
https://www.colorado.edu/demos/cathys-sandbox/node/258/layout
![screen shot 2018-06-20 at 12 56 26 pm](https://user-images.githubusercontent.com/638275/41678822-75f5200a-7489-11e8-95f2-c13247f94a1f.png)
![screen shot 2018-06-20 at 1 00 24 pm](https://user-images.githubusercontent.com/638275/41679005-09715bbe-748a-11e8-8a5f-880e23ce4291.png)

**Comment by kevincrafts** [comment]
You need to delete the blocks.

**Comment by cathysnider** [comment]
@kevincrafts I only knows these are quicktab blocks because I named them 'Quicktab'

Sites that have not labeled their blocks as quicktabs will not be able to find them because it's no longer an option in the drop down. 

Question: if the beans still exist, will the site continue to throw errors?
![screen shot 2018-06-20 at 1 04 09 pm](https://user-images.githubusercontent.com/638275/41679166-8910c8aa-748a-11e8-8c6b-bffc3213c2b7.png)

**Comment by kevincrafts** [comment]
Delete quicktabs from admin/structure/quicktabs
