### ISSUE TITLE
VSET - Freeze bundle changes

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2602]
## Context

`drush vset profile_module_manager_disable_enabling_text "Bundles are not available at this time due to the <a href='https://www.colorado.edu/webcentral/server-migration'>Server Infrastructure Upgrade</a>. Bundles will be available once a site has migrated to the new infrastructure. Contact <a href='websupport@colorado.edu'>websupport@colorado.edu</a> for questions regarding this."`

`drush vset profile_module_manager_disable_enabling_atlas_bundles 1`

![screen shot 2018-06-20 at 2 25 18 pm](https://user-images.githubusercontent.com/385234/41682761-df73868c-7495-11e8-888f-60c57ce5df46.png)

**Comment by owenmorrill** [comment]
On a new install:
`drush vset profile_module_manager_disable_enabling 1
Enter a number to choose which variable to set.
 [0]  :  Cancel                                                 
 [1]  :  profile_module_manager_disable_enabling (new variable) 
 [2]  :  profile_module_manager_disable_enabling_text
1`

**Comment by jbertrand** [comment]
CONTENT: 
Bundles are not available at this time due to the [Server Infrastructure Upgrade](https://www.colorado.edu/webcentral/server-migration). Bundles will be available once a site has migrated to the new infrastructure. Contact websupport@colorado.edu for questions regarding this.
