### ISSUE TITLE
As a SO/SE I would like to see the author column on the webform admin page

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#2624]
As an admin/ site owner, I would like to be able to quickly find the forms a user is a form manager of.

A new site owner asked who a user on their site was that had not logged in a couple of months so there is no formal name associated with them or a primary affiliation but was a form manager.

I could not use the content filters to find the forms they authored and the authoring information is also not on the webform admin page.

![user](https://user-images.githubusercontent.com/16137919/41860914-10bd61de-785d-11e8-8cb6-118500c18a15.JPG)
![filter content](https://user-images.githubusercontent.com/16137919/41860932-1e193c18-785d-11e8-9ecc-6a8ee7421b52.JPG)
![webform admin page](https://user-images.githubusercontent.com/16137919/41860946-2550d6d0-785d-11e8-9f0b-4dbde8c6b92d.JPG)

**Comment by cathysnider** [comment]
Sort should work for Real Name or IdentiKey
