### ISSUE TITLE
express_content_edit_lock update messaging, add tests

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2627]
## Context

![screen shot 2018-06-25 at 1 23 48 pm](https://user-images.githubusercontent.com/385234/41871083-18b4565e-787b-11e8-9b6d-aa6201784d4e.png)

Options are hardcoded in https://github.com/CuBoulder/express/blob/dev/modules/custom/express_content_edit_lock/express_content_edit_lock.module#L45

Should have been updated to use the hook logic added to https://github.com/CuBoulder/express/blob/dev/modules/contrib/user_external_invite/user_external_invite.api.php#L15 

This module also needs tests.

**Comment by alexfinnarn** [comment]
I think #2761 fixes the same issue.

**Comment by owenmorrill** [comment]
Crafts took care of the roles/permissions part of this in #2761 changing to create tests ticket.
