### ISSUE TITLE
Remove roles when a user is blocked.

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#2628]
## Context

Now that we have introduced a quote for how many users can have certain roles, we should remove roles when a user is blocked to relinquish any of the roles that might be limited.

## Process

1. Login to site as a [SO, ADMIN or DEV]
2. Click Users
3. Edit a user
4. Click Blocked radio button
5. Click Delete account

## Expected result

Any roles assigned to the user should be removed.

## Current result

User will keep any roles assigned to them even if they are blocked.

**Comment by kreynen** [comment]
I'm not sure we actually want to do that if we are doing https://github.com/cuboulder/express/issues/1823
