### ISSUE TITLE
If a user other than a dev attempts to log into a locked site, the page renders poorly due to an error

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2630]
## Context

![screen shot 2018-06-25 at 1 28 10 pm](https://user-images.githubusercontent.com/385234/41872359-d5f73382-787e-11e8-83c0-32c465a97331.png)

## Process

1. Lock a site using `drush lock_user_dev` after enabling `express_content_edit_lock`.
1. Attempt to login to site as a [SO, SE, CE or EO]

## Expected result

Form rejects the login attempt for all users who aren't admins or devs.

## Current result

The website encountered an unexpected error. Please try again later is displayed in the black background... not sure what the error actually is.

SO can still log in.

**Comment by alexfinnarn** [comment]
It is the watchdog function and the $variables variable. https://github.com/CuBoulder/express/blob/dev/modules/custom/express_content_edit_lock/express_content_edit_lock.module#L253

**Comment by owenmorrill** [comment]
I fixed the logout problem, but it looks like the watchdog piece was causing all kinds of problems. Including not having been written correctly in the first place. The PR should have everything all set.

**Comment by alexfinnarn** [comment]
I tried logging in as a content_editor and site_owner and could not do so. I could log in as myself. I also got an error message and ended up back on the user page after I tried to log in. Seems good to me.
