### ISSUE TITLE
Notice: Undefined variable: addon_rids in _user_external_invite_send_invite_accepted_mail() (line 472

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2642]
https://osr-prod-log01.int.colorado.edu/app/kibana#/doc/AWPMkQACuyrFPSU3HKey/filebeat-drupal_syslog-2018.06.26/drupal_syslog?id=AWQ9LAxrXC4IAFcwKE0G&_g=(refreshInterval:('$$hashKey':'object:614091',display:'1%20minute',pause:!f,section:2,value:60000),time:(from:now-36h,mode:relative,to:now))

**Comment by alexfinnarn** [comment]
same as #2643
