### ISSUE TITLE
user_external_invite PHP Notices When Sending An Invite Without Addon Roles

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2643]
## Context

```
Warning: array_map(): Argument #2 should be an array in _user_external_invite_send_invite_accepted_mail() (line 472...
```

https://osr-prod-log01.int.colorado.edu/app/kibana#/doc/AWPMkQACuyrFPSU3HKey/filebeat-drupal_syslog-2018.06.26/drupal_syslog?id=AWQ9LAxrXC4IAFcwKE0H&_g=(refreshInterval:('$$hashKey':'object:614091',display:'1%20minute',pause:!f,section:2,value:60000),time:(from:now-36h,mode:relative,to:now))

**Comment by alexfinnarn** [comment]
https://github.com/CuBoulder/express/tree/dev/modules/contrib/user_external_invite#L472

Five variables in that function either don't exist or are unused.

**Comment by alexfinnarn** [comment]
This PR will include many corrections for undefined notices relating to when addon roles aren't chosen when sending an invite.

**Comment by alexfinnarn** [comment]
closing due to merged PR.
