### ISSUE TITLE
Reduce Number of cu_update_ping Requests

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#2651]
https://osr-prod-log01.int.colorado.edu/app/kibana#/discover?_g=(refreshInterval:('$$hashKey':'object:614091',display:'1%20minute',pause:!f,section:2,value:60000),time:(from:now-24h,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWPMkQACuyrFPSU3HKey,key:drupal_category,negate:!f,type:phrase,value:cu_update_ping),query:(match:(drupal_category:(query:cu_update_ping,type:phrase))))),index:AWPMkQACuyrFPSU3HKey,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))

One spike I saw in that chart...of course it has changed since writing this but...was 4,457 messages.

I thought we had discussed only pinging the Express modules on drupal.org and not the other contrib modules in `modules/contrib`. I think selectively pinging only those modules makes sense with all the other stuff going on in cron.

**Comment by kreynen** [comment]
I don't want to exclude our contrib modules from the ping, but I don't think we need to ping all contrib.  However while cron is running every 5 minutes, https://github.com/CuBoulder/express/blob/dev/modules/custom/cu_update_ping/cu_update_ping.module#L15 limits these to once every week.  

I created a 3.0 label for Cron related tasks, but this really has very little impacted compared to moving LinkChecker to an external service or https://github.com/CuBoulder/express/issues/2419
