### ISSUE TITLE
Honeypot fail on Feedback Forms

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2660]
"Leave this field blank" is appearing on Feedback forms. 

![screen shot 2018-06-27 at 1 44 59 pm](https://user-images.githubusercontent.com/638275/41995916-7b1d1c4a-7a10-11e8-8c91-ccae0e40a413.png)

If you take off Honeypot protection for webforms on "/admin/config/content/honeypot", the the field goes away.

This issue has happened before: https://github.com/CuBoulder/express/issues/2227

It is happening again  on launched sites running 2.9.2

## Links to Examples

https://www.colorado.edu/bouldertalks
https://www.colorado.edu/healthcenter
https://www.colorado.edu/bfp
https://www.colorado.edu/amath
https://www.colorado.edu/ocg

**Comment by alexfinnarn** [comment]
https://github.com/CuBoulder/cu_forms_bundle/blob/master/cu_feedback/cu_feedback.module#L81

When the cu_feedback.module file was moved to the Forms Bundle it was never kept in sync with what was in Express.

**Comment by alexfinnarn** [comment]
Applying https://github.com/CuBoulder/express/pull/2230/files#diff-b47820e53b16a105db875e82e7dc3652 again should solve the issue.

**Comment by kevincrafts** [comment]
The issue is that the honeypot css file is not being added to the site's pages.
Adding in our own css will make sure the field is hidden all the time.

**Comment by kevincrafts** [comment]
https://github.com/CuBoulder/express/pull/2679

**Comment by alexfinnarn** [comment]
I don't think that PR is a solution. First of all, it is in Express when the module is in its own repo. Secondly, it doesn't address the issue with the form needing rendering every time it is opened or closed.

<img width="1026" alt="screen shot 2018-06-29 at 9 51 01 am" src="https://user-images.githubusercontent.com/3640707/42096038-5138cb72-7b82-11e8-9e7f-7071e3c1144c.png">

I can't reproduce this on my local, and I just tried with 2.9.1 and the forms bundle at https://osr-atlas03.int.colorado.edu/atlas/code/5b22c93d926f5b125c094a76 but I couldn't reproduce the "leave field blank" on https://www-dev-new.colorado.edu/p196fb7f4e7a/content/webform.

**Comment by alexfinnarn** [comment]
Here is my PR to check over: https://github.com/CuBoulder/cu_forms_bundle/pull/26. It applies the same code that the previous PR did in https://github.com/CuBoulder/express/pull/2230

**Comment by cathysnider** [comment]
The problem seems to be with the 2.9.2 release: 
https://www-dev-new.colorado.edu/p1e176d1a656/

![screen shot 2018-06-29 at 8 55 58 am](https://user-images.githubusercontent.com/638275/42099301-4ca939d2-7b7a-11e8-8c7a-3e271e5822ce.png)

**Comment by cathysnider** [comment]
Looks good: The extra field is not appearing on the Feedback Form:
https://www-dev-new.colorado.edu/p136401211b2/
![screen shot 2018-06-29 at 1 20 11 pm](https://user-images.githubusercontent.com/638275/42110711-65edd96e-7b9f-11e8-961c-6d30be86e611.png)
