### ISSUE TITLE
User warning: The following module is missing from the file system: ldap_sso.

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#2669]
Seen after visiting "admin/config/people/ldap/authentication".

It was removed sometime after the 2.8.2 release.
https://github.com/CuBoulder/express/tree/release/2.8.2/modules/contrib/ldap/ldap_sso

There is a patch for this issue in the LDAP module and it looks like it is in the dev 7.x branch.
https://www.drupal.org/project/ldap/issues/2958197

**Comment by kreynen** [comment]
We've run drush en module_missing_message_fixer -y; sudo -u apache drush mmmff --all; sudo -u apache drush dis module_missing_message_fixer -y on all sites on old prod and new prod to clear any system table cruft.  As sites are migrated any `User warning: The following module is missing from the file system` errors should be treated as real issues as it may be related to https://github.com/CuBoulder/express/issues/2655.  Webcentral also has https://github.com/CuBoulder/custom_webcentral_bundle/issues/86, but that's a different issue
