### ISSUE TITLE
As a SO/SE I would like to be able to embed an outlook calendar on a web express site

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#2671]
Being able to schedule rooms or appointment times is university functionality that is part of outlook. The photography department is trying to find a way to allow university clients to self register for appoint times to get their head shots taken. We can publish an Outlook calendar as an internet calendar

It would be great if they could embed the schedule on a webpage because not all employees use outlook personally

Related to Issue:
#2558

Resources? 
#2558
![image](https://user-images.githubusercontent.com/16137919/42048719-5469c4c0-7ac1-11e8-8d90-1e0b7734807c.png)

**Comment by kevincrafts** [comment]
Drupal project is for 8.x.
