### ISSUE TITLE
Permissions have gotten WAY too distributed

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2677]
On /webcentral I'm seeing secure_permission_hooks in all these places

`Atlas Sites Entity
Webcentral
Advanced Content
Advanced Design
Advanced Layout
Block Row
Block to Bean
Content List
Content Sequence Bundle
CU SEO Dashboard
Expandable
Google CSE Admin
CU HelpScout
Inactive Users
Newsletter Bundle
News and Articles
People
Photo Gallery Bundle
RSS Feeds
RSS Block
CU Search
Search Engine Optimization
Social Media
Video Hero Unit Bundle
Video Reveal
Express Block Designer
Express Content Edit Lock
Express User Dashboard
Express Layout
Express Localist Bundle
Express MathJax Bundle
Express Permissions
Forms
CU Users
Express`

This is contributing to https://github.com/CuBoulder/express/issues/2287

We really don't need https://github.com/CuBoulder/express/blob/dev/express.profile#L221 when  the express profile requires express_permissions.  I think we only need permissions in 

- profile (express_permissions) - used by every site including UCD
- cores (cu_core) - Boulder specific permissions 
- hosting? 
- bundles

**Comment by alexfinnarn** [comment]
#2448
