### ISSUE TITLE
Enable ucb_on_prem_hosting For The Other Hosting Modules

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#2688]
While different hosting modules makes sense form a theoretical perspective, in practice things only get added to the hosting module where the production sites are hosted.

I end up putting `$_SERVER['TRAVIS'] = TRUE;` in my settings.php file so that I can see a site as it would be installed on Travis CI. In the process of doing that I found #2665 and #2650. I'm not sure what else is different, either.

Rather than try to enforce looking at all of the hosting module changes and syncing them when they get out of sync, I think it makes more sense to enable `ucb_on_prem_hosting` in the install hooks of other hosting modules.

Right now, all that is needed is for the LDAP authentication variable to be set to 1 for mixed mode. It is serialized, but loading and changing that value after install shouldn't be too hard to accomplish. Other than that, `ucb_on_prem_hosting` sets some variables for SMTP and the timezone. 

I think the other hosting modules do enough to be kept in the codebase, and additional code can be added to undo or change what `ucb_on_prem_hosting` does that can't work on Travis CI or Pantheon.

**Comment by kreynen** [comment]
Making the ldap modules a requirement of cu_core makes more sense than enabling modules that will not work in different hosting environments.  The way we handle LDAP is going to have to be re-evaluated with SAML as well.
