### ISSUE TITLE
Notice: Undefined index: und in cu_block_section_preprocess_entity() (line 99

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2699]
Notice: Undefined index: und in cu_block_section_preprocess_entity() (line 99

https://osr-prod-log01.int.colorado.edu/goto/a79d7b038c1a5532b3b2c155671768ae

https://github.com/CuBoulder/express/blob/dev/modules/features/cu_block_section/cu_block_section.module#L99 

LANGUAGE_NONE is used, so I'm not sure if this is an issue where blocks were created on sites while a language was set or something isn't getting rendered.

**Comment by alexfinnarn** [comment]
I think this is a case where the field doesn't have a language component or the array structure changed. 

But https://www.colorado.edu/chembio/block/homepage-block-section-undergrad/edit?destination=node/2 is a block section and https://www.colorado.edu/chembio/ shows that error.

**Comment by alexfinnarn** [comment]
If you create a block section with no blocks, then you should get this error. Example: https://www.colorado.edu/alumni/block/block-section-staff-photo/edit?destination=node/67 showing up on https://www.colorado.edu/alumni/about.

I think a solution would be to make each one of these "collections of beans" beans require at least two blocks.

**Comment by alexfinnarn** [comment]
Also https://www.colorado.edu/artsandsciences/block/books-shorter-profile/edit?destination=node/1046

Other sites can be spot-checked, but I would make a change to require blocks in block sections first, as well as fixing the notice for sites that already have this issue.
