### ISSUE TITLE
Warning: uasort() expects parameter 1 to be array, null given in node_view_multiple()

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2700]
https://osr-prod-log01.int.colorado.edu/goto/e724f97e6b30606c93313d4b0ff7ca73

Reporting on pages like https://www.colorado.edu/admissions/social and https://www.colorado.edu/demos/web-express/add-bundles

**Comment by kevincrafts** [comment]
This is caused by an article list page that returns no results.
