### ISSUE TITLE
Notice: Undefined offset: 11366 in _field_invoke_multiple() on https://www.colorado.edu/research/report/2016-7/ nodes

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2711]
https://www.colorado.edu/research/report/2016-7/grand-challenge-eye-sky is generating errors

Notice: Undefined offset: 11366 in _field_invoke_multiple() (line 328 of /data/atlas/code/cores/drupal/drupal-7.57/modules/field

These errors appear to only be sites https://www.colorado.edu/research/report/2016-7 under https://osr-prod-log01.int.colorado.edu/goto/bef5cd3e6ad4e811bc0ef5919646d6e4

https://www.colorado.edu/admin/structure/context/list/research-report-2016-2017/edit is applied to node/10946

**Comment by kevincrafts** [comment]
The css rendering and the undefined offset are unrelated.  Making a new issue for the css part.

https://github.com/CuBoulder/express/issues/2736

**Comment by kevincrafts** [comment]
Updated issue description and removed image from the other issue

**Comment by alexfinnarn** [comment]
Each undefined offset relates to a node, e.g. the nodes listed in the content_grid of https://www.colorado.edu/block/block-section-rr17-features/edit?destination=node/10946.

When I look for ` _field_invoke_multiple()` in the code base, I see it used on the layout pages while loading inline entity forms. https://github.com/CuBoulder/express/blob/dev/modules/custom/express_layout/express_layout.module#L866

I'm guessing that one of the form elements...eh, I got nothing. I tried to load the layout form and save/edit it with a content_grid inside of a block_section, but I couldn't reproduce the errors.
