### ISSUE TITLE
Make decisions about how often core/contrib cron processes should be running

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2714]
Related to https://github.com/CuBoulder/express/issues/2713

We are running cron every 1 hour on every laucnhed site and 3 hours on installed sites then using https://www.drupal.org/project/elysia_cron so we aren't trying to run every cron job every a site has queue up every 5 minutes.

Many of these jobs have checks in the cron hook to see if there is anything that needs to be done, but even the checking the check every 1 hour is a performance hit.

We should use hook_cronapi to prioritize what we want running more or less often.

**Comment by jwfuller** [comment]
https://github.com/CuBoulder/express/issues/1353

**Comment by jeor0980** [comment]
Now that we are running Elsyia, we want to turn it further.

- Look at shifting CPU load into off hours. Ex: Linkchecker
- Go through core bundles to set cron timings

[List of cron_hooks](https://docs.google.com/spreadsheets/d/1TZNENelBMWLKwgMv9bKKHP7GaIrbahqCyrI4LV2qexk/edit#gid=0)
