### ISSUE TITLE
Warning: Invalid argument supplied for foreach() in element_children() (line 6594

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2719]
## Context

Empty content grid results in 3 warnings on any page it is placed.

https://osr-prod-log01.int.colorado.edu/goto/149f15cfabcaacac335fb35afaa09c75

https://www.colorado.edu/chembio/block/example-content-grid is placed on https://www.colorado.edu/chembio/resources

Results in...

```
Warning: array_intersect_key(): Argument #1 is not an array in cu_feature_callout_preprocess_entity() (line 178 of /data/atlas/code/profiles/express/express-2.9.1/modules/features/cu_feature_callout/cu_feature_callout.module).

Warning: Invalid argument supplied for foreach() in element_children() (line 6594 of /data/atlas/code/cores/drupal/drupal-7.57/includes/common.inc).

Warning: Invalid argument supplied for foreach() in cu_feature_callout_preprocess_entity() (line 200 of /data/atlas/code/profiles/express/express-2.9.1/modules/features/cu_feature_callout/cu_feature_callout.module)

```

**Comment by kevincrafts** [comment]
I was not able to reproduce this warning, but it looks like it comes from a content grid not having any cells.  This is also difficult to create, because it seems that there is always 1 cell, even if it's empty.

**Comment by alexfinnarn** [comment]
```
Warning: array_intersect_key(): Argument #1 is not an array in cu_feature_callout_preprocess_entity() (line 178 of /data/atlas/code/profiles/express/express-2.9.1/modules/features/cu_feature_callout/cu_feature_callout.module).

Warning: Invalid argument supplied for foreach() in cu_feature_callout_preprocess_entity() (line 200 of /data/atlas/code/profiles/express/express-2.9.1/modules/features/cu_feature_callout/cu_feature_callout.module).
```

https://github.com/CuBoulder/express/blob/dev/modules/features/cu_feature_callout/cu_feature_callout.module#L178

These are in sequence with the `element_children()` error. They were happening on https://www-prod-new.colorado.edu/amath, e.g. https://www-prod-new.colorado.edu/amath/prospective-students. When I turned on dblog, I saw the messages right away.

It looks like `$vars['content']['field_callouts']` isn't an array.

**Comment by alexfinnarn** [comment]
To reproduce:
1. Create a new site and turn on cu_advanced_content_bundle.
2. Create an empty content grid.
3. Place it on a page via the layout tool.
4. Go to the page as an anonymous user after the cache has been cleared.
4. View the messages in dblog.

**Comment by alexfinnarn** [comment]
For some reason, I only see the error as an anonymous user. I think it might be related to permissions then, and the field_callouts part of the content array not being included for some reason for anonymous users.
