### ISSUE TITLE
Match Redirect: Administrator role cannot add a Match Redirect. 

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2720]
## Context

Administrators are supposed to be able to create Match Redirects. Currently, they have no way to navigate to the Match Redirect Configuration page at admin/config/search/match_redirect. So they cannot add a pattern match redirect. 

## Process

Admins cannot access the Configuration page. Currently they go Settings then click Redirect then click the Wildcard tab. They can see any redirects that have been set by developers, but they cannot create any new ones. 

## To Do

On the Wildcard tab (admin/config/search/redirect/wildcards) add a link to the match redirect configuration page

## Screenshots

![addmatchredirect](https://user-images.githubusercontent.com/638275/42349172-01f9893e-8069-11e8-9800-7ebe103dbcac.jpg)

----

## Links to Examples

https://www-dev-new.colorado.edu/p10e33220073/

**Comment by owenmorrill** [comment]
The page that admins and developers need to go to to add a match redirect is: admin/config/search/match_redirect

Simply viewing already available redirects is done at: admin/config/search/redirect/wildcards

**Comment by cathysnider** [comment]
Administrators cannot get to admin/config/search/match_redirect.

While it is true that the page "admin/config/search/match_redirect" does not generate a 403 error, Admins cannot GET there, because they don't have access to the Configuration page. 

Admins need a link to the Match Redirect page. 

![adminsandconfiguration](https://user-images.githubusercontent.com/638275/45705124-fe5d7a80-bb35-11e8-9f0d-5de5390f01df.jpg)

**Comment by cathysnider** [comment]
New solution:

![screen shot 2018-09-20 at 10 55 25 am](https://user-images.githubusercontent.com/638275/45834156-b9674e80-bcc3-11e8-8bac-273110e07110.png)
