### ISSUE TITLE
Metatag "Master Controls for All Entities" should not be exposed to Site Owners & Site Editors

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2734]
## Context

When the SEO Bundle is enabled, the Site Owner gets a green 'Thank you' message, that contains a link to Settings at /admin/config/search/metatags/settings

![screen shot 2018-07-06 at 2 51 42 pm](https://user-images.githubusercontent.com/638275/42400637-9b9d4de8-812f-11e8-9094-62b3b3126df3.png)

They can access Defaults, Settings and Bulk Revert.

![screen shot 2018-07-06 at 3 17 44 pm](https://user-images.githubusercontent.com/638275/42400690-d5f1ad90-812f-11e8-9ae7-4b11b44ac7af.png)

This should be turned off, possibly by removing that sentence with the link to Settings.

**Comment by kevincrafts** [comment]
Permissions should be Edit meta tags, not Administer meta tags
