### ISSUE TITLE
Error in _atlas_statistics_get_webform_statistics called at atlas/atlas_statistics/atlas_statistics.inc

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#2738]
```
Error: Uncaught exception 'Error' with message 'Call to undefined function webform_get_submission_count()' in /data/atlas/code/profiles/express/express-2.9.1/modules/custom/atlas/atlas_statistics/atlas_statistics.inc:174

in _atlas_statistics_get_webform_statistics called at /data/atlas/code/profiles/express/express-2.9.1/modules/custom/atlas/atlas_statistics/atlas_statistics.inc (93)
in atlas_statistics_atlas_statistics called at /data/atlas/code/cores/drupal/drupal-7.57/includes/module.inc (957)
in module_invoke_all called at /data/atlas/code/profiles/express/express-2.9.1/modules/custom/atlas/atlas_statistics/atlas_statistics.inc (16)
in atlas_statistics_get_statistics called at /data/atlas/code/profiles/express/express-2.9.1/modules/custom/atlas/atlas_statistics/atlas_statistics.module (46)
in atlas_statistics_cron called at /data/atlas/code/profiles/express/express-2.9.1/modules/contrib/elysia_cron/elysia_cron.module (1460)
in elysia_cron_internal_execute_job called at /data/atlas/code/profiles/express/express-2.9.1/modules/contrib/elysia_cron/elysia_cron.module (1424)
in elysia_cron_internal_execute_channel called at /data/atlas/code/profiles/express/express-2.9.1/modules/contrib/elysia_cron/elysia_cron.module (1283)
in elysia_cron_run called at /data/atlas/code/profiles/express/express-2.9.1/modules/contrib/elysia_cron/elysia_cron.drush.inc (161)
in drush_elysia_cron_run_wrapper called at /usr/share/drush/includes/command.inc (422)
in _drush_invoke_hooks called at /usr/share/drush/includes/command.inc (231)
in drush_command called at /usr/share/drush/includes/command.inc (199)
in drush_dispatch called at /usr/share/drush/lib/Drush/Boot/BaseBoot.php (67)
in Drush\Boot\BaseBoot::bootstrap_and_dispatch called at /usr/share/drush/includes/preflight.inc (66)
in drush_main called at /usr/share/drush/drush.php (12)
```

https://github.com/CuBoulder/express/blob/dev/modules/custom/atlas/atlas_statistics/atlas_statistics.inc#L174

I think some sites must have webforms on them but never had the forms bundle added after it was removed. The entires remain in the database so the foreach loop has webforms to loop through, but none of the code exists.

I think all of the statistics related to bundles should implement `hook_atlas_statistics()` https://github.com/CuBoulder/express/blob/dev/modules/custom/atlas/atlas_statistics/atlas_statistics.inc#L21 instead of checking for modules or bundles to exist.

**Comment by alexfinnarn** [comment]
All for /ethnicstudies https://osr-prod-log01.int.colorado.edu/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),filters:!(),index:AWPMkQACuyrFPSU3HKey,interval:auto,query:(query_string:(analyze_wildcard:!t,query:%22_atlas_statistics_get_webform_statistics%22)),sort:!('@timestamp',desc))

**Comment by alexfinnarn** [comment]
Another improvement, couldn't https://github.com/CuBoulder/express/blob/dev/modules/custom/atlas/atlas_statistics/atlas_statistics.inc#L56 be a db_query only for username, email, and roles? I think that would be much faster than loading all the users, and I wonder how much that cost could impact the duration of cron runs.

**Comment by kreynen** [comment]
Issue moved to [CuBoulder/cu_forms_bundle #33](https://github.com/CuBoulder/cu_forms_bundle/issues/33) via [**ZenHub**](https://www.zenhub.com/)
