### ISSUE TITLE
Improve How Atlas Sends Statistics

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#2740]
There are several tickets about Atlas and stats that can be grouped together. As the number of stats gathered increases, some sort of time measurement should be created for a baseline to check and see  how adding certain stats affects cron run times on large sites.

**Comment by kreynen** [comment]
As we improve the parsing of Drush commands into Kibana, a lot of what we're gathering to build a  report can be replaced by a `drush sqlq "COUNT(id);"` style commands.  We need to resolve https://github.com/CuBoulder/atlas/issues/407 so a command can be run against all sites in a single batch, but this will allow us to limit the use stats for trending.  Realtime reporting can shift to a combination of drush commnads and Kibaba reports

**Comment by alexfinnarn** [comment]
<img width="660" alt="screen shot 2018-07-17 at 10 46 45 am" src="https://user-images.githubusercontent.com/3640707/42824856-bb84b39e-89ae-11e8-832d-33167abfb521.png">

`atlas_statistics` is the slowest hook on average to be called on the old infrastructure according to New Relic.
