### ISSUE TITLE
Remove cu_directory Lookup Logging

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#2747]
https://osr-prod-log01.int.colorado.edu/goto/f62ac74e58318dd978639b52d12130b4

"Looked up: something". Does that really tell anyone anything? On the new prod instances, there are over 34,000 hits for that message over the last week. It is probably better to log "Lookup for "something" failed".

Also, the messages are logged twice for each search.

**Comment by alexfinnarn** [comment]
I think this is a small change and can be done when code is able to be pushed again.

**Comment by kreynen** [comment]
Issue moved to [CuBoulder/custom_homepage_bundle #175](https://github.com/CuBoulder/custom_homepage_bundle/issues/175) via [**ZenHub**](https://www.zenhub.com/)
