### ISSUE TITLE
cu_newsletter errors or notices

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#2759]
https://osr-prod-log01.int.colorado.edu/goto/d19a57699658b3a467cf81488e08064c

There are a bunch of PHP notices and errors related to the newsletter code. I think a lot of them can be worked on together, but it is better to list them individually so that people will see them when searching for bugs/past regressions. 

Code: https://github.com/CuBoulder/cu_newsletter_bundle

Please place at least the function name and line number of the message in the title or body of the issue.

**Comment by alexfinnarn** [comment]
I'm pausing for now, but there are still a lot of notices to be captured.

**Comment by kevincrafts** [comment]
I think we need to update the code on the environments and re-evaluate because I think some of these things might have been addressed already.
