### ISSUE TITLE
Cache Site Information Block

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#2780]
If you set a breakpoint/dpm in a shortcode filter processing callback, you should see that every page load processes the filter while the body content is only processed once and then cached.

Since the site information block is loaded on all non-admin pages, at least I think you can't turn it off, I think more caching would be better.

https://api.drupal.org/api/drupal/modules%21block%21block.api.php/function/hook_block_info/7.x

The default for blocks is per user role, so you could have as many versions of the block cached as there are user roles when you only want one version.

**Comment by kevincrafts** [comment]
Maybe I'm not understanding this, but if the default is DRUPAL_CACHE_PER_ROLE, wouldn't that mean that it would NOT be processed on every page load as long as the role was the same?
