### ISSUE TITLE
Replace hook_theme_registry_alter() With hook_theme() Where Possible

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#2787]
While profiling a request on a local site, I saw that "_theme_process_registry()" was taking a decent amount of time in a page render. If you look in the Express codebase, you'll see calls in functions like https://github.com/CuBoulder/express/blob/dev/modules/features/cu_article/cu_article.module#L111.

I've always wondered why hook_theme() isn't used instead. You can add preprocess functions in hook_theme() and hook_theme_registry_alter() only alters what hook_theme() returns.

The way beans are captured in Features is through the bean_admin_ui module, but hook_bean_types() can be used to declare plugins as well.
https://github.com/CuBoulder/express/blob/dev/modules/contrib/bean/bean.api.php#L23 

Maybe if they are plugins then they don't need a registry_alter function call to declare the template files?

**Comment by alexfinnarn** [comment]
#2785

**Comment by kevincrafts** [comment]
The registry alter is needed to tell the system that a template file lives within a module directory.
