### ISSUE TITLE
As a SO/SE I would like to add blocks to the newsletter content type

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#2793]
I would like to be able to add a banner image to the newsletter content type that would appear on the webpage version only

I would like to be able to add a newsletter archive block in the right sidebar and a sign up button

Maybe we could create a special context that would only allow text blocks, menu blocks to be added to the content type.

**Comment by kevincrafts** [comment]
This is never going to happen, due to the limitations of HTML email.  The only kind of block we could really include is a text block, which is already addressed in the various text fields in the newsletter content type.

**Comment by kreynen** [comment]
Issue moved to [CuBoulder/cu_newsletter_bundle #38](https://github.com/CuBoulder/cu_newsletter_bundle/issues/38) via [**ZenHub**](https://www.zenhub.com/)
