### ISSUE TITLE
Update contrib dependencies

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2800]

**Comment by owenmorrill** [comment]
Display Suite | 7.x-2.14 | Not secure
-- | -- | --
Bean | 7.x-1.11 | Update available
Disable Messages | 7.x-1.1 | Update available
File Entity (fieldable files) | 7.x-2.18 | Update available
Google Analytics | 7.x-2.4 | Update available
Honeypot | 7.x-1.24 | Update available
Link | 7.x-1.4 | Update available
Modernizr | 7.x-3.10 | Update available
Varnish | 7.x-1.8 | Update available
Views | 7.x-3.18 | Update available
Views Bulk Operations (VBO) | 7.x-3.4 | Update available
