### ISSUE TITLE
Port Developer Blog Functionality

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#2815]
The goal of this ticket is to create a website that hosts blog posts from developers as well as provides resources for collaboration, such as meeting info, roadmaps, etc.

To start, the syntax highlighting bundle will be ported to create a simple blog listing, and then other pages can fit in around it.

List of Express -> Backdrop modules: Pick from https://docs.google.com/spreadsheets/d/1Yske73hdxu_i3-fypXnuSo8MQwRvOqf8PQHa_SA3Jv8/edit#gid=0 

Coder Upgrade:  https://github.com/backdrop-contrib/coder_upgrade

**Comment by alexfinnarn** [comment]
This bundle included shortcode and I'm using https://github.com/CuBoulder/backdrop-shortcode for that.

**Comment by alexfinnarn** [comment]
Sections to add:
- [ ] Blog: depends on syntax highlighting bundle and creating a view. Use "Post" content type for now.
- [ ] About: 
-- [ ] Docs: Links to documents people might want to read
-- [ ] Open Source Work: Links to that work
-- [ ] 
- [ ] Get Involved: Ways to contribute
-- [ ] GitHub links

**Comment by kreynen** [comment]
I was going to write that we'd look pretty foolish if we didn't recreate the feed using the existing uuids since https://www.colorado.edu/webcentral/2016/09/14/add-rss-your-d8-migration-checklist was the first post to that blog.

Instead, I'm opening https://github.com/CuBoulder/express/issues/2825

**Comment by kreynen** [comment]
https://api.backdropcms.org/api/backdrop/core%21includes%21uuid.inc appears to be in Backdrop core?
