### ISSUE TITLE
Scope Directory Replacement Work

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#2816]
The directory http://atozapi.colorado.edu/ needs to be replaced with something. Since our team knows PHP, it makes sense to create the stack around PHP and explore Laravel in the process. One could also start with basic Symfony components (Laravel uses some Symfony components).

I know that the homepage bundle connects to the directory to look up people
https://www.colorado.edu/atoz/letter/a
https://github.com/CuBoulder/custom_homepage_bundle/tree/master/modules/custom/cu_atoz

I don't know much about the current issues already out there in the Express repo, but the first step would be to capture what the Directory API does and how it interacts with its consumers. I think the Homepage is the only consumer, but I'm not sure.

Also involved here is getting "expert" advice from Symfony/API Platform/Laravel community and any local/remote shops that could do contract work and/or consultations.

**Comment by kreynen** [comment]
Issue moved to [CuBoulder/directory #5](https://github.com/CuBoulder/directory/issues/5) via [**ZenHub**](https://www.zenhub.com/)
