### ISSUE TITLE
Gather A List Of Endpoints

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#2818]
The homepage bundle provides some paths accessed in the directory API, but there might be other ones...probably not listed anywhere.

- **/letter/%** - Gives a listing based on letter
- **/show/%** - Shows a particular ID of a directory record...doesn't work...only in Drupal module menu paths
- **/category/%** - List of categories
- **/ou/%** 

http://atozapi.colorado.edu/letter/b

http://atozapi.colorado.edu/categories
http://atozapi.colorado.edu/category/museum

**Comment by kreynen** [comment]
Issue moved to [CuBoulder/directory #3](https://github.com/CuBoulder/directory/issues/3) via [**ZenHub**](https://www.zenhub.com/)
