### ISSUE TITLE
Setup API Platform

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#2819]
The most viable candidate as far as a tech stack goes is API Platform. This is mainly due to my knowledge of PHP and it being the most popular API tool in the PHP world.

https://api-platform.com/docs/

The project already has a recommended admin interface built in React and Graph QL support. Both of those are pretty common for any contractor that might be involved in this project.

I've set up the API Platform before, and it is really easy to get a basic API with different endpoints. I've not experimented with the admin UI or the Graph QL support. Maybe those extras aren't needed, but there is a lot of community support for them so there will be great patterns to pick up on for building out a directory.

**Comment by kreynen** [comment]
Issue moved to [CuBoulder/directory #1](https://github.com/CuBoulder/directory/issues/1) via [**ZenHub**](https://www.zenhub.com/)
