### ISSUE TITLE
Site search results open in new window

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#2820]
## Context

All sites that have a CSE custom search have results that open in a new window.

## Examples

- https://www.colorado.edu/music/search?cse=brass&op=Search
- https://www.colorado.edu/english/search?cse=Freshman+Writing+Seminar&op=Search
- https://www.colorado.edu/webcentral/search?search-option=This+site&cse=images&op=Search

**Comment by alexfinnarn** [comment]
I think in https://github.com/CuBoulder/express/blob/dev/modules/contrib/google_cse/google_cse.theme.inc#L26 the "linkTarget" attribute can be added to prevent "_blank" from opening a new page: https://developers.google.com/custom-search/docs/element

**Comment by alexfinnarn** [comment]
@jeor0980 confirmed that ^^^ works so it would be a variable set in a command to fix on launched sites and install hook/features/strongarm for new sites. 

I think a command would be more performant `drush vset` vs. `drush updb`.
