### ISSUE TITLE
Shadow theme need a layout-boxed class.

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#2852]
## Context

Many themes that have a layout option will add the "layout-boxed" class if the layout is set to boxed.  The Shadow theme is ALWAYS a boxed layout, but the class isn't applied.  Other styles rely on that class so we should set it in the code.

**Comment by kevincrafts** [comment]
create an article, place a hero sized image in the content, set the article layout to feature

**Comment by cathysnider** [comment]
So the problem is that:
Shadow Theme + Node with Feature Layout + Hero Image in Content area == images breaks out of content boundary. 

![screen shot 2018-08-29 at 2 51 23 pm](https://user-images.githubusercontent.com/638275/44814843-111a0a80-ab9b-11e8-923b-df14df5d7319.png)
