### ISSUE TITLE
Honeypot "leave this field blank" input field is showing on exposed views

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2869]
Several sites are reporting that this problem has returned. 

The problem occurs on People List Pages and Article List Pages. 
Example: https://www.colorado.edu/psych-neuro/

## Related to

This problem has been fixed before. See Issue: https://github.com/CuBoulder/express/issues/1571

## Screenshots

![listnews](https://user-images.githubusercontent.com/638275/44541072-16bcaf80-a6c6-11e8-8ea0-23f4a5056a16.jpg)
![listpeople](https://user-images.githubusercontent.com/638275/44541073-16bcaf80-a6c6-11e8-93a7-428678d3285d.jpg)

**Comment by jwfuller** [comment]
The solution is to clear the Drupal cache.
