### ISSUE TITLE
Need description of deprecated version of Content Editor

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2883]
Related to https://github.com/cuboulder/express/issues/2761

![3invite_new_user___university_of_colorado_boulder](https://user-images.githubusercontent.com/385234/45044358-18269a00-b02d-11e8-840b-a5c514e68631.png)

**Comment by jbertrand** [comment]
Here is a link to the content for the User Dashboard that includes description for the Content Editor (deprecated) as well as some addition content edits for the page:
https://docs.google.com/document/d/1XwuBIeWzmkuRSNV3zONotnCHZB5bF8wmoHMm7WQPGL8/edit?usp=sharing

**Comment by owenmorrill** [comment]
This role will be changing (see updated version). The role originally had full edit access to add and/or delete all content as well as layout tools. It will being demoted to Edit only access (see Updated version). 
Site owners need to determine if a user with Content Editor should be in the new updated version or promoted to Site Editor.

**Comment by cathysnider** [comment]
One fix: change 'There are four core roles' to 'There are five core roles'. We can change it back to four when we remove the deprecated Content Editor.
![rolenames](https://user-images.githubusercontent.com/638275/50860167-79030d80-1352-11e9-84d9-ecd3bac964e7.jpg)
