### ISSUE TITLE
Alter role names in admin/users View

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2884]
Related to https://github.com/cuboulder/express/issues/2761

This hasn't been that big of a deal since the machine names of the roles were so similar to labels, but with Content Editor (edit only) and Content Editor (deprecated), it gets more confusing.  I think this may be the last place the role machine names are visible.

![screen shot 2018-09-04 at 10 36 56 am](https://user-images.githubusercontent.com/385234/45044855-8455cd80-b02e-11e8-8b1d-b294680e282b.png)

**Comment by cathysnider** [comment]
Looking good. The two roles names are spelled out.

![rolenamesadminview](https://user-images.githubusercontent.com/638275/46426836-f0deed80-c6fc-11e8-9be1-2b23c1aa41e1.jpg)
