### ISSUE TITLE
Replace hook_views_pre_render with hook_views_query_alter or multiple, permission views

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2890]
I was looking at the changes made to this view for https://github.com/CuBoulder/express/issues/2889

On sites with hundreds or thousands of users, https://github.com/CuBoulder/express/blob/dev/modules/custom/cu_users/cu_users.module#L230 is a really inefficient way to do this vs. simple excluding these users from the query with hook_views_query_alter or 2 versions of the view.

**Comment by owenmorrill** [comment]
This was somehow wrapped into #2891  

https://github.com/CuBoulder/express/pull/2925/files

**Comment by kreynen** [comment]
This entire thing needs to be refactored for https://github.com/CuBoulder/express/issues/3056
