### ISSUE TITLE
Remove cu_users_user_presave 

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2891]
I believe https://github.com/CuBoulder/express/blob/dev/modules/custom/cu_users/cu_users.module#L277 is now unnecessary.  The form has been altered into radio buttons, there is no way for SO or AM to add more than 1 core role to users.

**Comment by kreynen** [comment]
The reason I didn't merge this is I wanted to see what the altered user/%/edit form would do for SO if a dev made a mistake and selected 2 core roles. This function currently prevents devs from doing that.  If that prevents SO for editing a user, we want to leave it.

**Comment by owenmorrill** [comment]
The user edit page only shows one of the roles as being selected when the user has multiple core roles. Saving doesn't have a problem and overwrites the multiple roles with what the SO granted.
