### ISSUE TITLE
As SM, I would like users to see a 404 instead of a 403 when attempting to access unpublished nodes

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2893]
**Is your feature request related to a problem? Please describe.**
This is related to https://github.com/CuBoulder/express/issues/1823, but we want to make sure this works with https://github.com/CuBoulder/express/tree/dev/modules/contrib/r4032login. 

**Describe the solution you'd like**
I think enabling https://www.drupal.org/project/unpublished_404 would help differentiate between a 403 when accessing a form or admin/reports and a 403 when attempting to access an unpublished node.  The ideal behavior would be that users are prompted to login when attempting to access forms and admin pages, but shown a 404 for unpublished nodes.

**Comment by cathysnider** [comment]
Test results:
 - [x] Link to unpublished page: Logged out user gets a 404
 - [x] Link to admin/settings: Logged out user gets message "Access denied. You must log in to view this page." and are prompted to login. After login, you are taken to page if you have appropriate role.
