### ISSUE TITLE
As a SO, I don't want users without a role logging into the site

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2899]
https://www-dev-new.colorado.edu/feature/2889/ is set up to test these changes together.

**Comment by kreynen** [comment]
I'm merging all of these into https://github.com/CuBoulder/express/tree/integration/2889 as they are ready

**Comment by cathysnider** [comment]
So, can't we just make them an authenticated user instead of confusing them by giving them a role?

**Comment by cathysnider** [comment]
https://www-dev-new.colorado.edu/p14738925336/
