### ISSUE TITLE
Revert Bean

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#2917]
Rather than deal with https://github.com/CuBoulder/express/issues/2881 in 2.9.7, we are going to revert the Bean changes from https://github.com/CuBoulder/express/issues/2800

**Comment by cathysnider** [comment]
Acceptance Criteria:

 - [ ] The problem documented in https://github.com/CuBoulder/express/issues/2881 ("After Upgrading Bean, Some Block Titles and Contextual Widgets are Duplicated") is no longer occurring.  No bean has a duplicate title or duplicate contextual widget.
