### ISSUE TITLE
Content Editor (Edit Only) role should be able to edit Advanced Content Bundle nodes and blocks

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2945]
**Advanced Content:**
Content List Page
Content List
Content Grid
Expandable
Video Reveal

**Comment by owenmorrill** [comment]
Cathy's writing tests.

**Comment by cathysnider** [comment]
Edit Only can edit but not create or delete:
 - [ ] Content List Page
 - [ ] Content List
 - [ ] Content Grid
 - [ ] Expandable
 - [ ] Video Reveal
