### ISSUE TITLE
Editing User notices

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#2948]
When editing a user and changing their role(s) I get the following warning:

Warning: array_key_exists(): The first argument should be either a string or an integer in {closure}() (line 340 of modules/custom/cu_users/cu_users.module).

**Comment by owenmorrill** [comment]
What branch and what role were you using when changing the role?

**Comment by kreynen** [comment]
https://github.com/CuBoulder/express/blob/dev/modules/custom/cu_users/cu_users.module#L340 is part of hook_user_presave() which would be removed if we merge https://github.com/CuBoulder/express/issues/2891
