### ISSUE TITLE
Video Reveal doesn't play video when clicked

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#2974]
Youtube changed the way a video can be autoplayed so right now a video reveal will require 2 clicks for a video to play - 1 to show the video, and then clicking the video play button.

**Comment by cathysnider** [comment]
I am not seeing this problem. All of these play when clicked once. Examples:
https://www.colorado.edu/demos/cathys-sandbox/blocks/video-reveal
https://www.colorado.edu/controller/sponsored-projects/level-budget-detail
https://www.colorado.edu/theatredance/mfa-experience-design
https://www.colorado.edu/ebio/block/undergraduate-overview-undergrad

**Comment by jwfuller** [comment]
Tested in Chrome and Safari, one-click also worked for me.

**Comment by jwfuller** [comment]
@kevincrafts Is going to verify that this is okay to close

**Comment by kevincrafts** [comment]
tested and confirmed working in multiple browsers
