### ISSUE TITLE
Bug: Enabling the Metatag module overwrites fix for Bug/1014

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2975]
**Describe the bug**

https://github.com/CuBoulder/express/pull/2941 fixed the "duplicate campus name in HTML page title" problem. Enabling any bundle that adds the Metatag module overrides this fix. -- i.e Social Media Bundle or Search Engine Optimization Bundle.

Before enabling metatag module, Home Page Title is correctly shown as  "Home | Site Name | University of Colorado"

After enabling the metatag module, the Home Page Title reverts to the old way of "Site Name | University of Colorado | University of Colorado|

**To Reproduce**
Create a site using Dev branch profile. 
Go to admin/settings and give site a name
Go to home page and observe HTML Page Title
Next, enable the Social Media Bundle or the Search Engine Optimization Bundle
Go to home page and observe incorrect HTML Page Title

**Screenshots**

Before enabling 
![before](https://user-images.githubusercontent.com/638275/47738094-05e56880-dc38-11e8-8689-0dd81dbfc61d.jpg)

After enabling 
![after](https://user-images.githubusercontent.com/638275/47738111-10076700-dc38-11e8-91aa-8af1e9099709.jpg)

**Comment by owenmorrill** [comment]
I'm getting "Site Name | Site Name | University of Colorado Boulder" which means the seo bundle might just be taking over the homepage title. Pages have "Page Title | Site Name | University of Colorado Boulder."

**Comment by cathysnider** [comment]
This issue duplicates the one that was fixed in https://github.com/CuBoulder/express/issues/1014. The Site Slogan needs to stop showing up on the Home Page.

![mysitetitle](https://user-images.githubusercontent.com/638275/50792672-fd865b00-1282-11e9-8a44-de86cc3f90da.jpg)

**Comment by cathysnider** [comment]
Closed for now until bigger problems are solved.
