### ISSUE TITLE
Old Custom Profile for Recreation generating 404s

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2977]
**Describe the bug**

The following asset is no longer on the system; generates approx 250 'Page Not Found' errors per day as system tries to reach it:
/recreation/profiles/cu_recreation/themes/rc/logo.png

Can we get that profile out of there?

**Kibana Report**

[Apache 404](https://osr-prod-log01.int.colorado.edu/app/kibana#/visualize/edit/AWQ-bQdZ1KL0mhto8L1i?_g=()&_a=(filters:!(),linked:!t,query:(match_all:()),uiState:(vis:(params:(sort:(columnIndex:!n,direction:!n)))),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(field:request,order:desc,orderBy:'1',size:30),schema:bucket,type:terms)),listeners:(),params:(perPage:30,showMeticsAtAllLevels:!f,showPartialRows:!f,showTotal:!f,sort:(columnIndex:!n,direction:!n),totalFunc:sum,type:table),title:'Apache%20404s',type:table)))
 
**Screenshots**

![apachekibana](https://user-images.githubusercontent.com/638275/48085304-15742c80-e1b7-11e8-911d-feb7647e6735.jpg)

**Comment by kevincrafts** [comment]
Not sure the title is accurate - something is linking to a logo from when the site had a custom profile - the linked Kibana report doesn't seem to show where the link comes from.

**Comment by cathysnider** [comment]
No, I thought the old theme profile was still up there. If it is not, then your assessment is correct -- its something else. 

Maybe this: https://recreation-portal.colorado.edu

**Comment by cathysnider** [comment]
Found this in source of page:
![screen shot 2018-11-06 at 4 16 13 pm](https://user-images.githubusercontent.com/638275/48100160-5ed87200-e1df-11e8-9e5a-e22b8b571474.png)

![screen shot 2018-11-06 at 4 15 29 pm](https://user-images.githubusercontent.com/638275/48100183-6bf56100-e1df-11e8-99ce-a75ac93d676a.png)

**Comment by cathysnider** [comment]
Never mind; this is not something we have control over.
