### ISSUE TITLE
As a SO/SE I would like a mega menu functionality on my site

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#2990]
As a So/SE I would like a configurable mega menu that would include links and minimal content that would appear upon clicking/tapping a main menu item.

![screen shot 2018-12-03 at 4 08 56 pm](https://user-images.githubusercontent.com/349713/49407421-c8339e00-f715-11e8-8289-96ae9de52b50.png)
![screen shot 2018-12-03 at 4 08 50 pm](https://user-images.githubusercontent.com/349713/49407422-c8cc3480-f715-11e8-826c-a1392996c1af.png)

**Comment by cathysnider** [comment]
It is looking pretty good:
https://www-test.colorado.edu/p126572608c9/

**Comment by jwfuller** [comment]
https://github.com/CuBoulder/express_mono/issues/48
