### ISSUE TITLE
Bug: No Box Colors in new Brand theme

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2991]
Colors and Styles are not being applied to the Box shortcode.

Code example: 
[box title="Light Gray Border" color="lightgray" style="border" float="none"]Cupcake ipsum dolor sit amet lollipop pastry. Gummi bears cupcake ice cream biscuit chocolate cake tiramisu. Croissant cupcake dragée.[/box]

Design Themes checked: Spirit, Ivory, Minimal and Traditional; failed in all four.

![boxcolors](https://user-images.githubusercontent.com/638275/49604561-678da680-f94b-11e8-9658-2fb1c1f8530a.png)

**Comment by kevincrafts** [comment]
https://github.com/CuBoulder/express/commit/0d2dcc1f4a2a29196d487d2cd5d1cfd7e3efad9c
