### ISSUE TITLE
Bug: Site Affiliation only showing in Tradition and Swatch themes

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2992]
**Expected Behavior**

When Display Affiliation is checked in Site Settings/Site Name (admin/settings/site-configuration/site-name), Site Affiliation should show in web site banner.

**Current Behavior**

The Site Affiliation only shows in themes Tradition and Swatch.

**Examples**

Swatch
![screen shot 2018-12-06 at 12 15 18 pm](https://user-images.githubusercontent.com/638275/49606724-58115c00-f951-11e8-8ca4-7b6072269209.png)

Highlight
![screen shot 2018-12-06 at 12 15 39 pm](https://user-images.githubusercontent.com/638275/49606745-63fd1e00-f951-11e8-8969-36cf120c4201.png)

**Comment by kevincrafts** [comment]
I have not been able to reproduce this.

**Comment by owenmorrill** [comment]
I've not been able to get an affiliation to show up on my sites.

**Comment by cathysnider** [comment]
@kevincrafts Please feel free to experiment with site name, affiliation and design at https://www-dev.colorado.edu/brandtest/

**Comment by kevincrafts** [comment]
This was an issue with me changing some variable names in my environment - seems to be working now

**Comment by cathysnider** [comment]
QA: The Site Affiliation shows in the main banner for all Design Themes. 
Example: Highlight Theme:
![screen shot 2019-01-04 at 11 42 49 am](https://user-images.githubusercontent.com/638275/50704805-e858c480-1015-11e9-8e00-2d8f2642dea5.png)
