### ISSUE TITLE
Bug: Buttongroup color not being applied to buttongroup

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2993]
Expected behavior of Buttongroup color is that 
 1. Buttongroup color overrides any individual button color. 
 1. If no color is assigned, buttongroup default to blue

This is not happening. The button group color is not being applied; there's no gold or default buttongroup color. 

**Code**

[buttongroup size="regular" color="gray"]
[button url="node/156" color="blue" icon="fa-birthday-cake"]Hydrology[/button]
[button url="node/156" color="black" icon="fa-bell"]Geodynamics[/button]
[button url="node/156" color="gold" icon="fa-bug"]Aerospace[/button]
[/buttongroup]

**What I see**
![buttongroup1](https://user-images.githubusercontent.com/638275/49608882-226f7180-f957-11e8-8314-e27cd0330bd6.jpg)

**What I should see**
![buttongroup2](https://user-images.githubusercontent.com/638275/49608888-2a2f1600-f957-11e8-9309-70aaa7baa169.jpg)

**Comment by kevincrafts** [comment]
https://github.com/CuBoulder/express/commit/e6813421ee22eecdaeb79425e74822c0263c9eff
https://github.com/CuBoulder/express/commit/12c1eea456880eaee679f148c9571b28ec19ab25
