### ISSUE TITLE
Bug: Hero Image breaking out of content area

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#2997]
An image placed as size Hero on a node with Feature Layout breaks out of the left side boundary.  And is significantly offset.

This problem is very similar to what was solved in https://github.com/CuBoulder/express/pull/2873
Shadow Theme + Node with Feature Layout + Hero Image in Content area == images breaks out of content boundary.

![screen shot 2018-12-06 at 1 50 35 pm](https://user-images.githubusercontent.com/638275/49611166-f4d9f680-f95d-11e8-93c6-6d9779eb6566.png)

**Comment by kevincrafts** [comment]
https://github.com/CuBoulder/express/commit/558ba9b6f883c085f304468532452978de3fbf2e
