### ISSUE TITLE
Bug: Class attribute being stripped from Div tag

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3003]
The class attrigute is being stripped from the div tag, so no background colors are showing up.

**Example: This code is typed in**
< div class="padding background-black" >Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. < /div >

**But this is the code that is rendered by Web Express:**
< div >Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.< /div >

**Resulting in this:**

![screen shot 2018-12-11 at 11 23 36 am](https://user-images.githubusercontent.com/638275/49821422-9fc02b00-fd37-11e8-89cd-56fbd0e49710.png)

**Comment by kevincrafts** [comment]
This is expected behavior - we have always discouraged the editing of html and adding classes in the wysiwyg.

These colors will be implemented in Web Express through block designer, hero units, and block sections.

**Comment by cathysnider** [comment]
These work as box colors too. 
![screen shot 2018-12-11 at 2 20 17 pm](https://user-images.githubusercontent.com/638275/49831036-179a4f80-fd50-11e8-8ea8-df6677313356.png)
