### ISSUE TITLE
Regions: Inner Left Region is not floating left

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3006]
**Describe the bug**
A text block was created via Page Layout in the Inner Left Region.  The block is stretching across the content area instead of floating left.

https://www-dev.colorado.edu/brandtest/regions

![screen shot 2018-12-13 at 12 00 11 pm](https://user-images.githubusercontent.com/638275/49960968-aaf98f00-fece-11e8-8750-5dbab79a091d.png)

**Comment by kevincrafts** [comment]
https://github.com/CuBoulder/express/commit/7e5c18eb579cfcbb4433d84f03790993346c9c6b
