### ISSUE TITLE
Clear Shortcode is not working

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3007]
**Describe the bug**
[ clear /] should clear floats. It is not.

**Images:**
https://www-dev.colorado.edu/brandtest/img-caption/clearing-float
![screen shot 2018-12-13 at 1 40 37 pm](https://user-images.githubusercontent.com/638275/49966401-16e2f400-fedd-11e8-8d82-b2e8ed8fcafd.png)

**Columns:**
A column set, which has the last column considerably shorter than the other two, doesn’t clear the last column, even if you put a [clear/] after it. This is a problem in production but I did not notice it earlier.

https://www-dev.colorado.edu/brandtest/shortcodes/columns
![columnshortcode](https://user-images.githubusercontent.com/638275/49961451-eb0d4180-fecf-11e8-97ca-a137311b5037.gif)

Note how the text “Paragraph following the Triple Column” isn’t starting at the far left.

**Comment by kevincrafts** [comment]
https://github.com/CuBoulder/express/commit/44330f0c3eb5962daf1eb0c44ec87d7630378278
