### ISSUE TITLE
Icons: Medium Gray for icon doesn't match Medium Gray for background

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3008]
**Describe the bug**

The Gray Icon should probably be darker, eh? It should be same color gray as the Gray Icon Backgrounds.

https://www-dev.colorado.edu/brandtest/shortcodes/icon-sizes-colors-and-styles
 
![grayicon](https://user-images.githubusercontent.com/638275/49961712-95856480-fed0-11e8-8278-79c702d70f90.gif)

**Comment by kevincrafts** [comment]
https://github.com/CuBoulder/express/commit/26792ad500ccb7a511f88f2d993a39ba6123aa04
