### ISSUE TITLE
Block Background Color combinations: some are problematic

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3009]
**Describe the bug**

Here's a comparison of all the block background colors: 
https://www-dev.colorado.edu/brandtest/block-rows

Some of the color combos are problematic:
All Light colored backgrounds on Brick == can't see the link

Dark Gray block on Light background == link hard to make out

White block on Dark Gray == link hard to make out

All Light colored backgrounds on Dark Blue == can't see the link

![screen shot 2018-12-13 at 12 23 42 pm](https://user-images.githubusercontent.com/638275/49962245-fc574d80-fed1-11e8-8216-878223e26b22.png)

![screen shot 2018-12-13 at 12 23 14 pm](https://user-images.githubusercontent.com/638275/49962238-f6616c80-fed1-11e8-9fa1-ada94555586f.png)

![screen shot 2018-12-13 at 12 22 22 pm](https://user-images.githubusercontent.com/638275/49962175-d5008080-fed1-11e8-95c6-f54789d84f58.png)

**Comment by kevincrafts** [comment]
https://github.com/CuBoulder/express/commit/082a9ebcb9942b4d808a099b10fed370bffe8752
