### ISSUE TITLE
Dark Gray Banner in new Branding is two-colored; should be one color

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3010]
**Describe the bug**
Two Themes have a Dark Gray banner: Rise and Layers. In both themes, the Banner background of the Site Name is two colored: Gray and Dark Gray. It should be only Dark Gray. 

#Example:#
https://www-dev.colorado.edu/brandtest/

**Rise:**
![riseintrowide1](https://user-images.githubusercontent.com/638275/50111908-1e670d80-01fb-11e9-8297-ea831a873b99.png)

Here's how Rise looks in Prod:
![riseintrowide2](https://user-images.githubusercontent.com/638275/50111954-36d72800-01fb-11e9-901f-ef373d66ab69.png)

Layers
![screen shot 2018-12-17 at 2 18 35 pm](https://user-images.githubusercontent.com/638275/50116333-1c0ab080-0207-11e9-9560-3dda035e2778.png)

**Comment by kevincrafts** [comment]
https://github.com/CuBoulder/express/commit/624facf3ef0de252bc7798818f9351a61c7ea8b9
