### ISSUE TITLE
Rise theme in New Branding: Main Nav needs lower margin

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3011]
**Describe the bug**
No room for bread crump trail, and sliders bump right against it.
https://www-dev.colorado.edu/brandtest/shortcodes-0

![screen shot 2018-12-17 at 12 48 12 pm](https://user-images.githubusercontent.com/638275/50112347-44d97880-01fc-11e9-87de-63ec7cb74cbb.png)
![screen shot 2018-12-17 at 1 02 10 pm](https://user-images.githubusercontent.com/638275/50112382-57ec4880-01fc-11e9-93cd-b2b346224f6b.png)

There should be space enough under the Main Nav for bread crumb trail
![screen shot 2018-12-17 at 1 05 49 pm](https://user-images.githubusercontent.com/638275/50112467-8702ba00-01fc-11e9-93a1-6687e5ad5b2d.png)

**Comment by kevincrafts** [comment]
https://github.com/CuBoulder/express/commit/ea5ac9bece9f00ca7dba44e738bbdee0fd3e6bb7
