### ISSUE TITLE
Light Gray Slider Regions have White Block Titles - i.e. unreadable

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3012]
**Describe the bug**
A block placed in the slider region of a themes that has a light gray slider region -- examples Ivory and Rise Light -- have white Block Titles. This is not accessible.

![slidertitle](https://user-images.githubusercontent.com/638275/50113261-aa2e6900-01fe-11e9-8bb8-abc0e812ea03.jpg)

https://www-dev.colorado.edu/brandtest/home-page-3

**Comment by kevincrafts** [comment]
https://github.com/CuBoulder/express/commit/26e462795aab7d54cff6ca970a103fa847db7b14
