### ISSUE TITLE
Hero Unit Text: When text color is set to White, it is displayed as Black

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3013]
A hero unit, set to use white text, does not. It's all black. Using an overlay doesn't change it.

https://www-dev.colorado.edu/brandtest/page-hero-units

![screen shot 2018-12-17 at 4 00 56 pm](https://user-images.githubusercontent.com/638275/50121185-292e9c00-0215-11e9-98a6-215b03643a9d.png)

**Comment by kevincrafts** [comment]
https://github.com/CuBoulder/express/commit/20d108e967269a5eeec7a431bd374189006ea8f0

**Comment by cathysnider** [comment]
Looks good!

![screen shot 2019-01-11 at 9 50 04 am](https://user-images.githubusercontent.com/638275/51047660-4c373c00-1586-11e9-980a-677f0eb740ca.png)
