### ISSUE TITLE
Block Row Padding is off

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3019]
A Block Row on its own has lots of left and right interior padding. 

A Block Row within a Block Section has lots of left and right exterior margin. 

I'm not sure if this is what is intended.

https://www-dev.colorado.edu/brandtest/block-row-distribution-test

![blockrowdistribution1](https://user-images.githubusercontent.com/638275/50367367-0534c880-053d-11e9-9e55-5507249c04d8.jpg)

![blockrowdistribution2](https://user-images.githubusercontent.com/638275/50367374-11208a80-053d-11e9-891f-5d50a178e6ab.jpg)

**Comment by kevincrafts** [comment]
https://github.com/CuBoulder/express/commit/7ef7ce57674db9383c4bff86a02d01c8e64a7351

**Comment by cathysnider** [comment]
The padding is much better:
![screen shot 2019-01-08 at 9 38 02 am](https://user-images.githubusercontent.com/638275/50845094-5a3c5100-1329-11e9-87bb-10d9afe0b05f.png)
