### ISSUE TITLE
Shortcode Give Button colors are not working

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3021]
The Shortcode Give button is supposed to have three color options: Dark, Light and Gold. However, none of the colors are being displayed; they are all defaulting to blue. This is occurring in all themes.

https://www-dev.colorado.edu/brandtest/shortcodes/give-shortcode-button

**Screenshots**

Here is what they look like in the new branded theme:
![screen shot 2019-01-02 at 10 07 09 am](https://user-images.githubusercontent.com/638275/50603047-5e262a00-0e76-11e9-97f0-a924bc5cb3e0.png)

Here is what they are supposed to look like: 
![screen shot 2019-01-02 at 10 10 02 am](https://user-images.githubusercontent.com/638275/50603120-a80f1000-0e76-11e9-9ed4-08bcd8bd9254.png)

**Comment by kevincrafts** [comment]
https://github.com/CuBoulder/express/commit/8f3fb372510c05a663951271f34cd3200dd8d018

**Comment by cathysnider** [comment]
Fixed: 
![screen shot 2019-01-08 at 9 25 35 am](https://user-images.githubusercontent.com/638275/50844488-139a2700-1328-11e9-8f88-76884b23c185.png)
