### ISSUE TITLE
Bug: Site Affiliation is for Branding; should not be exposed in 2.10 release.

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3022]
**Describe the bug**
A little of the Site Affiliation code has been pushed to 2.10. The functionality is both 1) incomplete and 2) not scheduled to be released with 2.10

**To Reproduce**
go to admin/settings/site-configuration/site-name on a dev site
https://www-dev.colorado.edu/testing/cathy-1/admin/settings/site-configuration/site-name

**Expected behavior**
I should not see Site Affiliation

**Screenshots**
![siteaffiliationbroken](https://user-images.githubusercontent.com/638275/50706258-8b134200-101a-11e9-9f2c-3bc97e9173fd.jpg)

**Comment by kreynen** [comment]
After discussing this with @kevincrafts and @jbertrand, the decision was that since most of the 1200 sites will have an affiliation this is considered acceptable.  There will only be a few site types like events that won't be affiliated.
