### ISSUE TITLE
Bug: CTools CSS Cache is misconfigured in 2.10

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3023]
**Describe the bug**
The test sites on dev which are running 2.10 all report a problem with CTools CSS Cache: 
"Unable to create; The CTools CSS cache directory, ctools/css could not be created due to a misconfigured files directory. Please ensure that the files directory is correctly configured and that the webserver has permission to create directories."

**Screenshots**
![screen shot 2019-01-08 at 9 44 26 am](https://user-images.githubusercontent.com/638275/50845494-3a595d00-132a-11e9-9565-dee539cb6498.png)

**Examples**
https://www-dev.colorado.edu/p12fbbd902ef/
https://www-dev.colorado.edu/feature/2889/
https://www-dev.colorado.edu/schedulingtest/
https://www-dev.colorado.edu/testing/cathy-1/

**Comment by kreynen** [comment]
This is a server/hosting issue
