### ISSUE TITLE
Bug: on site /cisc, Administrator role has lost ability to edit a webform. 

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3030]
Users with the administrator role cannot edit a webform on this particular site. 

To test: Login to https://www.colorado.edu/cisc/ as user 'osr-test-form-mgr' which has been given the 'administrator' role for now. Verify on the Dashboard that you have the administrator role.
![webforms3](https://user-images.githubusercontent.com/638275/51209145-ca6c4900-18cc-11e9-8460-dda64a17c382.png)

Go to https://www.colorado.edu/cisc/admin/content/webform and under 'Operations' column choose 'Edit' 
![webforms1](https://user-images.githubusercontent.com/638275/51209159-d2c48400-18cc-11e9-9f7a-2caed9fc9d68.png)

Note that you are getting 'Access denied.'
![webforms2](https://user-images.githubusercontent.com/638275/51209185-e112a000-18cc-11e9-955d-88e8afb2fe13.png)

No other site that we've checked is showing this problem, only /cisc

**Comment by owenmorrill** [comment]
Secure permissions flush/save fixed this bug.

**Comment by cathysnider** [comment]
Looks good; working now.
