### ISSUE TITLE
Certain character combinations in the URL of a button are converted to their ASCII equivalent

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#3048]
**Describe the bug**
Certain character combinations in the URL of a button are converted to their ASCII equivalent when saved.  An example is adding &gtm=on to a URL results in <m=on because CKEditor is seeing this as &gt; 

https://www.w3schools.com/charsets/ref_html_symbols.asp

**To Reproduce**
1. Go to 'node/add/page'
2.  Enter any title
3. In the body, add a button with the URL that includes the query sting ?test=no&gtm=on
4. Save the node
5. See error

**Comment by kevincrafts** [comment]
A workaround for this would be to move the gtm value to the beginning of the string so it would be ?gtm instead of &gtm
