### ISSUE TITLE
Administrators were granted too many permissions to edit roles

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#3058]
A user with the Administrator role is missing any role related fields when they try to edit a user

**Comment by kreynen** [comment]
We merged https://github.com/CuBoulder/express/commit/170a1b5eb7ff72aa2be30c626f37cbf9674ff4fb as a quick fix, but this over grants permissions to the point it would be a problem if secure_permissions isn't locking the permission grid UI

**Comment by jwfuller** [comment]
https://github.com/CuBoulder/express_mono/issues/114
