### ISSUE TITLE
Improve Last Edit Logic for Atlas Stats

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#3063]
With, we had to restore a site to a pre-update backup before.  In looking at how Atlas determines when a site needs to be backed up, this needs to be improved. The atlas statistic module only uses the change date of nodes to determine that date.  In addition to many other things that could have changed on a site (layouts, context, configuration, theme, webform submissions, users permissions, etc), the way this date is calculated is problematic since deleting nodes could result in the edit date being much older.  

We need to find a better way to deal with this if we are going to be using these backups on these servers for another 2+ years.

https://github.com/CuBoulder/atlas/blob/dev/atlas/tasks.py#L1042
https://github.com/CuBoulder/express/blob/dev/modules/custom/atlas/atlas_statistics/atlas_statistics.inc#L52

**Comment by jwfuller** [comment]
Issue moved to [CuBoulder/express_mono #105](https://github.com/CuBoulder/express_mono/issues/105) via [**ZenHub**](https://www.zenhub.com/)
