### ISSUE TITLE
Block Sections with Article Grid: Light backgrounds have white text which is unreadable

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3083]
Also review the medium colors: Gold on Medium Blue is a poor combo; 

![screen shot 2019-02-21 at 12 56 56 pm](https://user-images.githubusercontent.com/638275/53197852-5104fc00-35d8-11e9-85b8-e552fa3382e3.png)

![screen shot 2019-02-21 at 12 57 46 pm](https://user-images.githubusercontent.com/638275/53197864-595d3700-35d8-11e9-844b-db9ea40f08f3.png)

**Comment by kevincrafts** [comment]
I can't reproduce this problem - check the block section configuration to see what the text color is set to.
