### ISSUE TITLE
Improve www-test GTM hack

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#3094]
Prod and test use different GTM instances so site users can place pixels and then are migrated/imported to the prod instance.

Every time a site is synced from prod to test, the GTM instance is reset to the prod instance.

We need to merge https://github.com/CuBoulder/express/pull/3091 to be able to continue to review

**Comment by jwfuller** [comment]
https://github.com/CuBoulder/express_mono/issues/117
