### ISSUE TITLE
Secondary Menu Label not properly aligned

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3099]
The Secondary Menu Label is appearing above the menu links. It should appear to the left:

**On Test:**
https://www-test.colorado.edu/music/
![screen shot 2019-02-22 at 4 16 20 pm](https://user-images.githubusercontent.com/638275/53276738-b0890780-36bd-11e9-8993-6922089a5348.png)

**On Prod: How it should be:**
https://www.colorado.edu/music/
![screen shot 2019-02-22 at 4 20 43 pm](https://user-images.githubusercontent.com/638275/53276773-d57d7a80-36bd-11e9-8f7e-68c46f29319a.png)

To reproduce, go to admin/structure/menu/settings and enter text in the Secondary Menu Label field.

**Comment by kevincrafts** [comment]
closing as a duplicate
