### ISSUE TITLE
Social icons on homepage footer are displayed as grey squares

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#3103]
I thought this might be related to https://github.com/CuBoulder/express/pull/3079, but it's still an issue

![screen shot 2019-02-25 at 9 05 38 am](https://user-images.githubusercontent.com/385234/53350679-d6d8be00-38dc-11e9-81a1-1755b2a51da9.png)

**Comment by kevincrafts** [comment]
Homepage social icons use a full html text block - classes needed to be updated
