### ISSUE TITLE
Partner images are HUGE

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#3118]
https://www-test.colorado.edu/alumni/ vs. https://www.colorado.edu/alumni/

![screen shot 2019-02-25 at 2 39 40 pm](https://user-images.githubusercontent.com/385234/53370551-3e0d6700-390b-11e9-89d1-48c4a462a8f4.png)

**Comment by kevincrafts** [comment]
This should be fixed by https://github.com/CuBoulder/express/pull/3096

**Comment by kreynen** [comment]
Confirmed fix on www-test
