### ISSUE TITLE
Existing Five Column Content Grids are displayed vertically

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3135]
Pre-existing Five Column Content Grids are displayed vertically. 

This does not happen in content grids that are created WebExp 3.0; only ones that are migrated from an earlier version. 
 
Examples: 
https://www-test.colorado.edu/orientation/contact-us
https://www-test.colorado.edu/engineering/
![screen shot 2019-02-26 at 9 59 06 am](https://user-images.githubusercontent.com/638275/53431543-fc81c800-39ad-11e9-9129-0c0bd4495c7c.png)

Example of Content Grids created in 3.0
https://www-test.colorado.edu/p1a52ecf7f71/content-grids
![screen shot 2019-02-26 at 10 02 11 am](https://user-images.githubusercontent.com/638275/53431561-0277a900-39ae-11e9-95c4-a0fb44a3badc.png)

**Comment by kevincrafts** [comment]
https://github.com/CuBoulder/express/issues/3095
