### ISSUE TITLE
Pre-existing slider in Above Content Area does not fill space

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3136]
A pre-exisiting slider in Above Content regiion does not fill entire content area. 

This does not happen with sliders that are created in WebExp 3.0; only ones that are migrated from an earlier version.

Examples:
https://www-test.colorado.edu/engineering/news
![screen shot 2019-02-26 at 10 11 34 am](https://user-images.githubusercontent.com/638275/53432880-98acce80-39b0-11e9-89ef-b97cb636b2df.png)

Example of same slider created in 3.0:
https://www-test.colorado.edu/p1a52ecf7f71/

As it appears in PROD
https://www.colorado.edu/engineering/news
![screen shot 2019-02-26 at 10 25 17 am](https://user-images.githubusercontent.com/638275/53433009-d6115c00-39b0-11e9-8742-a9d9e7834843.png)

**Comment by kevincrafts** [comment]
https://github.com/CuBoulder/express/pull/3153
