### ISSUE TITLE
Block Row content spans entire region

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3142]
The Block Row, when placed in  a Wide Region, should constrain its interior blocks to the width of the Main Content Region, not let them go spanning the entire width of the Wide Region.

**Examples:**
https://www-test.colorado.edu/libraries/

https://www-test.colorado.edu/engineering/news
![screen shot 2019-02-26 at 12 39 02 pm](https://user-images.githubusercontent.com/638275/53441384-f7c80e80-39c3-11e9-9881-9cc881e31aba.png)

**How it should be:**
https://www.colorado.edu/engineering/news
![screen shot 2019-02-26 at 12 40 13 pm](https://user-images.githubusercontent.com/638275/53441394-ff87b300-39c3-11e9-8e4c-82f52991d4c4.png)

**Comment by kevincrafts** [comment]
This issue is caused by people adding block rows directly into wide sections. We had some previous code that set a max-width on block rows, however, no other blocks had this.  I think we should make blocks work consistently and fix this sites before hand by adding the block rows to block sections.
