### ISSUE TITLE
osr-test accounts showing up for SOs again in admin/people

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#3154]
![screen shot 2019-02-27 at 10 12 56 am](https://user-images.githubusercontent.com/385234/53514137-3de4a700-3a84-11e9-8ecc-0e15997907fb.png)

**Comment by cathysnider** [comment]
They do not show up for 'Regular' site owners, only for the OSR Test Owner. So this is working as designed.

Here's Site Owner as regular LDAP user: 
![screen shot 2019-02-27 at 11 57 01 am](https://user-images.githubusercontent.com/638275/53515307-e4ca4280-3a86-11e9-9cd2-736c3bc0dc15.png)
