### ISSUE TITLE
Roles: Content Editor (Edit Only) should show in roles, NOT Content Editor (Deprecated)

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3155]
To Reproduce: 

1) Sign on to https://www-dev.colorado.edu/p1cd63b31331/user as a Site Owner
2) Go to admin/people and promote someone (for testing purposes, all WebExp folk have been demoted to regular roles.)
3) Go to Promote Existing Users tab. 
4) You should see 'Content Editor Edit Only' and NOT 'Content Editor Deprecated'

![screen shot 2019-02-27 at 12 10 21 pm](https://user-images.githubusercontent.com/638275/53516193-f1e83100-3a88-11e9-80f8-92ced365bf95.png)

**Comment by kreynen** [comment]
I can't reproduce this on sites updated from 2.10.0 or cleanly installed 3.0.0 sites.  It's possible that issue only impacted a dev site that was updated from something like 2.9.5 -> 3.0.0.  3.0.0 removed the 2.x update hook so it REQUIRES the site to update to the last version to the 2.x branch before updating to 3.x.  

This is the same thing we did with 1.x -> 2.0.
