### ISSUE TITLE
As a SM I want to temporarily disabled the Bundle UI

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#3173]

**Comment by kevincrafts** [comment]
drush vset disable_bundle_ui 1

**Comment by kreynen** [comment]
We still need to reconcile what was merged into 3.0.0 and what was merged into 2.10.1 after 3.0 is deployed

**Comment by jwfuller** [comment]
https://github.com/CuBoulder/express_mono/issues/109
