### ISSUE TITLE
Icon alignment off on Fiske page with custom HTML

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#3192]
https://www.colorado.edu/fiske/showtimes

![showtimes___fiske_planetarium___university_of_colorado_boulder](https://user-images.githubusercontent.com/385234/53904889-5d3f7f00-4004-11e9-84b4-1494f73e9989.png)

**Comment by kevincrafts** [comment]
This issue is actually caused by the custom javascript we've allowed them to have on their site - I have added some css just so this doesn't happen.
