### ISSUE TITLE
Icons have transparent or no color 

### ISSUE THREAD

**Issue by jbertrand** [CuBoulder/express#3193]
Wendy noticed that the icon colors are not showing correctly on homepage. You can see an example on the homepage about section: https://www.colorado.edu/about

**Comment by kevincrafts** [comment]
I think this was a block section configuration issue - the icons were set to be light gray on a white background - set the text color to white/background color to black

**Comment by jbertrand** [comment]
![icon-fade-example](https://user-images.githubusercontent.com/1840123/53907780-228d1500-400b-11e9-92b3-05229332d439.jpg)
