### ISSUE TITLE
Issue with breadcrumbs not lining up on homepage

### ISSUE THREAD

**Issue by jbertrand** [CuBoulder/express#3194]
Received this from the admissions team:
 I did notice a small formatting issue in IE and Firefox (didn’t see it in Chrome). Jo, you’re probably already working on it, but just in case:

They are all on PCs.

**Comment by jbertrand** [comment]
![breadcrumb_notlining_up](https://user-images.githubusercontent.com/1840123/53909971-09d32e00-4010-11e9-88da-4452f14e1d16.jpg)

**Comment by kevincrafts** [comment]
This was an issue on the homepage theme which was fixed
