### ISSUE TITLE
Text overlapping on ecenter

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#3210]
https://www.colorado.edu/ecenter/bioneers/ongoing-events

![screen shot 2019-03-08 at 8 41 27 am](https://user-images.githubusercontent.com/385234/54038611-2ee5af00-417e-11e9-8d35-666e669fbe95.png)

**Comment by kevincrafts** [comment]
This is not a new issue with 3.0. I tested the content with previous Express versions.

User has entered a long, no-spaces string that won't wrap.
