### ISSUE TITLE
Reduced weight of text makes it unreadable

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#3215]
![screen shot 2019-03-08 at 10 19 29 am](https://user-images.githubusercontent.com/385234/54044242-b84fae00-418b-11e9-9d91-944240e1afe4.png)

current https://www.colorado.edu/ceae/current-students vs. older version https://web.archive.org/web/20170919112350/https://www.colorado.edu/ceae/current-students

The wayback version doesn't have the background image, but you can see the front changes

**Comment by kevincrafts** [comment]
This is a setting they have chosen. They have changed these settings between when the archive was captured.
