### ISSUE TITLE
Add New Slider block in Edit Layout view has two link fields

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3234]
When adding a Slider in Edit Layout view, there are two link fields. 
(node/3/layout for example)

The second link field does not show when creating a slider block from the Block page (/block/add/slider)

![Screen Shot 2019-03-11 at 2 32 38 PM](https://user-images.githubusercontent.com/638275/54156173-4d140f00-440b-11e9-9db3-d8bde1bdf960.png)

**Comment by kevincrafts** [comment]
This isn't something introduced in 3.0 - this field was the original way to link a slider which we hide in the normal form interface but never hid in the inline form interface.

The pr deletes the old field entirely.
