### ISSUE TITLE
Content block overlaying another block when applying block design

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#3243]
**Describe the bug**
This is not a typical page layout but if you are using a block in the below content region and then you add a block in the inner right region, then the inner right block is overlapped and you cannot click on the gear for the block to edit it.

If you add a block style to the block in the below content region and then cover the content of the block in the inner right region

**To Reproduce**
1. Go to 'Edit Layouts'
2. Click on 'Add new block in the below content region'
3. Save and Update Layout
4. Go to 'Edit Layouts'
5. Click on 'Add new block in the inner right region'
6. Save and Update Layout
7. Click on the gear in the top right and select block designer and apply a block style

**Expected behavior**

**Screenshots**
![Below content and inner right block](https://user-images.githubusercontent.com/16137919/54223122-704ac700-44bc-11e9-8be0-22b66c4f9348.JPG)
After step 6
![below content block with block style](https://user-images.githubusercontent.com/16137919/54223225-a25c2900-44bc-11e9-9f41-c99c5b49263f.JPG)
After step 7

**Desktop (please complete the following information):**
 - OS: PC
 - Browser Chrome
 - Version latest

**Comment by cathysnider** [comment]
This is actually working as designed. The 'Below content' region appears directly below whatever is put in the WYSIWYG body field. There's no point in using the Below Content region if you have no content in the body field.

**Comment by kevincrafts** [comment]
This is from multiple elements set to display the contextual links - I'm not wanting to try and change this as this could introduce problems elsewhere as this is a style and properties that come from Drupal core and changing it may cause other issues.

**Comment by kevincrafts** [comment]
Also, the overlap does not happen when you're logged out I believe
