### ISSUE TITLE
Readability issues on Expandables with Colored Backgrounds:

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3252]
Some of the color combos for Expandable with Horizontal tabs are problematic:

Dark Gray is the most unreadable; other colors are a little funky.
https://www.colorado.edu/grandchallenges/documenting-change

https://www-dev.colorado.edu/p17558f24e44/expandables-colored-backgrounds
![Screen Shot 2019-03-14 at 11 49 02 AM](https://user-images.githubusercontent.com/638275/54380219-93a67b00-4650-11e9-8e32-10f66cf2b49a.png)
![Screen Shot 2019-03-14 at 11 49 12 AM](https://user-images.githubusercontent.com/638275/54380229-9903c580-4650-11e9-9a0f-ee2978bb7c36.png)
![Screen Shot 2019-03-14 at 11 49 23 AM](https://user-images.githubusercontent.com/638275/54380246-9dc87980-4650-11e9-9d59-c7cc643a231f.png)

**Comment by jwfuller** [comment]
https://github.com/CuBoulder/express_mono/issues/10
