### ISSUE TITLE
Height of site header container fluctuates between home page and any other page

### ISSUE THREAD

**Issue by johnquest** [CuBoulder/express#3253]
Seems to do this in all themes - height of non-home page header container is shorter than on homepage

**Comment by cathysnider** [comment]
Examples showing screenshots from two pages side by side:

![example1](https://user-images.githubusercontent.com/638275/54392253-c65e6c80-466c-11e9-819d-892b49b20dc5.jpg)

![example2](https://user-images.githubusercontent.com/638275/54392272-d1b19800-466c-11e9-9ff0-6ee7b8bfef66.jpg)

**Comment by jwfuller** [comment]
https://github.com/CuBoulder/express_mono/issues/9
