### ISSUE TITLE
Form blocks placed in block sections with white text could be improved

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#3258]
The default styling of form elements were done with the idea of them being placed on white backgrounds. Testing of form blocks being added to block sections with dark backgrounds/white text is less than ideal.

![Screen Shot 2019-03-19 at 10 56 37 AM](https://user-images.githubusercontent.com/349713/54626010-f4a9c680-4a35-11e9-82a3-808e7730689b.png)

**Comment by jwfuller** [comment]
https://github.com/CuBoulder/express_mono/issues/8
