### ISSUE TITLE
Nested elements with different background colors may not use the correct text and link colors

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#3262]

**Comment by cathysnider** [comment]
## Here are some examples of super-nested stuff: 

### The Herd

Start with a text block (so far so good)
https://www.colorado.edu/theherd/block/text-block-events-interested-in

Wrap it in a block section: (still looks good)
https://www.colorado.edu/theherd/block/block-section-events-interested-

Place it in a block row: (still good)
https://www.colorado.edu/theherd/block/block-row-traditions-page-intere
![Screen Shot 2019-04-03 at 10 40 30 AM](https://user-images.githubusercontent.com/638275/55496740-f611ec00-55fc-11e9-9d3b-23514107f80c.png)

Now wrap it in a block section and put it on a page: (no longer good)
https://www.colorado.edu/theherd/block/block-section-events-page-intere

Final:
https://www.colorado.edu/theherd/events
![Screen Shot 2019-04-03 at 10 41 09 AM](https://user-images.githubusercontent.com/638275/55496776-07f38f00-55fd-11e9-829d-b1b453ec4cba.png)

### Biochemistry Shared Instruments Pool

Expandable with Dark Gray background
https://www.colorado.edu/lab/biochem-instruments/imaging-systems

![Screen Shot 2019-04-04 at 12 12 38 PM](https://user-images.githubusercontent.com/638275/55578618-976b7180-56d3-11e9-9041-b7b486fefba3.png)

**Comment by kevincrafts** [comment]
#3274

**Comment by jwfuller** [comment]
https://github.com/CuBoulder/express_mono/issues/6
