### ISSUE TITLE
The Forms bundles is not displayed on the Enabled Bundles tab when it is enabled on a site

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#3264]
The Forms bundles is not displayed on the Enabled Bundles tab when it is enabled on a site

**Comment by cathysnider** [comment]
Verification: No Longer True
The Forms bundle IS displayed on Enabled Bundles tab. 
Three sites tested, all on www-test: 
one unlaunched, running Drupal 7.67 and Express 3.0.2
two launched, running Drupal 7.66 and Express 3.0.2


![Screen Shot 2019-05-14 at 11 30 23 AM](https://user-images.githubusercontent.com/638275/57718875-b1d22c80-763b-11e9-8bf0-b76f3dcb8a3a.png)

**Comment by cathysnider** [comment]
Issue has solved itself.
