### ISSUE TITLE
When a block is relabeled, it should be given a new URL

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3266]
Or maybe this is a stupid idea; I dunno ... 

As a site gets older, more and more blocks become unused. 

Currently, if one of them is repurposed and relabeled, the old URL stays the same. This could leave to confusion.

Example: This previously unused block was repurposed:
https://www.colorado.edu/business/block/aacsb-page-feature-stats-2016

It has been placed here:
https://www.colorado.edu/business/students/career-development/career-search-steps

This is not that big a problem, but it could lead to confusion on the part of our Site Builders, when the URL doesn't match the Label.

**Comment by kevincrafts** [comment]
Drupal uses the block labels as deltas and identifiers in many cases, so these cannot be changed without rewriting a ton of core and contrib code.
