### ISSUE TITLE
Content Grid: a Teaser View with minimal text has bad layout

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3267]
If a Content Grid has minimal text, but is set to Teaser View, the layout is incorrect. 

The photos should be vertically aligned with the text to the right; instead they are laid out horizontally.

Examples:
https://www.colorado.edu/center/british-irish-studies/our-people
![Screen Shot 2019-03-28 at 11 11 31 AM](https://user-images.githubusercontent.com/638275/55178064-4ba44f80-514a-11e9-86ad-1082f3174cd6.png)

https://www.colorado.edu/demos/cathys-sandbox/blocks/content-grids/content-grid-teaser
![Screen Shot 2019-03-28 at 11 14 46 AM](https://user-images.githubusercontent.com/638275/55178297-bd7c9900-514a-11e9-9d36-844ebcdd07d7.png)

**Comment by jwfuller** [comment]
https://github.com/CuBoulder/express_mono/issues/4
