### ISSUE TITLE
Administrator role cannot edit Mega Menus

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#3270]
**Describe the bug**
Developers and Site Owners can create Mega Menus. Administrators cannot. This is an oversight in permissions. 
When an administrator goes to /admin/structure/mega-menu, they get an 'Access Denied' message.

**Expected behavior**
Administrators be able to create and edit Mega Menus

**Comment by cathysnider** [comment]
Verified May 14 2019

Administrator role is denied access to /admin/structure/mega-menu 

![megaMenus](https://user-images.githubusercontent.com/638275/57717010-7c2b4480-7637-11e9-97b5-2f5b4f66cd25.jpg)

**Comment by jwfuller** [comment]
https://github.com/CuBoulder/express_mono/issues/48
