### ISSUE TITLE
Group filter in localist block not setting saved value when edited

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#3272]

**Comment by kevincrafts** [comment]
https://github.com/CuBoulder/express_localist_bundle/pull/30

**Comment by cathysnider** [comment]
Problem: When a block has selected a Group filter, and then that block is re-edited and saved, all selections are cleared and the block reverts back default.

Working in test environment: 
https://www-test.colorado.edu/p1eda09dd943/block/interests-and-groups/view

**Comment by cathysnider** [comment]
After updates of May 2, the block is still working in the test environment:. A Localist block with a Group filter selected will maintain that filter through the operations of editing and savings:

- https://www-test.colorado.edu/menv/block/localist-events-homepage/view
- https://www-test.colorado.edu/bursar/block/bursar-dates--deadlines
- https://www-test.colorado.edu/ethnicstudies/block/department-events/view
