### ISSUE TITLE
Related Articles calculation off because term reference field is storing multiple rows with the same value

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#3277]
This means the query asking for articles with a particular term may get more results than it should because there are multiple non-unique values in the database.
![Screen Shot 2019-04-19 at 12 08 18 PM](https://user-images.githubusercontent.com/349713/56438196-4779d680-629f-11e9-87f7-6490bf9c3657.png)

**Comment by jwfuller** [comment]
https://github.com/CuBoulder/express_mono/issues/1
