### ISSUE TITLE
Cannot make a new Express site using install.php: Error: Call to undefined function libraries_get_path() in cu_slider_init()

### ISSUE THREAD

**Issue by zrhoffman** [CuBoulder/express#3278]
**Describe the bug**
In the "Install profile" step on the `install.php` page, I get the following error:

```
The installation has encountered an error.
Please continue to the error page
An AJAX HTTP error occurred. HTTP Result Code: 500 Debugging information follows. Path: http://from-web.express.io/install.php?profile=express&locale=en&id=1&op=do StatusText: Service unavailable (with message) ResponseText: Error: Call to undefined function libraries_get_path() in cu_slider_init() (line 38 of /app/web/profiles/express/modules/features/cu_slider/cu_slider.module).
```

Related to #3055

**To Reproduce**
1. Get and start a web environment. I am using Docker: PHP 7.3 FPM (Alpine base image) with Nginx 1.15 as a web server and MySQL 5.7 for persistent storage.
1. Add Drupal 7 to the web root (using core version 7.66).
1. Add the Express profile from github.com/CuBoulder/express, `dev` branch (tested with HEAD at fb3ab43fec).
1. Go to from-web.express.io (this should resolve to your web host, e.g., 127.0.0.1), choose Express profile and English language, enter database credentials, and continue.
1. Wait a few seconds, then see error

**Expected behavior**
The "Install profile" step should complete without errors.

**Screenshots**
![Failed installation screenshot](https://i.imgur.com/OCBorBY.png)

**Desktop:**
 - OS: Arch Linux with 5.0.9 kernel
 - Browser: Firefox 68 nightly (`Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0`)

**Additional context**
A batch install from drush (version 8) works fine:

```shell
drush site:install --yes --db-url=mysql://user:pass@db-host/db-name express express_profile_configure_form.express_core_version=cu_core
```

**Comment by jwfuller** [comment]
Thanks for the report, we fixed it here https://github.com/CuBoulder/express_mono/pull/88
