### ISSUE TITLE
/homecoming site may have permissions issue

### ISSUE THREAD

**Issue by ekellagher** [CuBoulder/express#3287]
**Describe the bug**
log into site and I do not have the Express toolbar available
permission level administrator

**To Reproduce**
1. Log in with user account with administrator permissions
2. Go to 'https://www.colorado.edu/homecoming/admin/dashboard/user'
3. See there is not express toolbar links except help and logout
![Homecoming Dashboard](https://user-images.githubusercontent.com/16137919/57488153-7ddbbd80-726f-11e9-8bf0-e1beb08110bf.JPG)

**Desktop (please complete the following information):**
 - OS: PC windows 10
 - Browser chrome
 - Version latest

**Comment by cathysnider** [comment]
Verified May 25
Status Report shows no red-level errors: https://www.colorado.edu/homecoming/admin/reports/status
Though tokens are messed up
![Screen Shot 2019-05-14 at 11 41 20 AM](https://user-images.githubusercontent.com/638275/57719702-90724000-763d-11e9-802a-e61814b82e60.png)

The Status Report did not say that update.php needed to be run. But I ran it anyway, and now the toolbars are showing, for all roles.
![Screen Shot 2019-05-14 at 11 45 32 AM](https://user-images.githubusercontent.com/638275/57719828-cfa09100-763d-11e9-9da2-2ca40f8ff13e.png)
