### ISSUE TITLE
Add a CONTRIBUTING file

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express#811]
## Context

We have discussed adding a CLA. Since we are moving our queue public, this seems like a good time to do this. 

## Expected result

Repo has CLA

## Current result

Repo has no CLA

## Possible Fix

* Github CLA
* CLA assistant
* One that Harvard or MIT runs

----

## Links to Examples

* [Github documentation on file creation](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)
* [Github CLA](https://cla.github.com/)
* [CLA Assistant](https://cla-assistant.io/)

**Comment by kreynen** [comment]
Started this https://www.clahub.com/agreements/CuBoulder/cu-express-drops-8, but needs feedback
