### ISSUE TITLE
As a SO/CE, I want to know about potential path conflicts with F5 routing

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#813]
## Context

Because of the number of legacy patch still in the F5, we are often getting reports about errors when trying to create homepage content.

Not sure if this is something that we need in all Express sites or only in the express_homepage bundle.  Check with @jwfuller 

## Process

1. Login to homepage as a SO, CE, ADMIN or DEV
2. Click Express > Content
4. Add Content > Basic Page
5. Under the **URL path settings**, uncheck **Generate automatic URL alias**
6. Set the path to "test" or "123test"
5. Click save

## Expected result

You would see your node

## Current result

Depending on the current legacy configuration you will see a white screen, legacy 404, of varnish 404

## Possible Fix

Add validation hook that checks Atlas for potential F5 routing conflicts.

**Comment by tommycox** [comment]
Does this only apply to prod? I installed a site on dev and created a _TEST_ node which didn't recreate the issue: http://www-dev.colorado.edu/p1aed93ac240/test

**Comment by jwfuller** [comment]
It applies to all environments, the list of conflicts varies by env

**Comment by jwfuller** [comment]
Atlas query is `where={"pool":"WWWLegacy"}`

**Comment by tommycox** [comment]
Something to be noted here: I've attempted to use `hook_node_validate()` to prevent a user from creating a node that conflicts with F5 routing but there's no way to get the pathauto generated path at that point. We may at best be able to emulate the behavior by copying and altering the `pathauto_create_alias()` function but that seems somewhat hacky. As an alternative, we _can_, however, check the path at `hook_node_insert()` and then set a warning message that the freshly created node path is a conflict.

One last thought is we could possibly populate the table of paths that are checked against for unique URLs (`{menu_router}`?) with the legacy paths so when a new node is created it'll create a unique URL or throw a message if manually attempting to enter the URL.

**Comment by tommycox** [comment]
Moved this issue to the express_homepage repo since that's where the code is.

**Comment by alexfinnarn** [comment]
Could maybe test with a text file containing JSON of paths.

**Comment by kreynen** [comment]
Related https://github.com/CuBoulder/express/issues/1886

**Comment by kreynen** [comment]
The f5 is being deprecated so this is no longer relevant.
