### ISSUE TITLE
Change OSR staff and test account creation from install to login, delete unused accounts

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#814]
## Context

There is no reason to create accounts on install. Accounts for OSR staff and testing should only be promoted to the developer or admin roles if the account logs into a site.

As the team grows, not creating accounts will noticeably reduce install time.

## Process

[ordered list the process to finding and recreating the issue, example below]

1. Login to site as yourself or test accounts for SO, CE, and EO roles

## Expected result

You should see the options a user with the role of the account you used should have

## Current result

[describe what you currently experience from this process, and thereby explain the bug]

## Possible Fix

Rather than prepopulate accounts, the role assignment should be made using the user account creation hook.

Existing OSR and testing accounts that haven't been used should be deleted with an update hook.

**Comment by alexfinnarn** [comment]
Do we need to check if a user has created content before deleting? Using the login variable for that check might end up having a lot of content assigned to the anonymous user.
