### ISSUE TITLE
Hide osr test users in admin/users from SO

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#816]
## Context

SO now see the OSR test user accounts for SO, CE, and EO.  Even with https://github.com/CuBoulder/express/issues/814, we want these accounts hidden from SO even if they are used.

## Process

[ordered list the process to finding and recreating the issue, example below]

1. Login to site as a SO
2. Click Express > Users

## Expected result

SO should only see themselves and users they've added

## Current result

SO sees osr-test-owner, osr-test-content and osr-test-edit-own

**Comment by cathysnider** [comment]
Acceptance Criteria:
- [ ] Developers should see all users (devs, admins, test users, and the clients)
- [ ] Site Owners should not see devs or admins
- [ ] Site Owners should not see the test users
- [ ] Site Owners should see other users at their level and below

**Comment by cathysnider** [comment]
https://www-dev.colorado.edu/p12c793753e6/
Fail: Site Owners CAN see the devs, admins and all the test users. 
![screen shot 2017-07-12 at 12 05 16 pm](https://user-images.githubusercontent.com/638275/28133427-383845d4-66fd-11e7-9f08-b991d5a56d56.png)

**Comment by owenmorrill** [comment]
#974 

OSR accounts can see other osr accounts, but regular users cannot.

**Comment by cathysnider** [comment]
New Test Aug 10
https://www-dev.colorado.edu/p112d521d029/

Acceptance Criteria:
- [x] Developers should see and edit all users (devs, admins, test users, and the clients)
- [ ] Site Owners should not see devs or admins
- [ ] Site Owners should not see the test users
- [ ] Site Owners should see other users at their level and below
- [ ] OSR Test users behave as regular users, with the exception that they CAN see themselves
