### ISSUE TITLE
As an ADMIN, DEV and SO, I want the option to lock out other editors

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#817]
## Context

This will eventually be used during site replication, but there are potential uses for this now so we can add the feature at any time.  

We've already established the method of doing this in the Demo Mode Bundle and in Atlas before a site is installed.  

The details of the UI need to be worked out, but the feature should enable a SO to lock out all other SOs, CE and EO or select specific users as exceptions.  DEVs should be able to do the same.  

When locking users out, the user initiating the lockout should have the option of leaving users a message.  Once we have site replication, this is where they would share the new temp URL.  Developers can also use this feature to leave a message if we lock a site because of performance problems or a bug that is causing loss of content.

Webforms should no be locked and users should be warned about this.

**Comment by owenmorrill** [comment]
Merged this into #1173.
