### ISSUE TITLE
Update user_ext_invite message to inviter to include url of site

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#818]
## Context

The current message only includes the P1 in the email it is sent from.

## Process

[ordered list the process to finding and recreating the issue, example below]

1. Login to site as yourself in a SO, ADMIN or DEV role (email needs to be correct)
2. Click Express > Users > Invite users
3. Invite a user

## Expected result

The email you get should include the url of the site you invited the users to join 

## Current result

> On 2/6/17, 10:26 AM, "cudrupal+p155c6d30b21@gmail.com on behalf of Kevin.Reynen@Colorado.EDU" <cudrupal+p155c6d30b21@gmail.com on behalf of Kevin.Reynen@Colorado.EDU> wrote:
> We have received your request to grant Site Owner access to the following:
> vasa@Colorado.EDU
> An email invitation has been sent requesting the user to login and accept the
> invitation. Upon completion, a confirmation email will be sent.
> If you did not submit this request or need to modify it, please contact us at
> websupport@colorado.edu.
> –
> The Web Express Team
> http://www.colorado.edu/webcentral
> websupport@colorado.edu

**Comment by cathysnider** [comment]
Verified: The invitation emails and the confirmations emails have been updated to include site name and URL, as noted below. The emails note what level of access has been granted.

Invitation Email sent to client includes name of website: "You have been invited to join the Feature 818: Email Invitations  Web Express website as an editor with Site Owner access privileges."

Invitation Email sent to invitor includes site URL: "We have received your request to grant Site Owner access to the following users:  sniderc@colorado.edu. An email invitation has been sent requesting the user to login to https://www-dev.colorado.edu/feature/818/ and accept the invitation. Upon completion, a confirmation email will be sent."

Confirmation Email sent to client includes name of website: " You have successfully joined the Feature 818: Email Invitations Web Express website as an editor with  access privileges."

Confirmation email sent to invitor includes name of website and URL: "We are confirming sniderc@colorado.edu now has Site Owner access to theFeature 818: Email Invitations , https://www-dev.colorado.edu/feature/818/, website."
