### ISSUE TITLE
As a SO, I want to be able to add tracking pixels and other embeds quickly

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#820]
## Context

@kevincrafts has already written https://github.com/CuBoulder/express/tree/dev/modules/custom/cu_seo_admin_bundle and improved it to be more self-service with https://github.com/CuBoulder/express/tree/feature%2FFIT-2458

Most of the dev team haven't had to deal with these, but the number of requests has increased to the point that we cannot limit this to something only a dev can do.  The form users use to request tracking pixels can be found at https://www.colorado.edu/strategicrelations/tracking-pixel-submission-form

McGill University has shared https://www.drupal.org/project/campaign_tracker.  That project supports Facebook, Google Adwords and Doubleclick tracking pixels.  That project uses custom bean types for each type of pixel they support.  We also need to add support for Twitter, Siteimprove, and Slate.

While I'd love to team up with another university to try to keep up with changes to supported services and new services, @kevincrafts and I agree that bean isn't the right way to go for our service.

Instead, we want to build on the existing tracking pixel entities to add types for supported services.  Users would be able to add their own pixels if they only require adding values that can be entered into the form for each type.  We would still support adding custom javascript to leverage the more advanced features of these services or new services we haven't defined a type for, but only developers would be able to add those.

The current solution will only allow placing a pixel at a specific path.  We need to expand that so that the pixel entities can be placed using url patterns/wildcards and/or placed using Context.  Context may not be available in D8, so pattern placement might be the way to go long term.  If that is going to add significant time, using Context in D7 is an acceptable interim solution.

**Comment by alexfinnarn** [comment]
referencing https://cuboulder.atlassian.net/browse/FIT-2099

**Comment by alexfinnarn** [comment]
referencing https://cuboulder.atlassian.net/browse/FIT-2287 - Put tracking pixel into existing feature group

**Comment by alexfinnarn** [comment]
The next step for this issue would be to add https://www.drupal.org/project/embed_templates to an Express site via Atlas and start developing any CU-specific functionality. If that functionality is general enough, then that code should go up on drupal.org in the mebd_templates ecosystem.

**Comment by kreynen** [comment]
Defined remaining tasks in #1102
