### ISSUE TITLE
As a SM, we need more data about webform usage 

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#822]
## Context

We have the node count for webforms, but we don't know how many of these forms are active (not just active in the webform node configuration, but actually linked in the site and/or actively taking submissions).   If there is a form that hasn't had a submission in 13 months, we shouldn't consider that active.  13 months will include yearly events, but I think we should actually be warning users if they have an active form with no submissions in > 90 days.

If we are seriously evaluating hosting webforms on child sites or a centralized service, we need more data.

Once you have some idea of what data we want to build a report, we'll need an Atlas issue to update the stats schema to include this information.

**Comment by owenmorrill** [comment]
Webform stats needed:
- how many webforms (node count, already have)
- number of total submissions made on site (int)
- date/time of last submission for each form (timestamp?)

Atlas ticket: https://github.com/CuBoulder/atlas/issues/174

**Comment by alexfinnarn** [comment]
I have no idea where this ticket left off, so I am adding all of the labels back.

**Comment by jwfuller** [comment]
https://github.com/CuBoulder/express/pull/854 was merged
