### ISSUE TITLE
As a SO/CE I need additional background colors options for block themes, hero units, and block sections

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#824]
## Context

To add some additional design options in presenting content, two additional backgrounds options (light blue, tan) should be added for text blocks, hero units, and block sections.

## Process

1. Create a text block
2. Choose from one of the new color options (light blue, tan)

## Expected result

The block should have the background color you selected.

## Current result

These two options are currently not available.

## Screenshots

![screen shot 2017-01-25 at 12 12 20 pm](https://cloud.githubusercontent.com/assets/349713/23715850/48e8bde8-03eb-11e7-9072-2b959a4b061d.jpg)

**Comment by kreynen** [comment]
Reopening to resolve https://github.com/CuBoulder/express/pull/934#issuecomment-300856197

**Comment by ekellagher** [comment]
Web Central Documentation updated:
https://www.colorado.edu/webcentral/tutorial/v2/block-configuration

**Comment by cathysnider** [comment]
https://www-dev.colorado.edu/feature/824

**Comment by cathysnider** [comment]
Verified: The two new colors are available for Block Themes, Hero Units, and Block Sections

**Comment by kevincrafts** [comment]
Closing as fixed/done.
