### ISSUE TITLE
Add cu_collections to Advanced Content Bundle

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#825]
## Context

The cu_collections module has been deployed and enabled on a few sites but it needs to be added to a bundle before we open it up to anyone. The Advanced Content Bundle is a good fit.

## Possible Fix

* Add cu_collections  as a dependency to the Advanced Content Bundle
* Add an update hook to the Advanced Content Bundle to enable cu_collections

**Comment by kreynen** [comment]
We decided to define collections as its own bundle since it is unlikely that a majority of sites that have Advanced Content enabled would use collections.
