### ISSUE TITLE
Delete doesn't work via Atlas module

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express#827]
## Context

An instance should be able to request it's deletion from Atlas. This is particularly nice when working locally.

## Process

1. Login to site as a DEV
2. Visit Admin >> Config >> Development >> Atlas
3. Choose 'Delete' from the status drop down
4. Submit form

## Expected result

Site should be queued for deletion.

## Current result

Status is changed and then nothing happens since Atlas responds only to the `DELETE` method. 

## Possible Fix

* Add new form for deletion, since it is such a significant action and use the `DELETE` method

**Comment by owenmorrill** [comment]
Does this need to immediately kick-off the "DELETE" functionality? Where the site is gone upon submission of that form? Or is there a "take down" method that would set this to be taken down later on?
