### ISSUE TITLE
Anchor list shortcode contains status/warning headers

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#833]
## Context

I'm not sure if this is a bug per say, but the recommended selector is "#content h2" which includes the status and warning message sections. They have an invisible h2 for screen readers. 

Ideally, you'd want the anchor shortcode to list h2's since that should be the correct heading to use. I don't think this will be an issue most of the time, but if a warning or status message happens to appear on pages where this anchor tag is used as is, they would see the headings in the page. 

## Process

1. Login to site as a Site Owner.
2. Create a basic page with h2 headers and an anchor shortcode "[anchors selector="#content h2" title="A list:" /]
3. Edit another page and don't save it. Navigate away from that page to create a content lock warning message.
4. Go back to the anchor shortcode page and you should see "Warning Message" show up in the anchor list shortcode section.

## Expected result

The anchor list shortcode example should not contain the status message h2s. 

## Current result

The anchor list shortcode example contains status message h2s.

## Possible Fix

A suggestion would be to have the shortcode example include ".region-content h2" as the default since that only contains the content people would want to target. 

## Screenshots

Screenshot attached
![screen shot 2017-02-27 at 4 05 36 pm](https://cloud.githubusercontent.com/assets/3640707/23384806/97b12368-fd09-11e6-9520-36a1e59c7e00.png)

**Comment by owenmorrill** [comment]
Doesn't seem to be reproducible with the current dev branch.

![anchor-warning-text](https://user-images.githubusercontent.com/5008565/30702598-9a73d68e-9eaa-11e7-826a-219a89498b05.png)

**Comment by owenmorrill** [comment]
![anchor-warning-text2](https://user-images.githubusercontent.com/5008565/30703139-14627c38-9eac-11e7-86e8-59143543e92d.png)

**Comment by cathysnider** [comment]
Same. Unable to reproduce on dev or test.
