### ISSUE TITLE
As a SO hosting externally, I need to know when a custom Express+ bundle has been updated

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#841]
## Context

This is currently issues with connect.cu.edu and living.colorado.edu.  I created an issue about this in Jira (DEVOPS-311) when we started https://github.com/CuBoulder/cu-express-drops-7

I think the answer might be https://www.drupal.org/project/erus running in Express and https://github.com/SU-SWS/erus on GitHub.

We'd need to add additional values to each bundle's .info and there is currently no real plan for D8, but the ERUS project is maintained and used by Stanford University.  I've already reached out to the project's maintainer.  They are very open to our contributions and working together on a D8 branch.

I'd like to see this integrated now with any project that we know is being used on an external host (Classes Bundle, Video Hero Unit, ??).  

Whether or not we can do this successfully will impact our ability to offer "build on Express as a base" to other developers and how we structure code repositories in D8.

**Comment by kreynen** [comment]
This is now related to https://github.com/CuBoulder/express/issues/907

**Comment by alexfinnarn** [comment]
covered by #956
