### ISSUE TITLE
Remove Content Editor From SEO Dashboard View

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#845]
## Context

While logged in as a content editor on "admin/dashboard/seo," all of the links lead to "Access Denied." The permission for "use seo dashboard" was entered incorrectly. 

## Expected result

Given I am logged in as a user with the <role> role
When I enable the "cu_seo_bundle" module
And I go to "admin/dashboard/seo"
Then I should see <message>

    Examples:
    | role | message |
    | content_editor | "Access denied" |
    | edit_my_content | "Access denied" |
    | site_owner | "Search Engine Optimization Checklist" |
    | administrator | "Search Engine Optimization Checklist" |
    | developer | "Search Engine Optimization Checklist" |

## Current result

1. Login to site as content_editor.
2. Enable SEO bundle.
3. Go to SEO dashboard overview page. 
4. View links that all have "access denied" status when clicked. 

## Possible Fix

Change "view seo dashboard" permission to "use seo dashboard" in cu_seo_bundle module. 

## Related Links

[https://www-test.colorado.edu/cmci/admin/dashboard/seo](https://www-test.colorado.edu/cmci/admin/dashboard/seo)

**Comment by kreynen** [comment]
Since CE's edit and author most content, locking them out of feedback loop.  Closing this for now in favor of keeping CEs and CEs and not adding more SOs.  

One way to fix this would be https://github.com/CuBoulder/express/issues/1799
