### ISSUE TITLE
Create Generalized Approved Embed Module

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#865]
## Context

Currently, only devs can add tracking pixels to sites. To lessen the burden on devs, the process of adding tracking pixels needs to be more streamlined in order for a user to enter those themselves. 

This ticket will encompass a rewrite of the cu_tracking_pixels module. Since there is nothing CU-specific about it, the module could be abstract enough to live on d.o https://www.drupal.org/project/tracking_pixels isn't taken yet. 

Rather than list everything out now, this ticket will add to this description as development evolves. Instead of creating smaller tickets for adding forms, templates, etc. the entire module will be added to the Express repo in this ticket's branch.

**Comment by alexfinnarn** [comment]
It looks like there are only 2 fields for Slate forms.  An id or form id…
 
https://grad.apply.colorado.edu/register/?id=ca6faf28-48dd-4378-a29a-0bcb9e272c25&output=embed&div=form_ca6faf28-48dd-4378-a29a-0bcb9e272c25
 
Then there will be a GUID for department that ideally we’d populate from JSON provided by the service.

**Comment by kreynen** [comment]
The list of department options for Slate form embed can be populated from https://grad.apply.colorado.edu/manage/query/run?id=aba3628b-4c9d-4f72-bc47-63fe38e1ebdc&h=3aeeaf4a-04a7-de2b-388e-483abf8e6faf&cmd=service&output=xml or https://grad.apply.colorado.edu/manage/query/run?id=aba3628b-4c9d-4f72-bc47-63fe38e1ebdc&h=3aeeaf4a-04a7-de2b-388e-483abf8e6faf&cmd=service&output=json

@alexfinnarn Is that going to be possible with the current form template?

**Comment by alexfinnarn** [comment]
There is no "add another" functionality so not right now if you mean a particular tracking pixel entity can have all of those values. 

The options can be defined to have many values, e.g. id1, id2, id3, but that doesn't scale. 

Not sure I know what that output will be used for, but I think it is to reduce the number of entities by having multiple option sets.

**Comment by kreynen** [comment]
no... department would be the key.  The XML or JSON would limit the values in a select list.

**Comment by alexfinnarn** [comment]
Development of this module/code has switched to drupal.org. Issues are located here: https://www.drupal.org/project/issues/embed_templates
