### ISSUE TITLE
As a SO, I need to be able to run an accessibility scan on a site I'm redesigning before it launches

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#867]
## Context

While we've identified how we can add registering sites with Siteimprove as part of the process of allocating sites, we need temporary sites that will eventually replace live sites to be scanned periodically as well.

## Process

(This still needs to be defined)

1. Login to site as a SO, ADMIN or DEV
2. Click Express > Settings
3. Click Request Replicate

## Expected result

Site is replicated.  An OSR staff member periodically checks a list of Atlas site records without a Siteimprove site or group id and registers the site within 72 hours of it's creation.  Once the site is registered with Siteimprove, the SO can see a report about the accessibility of the changes they are making.

Only sites that are being created with the intention of launching on prod should be registered with Siteimprove.  Not sure if this is an option SO see when requested a replica?

**Comment by alexfinnarn** [comment]
too many moving parts to consider writing a test when so many other tests need to be written.
