### ISSUE TITLE
Define the process for how service integration outages are communicated

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#878]
## Context

There are limits to what we can do with statuspage.io, but we're going to move forward with using that for the next 3-6 months.  Based on Pingdom, it seems like we are experiencing weekly outages from the old calendar service again. I _think_ the new version of that is going to be much more stable, but we experienced problems with several services we integrate during last week's Amazon S3 outage.

Currently many Express users precieve these as problems with Express.  Several new features are based on integrating with new services with questionable track records.  Technolution's Slate service is one these problem services.  That vendor claims 99.99% uptime but users of the service reported not being able to upload files with form submissions and/or view uploaded files for several hours during the S3 outage.  

We don't want to end up in a situation where we are troubleshooting problems with these services.  When we know about an issue, we should have a process for deciding when to pass that information on to the owners of the impacted sites.

## Process

1. An issue is reported by an Express user or an automated check of a service integrated with Express
2. Evaluate the issue
3. ???

## Expected result

Express site owners with sites being impacted by this are informed that some of the functionality on their site may not be working because of an issue with an external service.

## Current result

We only respond to the users who open issues.

**Comment by ekellagher** [comment]
Internal Policy
https://docs.google.com/a/colorado.edu/document/d/14nkHrDvP7cQAgNKB1EVSZeqmeOzNknGdFFboKLCLiF8/edit?usp=sharing

Web Central Page
