### ISSUE TITLE
As a SO, I want to be able to see statuspage.io info on Dashboard

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#879]
## Context

We are still exploring how much we want to display on http://www.colorado.edu/webcentral/ and how much we want to live outside of the Web Express service itself, but we want at least some basic branding of this site and to understand the limits of what can be customized in the design.

**Comment by kevincrafts** [comment]
![screen shot 2017-03-17 at 2 34 47 pm](https://cloud.githubusercontent.com/assets/349713/24062039/80bb0010-0b1f-11e7-9f1d-04c1ade3f316.jpg)

**Comment by alexfinnarn** [comment]
No PR so marking back to In Progress.

**Comment by jwfuller** [comment]
We want to make sure we aren't doing a large number of separate lookups for each item.

**Comment by kreynen** [comment]
This task evolved from designing http://status.colorado.edu/ to somethign that needs to be reviewed and merged

**Comment by alexfinnarn** [comment]
With all systems operational, I think the message looks weird. 
![screen shot 2017-05-31 at 3 32 49 pm](https://cloud.githubusercontent.com/assets/3640707/26655472/363e5d8c-4618-11e7-887c-a00188ce1634.png)

**Comment by alexfinnarn** [comment]
Moving back to In Progress until someone agrees with or says my comment is dumb.
