### ISSUE TITLE
Atlas module always sends empty packages array

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express#882]
## Context

The Atlas module needs to be able to send an empty array to remove all packages. But it sends it when there have never been any packages resulting in extra work on the servers.

## Process

1. Provision a site
2. `tailatlas` on the appropriate Atlas server
3. Use the Atlas UI in Web Express to move a site to `installing`
4. See that `Found package changes.` appears in the Atlas logs.

## Expected result

Should only update the settings.php files

## Current result

Updates settings.php; removes old packages; adds new ones (Null); runs `drush rr`; runs `drush updb -y`

## Possible Fix

When creating payload to send to Atlas, check to see if the package list is changing.

**Comment by owenmorrill** [comment]
Changing to the following:

`
// Check for First added package, Remove all packages, or Change packages.
    if (!empty($packages_diff)) {
      $request_data['code']['package'] = $form_state['values']['atlas_packages'];
    }
`

Gets rid of the `drush rr` and `Found package changes.` but not `drush updb -y`--that's still there.
