### ISSUE TITLE
As a SO/CE, when my content is shared on Twitter, I want it to be displayed in the Twitter Card format

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#887]
## Context

Rather than just a link being shared, the Twitter Card format is more engaging.

https://dev.twitter.com/cards/getting-started

## Proposed Solution

The Open Graph and Twitter Cards submodules of MetaTag can handle most of the work, However, getting the thumbnail image from various fields on various content types still needs to be done.

1. Enable metatag_opengraph and metatag_twitter_cards
2. Remove custom open graph code except for image handeling from pages, articles, persons, and photo galleries.

## To Test
1. Enable SEO Bundle
2. Click Home
3. Click Edit
4. Add image to image field
5. Click Save
6. HTML Source code should contain the following meta tag names: twitter:card, twitter:url, twitter:title, twitter:description

**Comment by alexfinnarn** [comment]
I don't see the summary part...
![screen shot 2017-05-17 at 1 12 49 pm](https://cloud.githubusercontent.com/assets/3640707/26171788/6e02fedc-3b03-11e7-8cd7-1f9d9411f935.png)

![screen shot 2017-05-17 at 1 21 07 pm](https://cloud.githubusercontent.com/assets/3640707/26171875/be54ed46-3b03-11e7-868b-4c4a61dcb102.png)

**Comment by owenmorrill** [comment]
![twitter-card](https://cloud.githubusercontent.com/assets/5008565/26413321/df9503fa-4068-11e7-848e-765e02c6f55d.png)

Seems to be working as designed.

**Comment by cathysnider** [comment]
Tested: https://www-dev.colorado.edu/p179076d9ede/
This works as stated on the home page, but not on subpages. 
Q: Is the Twitter Card format supposed to work on subpages of a site as well? 
If the inserted photo is the first thing in the content area, then no twitter description meta tag is added. Examples:  https://www-dev.colorado.edu/p179076d9ede/page-two and https://www-dev.colorado.edu/p179076d9ede/page-five
Placing a content grid in the Above Content region has no ill effect; the twitter description meta tag is added just fine. Example: https://www-dev.colorado.edu/p179076d9ede/page-four

**Comment by alexfinnarn** [comment]
My comment/issue seems to have been resolved. Chalking it up to caching.

**Comment by alexfinnarn** [comment]
From @cathysnider 's concern, I can now see a description on https://www-dev.colorado.edu/p179076d9ede/page-two in the source.

**Comment by cathysnider** [comment]
@alexfinnarn because you added a summary to the summary field. Clients will not know to do this.
