### ISSUE TITLE
Documentation of Collections

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#891]
## Context

This is a new feature that requires documentation.

**Comment by ekellagher** [comment]
Addon Bundle Page
https://www.colorado.edu/webcentral/web-express-features/bundles-features
Collections sample
https://www.colorado.edu/webcentral/web-express-features/bundles-features/add-bundles/collections

Collection Tutorials:
Tutorial Set
http://www.colorado.edu/webcentral/tutorials/collection-bundle
Collection Grid Block
http://www.colorado.edu/webcentral/tutorial/v2/collection-grid-block
http://www.colorado.edu/webcentral/tutorial/v2/collection-item-page
