### ISSUE TITLE
As a SO/CE I would like to place content width and full width blocks below the page title

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#896]
## Context

Many page layouts are created using the the wide regions. The Intro Wide  region, at the top of the page, and Post Wide region, below the main content are used for this.

While the Intro Wide region works great for a site's homepage, it does not always work for lower level pages, as it puts important content outside of the page hiearchy (above the h1 page title).

While the Post Wide region can recreate the proper structure for very simple pages (no sidebar content, sub navigation, etc), it requires many more block entities to be created and makes the page creation and editing much more complex.

Being able to place blocks in these positions makes more layouts possible, makes the page more accessible by placing the content within the proper hierarchy, and reduces the complexity of the page by trying to achieve this through alternate means.

## Proposed Solution

Add two additional regions below the page title. One full browser widow width, one content width. Add additional layout fields to place content into these regions.

## Screenshots

![screen shot 2017-01-25 at 4 52 24 pm](https://cloud.githubusercontent.com/assets/349713/23759595/71f85d50-04aa-11e7-817d-58b1d57a020a.jpg)
![screen shot 2017-01-25 at 4 52 31 pm](https://cloud.githubusercontent.com/assets/349713/23759594/71f2a3c4-04aa-11e7-9478-dd52adc5b2fb.jpg)

## Testing

Important: Any testing of this should be done on all themes.

**Comment by cathysnider** [comment]
https://www-dev.colorado.edu/p1bd3d8206dd/

**Comment by cathysnider** [comment]
Acceptance Criteria:
- [ ] Regions Post Title and Post Title Wide can be placed via Context and via Page Layout, on all pages that support Intro Wide and Slider, in all themes.

Test Results: 
| ﻿Context           |        |           |       |        |         |        |      |        |        |        |           |
|-------------------|--------|-----------|-------|--------|---------|--------|------|--------|--------|--------|-----------|
|                   | Spirit | Highlight | Ivory | Layers | Minimal | Modern | Rise | Shadow | Simple | Swatch | Tradition |
| Homepage          | x      | x         | x     | x      | x       | x      | x    | x      | x      | x      | x         |
| Basic Page        | x      | x         | x     | x      | x       | x      | x    | x      | x      | x      | x         |
| FAQ page          | x      | x         | x     | x      | x       | x      | x    | x      | x      | x      | x         |
| Content List Page | x      | x         | x     | x      | x       | x      | x    | x      | x      | x      | x         |
| Article           | x      | x         | x     | x      | x       | x      | x    | x      | x      | x      | x         |
| Article List Page | x      | x         | x     | x      | x       | x      | x    | x      | x      | x      | x         |
| Person            | x      | x         | x     | x      | x       | x      | x    | x      | x      | x      | x         |
| People List Page  | x      | x         | x     | x      | x       | x      | x    | x      | x      | x      | x         |
| Photo Gallery     | x      | x         | x     | x      | x       | x      | x    | x      | x      | x      | x         |
| Webform           | x      | x         | x     | x      | x       | x      | x    | x      | x      | x      | x         |
|                   |        |           |       |        |         |        |      |        |        |        |           |
|                   |        |           |       |        |         |        |      |        |        |        |           |
| Layout            |        |           |       |        |         |        |      |        |        |        |           |
|                   | Spirit | Highlight | Ivory | Layers | Minimal | Modern | Rise | Shadow | Simple | Swatch | Tradition |
| Homepage          | x      | x         | x     | x      | x       | x      | x    | x      | x      | x      | x         |
| Basic Page        | x      | x         | x     | x      | x       | x      | x    | x      | x      | x      | x         |
| FAQ page          | x      | x         | x     | x      | x       | x      | x    | x      | x      | x      | x         |
| Content List Page | x      | x         | x     | x      | x       | x      | x    | x      | x      | x      | x         |
| Article           | x      | x         | x     | x      | x       | x      | x    | x      | x      | x      | x         |
| Article List Page | x      | x         | x     | x      | x       | x      | x    | x      | x      | x      | x         |
| Person            | x      | x         | x     | x      | x       | x      | x    | x      | x      | x      | x         |
| People List Page  | x      | x         | x     | x      | x       | x      | x    | x      | x      | x      | x         |
| Photo Gallery     | x      | x         | x     | x      | x       | x      | x    | x      | x      | x      | x         |
| Webform           | x      | x         | x     | x      | x       | x      | x    | x      | x      | x      | x         |
|                   |        |           |       |        |         |        |      |        |        |        |           |

**Comment by cathysnider** [comment]
## Context ##

Page Type | Spirit | Highlight | Ivory | Layers | Minimal | Modern | Rise | Shadow | Simple | Swatch | Tradition
------- | ------- | ------- | ------- | ------- | ------- | ------- | ------- | ------- | ------- | ------- | ------- 
Homepage | x  | x  | x  | x  | x  | x  | x  | x  | x  | x  | x 
Basic Page | x  | x  | x  | x  | x  | x  | x  | x  | x  | x  | x 
FAQ page | x  | x  | x  | x  | x  | x  | x  | x  | x  | x  | x 
Content List Page | x  | x  | x  | x  | x  | x  | x  | x  | x  | x  | x 
Article | x  | x  | x  | x  | x  | x  | x  | x  | x  | x  | x 
Article List Page | x  | x  | x  | x  | x  | x  | x  | x  | x  | x  | x 
Person | x  | x  | x  | x  | x  | x  | x  | x  | x  | x  | x 
People List Page | x  | x  | x  | x  | x  | x  | x  | x  | x  | x  | x 
Photo Gallery | x  | x  | x  | x  | x  | x  | x  | x  | x  | x  | x 
Webform | x  | x  | x  | x  | x  | x  | x  | x  | x  | x  | x 

## Page Layout ##

Page Type | Spirit | Highlight | Ivory | Layers | Minimal | Modern | Rise | Shadow | Simple | Swatch | Tradition
------- | ------- | ------- | ------- | ------- | ------- | ------- | ------- | ------- | ------- | ------- | ------- 
Homepage | x  | x  | x  | x  | x  | x  | x  | x  | x  | x  | x 
Basic Page | x  | x  | x  | x  | x  | x  | x  | x  | x  | x  | x 
FAQ page | x  | x  | x  | x  | x  | x  | x  | x  | x  | x  | x 
Content List Page | x  | x  | x  | x  | x  | x  | x  | x  | x  | x  | x 
Article | x  | x  | x  | x  | x  | x  | x  | x  | x  | x  | x 
Article List Page | x  | x  | x  | x  | x  | x  | x  | x  | x  | x  | x 
Person | x  | x  | x  | x  | x  | x  | x  | x  | x  | x  | x 
People List Page | x  | x  | x  | x  | x  | x  | x  | x  | x  | x  | x 
Photo Gallery | x  | x  | x  | x  | x  | x  | x  | x  | x  | x  | x 
Webform | x  | x  | x  | x  | x  | x  | x  | x  | x  | x  | x
