### ISSUE TITLE
As a SO I need to enable additional functionality on my site

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#898]
## Context

Web Express has a core set of features (Core Bundles) that are installed with every instance.

Additional classes of bundles can be used to allow other functionality.

### Add On Bundles

Additional functionality that is available to any Web Express site but is not included with each install. These bundles must be added as code assets through Atlas and when a user adds one of these bundles Atlas will link the code and notify the requesting user that the bundle is ready for them to enable.

### Add On Bundles (Require Approval)

Some additional functionality may have certain requirements be met.  For example, the Newsletter Bundle requires you have an eComm account.

The user is able to request this bundle be installed, but it must first be approved before it can be installed.  User should be able to request this through their site which will create a web support ticket.

### Custom Bundles

Some projects may have custom bundles that include modules/libraries/themes/etc for a particular project.  These bundles are added through the Atlas interface by a developer but should still show up on the enable bundles screen.

## Process

[ordered list the process to finding and recreating the issue, example below]

1. Login to site as a [SO, CE, EO, ADMIN or DEV]
2. Click Administer
3. Click Webform
4. Enter "Kevin, don't do that" in the body field
5. Click save

## Ideas

![2017-03-09 11 56 26](https://cloud.githubusercontent.com/assets/349713/23765818/b76bd942-04bf-11e7-8ef3-505306e8e2f6.png)

**Comment by kreynen** [comment]
One challenge with this is we want https://www.drupal.org/project/profile_module_manager to remain usable as contrib and for sites that aren't using Atlas to manage code like https://living.colorado.edu/ and http://alerts.colorado.edu/.

To do this we need to update the contrib version of PMM with an option to ignore _bundles in /sites/all and a hook to extended the bundle list with custom output for other modules.

Then for the Atlas managed sites we will add cu_profile_module_manager that will look up all bundles registered as a code asset with a public tag and allow users to request Atlas add that code to sites/all/modules.

Custom, site specific  bundles like express_webcentral will not show up as something SOs can request.  That will remain a DEV task, but once the code is added we want SO to know that this site is a "special snowflake".  We'll probably need to go back to using custom_ in the naming.

**Comment by kreynen** [comment]
How are we handling bundles that are currently _admin like debug?

**Comment by owenmorrill** [comment]
Until Atlas 195 is complete, add the following under the 'name' meta piece in config_data_structure.py in Atlas.

`
            'label': {
                'type': 'string',
                'minlength': 3,
                'required': True,
            },
`

**Comment by owenmorrill** [comment]
![core-bundles](https://cloud.githubusercontent.com/assets/5008565/24674979/b6a85776-193a-11e7-91dd-dd51c71d76e9.png)
![addon-bundles](https://cloud.githubusercontent.com/assets/5008565/24674986/bc1343c4-193a-11e7-901d-267924a03e56.png)

**Comment by kreynen** [comment]
Found the potential issue in the "define array in Express, update array from bundle's .info" plan.  Not all of our bundle project repos have the bundles's .info at the root level.  In https://github.com/CuBoulder/cu_classes_bundle, you'd have to figure out that the .info is in https://github.com/CuBoulder/cu_classes_bundle/blob/master/modules/custom/cu_classes_bundle/cu_classes_bundle.info.

@kevincrafts, @jbertrand and @ekellagher, we need to decide if we want to merge this into 2.4.0 as is and improve it in 2.4.1, hold up the release until this is "finished" or leave this out of 2.4.0

**Comment by owenmorrill** [comment]
Updated PR to hide custom bundles unless the package has been added by Atlas.

**Comment by ekellagher** [comment]
Here is a draft document of the pages and changes to Web Central content that will be needed when this is implemented - When I know what bundles will be in each section I will create the content
https://docs.google.com/a/colorado.edu/document/d/1wH3KneNbGtSjUPLXeKwNEvZ5rB35akQlfgYVWOBCtoU/edit?usp=sharing

**Comment by jwfuller** [comment]
This doesn't inherently have any performance concerns. We may need to re-allocate workers in Atlas to deal with demand if end users go wild.

**Comment by kevincrafts** [comment]
When I looked at this last week, the page contained a form and a bunch of fieldsets but no actual input fields or buttons.  If this is going to be a form, it should include form elements, not just links.

**Comment by kevincrafts** [comment]
Also, I would like to review this again from a design perspective to see if it is introducing new design patterns before it is merged.

**Comment by ekellagher** [comment]
Web Central Documentation
Features Landing Page: http://www.colorado.edu/webcentral/web-express-features (updated)
Core Bundles Page: http://www.colorado.edu/webcentral/web-express-features/bundles-features/core-bundles (new/updated)
Add-on Bundles Page: http://www.colorado.edu/webcentral/web-express-features/bundles-features ( new/updated)
Express+ Bundles Page: http://www.colorado.edu/webcentral/web-express-features/bundles-features/express-bundles (new/updated)
Express+ Bundle Request Form: http://www.colorado.edu/webcentral/content/express-bundle-request
LiveChat Sample Page: http://www.colorado.edu/webcentral/web-express-features/bundles-features/express-bundles/livechat (new)
Newsletter Sample Page: http://www.colorado.edu/webcentral/web-express-features/bundles-features/express-bundles/newsletter (new)
Video Hero Sample Page: http://www.colorado.edu/webcentral/web-express-features/bundles-features/express-bundles/newsletter (needs review)
All Core Bundles tutorials have been updated with info block reflecting their bundle type
All Add-on Bundles tutorials have been updated with info block reflecting their bundle type
All Express+ Bundles tutorials have been updated with info block reflecting their bundle type

**Comment by ekellagher** [comment]
![core bundles](https://cloud.githubusercontent.com/assets/16137919/26132043/c686cfec-3a5a-11e7-9612-275e9bf49136.jpg)

**Comment by alexfinnarn** [comment]
This issue can't be fully tested due to the fact we don't have a way to mock objects in our Drupal 7 tests. I have made https://github.com/CuBoulder/express/issues/1065 to explore how to do that; however, I doubt we would implement this in Drupal 7 and instead use mocks in Drupal 8 where there are built-in methods for using them.

**Comment by ekellagher** [comment]
Addon Tab needs to be updated to "Add-on" this is how we are referring to the process on Web Central
