### ISSUE TITLE
Disable custom logo module for sites without custom logo variable

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#903]
## Context

This functionality has been moved around since the 1.6 releases.  Currently it's a mess of our own making with the cu_custom_logo enabled on all sites, but only actually used on a few.  We already have https://github.com/CuBoulder/cu_custom_logo_bundle, but need to add that to only the sites that actually allowed to use a custom logo.

Requesting a custom logo is no something we are going to promote in the UI for https://github.com/CuBoulder/express/issues/898, so I think this bundle needs to be and _admin or _custom.

**Comment by tommycox** [comment]
> so I think this bundle needs to be and _admin or _custom
 is this just a matter of re-naming the bundle?
