### ISSUE TITLE
As SM, we need to increase speed and reliability of homepage and Today sites

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#907]
## Context

The Homepage and Today sites will be moved to Platform.sh for hosting in order to increase the availability and speed of those sites. In order to make that move successful, several new features such as Shibboleth, CDNs, and PHP 7 need to be tested before finally moving those sites over.

**Comment by alexfinnarn** [comment]
Closing this issue since still haven't moved to Platform.sh and there is another issue about analyzing performance...also on PHP 7 now.
