### ISSUE TITLE
SAML authentication on Platform

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#911]
## Context

I've started this process for Pantheon using the information at https://pantheon.io/docs/sso-organizations/ and http://www.colorado.edu/oit/services/identity-access-management/federated-identity.  Not finding a similar guide for Platform.sh.  We need to confirm this is possible.

**Comment by alexfinnarn** [comment]
I have setup SAML on Pantheon and Platform as far as I could go and am awaiting a ServiceNow ticket to see what other information might be needed to connect.

**Comment by alexfinnarn** [comment]
update to latest version via https://simplesamlphp.org/download

**Comment by alexfinnarn** [comment]
SAML login seems to be working on Pantheon hosting, but I'm not sure we think this is such a good idea now due to the inability to log people out of the SSO if they request to be logged out.
