### ISSUE TITLE
Remove Atlas UI 'packages' piece

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#913]
This issue started as a bug, but between the PMM changes and Shrugger, it doesn't make sense to maintain this functionality in yet another way.  Removing this from the module makes the most sense to me.

## Context

When having multiple bundles added on a site, if one is to be removed, submitting the form will not allow you to only remove one.

## Process

1. Add multiple plus bundles
2. Try to remove only one

## Expected result

A single bundle should be able to be removed.

## Current result

The bundle you selected to be removed is still selected.

**Comment by owenmorrill** [comment]
Add multiple bundles from admin/config/development/atlas?

**Comment by kevincrafts** [comment]
Experienced this issue again on 10/6 when we tried to remove the Query Reduction Bundle from the Homepage site on prod.

We ended up needing to add another bundle at the same time we were removing one.

**Comment by alexfinnarn** [comment]
If you can PATCH the site record via Postman and remove the code asset, then this is not an Atlas bug. I highly doubt it is an Atlas bug, and I know we've had other issues (maybe related) with the form on "admin/config/development/atlas".

I'm pretty sure you can remove https://github.com/CuBoulder/express/blob/dev/modules/custom/atlas/atlas.module#L261 and just send in what is in the form. 

```
// No if/else statement since you need all asset IDs included for "code.packages".  
$request_data['code']['package'] = array_diff($form_state['values']['atlas_packages'], $site_array['code']['package']);
```

**Comment by alexfinnarn** [comment]
I think all of the functionality of the Atlas screen should be done in lil_shrugger now.

**Comment by owenmorrill** [comment]
https://www-dev-new.colorado.edu/p16b8c5e3bf9/admin/config/development/atlas

**Comment by owenmorrill** [comment]
All this functionality (for packages) will be done in Shrugger now.

**Comment by jwfuller** [comment]
https://github.com/CuBoulder/express_mono/issues/113
