### ISSUE TITLE
Make _core modules more generic 

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#916]
## Context

Since the only difference between cu_core and pantheon_core seem to be the modules that are installed, a check for $_ENV in the install hook would do the trick. Testing_core could be included in cu_core also, even if there are more differences than the modules installed. 

## Expected Result

cu_testing_core and cu_pantheon_core are combined into cu_core using $_ENV variables for Travis, Pantheon, and Platform.sh functionality.

**Comment by johnquest** [comment]
Currently our core is similar to pantheon_core in that not all modules need to load and/ or we'll need to load different ones. For example we'd like to not load rave_alerts.

**Comment by kreynen** [comment]
This merge was reverted on 1/2.  Removing all of these dependencies from the core.info without re-adding them at the Express/core or bundle level would put ever site in an error state.
