### ISSUE TITLE
Backport D8 Fitvids css selector functionality to D7 version

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#918]
## Context

The FitVids.js functionality is called on all video iframes. Currently there is a global selector ("body") to tell FitVids to act on all iframe videos with in the body tag. 

We don't want FitVids to act on video hero units because we are doing our own resizing.

FitVids.js supports excluding selectors. The D8 version of the module supports this too. This needs to be back ported to the D7 version.

https://www.drupal.org/node/1513980

**Comment by kreynen** [comment]
http://cgit.drupalcode.org/fitvids/tree/src/Form/FitvidsAdminSettingsForm.php?h=8.x-1.x#n57

http://cgit.drupalcode.org/fitvids/tree/fitvids.module?h=8.x-1.x#n57
http://cgit.drupalcode.org/fitvids/tree/fitvids.module?h=8.x-1.x#n75

**Comment by kevincrafts** [comment]
Closed because this still didn't seem to work correctly, but the new version of the library procided a class we could us to fix the issue.
