### ISSUE TITLE
As a SM, I want to see data about how interactive elements are used

### ISSUE THREAD

**Issue by jwfuller** [CuBoulder/express#921]
## Context

Click tracking for things like slideshow, button shortcodes, or hero units can give us valuable insight into the effectiveness of those elements. Google analytics supports taking in this data.

## Possible Fix

(Google Analytics Event Tracking module)[https://www.drupal.org/project/google_analytics_et]

**Comment by kreynen** [comment]
Is this necessary if we implement https://www.google.com/analytics/tag-manager/ ?

**Comment by jwfuller** [comment]
Yes, TM is for campaigns, click tracking is on-screen-event based.

**Comment by kreynen** [comment]
GTM is now the standard for doing this https://www.optimizesmart.com/event-tracking-in-google-tag-manager-v2-complete-guide/
