### ISSUE TITLE
Add stat for sites w/o owner that's employed or grad student

### ISSUE THREAD

**Issue by tommycox** [CuBoulder/express#922]
## Context

Related to CuBoulder/express_webcentral#51 we need to report if a site only has one site owner, and that owner is no longer employed by the University as determined by their presence in LDAP.

**Comment by tommycox** [comment]
Was able to connect to LDAP and load users' entries, but there doesn't appear to be any identifying information regarding the current status of a user's account. i.e. my entry:
```
# thco6272, Users, colorado.edu
dn: uid=thco6272,ou=Users,dc=colorado,dc=edu
mailRoutingAddress: thco6272@o365.colorado.edu
mailMessageStore: superman.int.colorado.edu
ownerDN: cuEduPersonUUID=100436361,ou=People,dc=Colorado,dc=edu
sn: thco6272
mailAlternateAddress: thco6272@Colorado.EDU
mailAlternateAddress: thco6272@culink.Colorado.EDU
mailAlternateAddress: Thomas.H.Cox@Colorado.EDU
mailAlternateAddress: thco6272@o365.colorado.edu
uid: thco6272
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: inetorgperson
objectClass: eduPerson
objectClass: mailRecipient
objectClass: coloradoUser
cn: thco6272
coloradoUserMail: Thomas.H.Cox@Colorado.EDU
```
compared to Matt Tucker's
```
# matu4291, Users, colorado.edu
dn: uid=matu4291,ou=Users,dc=colorado,dc=edu
mailRoutingAddress: matu4291@o365.Colorado.EDU
mailAlternateAddress: Matt.Tucker@Colorado.EDU
mailAlternateAddress: matu4291@Colorado.EDU
mailAlternateAddress: matu4291@ad.Colorado.EDU
mailAlternateAddress: matu4291@culink.Colorado.EDU
mailAlternateAddress: matu4291@o365.Colorado.EDU
mailMessageStore: riddler.int.colorado.edu
ownerDN: cuEduPersonUUID=100581480,ou=People,dc=Colorado,dc=edu
sn: matu4291
uid: matu4291
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: inetorgperson
objectClass: eduPerson
objectClass: mailRecipient
objectClass: coloradoUser
cn: matu4291
coloradoUserMail: Matt.Tucker@Colorado.EDU
```

**Comment by tommycox** [comment]
Per further discussions with @kreynen, we want to detect for graduate student site owners as to not raise false positives. We can detect graduate students using these fields from an LDAP callback:

![ldap graduate student employee](https://cloud.githubusercontent.com/assets/3009533/24302040/d9a702e4-1076-11e7-8a06-9de206f5116f.png)

Am working on implementing now.

**Comment by kreynen** [comment]
Because of the way LDAP is updated, we aren't going to be able to make any assumptions about sites based on that data.

**Comment by alexfinnarn** [comment]
Closed PR due to comment above.
