### ISSUE TITLE
[SI-ERROR-TRUE] 2.4.4 Link Purpose (In Context) - Non-distinguishable links

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#928]
> The same link text is used for links going to different destinations. Users might not know the difference if they are not somehow explained.

Siteimprove is suggesting using https://www.w3.org/TR/WCAG20-TECHS/ARIA7 to differentiate the links. This may be resolved by 

`<a href="/campusmap" style="z-index: 2147483646; position: relative;">Campus Map</a>`

`<div class="culinks"><strong>CU:</strong> <a href="/">Home</a> • <a href="/atoz">A to Z</a> • <a href="/campusmap">Campus Map</a></div>`

On the homepage it also complains about the link in the footer...

`<ul class="menu"><li class="first leaf"><a href="http://www.colorado.edu/atoz/letter/a" title="" class="menu__link">A to Z Directory</a></li>
<li class="leaf"><a href="http://www.colorado.edu/map/" title="" class="menu__link" style="z-index: 2147483646; position: relative;">Campus Map</a></li>
<li class="leaf"><a href="http://www.colorado.edu/events" title="" class="menu__link">Campus Events</a></li>
<li class="leaf"><a href="http://www.colorado.edu/pts/" title="" class="menu__link">Parking &amp; Transportation</a></li>
<li class="last leaf"><a href="http://www.colorado.edu/visit" title="" class="menu__link">Visit Information</a></li>
</ul>`

**Comment by tovstiadi** [comment]
From a test with a screen reader user on July 1: the links to site’s local home page and CU homepage are not distinguishable since both are labelled “home"
