### ISSUE TITLE
[SI-WARNING-TRUE] 1.3.1 Info and Relationships - Avoid using the 'i' tag

### ISSUE THREAD

**Issue by cathysnider** [CuBoulder/express#942]
## Problem Description per Siteimprove

The italics-tag 'i' is used to highlight text. Please note that even though 'i' tags are commonly used for inserting icons, this is considered bad practice.

## Page Description

Top level page of a fresh Web Express install; contains text in main content region only.
Any other page that uses Font Awesome icons. 

## What we're doing: 

We're using the 'I' tag to insert Font Awesome icons. 
Examples: 
< i class="fa fa-reorder fa-fw" >< /i >
< i class="fa fa-home" style="z-index: 2147483646; position: relative;"> < /i >
< i class="fa fa-angle-right" style="z-index: 2147483646; position: relative;" >< /i >

## Solution

none suggested at this time

**Comment by kreynen** [comment]
The use of the <i> is mainly from FontAwesome or legacy content that's been imported.  We're not going to stop using FontAwesome and can't tweak the SI check to ignore class="fa so I think we'll have to ignore this one.

**Comment by tovstiadi** [comment]
From a test with a screen reader user on July 1: we did find something curious here: content MORE accessible to a screen reader user than the sighted user. On an article with tags, the screen reads the icons as “tags” and “categories” (=meaningful clear labels) while sighted user gets two icons that look like a folder and a tag - not as transparent.
