### ISSUE TITLE
CU Collections Overridden Feature 

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#950]
## Context

As part of the Feature export, there was a time-related variable exported. Since the date always updates, the Feature will always report as overridden.  

## Process

Look at:
https://github.com/CuBoulder/express/blob/dev/modules/custom/cu_collections/cu_collections.strongarm.inc#L38

## Expected result

Feature is not overridden. 
https://www.colorado.edu/p1a8039d70e2/admin/structure/features/cu_collections

## Current result

Feature is overridden. 
https://www.colorado.edu/p1a8039d70e2/admin/structure/features/cu_collections

## Possible Fix

Don't export "cache_flush_cache_entity_field_collection_item" for that Feature.

**Comment by kreynen** [comment]
Issue moved to [CuBoulder/express_collections_bundle #8](https://github.com/CuBoulder/express_collections_bundle/issues/8) via [**ZenHub**](https://www.zenhub.com/)
