### ISSUE TITLE
Add ERUS Module to Express Repo

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#956]
## Context

The Update module can check for versions of Drupal modules that exist on drupal.org, but it provides no way to check for updated versions of modules hosted outside of drupal.org. Stanford has developed a module to provide update status for externally hosted modules and provides an integration with GitHub. 

## Expected result

A custom module that uses the ERUS module to provide update status for Express modules hosted on GitHub. An additional git hook to add an MD5 checksum to the release file would be a nice addition so that process doesn't have to be done manually. 

## Current result

There is no way of knowing if an Express module hosted outside of drupal.org is out-of-date.

## Links to Examples

* Stanford module - [https://github.com/SU-SWS/erus](https://github.com/SU-SWS/erus)

**Comment by alexfinnarn** [comment]
Other than adding one line to info files of custom bundles, there are no other code changes we have to make if the code lives on GitHub. 

https://github.com/CuBoulder/cu_classes_bundle/releases/tag/7.x-1.8

You have to add the md5 checksum in the release notes. 

https://dev-on-demand.pantheonsite.io/admin/reports/updates

And that site has the "Classes" module reporting as needing an update 1.7 -> 1.8.

**Comment by alexfinnarn** [comment]
Since this module adds things via Composer, the total weight is large. It will add 660 files to the repository. 

All the module needs to do is make a request to GitHub, which could be done via cURL, parse the response, and then feed to the Update module. 

There's no way that you need 660 files to do that. I propose to make an erus_lite module that takes much of what the Erus module already has in it while removing all the Composer dependencies.

**Comment by owenmorrill** [comment]
`Notice: Undefined offset: 1 in erusGithub->parse_latest_minor() (line 362 of /data/code/profiles/express/express-2.6.2/modules/custom/erus_lite/plugins/erusGithub.inc).`

Also seeing "No available releases found" instead of the github response. Just documenting it for posterity.

**Comment by alexfinnarn** [comment]
use https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_system_info_alter/7.x to write a test.
