### ISSUE TITLE
Enabling metatag_twitter_cards module causes @page behat test to fail

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#968]
## Context

In working on #887 , enabling the metatag_twitter_cards module is causing the @page test to fail

## Process

[ordered list the process to finding and recreating the issue, example below]

1. Checkout branch feature/887
2. Run @page behat test

## Expected result

 @api @page
  Scenario: An authenticated user should be able to create page node   # features/Express/cu_page/cu_page.feature:26
    Given CU - I am logged in as a user with the "content_editor" role # ExpressContext::assertAuthenticatedByRole()
    And I am on "node/add/page"                                        # Drupal\DrupalExtension\Context\MinkContext::visit()
    And for "Title" I enter "New Page"                                 # Drupal\DrupalExtension\Context\MinkContext::assertEnterField()
    And for "Body" I enter "Demo body content"                         # Drupal\DrupalExtension\Context\MinkContext::assertEnterField()
    And for "Menu link title" I enter "New Menu Item"                  # Drupal\DrupalExtension\Context\MinkContext::assertEnterField()
    When I press the "Save" button                                     # Drupal\DrupalExtension\Context\MinkContext::pressButton()
    Then the "h1" element should contain "New Page"                    # Drupal\DrupalExtension\Context\MinkContext::assertElementContains()
      The string "New Page" was not found in the HTML of the element matching css "h1". (Behat\Mink\Exception\ElementHtmlException)
    And I should see the text "Demo body content"                      # Drupal\DrupalExtension\Context\MinkContext::assertTextVisible()
    And I should see the text "New Menu Item"  

## Current result

@api @page
  Scenario: The provide menu link box should be checked on node creation but remain unchecked if user chooses to uncheck that box. # features/Express/cu_page/cu_page.feature:44
    Given CU - I am logged in as a user with the "site_owner" role                                                                 # ExpressContext::assertAuthenticatedByRole()
    When I go to "node/add/page"                                                                                                   # Drupal\DrupalExtension\Context\MinkContext::visit()
    And I fill in "edit-title" with "New Page"                                                                                     # Drupal\DrupalExtension\Context\MinkContext::fillField()
    Then the "edit-menu-enabled" checkbox should be checked                                                                        # Drupal\DrupalExtension\Context\MinkContext::assertCheckboxChecked()
    When I uncheck the box "edit-menu-enabled"                                                                                     # Drupal\DrupalExtension\Context\MinkContext::assertUncheckBox()
    And I press the "Save" button                                                                                                  # Drupal\DrupalExtension\Context\MinkContext::pressButton()
    And I click "Edit"                                                                                                             # Drupal\DrupalExtension\Context\MinkContext::assertClick()
    Then the checkbox "edit-menu-enabled" should be unchecked

**Comment by alexfinnarn** [comment]
This issue seems to be due to the fact that the Twitter Card module uses a "Title" label that conflicts with the page title field of nodes. I suggest that label be changed to "Page Title" in a form alter.

**Comment by alexfinnarn** [comment]
This fix was handled in #887. It is possible that this issue will come up again. If that happens, the form_alter() added in that ticket should be placed in a more general module and look for every "Title" label on a form changing the labels so that only one "Title" label exists on the form.
