### ISSUE TITLE
Seeing "[CATEGORY] has no results" error when Article List blocks  

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#972]
## Context

When using Article lists filtered by category, users see a warning on the next page load that "[CATEGORY] has no results" it there are no nodes with that category.

## Process

1. Visit http://www.colorado.edu/techtalks/
2. Go to any other page

## Expected result

No warning message

## Current result

Unless Articles have been added that use the Upcoming category, you will see a warning message on the next page load that says "Upcoming Tech Talks has no results"

![screen shot 2017-03-22 at 10 44 28 am](https://cloud.githubusercontent.com/assets/385234/24209809/e1424436-0eec-11e7-9332-16bbb878b468.png)

## Possible Fix

@kevincrafts has been able to fix this in other places.  Not sure if that fix will work here.

**Comment by kreynen** [comment]
related to https://github.com/CuBoulder/express/issues/986

**Comment by alexfinnarn** [comment]
I wasn't able to reproduce this issue locally. 

My fix is to include the no results message in the content of the listing block. A druapl_set_message() can get cached until the next request, and that is what I'm thinking happened here. By making the no results message into a message, the content area is blank and I think that is wrong.

I removed the drupal_set_message() and added the no results message to the content area of the article listing blocks/beans.

**Comment by cathysnider** [comment]
I was able to reproduce this error on a p1 site. The problem seems to be intermittent -- the problematic Article List block doesn't throw the error all the time, only occasionally.

**Comment by cathysnider** [comment]
Example of the problem: https://www-dev.colorado.edu/p197e3f21b9d/ Two Article List Blocks, Law and Category Two, have no articles so tagged. When you LEAVE a page with the empty AL block, the page you go to displays an error message that the block was empty.

**Comment by cathysnider** [comment]
Test Results: https://www-dev.colorado.edu/p15f21771fd6/
