### ISSUE TITLE
When changing content using Context on Pantheon, caching isn't cleared

### ISSUE THREAD

**Issue by kreynen** [CuBoulder/express#973]
## Context

This happened during the RAVE Alert test on http://alerts.colorado.edu/.  When making a Context change, the varnish cache of the front page of the site isn't cleared and cached content is still displayed.  Not sure if this issue is specific to Pantheon or we are going to run into the same issue on Platform.

The emergency communication team can work around the problem by editing the homepage node, but we need to find a better fix.

## Process

1. Login to site as a SO/CE
2. Click Express > Short Cuts > Context
3. Modify the blocks in a Context
4. Open the site in an incognito session

## Expected result

Content changes

## Current result

Content 

## Possible Fixes

Extend the functionality of admin/settings/admin/clear-cache to include varnish

**Comment by alexfinnarn** [comment]
The best way to handle this, IMHO, would be to only purge the pages listed in the context from Varnish, but per https://pantheon.io/docs/unsupported-modules-plugins/ you can't selectively purge the varnish cache on Pantheon.

The only other way around this is to bypass Varnish, but that is what was killing the alerts site before. https://pantheon.io/docs/caching-advanced-topics/

Maybe you could add a...nope...I got nothin'.

**Comment by alexfinnarn** [comment]
I thought Platform.sh would be better at configuring caching, but it seems like they do their own thing: https://docs.platform.sh/configuration/routes/cache.html. 

It does seem...nope...I got nothin' again.

**Comment by alexfinnarn** [comment]
Regarding extending "admin/settings/admin/clear-cache" to include Varnish, it already should clear Varnish if the pantheon_api module is enabled. 

https://pantheon.io/docs/clear-caches/

**Comment by kreynen** [comment]
Issue moved to [CuBoulder/cu-express-drops-7 #6](https://github.com/CuBoulder/cu-express-drops-7/issues/6) via [**ZenHub**](https://www.zenhub.com/)
