### ISSUE TITLE
Collection Items can't be added to content lists

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#976]
## Context

Currently, only articles, pages, and persons can be added to content lists. Collection items should be allowed too.

## Process

1. Install/enable express_collections_bundle
2. Login to site as a SO/CE
3. Click Add Content
4. Click Collection Item
5. Add some content
6. Click save
7. Enable advanced_content_bundle
8. Click Add Content
9. Click Content List Page
10. Add the collection item you created above

## Expected result

The collection item should be returned in the auto complete field and display when you view the content list
## Current result

Collection items cannot be added to content lists right now

## Possible Fix

Content lists use various view modes for display (title, sidebar, embed, teaser) and each of these needs to be configured for collection item nodes.

Content list reference fields need to allow collection items.

**Comment by ekellagher** [comment]
Updated Totorials to reflect this new functionality
https://www.colorado.edu/webcentral/tutorial/v2/content-list-block
https://www.colorado.edu/webcentral/tutorial/v2/content-list-page
