### ISSUE TITLE
Express Layout Advanced Configuration Bug

### ISSUE THREAD

**Issue by alexfinnarn** [CuBoulder/express#991]
## Context

This is a rather large bug that affects all Express sites. A developer must save a form for the bug to appear, and we haven't seen the issue because we "vset" the variable instead of saving the form. 

## Process

1. Login to site as a developer.
2. Go to a basic page and see that you can edit a layout. 
3. Go to "admin/config/content/express-layout/advanced".
4. Save the form with any values.
5. Go to a basic page to see that you can't edit a layout.

## Expected result

You can exclude content types from creating layouts without losing permissions to edit any layout.

## Current result

Saving the form to exclude content types from layouts ends up locking you out of editing any permissions. 

## Possible Fix

Change how "express_layout_node_type_ignore" is handled in https://github.com/CuBoulder/express/blob/dev/modules/custom/express_layout/express_layout.module#L143. "in_array" should be changed to handle how that variable is saved.

**Comment by cathysnider** [comment]
Acceptance Criteria:
- [ ] Changing Express Layout Advanced Configuration does not lock users (Devs, SOs or CEs) from editing layout on Basic Pages. 

Yep, this works. 
https://www-dev.colorado.edu/p1d9985fa173/
