### ISSUE TITLE
Hover on Safari animates css background position

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/express#998]
## Context

Newer versions of Safari seem to animate changes in background position. even when this attribute was not set to be animated. It seems to be tied to -webkit-box-shadow.

Elements effected: Slider item navigation, contextual menus.

## Process

1. Login to site as a [SO, CE, EO, ADMIN or DEV]
2. Hover over a contextual menu.

## Expected result

The backgrounds should switch instantly.

## Current result

Here's an example of what happens with slider navigation
![ezgif-2-6026e7626f](https://cloud.githubusercontent.com/assets/349713/24715173/ca274b4c-19e7-11e7-8ca7-e085a1431764.gif)

## Possible Fix

Remove the -webkit-box-shadow transition from links.

**Comment by cathysnider** [comment]
Verified: The little button under the slider is not animated any longer. https://www-dev.colorado.edu/p10072550f11/page-one
